# NOTE: currently implemented countries
countries = [
    'argentina',
    'australia',
    'austria',
    'belarus',
    'belgium',
    'bolivia',
    'brazil',
    'bulgaria',
    'canada',
    'chile',
    'china',
    'colombia',
    'croatia',
    'czech republic',
    'denmark',
    'ecuador',
    'england',
    'estonia',
    'finland',
    'france',
    'germany',
    'greece',
    'hungary',
    'iceland',
    'india',
    'indonesia',
    'ireland',
    'italy',
    'japan',
    'kazakhstan',
    'latvia',
    'lithuania',
    'mexico',
    'netherlands',
    'new zealand',
    'norway',
    'paraguay',
    'peru',
    'philippines',
    'poland',
    'portugal',
    'romania',
    'russia',
    'saudi arabia',
    'scotland',
    'serbia',
    'slovakia',
    'slovenia',
    'south korea',
    'spain',
    'sweden',
    'switzerland',
    'taiwan',
    'tajikistan',
    'thailand',
    'tunisia',
    'turkey',
    'ukraine',
    'united kingdom',
    'united states',
    'uruguay',
    'uzbekistan',
    'venezuela',
    'vietnam'
]

country_alt_names = {
    'brasil': 'brazil',
    'u.s.': 'united states',
    'usa': 'united states',
    'u.s.a.': 'united states',
    'america': 'united states',
    'czechia': 'czech republic',
    'holland': 'netherlands',
    'deutschland': 'germany',
    'u.k.': 'england',
    'uk': 'england',
    'united kingdom.': 'england',
    'britain': 'england',
    'great britain': 'england',
    'korea': 'south korea'
}
