country_codes = {
    'argentina': 54,
    'australia': 61,
    'austria': 43,
    'belarus': 375,
    'belgium': 32,
    'bolivia': 591,
    'brazil': 55,
    'bulgaria': 359,
    'canada': 1,
    'chile': 56,
    'china': 86,
    'colombia': 57,
    'croatia': 385,
    'czech republic': 420,
    'denmark': 45,
    'ecuador': 593,
    'england': 44,
    'estonia': 372,
    'finland': 358,
    'france': 33,
    'germany': 49,
    'greece': 30,
    'hungary': 36,
    'iceland': 354,
    'india': 91,
    'indonesia': 62,
    'ireland': 353,
    'italy': 39,
    'japan': 81,
    'kazakhstan': 7,
    'latvia': 371,
    'lithuania': 370,
    'mexico': 52,
    'netherlands': 31,
    'new zealand': 64,
    'norway': 47,
    'paraguay': 595,
    'peru': 51,
    'philippines': 63,
    'poland': 48,
    'portugal': 351,
    'romania': 40,
    'russia': 7,
    'saudi arabia': 966,
    'scotland': 44,
    'serbia': 381,
    'slovakia': 421,
    'slovenia': 386,
    'south korea': 82,
    'spain': 34,
    'sweden': 46,
    'switzerland': 41,
    'taiwan': 886,
    'tajikistan': 992,
    'thailand': 66,
    'tunisia': 216,
    'turkey': 90,
    'ukraine': 380,
    'united kingdom': 44,
    'united states': 1,
    'uruguay': 598,
    'uzbekistan': 998,
    'venezuela': 58,
    'vietnam': 84
}

iso_codes = {
    'ar': 'argentina',
    'au': 'australia',
    'at': 'austria',
    'by': 'belarus',
    'be': 'belgium',
    'bo': 'bolivia',
    'br': 'brazil',
    'bg': 'bulgaria',
    'ca': 'canada',
    'cl': 'chile',
    'cn': 'china',
    'co': 'colombia',
    'hr': 'croatia',
    'cz': 'czech republic',
    'dk': 'denmark',
    'ec': 'ecuador',
    'ee': 'estonia',
    'fi': 'finland',
    'fr': 'france',
    'de': 'germany',
    'gr': 'greece',
    'hu': 'hungary',
    'is': 'iceland',
    'in': 'india',
    'id': 'indonesia',
    'ie': 'ireland',
    'it': 'italy',
    'jp': 'japan',
    'kz': 'kazakhstan',
    'kr': 'south korea',
    'lv': 'latvia',
    'lt': 'lithuania',
    'mx': 'mexico',
    'nl': 'netherlands',
    'nz': 'new zealand',
    'no': 'norway',
    'py': 'paraguay',
    'pe': 'peru',
    'ph': 'philippines',
    'pl': 'poland',
    'pt': 'portugal',
    'ro': 'romania',
    'ru': 'russia',
    'sa': 'saudi arabia',
    'rs': 'serbia',
    'sk': 'slovakia',
    'si': 'slovenia',
    'es': 'spain',
    'se': 'sweden',
    'ch': 'switzerland',
    'tw': 'taiwan',
    'tj': 'tajikistan',
    'th': 'thailand',
    'tn': 'tunisia',
    'tr': 'turkey',
    'ua': 'ukraine',
    'gb': 'united kingdom',
    'us': 'united states',
    'uy': 'uruguay',
    'uz': 'uzbekistan',
    've': 'venezuela',
    'vn': 'vietnam'
}

iso_codes_reversed = {
    'argentina': 'ar',
    'australia': 'au',
    'austria': 'at',
    'belarus': 'by',
    'belgium': 'be',
    'bolivia': 'bo',
    'brazil': 'br',
    'bulgaria': 'bg',
    'canada': 'ca',
    'chile': 'cl',
    'china': 'cn',
    'colombia': 'co',
    'croatia': 'hr',
    'czech republic': 'cz',
    'denmark': 'dk',
    'ecuador': 'ec',
    'england': 'gb',
    'estonia': 'ee',
    'finland': 'fi',
    'france': 'fr',
    'germany': 'de',
    'greece': 'gr',
    'hungary': 'hu',
    'iceland': 'is',
    'india': 'in',
    'indonesia': 'id',
    'ireland': 'ie',
    'italy': 'it',
    'japan': 'jp',
    'kazakhstan': 'kz',
    'south korea': 'kr',
    'latvia': 'lv',
    'lithuania': 'lt',
    'mexico': 'mx',
    'netherlands': 'nl',
    'new zealand': 'nz',
    'norway': 'no',
    'paraguay': 'py',
    'peru': 'pe',
    'philippines': 'ph',
    'poland': 'pl',
    'portugal': 'pt',
    'romania': 'ro',
    'russia': 'ru',
    'saudi arabia': 'sa',
    'scotland': 'gb',
    'serbia': 'rs',
    'slovakia': 'sk',
    'slovenia': 'si',
    'spain': 'es',
    'sweden': 'se',
    'switzerland': 'ch',
    'taiwan': 'tw',
    'tajikistan': 'tj',
    'thailand': 'th',
    'tunisia': 'tn',
    'turkey': 'tr',
    'ukraine': 'ua',
    'united kingdom': 'gb',
    'united states': 'us',
    'uruguay': 'uy',
    'uzbekistan': 'uz',
    'venezuela': 've',
    'vietnam': 'vn'
}
