cities = [
    'Abbeville',
    'Abernant',
    'Adamsville',
    'Addison',
    'Adger',
    'Akron',
    'Alabaster',
    'Alberta',
    'Albertville',
    'Alexander City',
    'Alexandria',
    'Aliceville',
    'Allgood',
    'Alma',
    'Alpine',
    'Alton',
    'Altoona',
    'Andalusia',
    'Anderson',
    'Annemanie',
    'Anniston',
    'Arab',
    'Ardmore',
    'Ariton',
    'Arley',
    'Arlington',
    'Ashford',
    'Ashland',
    'Ashville',
    'Athens',
    'Atmore',
    'Attalla',
    'Auburn',
    'Auburn University',
    'Autaugaville',
    'Axis',
    'Baileyton',
    'Banks',
    'Bankston',
    'Bay Minette',
    'Bayou La Batre',
    'Bear Creek',
    'Beatrice',
    'Beaverton',
    'Belk',
    'Bellamy',
    'Belle Mina',
    'Bellwood',
    'Berry',
    'Bessemer',
    'Billingsley',
    'Birmingham',
    'Black',
    'Blountsville',
    'Boaz',
    'Boligee',
    'Bon Air',
    'Bon Secour',
    'Booth',
    'Boykin',
    'Brantley',
    'Bremen',
    'Brent',
    'Brewton',
    'Bridgeport',
    'Brierfield',
    'Brilliant',
    'Brooklyn',
    'Brookside',
    'Brookwood',
    'Brownsboro',
    'Brundidge',
    'Bryant',
    'Bucks',
    'Buhl',
    'Burnt Corn',
    'Burnwell',
    'Butler',
    'Bynum',
    'Calera',
    'Calvert',
    'Camden',
    'Camp Hill',
    'Campbell',
    'Capshaw',
    'Carbon Hill',
    'Cardiff',
    'Carlton',
    'Carrollton',
    'Castleberry',
    'Catherine',
    'Cecil',
    'Cedar Bluff',
    'Centre',
    'Centreville',
    'Chancellor',
    'Chapman',
    'Chatom',
    'Chelsea',
    'Cherokee',
    'Childersburg',
    'Choccolocco',
    'Chunchula',
    'Citronelle',
    'Clanton',
    'Clay',
    'Clayton',
    'Cleveland',
    'Clinton',
    'Clio',
    'Clopton',
    'Cloverdale',
    'Coaling',
    'Coden',
    'Coffee Springs',
    'Coffeeville',
    'Coker',
    'Collinsville',
    'Columbia',
    'Columbiana',
    'Cook Springs',
    'Coosada',
    'Cordova',
    'Cottondale',
    'Cottonton',
    'Cottonwood',
    'Courtland',
    'Cowarts',
    'Coy',
    'Cragford',
    'Crane Hill',
    'Creola',
    'Cromwell',
    'Cropwell',
    'Crossville',
    'Cuba',
    'Cullman',
    'Cusseta',
    'Dadeville',
    'Daleville',
    'Danville',
    'Daphne',
    'Dauphin Island',
    'Daviston',
    'Dawson',
    'De Armanville',
    'Deatsville',
    'Decatur',
    'Deer Park',
    'Delmar',
    'Delta',
    'Demopolis',
    'Detroit',
    'Dickinson',
    'Dixons Mills',
    'Docena',
    'Dolomite',
    'Dora',
    'Dothan',
    'Double Springs',
    'Douglas',
    'Dozier',
    'Duncanville',
    'Dutton',
    'East Tallassee',
    'Eastaboga',
    'Echola',
    'Eclectic',
    'Edwardsville',
    'Eight Mile',
    'Elba',
    'Elberta',
    'Eldridge',
    'Elkmont',
    'Elmore',
    'Elrod',
    'Emelle',
    'Empire',
    'Enterprise',
    'Epes',
    'Equality',
    'Estillfork',
    'Ethelsville',
    'Eufaula',
    'Eutaw',
    'Eva',
    'Evergreen',
    'Excel',
    'Fackler',
    'Fairfield',
    'Fairhope',
    'Falkville',
    'Faunsdale',
    'Fayette',
    'Fitzpatrick',
    'Five Points',
    'Flat Rock',
    'Flomaton',
    'Florala',
    'Florence',
    'Foley',
    'Forest Home',
    'Forkland',
    'Fort Davis',
    'Fort Deposit',
    'Fort Mitchell',
    'Fort Payne',
    'Fort Rucker',
    'Fosters',
    'Franklin',
    'Frankville',
    'Frisco City',
    'Fruitdale',
    'Fruithurst',
    'Fulton',
    'Fultondale',
    'Furman',
    'Fyffe',
    'Gadsden',
    'Gainestown',
    'Gainesville',
    'Gallant',
    'Gallion',
    'Gantt',
    'Garden City',
    'Gardendale',
    'Gaylesville',
    'Geneva',
    'Georgiana',
    'Geraldine',
    'Gilbertown',
    'Glen Allen',
    'Glenwood',
    'Goodsprings',
    'Goodwater',
    'Goodway',
    'Gordo',
    'Gordon',
    'Goshen',
    'Grady',
    'Graham',
    'Grand Bay',
    'Grant',
    'Graysville',
    'Green Pond',
    'Greensboro',
    'Greenville',
    'Grove Hill',
    'Groveoak',
    'Guin',
    'Gulf Shores',
    'Guntersville',
    'Gurley',
    'Hackleburg',
    'Haleyville',
    'Hamilton',
    'Hanceville',
    'Hardaway',
    'Harpersville',
    'Hartford',
    'Hartselle',
    'Harvest',
    'Hatchechubbee',
    'Hayden',
    'Hayneville',
    'Hazel Green',
    'Headland',
    'Heflin',
    'Helena',
    'Henagar',
    'Higdon',
    'Highland Home',
    'Hillsboro',
    'Hodges',
    'Hollins',
    'Holly Pond',
    'Hollytree',
    'Hollywood',
    'Holy Trinity',
    'Honoraville',
    'Hoover',
    'Hope Hull',
    'Horton',
    'Houston',
    'Huntsville',
    'Hurtsboro',
    'Huxford',
    'Ider',
    'Irvington',
    'Iuka',
    'Jachin',
    'Jack',
    'Jackson',
    'Jacksons Gap',
    'Jacksonville',
    'Jasper',
    'Jefferson',
    'Jemison',
    'Jones',
    'Joppa',
    'Kansas',
    'Kellerman',
    'Kellyton',
    'Kennedy',
    'Kent',
    'Killen',
    'Kimberly',
    'Kinston',
    'Knoxville',
    'Laceys Spring',
    'Lafayette',
    'Lanett',
    'Langston',
    'Lapine',
    'Lawley',
    'Leeds',
    'Leesburg',
    'Leighton',
    'Lenox',
    'Leroy',
    'Lester',
    'Letohatchee',
    'Lexington',
    'Lillian',
    'Lincoln',
    'Linden',
    'Lineville',
    'Lisman',
    'Little River',
    'Livingston',
    'Loachapoka',
    'Lockhart',
    'Locust Fork',
    'Logan',
    'Louisville',
    'Lower Peach Tree',
    'Lowndesboro',
    'Loxley',
    'Luverne',
    'Lynn',
    'Madison',
    'Magnolia',
    'Magnolia Springs',
    'Malcolm',
    'Malvern',
    'Maplesville',
    'Marbury',
    'Margaret',
    'Marion',
    'Marion Junction',
    'Mathews',
    'Maylene',
    'McCalla',
    'McIntosh',
    'McKenzie',
    'McShan',
    'McWilliams',
    'Megargel',
    'Melvin',
    'Mentone',
    'Meridianville',
    'Mexia',
    'Midland City',
    'Midway',
    'Millbrook',
    'Millerville',
    'Millport',
    'Millry',
    'Minter',
    'Mobile',
    'Monroeville',
    'Montevallo',
    'Montgomery',
    'Montrose',
    'Moody',
    'Mooresville',
    'Morris',
    'Morvin',
    'Moulton',
    'Moundville',
    'Mount Hope',
    'Mount Meigs',
    'Mount Olive',
    'Mount Vernon',
    'Mulga',
    'Munford',
    'Muscadine',
    'Muscle Shoals',
    'Myrtlewood',
    'Nanafalia',
    'Natural Bridge',
    'Nauvoo',
    'Needham',
    'New Brockton',
    'New Castle',
    'New Hope',
    'New Market',
    'Newbern',
    'Newell',
    'Newton',
    'Newville',
    'Normal',
    'Northport',
    'Notasulga',
    'Oak Hill',
    'Oakman',
    'Odenville',
    'Ohatchee',
    'Oneonta',
    'Opelika',
    'Opp',
    'Orange Beach',
    'Orrville',
    'Owens Cross Roads',
    'Ozark',
    'Paint Rock',
    'Palmerdale',
    'Panola',
    'Pansey',
    'Parrish',
    'Pelham',
    'Pell City',
    'Pennington',
    'Perdido',
    'Perdue Hill',
    'Perote',
    'Peterman',
    'Peterson',
    'Petrey',
    'Phenix City',
    'Phil Campbell',
    'Piedmont',
    'Pike Road',
    'Pinckard',
    'Pine Apple',
    'Pine Hill',
    'Pine Level',
    'Pinson',
    'Pisgah',
    'Pittsview',
    'Plantersville',
    'Pleasant Grove',
    'Point Clear',
    'Prattville',
    'Princeton',
    'Quinton',
    'Ragland',
    'Rainbow City',
    'Rainsville',
    'Ralph',
    'Ramer',
    'Ranburne',
    'Randolph',
    'Range',
    'Red Bay',
    'Red Level',
    'Reform',
    'Remlap',
    'Repton',
    'River Falls',
    'Riverside',
    'Roanoke',
    'Robertsdale',
    'Rockford',
    'Rogersville',
    'Russellville',
    'Rutledge',
    'Ryland',
    'Safford',
    'Saginaw',
    'Saint Elmo',
    'Saint Stephens',
    'Salem',
    'Salitpa',
    'Samantha',
    'Samson',
    'Saraland',
    'Sardis',
    'Satsuma',
    'Sawyerville',
    'Sayre',
    'Scottsboro',
    'Seale',
    'Section',
    'Selma',
    'Seminole',
    'Semmes',
    'Shannon',
    'Sheffield',
    'Shelby',
    'Shorter',
    'Shorterville',
    'Silas',
    'Siluria',
    'Silverhill',
    'Sipsey',
    'Skipperville',
    'Slocomb',
    'Smiths',
    'Snow Hill',
    'Somerville',
    'Spanish Fort',
    'Spring Garden',
    'Springville',
    'Sprott',
    'Spruce Pine',
    'Stanton',
    'Stapleton',
    'Steele',
    'Sterrett',
    'Stevenson',
    'Stockton',
    'Sulligent',
    'Sumiton',
    'Summerdale',
    'Sunflower',
    'Sweet Water',
    'Sycamore',
    'Sylacauga',
    'Sylvania',
    'Talladega',
    'Tallassee',
    'Tanner',
    'Theodore',
    'Thomaston',
    'Thomasville',
    'Thorsby',
    'Tibbie',
    'Titus',
    'Toney',
    'Town Creek',
    'Townley',
    'Toxey',
    'Trafford',
    'Trenton',
    'Trinity',
    'Troy',
    'Trussville',
    'Tuscaloosa',
    'Tuscumbia',
    'Tuskegee',
    'Tuskegee Institute',
    'Tyler',
    'Union Grove',
    'Union Springs',
    'Uniontown',
    'Uriah',
    'Valhermoso Springs',
    'Valley',
    'Valley Head',
    'Vance',
    'Vandiver',
    'Verbena',
    'Vernon',
    'Vina',
    'Vincent',
    'Vinegar Bend',
    'Vinemont',
    'Vredenburgh',
    'Wadley',
    'Wagarville',
    'Walker Springs',
    'Walnut Grove',
    'Ward',
    'Warrior',
    'Waterloo',
    'Watson',
    'Wattsville',
    'Waverly',
    'Weaver',
    'Webb',
    'Wedowee',
    'Wellington',
    'Weogufka',
    'West Blocton',
    'West Greene',
    'Westover',
    'Wetumpka',
    'Whatley',
    'Wilmer',
    'Wilsonville',
    'Wilton',
    'Winfield',
    'Wing',
    'Woodland',
    'Woodstock',
    'Woodville',
    'York'
]
