cities = [
    'Aguila',
    'Ajo',
    'Alpine',
    'Amado',
    'Anthem',
    'Apache Junction',
    'Arivaca',
    'Arizona City',
    'Arlington',
    'Ash Fork',
    'Avondale',
    'Bagdad',
    'Bapchule',
    'Bellemont',
    'Benson',
    'Big Park',
    'Bisbee',
    'Black Canyon City',
    'Blue',
    'Blue Gap',
    'Bouse',
    'Bowie',
    'Buckeye',
    'Bullhead City',
    'Bylas',
    'Cameron',
    'Camp Verde',
    'Carefree',
    'Casa Grande',
    'Cashion',
    'Catalina',
    'Cave Creek',
    'Central',
    'Chambers',
    'Chandler',
    'Chandler Heights',
    'Chinle',
    'Chino Valley',
    'Chloride',
    'Cibecue',
    'Cibola',
    'Clarkdale',
    'Clay Springs',
    'Claypool',
    'Clifton',
    'Cochise',
    'Colorado City',
    'Concho',
    'Congress',
    'Coolidge',
    'Cornville',
    'Cortaro',
    'Cottonwood',
    'Crown King',
    'Dateland',
    'Dennehotso',
    'Dewey',
    'Dolan Springs',
    'Douglas',
    'Dragoon',
    'Duncan',
    'Eagar',
    'Eden',
    'Ehrenberg',
    'El Mirage',
    'Elfrida',
    'Elgin',
    'Eloy',
    'Flagstaff',
    'Florence',
    'Forest Lakes',
    'Fort Apache',
    'Fort Defiance',
    'Fort Huachuca',
    'Fort Mcdowell',
    'Fort Mohave',
    'Fort Thomas',
    'Fountain Hills',
    'Fredonia',
    'Gadsden',
    'Ganado',
    'Gila Bend',
    'Gilbert',
    'Glendale',
    'Globe',
    'Gold Camp',
    'Golden Valley',
    'Goodyear',
    'Grand Canyon',
    'Gray Mountain',
    'Green Valley',
    'Greer',
    'Hackberry',
    'Happy Jack',
    'Hayden',
    'Heber',
    'Hereford',
    'Higley',
    'Holbrook',
    'Hotevilla',
    'Houck',
    'Huachuca City',
    'Hualapai',
    'Humboldt',
    'Indian Wells',
    'Iron Springs',
    'Jerome',
    'Joseph City',
    'Kaibito',
    'Kayenta',
    'Keams Canyon',
    'Kearny',
    'Kingman',
    'Kirkland',
    'Kykotsmovi Village',
    'Lake Havasu City',
    'Lake Montezuma',
    'Lakeside',
    'Laveen',
    'Leupp',
    'Litchfield Park',
    'Littlefield',
    'Lukachukai',
    'Luke AFB',
    'Lukeville',
    'Lupton',
    'Mammoth',
    'Many Farms',
    'Marana',
    'Marble Canyon',
    'Maricopa',
    'Mayer',
    'Mcnary',
    'McNeal',
    'Meadview',
    'Mesa',
    'Mesquite',
    'Miami',
    'Mohave Valley',
    'Monument Valley',
    'Morenci',
    'Mormon Lake',
    'Morristown',
    'Mount Lemmon',
    'Munds Park',
    'Naco',
    'Navajo',
    'Nazlini',
    'New River',
    'Nogales',
    'North Rim',
    'Nutrioso',
    'Oatman',
    'Oracle',
    'Overgaard',
    'Page',
    'Palo Verde',
    'Paradise Valley',
    'Parker',
    'Parks',
    'Patagonia',
    'Paulden',
    'Payson',
    'Peach Springs',
    'Pearce',
    'Peoria',
    'Peridot',
    'Petrified Forest Natl Pk',
    'Phoenix',
    'Picacho',
    'Pima',
    'Pine',
    'Pinedale',
    'Pinetop',
    'Pinon',
    'Pirtleville',
    'Polacca',
    'Pomerene',
    'Poston',
    'Prescott',
    'Prescott Valley',
    'Quartzsite',
    'Queen Creek',
    'Red Rock',
    'Red Valley',
    'Rillito',
    'Rimrock',
    'Rio Rico',
    'Rio Verde',
    'Rock Point',
    'Roll',
    'Roosevelt',
    'Round Rock',
    'Sacaton',
    'Safford',
    'Sahuarita',
    'Saint David',
    'Saint Johns',
    'Saint Michaels',
    'Salome',
    'San Carlos',
    'San Luis',
    'San Manuel',
    'San Simon',
    'Sanders',
    'Sasabe',
    'Sawmill',
    'Scottsdale',
    'Second Mesa',
    'Sedona',
    'Seligman',
    'Sells',
    'Shonto',
    'Show Low',
    'Sierra Vista',
    'Skull Valley',
    'Snowflake',
    'Solomon',
    'Somerton',
    'Sonoita',
    'Springerville',
    'Stanfield',
    'Sun City',
    'Sun City West',
    'Sun Valley',
    'Supai',
    'Superior',
    'Surprise',
    'Tacna',
    'Taylor',
    'Teec Nos Pos',
    'Tempe',
    'Temple Bar Marina',
    'Thatcher',
    'Tolleson',
    'Tombstone',
    'Tonalea',
    'Tonopah',
    'Tonto Basin',
    'Topawa',
    'Topock',
    'Tortilla Flat',
    'Tsaile',
    'Tuba City',
    'Tubac',
    'Tucson',
    'Tumacacori',
    'Vail',
    'Valentine',
    'Valley Farms',
    'Vernon',
    'Waddell',
    'Wellton',
    'Wenden',
    'White Mountain Lake',
    'Whiteriver',
    'Wickenburg',
    'Wikieup',
    'Willcox',
    'Williams',
    'Willow Beach',
    'Window Rock',
    'Winkelman',
    'Winslow',
    'Wittmann',
    'Woodruff',
    'Yarnell',
    'Young',
    'Youngtown',
    'Yucca',
    'Yuma'
]
