cities = [
    'Adona',
    'Alco',
    'Alexander',
    'Alicia',
    'Alix',
    'Alleene',
    'Alma',
    'Almyra',
    'Alpena',
    'Alpine',
    'Altheimer',
    'Altus',
    'Amagon',
    'Amity',
    'Antoine',
    'Arkadelphia',
    'Arkansas City',
    'Armorel',
    'Ash Flat',
    'Ashdown',
    'Atkins',
    'Aubrey',
    'Augusta',
    'Austin',
    'Avoca',
    'Bald Knob',
    'Banks',
    'Barling',
    'Barton',
    'Bassett',
    'Bates',
    'Batesville',
    'Bauxite',
    'Bay',
    'Bearden',
    'Beaver',
    'Bee Branch',
    'Beebe',
    'Beech Grove',
    'Beedeville',
    'Beirne',
    'Bella Vista',
    'Belleville',
    'Ben Lomond',
    'Benton',
    'Bentonville',
    'Bergman',
    'Berryville',
    'Bexar',
    'Big Flat',
    'Bigelow',
    'Biggers',
    'Birdeye',
    'Biscoe',
    'Bismarck',
    'Black Oak',
    'Black Rock',
    'Blevins',
    'Blue Mountain',
    'Bluff City',
    'Bluffton',
    'Blytheville',
    'Board Camp',
    'Boles',
    'Bonnerdale',
    'Bono',
    'Booneville',
    'Boswell',
    'Bradford',
    'Bradley',
    'Branch',
    'Brickeys',
    'Briggsville',
    'Brinkley',
    'Brockwell',
    'Brookland',
    'Bryant',
    'Buckner',
    'Bull Shoals',
    'Burdette',
    'Cabot',
    'Caddo Gap',
    'Caldwell',
    'Cale',
    'Calico Rock',
    'Calion',
    'Camden',
    'Camp',
    'Canehill',
    'Caraway',
    'Carlisle',
    'Carthage',
    'Casa',
    'Cash',
    'Casscoe',
    'Cave City',
    'Cave Springs',
    'Cecil',
    'Cedarville',
    'Center Ridge',
    'Centerton',
    'Centerville',
    'Charleston',
    'Charlotte',
    'Cherokee Village',
    'Cherry Valley',
    'Chester',
    'Chidester',
    'Choctaw',
    'Clarendon',
    'Clarkedale',
    'Clarkridge',
    'Clarksville',
    'Cleveland',
    'Clinton',
    'Coal Hill',
    'College Station',
    'Colt',
    'Columbus',
    'Combs',
    'Compton',
    'Concord',
    'Conway',
    'Cord',
    'Corning',
    'Cotter',
    'Cotton Plant',
    'Cove',
    'Coy',
    'Crawfordsville',
    'Crocketts Bluff',
    'Crossett',
    'Crumrod',
    'Curtis',
    'Cushman',
    'Damascus',
    'Danville',
    'Dardanelle',
    'Datto',
    'De Queen',
    'De Valls Bluff',
    'De Witt',
    'Decatur',
    'Deer',
    'Delaplaine',
    'Delaware',
    'Delight',
    'Dell',
    'Dennard',
    'Dermott',
    'Des Arc',
    'Desha',
    'Diamond City',
    'Diaz',
    'Dierks',
    'Doddridge',
    'Dolph',
    'Donaldson',
    'Dover',
    'Drasco',
    'Driver',
    'Dumas',
    'Dyer',
    'Dyess',
    'Earle',
    'Edgemont',
    'Edmondson',
    'Egypt',
    'El Dorado',
    'El Paso',
    'Elaine',
    'Elizabeth',
    'Elkins',
    'Elm Springs',
    'Emerson',
    'Emmet',
    'England',
    'Enola',
    'Ethel',
    'Etowah',
    'Eudora',
    'Eureka Springs',
    'Evansville',
    'Evening Shade',
    'Everton',
    'Fairfield Bay',
    'Farmington',
    'Fayetteville',
    'Fifty Six',
    'Fisher',
    'Flippin',
    'Floral',
    'Fordyce',
    'Foreman',
    'Forrest City',
    'Fort Smith',
    'Fouke',
    'Fountain Hill',
    'Fox',
    'Franklin',
    'Frenchmans Bayou',
    'Friendship',
    'Fulton',
    'Gamaliel',
    'Garfield',
    'Garland City',
    'Garner',
    'Gassville',
    'Gateway',
    'Genoa',
    'Gentry',
    'Gepp',
    'Gilbert',
    'Gillett',
    'Gillham',
    'Gilmore',
    'Glencoe',
    'Glenwood',
    'Goodwin',
    'Goshen',
    'Gosnell',
    'Gould',
    'Grady',
    'Grannis',
    'Grapevine',
    'Gravelly',
    'Gravette',
    'Green Forest',
    'Greenbrier',
    'Greenland',
    'Greenway',
    'Greenwood',
    'Gregory',
    'Griffithville',
    'Grubbs',
    'Guion',
    'Gurdon',
    'Guy',
    'Hackett',
    'Hagarville',
    'Hamburg',
    'Hampton',
    'Hardy',
    'Harrell',
    'Harriet',
    'Harrisburg',
    'Harrison',
    'Hartford',
    'Hartman',
    'Harvey',
    'Hasty',
    'Hatfield',
    'Hattieville',
    'Hatton',
    'Havana',
    'Haynes',
    'Hazen',
    'Heber Springs',
    'Hector',
    'Helena',
    'Henderson',
    'Henning',
    'Hensley',
    'Hermitage',
    'Heth',
    'Hickory Plains',
    'Hickory Ridge',
    'Higden',
    'Higginson',
    'Hindsville',
    'Hiwasse',
    'Holly Grove',
    'Hope',
    'Horatio',
    'Horseshoe Bend',
    'Hot Springs',
    'Hot Springs National Park',
    'Hot Springs Village',
    'Houston',
    'Howell',
    'Hoxie',
    'Hughes',
    'Humnoke',
    'Humphrey',
    'Hunter',
    'Huntington',
    'Huntsville',
    'Huttig',
    'Ida',
    'Imboden',
    'Ivan',
    'Jacksonport',
    'Jacksonville',
    'Jasper',
    'Jefferson',
    'Jennie',
    'Jerome',
    'Jersey',
    'Jerusalem',
    'Jessieville',
    'Johnson',
    'Joiner',
    'Jones Mill',
    'Jonesboro',
    'Judsonia',
    'Junction City',
    'Keiser',
    'Kensett',
    'Keo',
    'Kingsland',
    'Kingston',
    'Kirby',
    'Knobel',
    'Knoxville',
    'La Grange',
    'Lafe',
    'Lake City',
    'Lake Village',
    'Lakeview',
    'Lamar',
    'Lambrook',
    'Laneburg',
    'Langley',
    'Lavaca',
    'Lawson',
    'Leachville',
    'Lead Hill',
    'Leola',
    'Lepanto',
    'Leslie',
    'Letona',
    'Lewisville',
    'Lexa',
    'Light',
    'Lincoln',
    'Little Rock',
    'Little Rock Air Force Base',
    'Lockesburg',
    'Locust Grove',
    'London',
    'Lonoke',
    'Lonsdale',
    'Louann',
    'Lowell',
    'Luxora',
    'Lynn',
    'Mabelvale',
    'Madison',
    'Magazine',
    'Magness',
    'Magnolia',
    'Malvern',
    'Mammoth Spring',
    'Manila',
    'Mansfield',
    'Marble Falls',
    'Marcella',
    'Marianna',
    'Marion',
    'Marked Tree',
    'Marmaduke',
    'Marshall',
    'Marvell',
    'Maumelle',
    'Mayflower',
    'Maynard',
    'Maysville',
    'McCaskill',
    'McCrory',
    'McDougal',
    'McGehee',
    'McNeil',
    'McRae',
    'Melbourne',
    'Mellwood',
    'Mena',
    'Menifee',
    'Midland',
    'Midway',
    'Mineral Springs',
    'Minturn',
    'Moko',
    'Monette',
    'Monroe',
    'Monticello',
    'Montrose',
    'Moro',
    'Morrilton',
    'Morrow',
    'Moscow',
    'Mount Holly',
    'Mount Ida',
    'Mount Judea',
    'Mount Pleasant',
    'Mount Vernon',
    'Mountain Home',
    'Mountain Pine',
    'Mountain View',
    'Mountainburg',
    'Mulberry',
    'Murfreesboro',
    'Nashville',
    'Natural Dam',
    'New Blaine',
    'New Edinburg',
    'Newark',
    'Newhope',
    'Newport',
    'Norfork',
    'Norman',
    'Norphlet',
    'North Little Rock',
    'O Kean',
    'Oak Grove',
    'Oakland',
    'Oark',
    'Oden',
    'Ogden',
    'Oil Trough',
    'Okolona',
    'Ola',
    'Omaha',
    'Oneida',
    'Onia',
    'Osceola',
    'Oxford',
    'Ozan',
    'Ozark',
    'Ozone',
    'Palestine',
    'Pangburn',
    'Paragould',
    'Paris',
    'Parkdale',
    'Parkin',
    'Parks',
    'Paron',
    'Parthenon',
    'Patterson',
    'Pea Ridge',
    'Peach Orchard',
    'Pearcy',
    'Peel',
    'Pelsor',
    'Pencil Bluff',
    'Perry',
    'Perryville',
    'Pettigrew',
    'Pickens',
    'Piggott',
    'Pindall',
    'Pine Bluff',
    'Pineville',
    'Plainview',
    'Pleasant Grove',
    'Pleasant Plains',
    'Plumerville',
    'Pocahontas',
    'Pollard',
    'Ponca',
    'Poplar Grove',
    'Portia',
    'Portland',
    'Pottsville',
    'Poughkeepsie',
    'Powhatan',
    'Poyen',
    'Prairie Grove',
    'Prattsville',
    'Prescott',
    'Prim',
    'Proctor',
    'Protem',
    'Pyatt',
    'Quitman',
    'Ratcliff',
    'Ravenden',
    'Ravenden Springs',
    'Rector',
    'Redfield',
    'Reydell',
    'Reyno',
    'Ripley',
    'Rison',
    'Rivervale',
    'Roe',
    'Rogers',
    'Roland',
    'Romance',
    'Rose Bud',
    'Rosie',
    'Rosston',
    'Rover',
    'Royal',
    'Rudy',
    'Russell',
    'Russellville',
    'Saffell',
    'Sage',
    'Saint Charles',
    'Saint Francis',
    'Saint Joe',
    'Saint Paul',
    'Salado',
    'Salem',
    'Saratoga',
    'Scotland',
    'Scott',
    'Scranton',
    'Searcy',
    'Sedgwick',
    'Sheridan',
    'Sherrill',
    'Sherwood',
    'Shirley',
    'Sidney',
    'Siloam Springs',
    'Sims',
    'Smackover',
    'Smithville',
    'Snow Lake',
    'Solgohachia',
    'Sparkman',
    'Springdale',
    'Springfield',
    'Stamps',
    'Star City',
    'State University',
    'Stephens',
    'Story',
    'Strawberry',
    'Strong',
    'Sturkie',
    'Stuttgart',
    'Subiaco',
    'Success',
    'Sulphur Rock',
    'Sulphur Springs',
    'Summers',
    'Summit',
    'Sweet Home',
    'Swifton',
    'Taylor',
    'Texarkana',
    'Theodosia',
    'Thida',
    'Thornton',
    'Tichnor',
    'Tillar',
    'Tilly',
    'Timbo',
    'Tomato',
    'Tontitown',
    'Traskwood',
    'Trumann',
    'Tucker',
    'Tuckerman',
    'Tumbling Shoals',
    'Tupelo',
    'Turner',
    'Turrell',
    'Twist',
    'Tyronza',
    'Ulm',
    'Umpire',
    'Uniontown',
    'Urbana',
    'Valley Springs',
    'Van Buren',
    'Vandervoort',
    'Vanndale',
    'Vendor',
    'Village',
    'Vilonia',
    'Viola',
    'Violet Hill',
    'Wabash',
    'Wabbaseka',
    'Walcott',
    'Waldenburg',
    'Waldo',
    'Waldron',
    'Walnut Ridge',
    'Ward',
    'Warm Springs',
    'Warren',
    'Washington',
    'Watson',
    'Weiner',
    'Wesley',
    'West Fork',
    'West Helena',
    'West Memphis',
    'West Point',
    'West Ridge',
    'Western Grove',
    'Wheatley',
    'Whelen Springs',
    'White Hall',
    'Wickes',
    'Wideman',
    'Widener',
    'Wilburn',
    'Williford',
    'Willisville',
    'Wilmar',
    'Wilmot',
    'Wilson',
    'Wilton',
    'Winchester',
    'Winslow',
    'Winthrop',
    'Wiseman',
    'Witter',
    'Witts Springs',
    'Woodson',
    'Wooster',
    'Wright',
    'Wrightsville',
    'Wynne',
    'Yellville',
    'Yorktown'
]
