cities = [
    'Agate',
    'Aguilar',
    'Akron',
    'Alamosa',
    'Allenspark',
    'Alma',
    'Almont',
    'Amherst',
    'Anton',
    'Antonito',
    'Arapahoe',
    'Arboles',
    'Arlington',
    'Arriba',
    'Arvada',
    'Aspen',
    'Atwood',
    'Ault',
    'Aurora',
    'Austin',
    'Avon',
    'Avondale',
    'Bailey',
    'Basalt',
    'Battlement Mesa',
    'Bayfield',
    'Bedrock',
    'Bellvue',
    'Bennett',
    'Berthoud',
    'Bethune',
    'Beulah',
    'Black Hawk',
    'Blanca',
    'Boncarbo',
    'Bond',
    'Boone',
    'Boulder',
    'Branson',
    'Breckenridge',
    'Briggsdale',
    'Brighton',
    'Broomfield',
    'Brush',
    'Buena Vista',
    'Buffalo Creek',
    'Burlington',
    'Burns',
    'Byers',
    'Cahone',
    'Calhan',
    'Campo',
    'Canon City',
    'Capulin',
    'Carbondale',
    'Carr',
    'Cascade',
    'Castle Rock',
    'Cedaredge',
    'Center',
    'Central City',
    'Chama',
    'Cheraw',
    'Cheyenne Wells',
    'Chimney Rock',
    'Chromo',
    'Cimarron',
    'Clark',
    'Clifton',
    'Climax',
    'Coal Creek',
    'Coaldale',
    'Coalmont',
    'Collbran',
    'Colorado City',
    'Colorado Springs',
    'Commerce City',
    'Como',
    'Conejos',
    'Conifer',
    'Cope',
    'Cortez',
    'Cory',
    'Cotopaxi',
    'Cowdrey',
    'Craig',
    'Crawford',
    'Creede',
    'Crested Butte',
    'Crestone',
    'Cripple Creek',
    'Crook',
    'Crowley',
    'Dacono',
    'De Beque',
    'Deer Trail',
    'Del Norte',
    'Delta',
    'Denver',
    'Dillon',
    'Dinosaur',
    'Divide',
    'Dolores',
    'Dove Creek',
    'Drake',
    'Dumont',
    'Dupont',
    'Durango',
    'Eads',
    'Eagle',
    'Eastlake',
    'Eaton',
    'Eckert',
    'Eckley',
    'Edwards',
    'Egnar',
    'El Jebel',
    'Elbert',
    'Eldorado Springs',
    'Elizabeth',
    'Empire',
    'Englewood',
    'Erie',
    'Estes Park',
    'Evans',
    'Evergreen',
    'Fairplay',
    'Firestone',
    'Flagler',
    'Fleming',
    'Florence',
    'Florissant',
    'Fort Collins',
    'Fort Garland',
    'Fort Lupton',
    'Fort Lyon',
    'Fort Morgan',
    'Fountain',
    'Fowler',
    'Franktown',
    'Fraser',
    'Frederick',
    'Frisco',
    'Fruita',
    'Galeton',
    'Garcia',
    'Gardner',
    'Gateway',
    'Genoa',
    'Georgetown',
    'Gilcrest',
    'Gill',
    'Glade Park',
    'Glen Haven',
    'Glenwood Springs',
    'Golden',
    'Granada',
    'Granby',
    'Grand Junction',
    'Grand Lake',
    'Granite',
    'Grant',
    'Greeley',
    'Green Mountain Falls',
    'Grover',
    'Guffey',
    'Gulnare',
    'Gunnison',
    'Gypsum',
    'Hamilton',
    'Hartman',
    'Hartsel',
    'Hasty',
    'Haswell',
    'Haxtun',
    'Hayden',
    'Henderson',
    'Hereford',
    'Hesperus',
    'Hillrose',
    'Hillside',
    'Hoehne',
    'Holly',
    'Holyoke',
    'Homelake',
    'Hooper',
    'Hot Sulphur Springs',
    'Hotchkiss',
    'Howard',
    'Hudson',
    'Hugo',
    'Hygiene',
    'Idaho Springs',
    'Idalia',
    'Idledale',
    'Ignacio',
    'Iliff',
    'Indian Hills',
    'Jamestown',
    'Jaroso',
    'Jefferson',
    'Jelm',
    'Joes',
    'Johnstown',
    'Julesburg',
    'Karval',
    'Keenesburg',
    'Kersey',
    'Kim',
    'Kiowa',
    'Kirk',
    'Kit Carson',
    'Kittredge',
    'Kremmling',
    'La Jara',
    'La Junta',
    'La Salle',
    'La Veta',
    'Lafayette',
    'Lake City',
    'Lake George',
    'Lamar',
    'Laporte',
    'Larkspur',
    'Las Animas',
    'Lazear',
    'Leadville',
    'Lewis',
    'Limon',
    'Lindon',
    'Littleton',
    'Livermore',
    'Lochbuie',
    'Log Lane Village',
    'Loma',
    'Lone Tree',
    'Longmont',
    'Louisville',
    'Louviers',
    'Loveland',
    'Lucerne',
    'Lyons',
    'Mack',
    'Maher',
    'Manassa',
    'Mancos',
    'Manitou Springs',
    'Manzanola',
    'Marvel',
    'Masonville',
    'Matheson',
    'Maybell',
    'McClave',
    'McCoy',
    'Mead',
    'Meeker',
    'Meredith',
    'Merino',
    'Mesa',
    'Mesa Verde National Park',
    'Milliken',
    'Minturn',
    'Model',
    'Moffat',
    'Molina',
    'Monarch',
    'Monte Vista',
    'Montrose',
    'Monument',
    'Morrison',
    'Mosca',
    'Nathrop',
    'Naturita',
    'Nederland',
    'New Castle',
    'New Raymer',
    'Niwot',
    'Norwood',
    'Nucla',
    'Nunn',
    'Oak Creek',
    'Ohio City',
    'Olathe',
    'Olney Springs',
    'Ophir',
    'Orchard',
    'Ordway',
    'Otis',
    'Ouray',
    'Ovid',
    'Padroni',
    'Pagosa Springs',
    'Palisade',
    'Palmer Lake',
    'Paoli',
    'Paonia',
    'Parachute',
    'Paradox',
    'Parker',
    'Parlin',
    'Parshall',
    'Peetz',
    'Penrose',
    'Peyton',
    'Phippsburg',
    'Pierce',
    'Pine',
    'Pinecliffe',
    'Pitkin',
    'Placerville',
    'Platteville',
    'Pleasant View',
    'Poncha Springs',
    'Powderhorn',
    'Pritchett',
    'Pueblo',
    'Ramah',
    'Rand',
    'Rangely',
    'Red Cliff',
    'Red Feather Lakes',
    'Red Wing',
    'Redvale',
    'Rico',
    'Ridgway',
    'Rifle',
    'Rockvale',
    'Rocky Ford',
    'Roggen',
    'Rollinsville',
    'Romeo',
    'Rush',
    'Rye',
    'Saguache',
    'Salida',
    'San Luis',
    'San Pablo',
    'Sanford',
    'Sargents',
    'Sedalia',
    'Sedgwick',
    'Seibert',
    'Severance',
    'Shawnee',
    'Sheridan Lake',
    'Sherrelwood',
    'Silt',
    'Silver Plume',
    'Silverthorne',
    'Silverton',
    'Simla',
    'Slater',
    'Snowmass',
    'Snowmass Village',
    'Snyder',
    'Somerset',
    'South Fork',
    'Springfield',
    'Starkville',
    'Steamboat Springs',
    'Sterling',
    'Stoneham',
    'Strasburg',
    'Stratton',
    'Sugar City',
    'Swink',
    'Tabernash',
    'Telluride',
    'Thornton',
    'Timnath',
    'Toponas',
    'Towaoc',
    'Trinchera',
    'Trinidad',
    'Twin Lakes',
    'Two Buttes',
    'U S A F Academy',
    'Vail',
    'Vernon',
    'Victor',
    'Vilas',
    'Villa Grove',
    'Vona',
    'Walden',
    'Walsenburg',
    'Walsh',
    'Ward',
    'Watkins',
    'Weldona',
    'Wellington',
    'Westcliffe',
    'Westminster',
    'Weston',
    'Wetmore',
    'Wheat Ridge',
    'Whitewater',
    'Wiggins',
    'Wild Horse',
    'Wiley',
    'Windsor',
    'Winter Park',
    'Wolcott',
    'Woodland Park',
    'Woodrow',
    'Woody Creek',
    'Wray',
    'Yampa',
    'Yellow Jacket',
    'Yoder',
    'Yuma'
]
