cities = [
    'Abington',
    'Amston',
    'Andover',
    'Ansonia',
    'Ashford',
    'Avon',
    'Ballouville',
    'Baltic',
    'Bantam',
    'Beacon Falls',
    'Bethany',
    'Bethel',
    'Bethlehem',
    'Bloomfield',
    'Bolton',
    'Botsford',
    'Bozrah',
    'Branford',
    'Bridgeport',
    'Bridgewater',
    'Bristol',
    'Broad Brook',
    'Brookfield',
    'Brooklyn',
    'Burlington',
    'Canaan',
    'Canterbury',
    'Canton',
    'Canton Center',
    'Centerbrook',
    'Central Village',
    'Chaplin',
    'Cheshire',
    'Chester',
    'Clinton',
    'Cobalt',
    'Colchester',
    'Colebrook',
    'Collinsville',
    'Columbia',
    'Cornwall',
    'Cornwall Bridge',
    'Cos Cob',
    'Coventry',
    'Cromwell',
    'Danbury',
    'Danielson',
    'Darien',
    'Dayville',
    'Deep River',
    'Derby',
    'Durham',
    'East Berlin',
    'East Canaan',
    'East Glastonbury',
    'East Granby',
    'East Haddam',
    'East Hampton',
    'East Hartford',
    'East Hartland',
    'East Haven',
    'East Killingly',
    'East Lyme',
    'East Windsor',
    'East Windsor Hill',
    'East Woodstock',
    'Eastford',
    'Easton',
    'Ellington',
    'Enfield',
    'Essex',
    'Fabyan',
    'Fairfield',
    'Falls Village',
    'Farmington',
    'Gales Ferry',
    'Gaylordsville',
    'Georgetown',
    'Gilman',
    'Glasgo',
    'Glastonbury',
    'Goshen',
    'Granby',
    'Greens Farms',
    'Greenwich',
    'Grosvenor Dale',
    'Groton',
    'Guilford',
    'Haddam',
    'Hadlyme',
    'Hamden',
    'Hampton',
    'Hanover',
    'Hartford',
    'Harwinton',
    'Hawleyville',
    'Hebron',
    'Higganum',
    'Ivoryton',
    'Jewett City',
    'Kensington',
    'Kent',
    'Killingworth',
    'Lakeside',
    'Lakeville',
    'Lebanon',
    'Ledyard',
    'Litchfield',
    'Madison',
    'Manchester',
    'Mansfield Center',
    'Mansfield Depot',
    'Marion',
    'Marlborough',
    'Melrose',
    'Meriden',
    'Middle Haddam',
    'Middlebury',
    'Middlefield',
    'Middletown',
    'Milford',
    'Milldale',
    'Monroe',
    'Montville',
    'Moodus',
    'Moosup',
    'Morris',
    'Mystic',
    'Naugatuck',
    'New Britain',
    'New Canaan',
    'New Fairfield',
    'New Hartford',
    'New Haven',
    'New London',
    'New Milford',
    'New Preston Marble Dale',
    'Newington',
    'Newtown',
    'Niantic',
    'Norfolk',
    'North Branford',
    'North Canton',
    'North Franklin',
    'North Granby',
    'North Grosvenordale',
    'North Haven',
    'North Stonington',
    'North Westchester',
    'North Windham',
    'Northfield',
    'Northford',
    'Norwalk',
    'Norwich',
    'Oakdale',
    'Oakville',
    'Old Greenwich',
    'Old Lyme',
    'Old Mystic',
    'Old Saybrook',
    'Oneco',
    'Orange',
    'Oxford',
    'Pawcatuck',
    'Pequabuck',
    'Pine Meadow',
    'Plainfield',
    'Plainville',
    'Plantsville',
    'Pleasant Valley',
    'Plymouth',
    'Pomfret',
    'Pomfret Center',
    'Poquonock',
    'Portland',
    'Preston',
    'Prospect',
    'Putnam',
    'Quaker Hill',
    'Quinebaug',
    'Redding',
    'Redding Center',
    'Redding Ridge',
    'Ridgefield',
    'Riverside',
    'Riverton',
    'Rockfall',
    'Rocky Hill',
    'Rogers',
    'Roxbury',
    'Salem',
    'Salisbury',
    'Sandy Hook',
    'Scotland',
    'Seymour',
    'Sharon',
    'Shelton',
    'Sherman',
    'Simsbury',
    'Somers',
    'Somersville',
    'South Britain',
    'South Glastonbury',
    'South Kent',
    'South Lyme',
    'South Willington',
    'South Windham',
    'South Windsor',
    'South Woodstock',
    'Southbury',
    'Southington',
    'Southport',
    'Stafford',
    'Stafford Springs',
    'Staffordville',
    'Stamford',
    'Sterling',
    'Stevenson',
    'Stonington',
    'Storrs Mansfield',
    'Stratford',
    'Suffield',
    'Taconic',
    'Taftville',
    'Tariffville',
    'Terryville',
    'Thomaston',
    'Thompson',
    'Tolland',
    'Torrington',
    'Trumbull',
    'Uncasville',
    'Unionville',
    'Vernon Rockville',
    'Versailles',
    'Voluntown',
    'W Hartford',
    'Wallingford',
    'Washington',
    'Washington Depot',
    'Waterbury',
    'Waterford',
    'Watertown',
    'Wauregan',
    'Weatogue',
    'West Cornwall',
    'West Granby',
    'West Hartland',
    'West Haven',
    'West Mystic',
    'West Simsbury',
    'West Suffield',
    'Westbrook',
    'Weston',
    'Westport',
    'Wethersfield',
    'Willimantic',
    'Willington',
    'Wilton',
    'Winchester Center',
    'Windham',
    'Windsor',
    'Windsor Locks',
    'Winsted',
    'Wolcott',
    'Woodbridge',
    'Woodbury',
    'Woodstock',
    'Woodstock Valley',
    'Yantic'
]
