cities = [
    'Bear',
    'Bethany Beach',
    'Bethel',
    'Bridgeville',
    'Camden Wyoming',
    'Cheswold',
    'Claymont',
    'Clayton',
    'Dagsboro',
    'Delaware City',
    'Delmar',
    'Dover',
    'Dover AFB',
    'Ellendale',
    'Farmington',
    'Felton',
    'Fenwick Island',
    'Frankford',
    'Frederica',
    'Georgetown',
    'Greenwood',
    'Harbeson',
    'Harrington',
    'Hartly',
    'Hockessin',
    'Houston',
    'Kenton',
    'Kirkwood',
    'Laurel',
    'Lewes',
    'Lincoln',
    'Little Creek',
    'Magnolia',
    'Marydel',
    'Middletown',
    'Milford',
    'Millsboro',
    'Millville',
    'Milton',
    'Montchanin',
    'Nassau',
    'New Castle',
    'Newark',
    'Newport',
    'Ocean View',
    'Odessa',
    'Port Penn',
    'Rehoboth Beach',
    'Rockland',
    'Saint Georges',
    'Seaford',
    'Selbyville',
    'Smyrna',
    'Townsend',
    'Viola',
    'Wilmington',
    'Winterthur',
    'Woodside',
    'Yorklyn'
]
