cities = [
    'Alachua',
    'Alford',
    'Altamonte Springs',
    'Altha',
    'Altoona',
    'Alturas',
    'Alva',
    'Anna Maria',
    'Anthony',
    'Apalachicola',
    'Apollo Beach',
    'Apopka',
    'Arcadia',
    'Archer',
    'Argyle',
    'Aripeka',
    'Astatula',
    'Astor',
    'Atlantic Beach',
    'Auburndale',
    'Avon Park',
    'Babson Park',
    'Bagdad',
    'Baker',
    'Balm',
    'Barberville',
    'Bartow',
    'Bascom',
    'Bay Pines',
    'Bell',
    'Belle Glade',
    'Belleair Beach',
    'Belleview',
    'Beverly Hills',
    'Big Pine Key',
    'Blountstown',
    'Boca Grande',
    'Boca Raton',
    'Bokeelia',
    'Bonifay',
    'Bonita Springs',
    'Bostwick',
    'Bowling Green',
    'Boynton Beach',
    'Bradenton',
    'Bradenton Beach',
    'Bradley',
    'Brandon',
    'Branford',
    'Bristol',
    'Bronson',
    'Brooker',
    'Brooksville',
    'Bryant',
    'Bryceville',
    'Bunnell',
    'Bushnell',
    'Callahan',
    'Campbellton',
    'Canal Point',
    'Candler',
    'Cantonment',
    'Cape Canaveral',
    'Cape Coral',
    'Captiva',
    'Carrabelle',
    'Caryville',
    'Cassadaga',
    'Casselberry',
    'Cedar Key',
    'Center Hill',
    'Century',
    'Chattahoochee',
    'Chiefland',
    'Chipley',
    'Chokoloskee',
    'Christmas',
    'Citra',
    'Citrus Ridge',
    'Clarcona',
    'Clarksville',
    'Clearwater',
    'Clearwater Beach',
    'Clermont',
    'Clewiston',
    'Cocoa',
    'Cocoa Beach',
    'Coleman',
    'Copeland',
    'Cortez',
    'Cottondale',
    'Crawfordville',
    'Crescent City',
    'Crestview',
    'Cross City',
    'Crystal Beach',
    'Crystal River',
    'Crystal Springs',
    'Cypress',
    'Dade City',
    'Dania',
    'Davenport',
    'Day',
    'Daytona Beach',
    'De Leon Springs',
    'Debary',
    'Deerfield Beach',
    'Defuniak Springs',
    'Deland',
    'Delray Beach',
    'Deltona',
    'Destin',
    'Doctors Inlet',
    'Dover',
    'Dundee',
    'Dunedin',
    'Dunnellon',
    'Durant',
    'Eagle Lake',
    'Earleton',
    'East Palatka',
    'Eastlake Weir',
    'Eastpoint',
    'Eaton Park',
    'Ebro',
    'Edgewater',
    'Eglin AFB',
    'Elfers',
    'Elkton',
    'Ellenton',
    'Englewood',
    'Estero',
    'Eustis',
    'Everglades City',
    'Evinston',
    'Fairfield',
    'Fedhaven',
    'Felda',
    'Fellsmere',
    'Fernandina Beach',
    'Ferndale',
    'Flagler Beach',
    'Florahome',
    'Floral City',
    'Florida City',
    'Fort Lauderdale',
    'Fort McCoy',
    'Fort Meade',
    'Fort Myers',
    'Fort Myers Beach',
    'Fort Ogden',
    'Fort Pierce',
    'Fort Walton Beach',
    'Fort White',
    'Fountain',
    'Freeport',
    'Frostproof',
    'Fruitland Park',
    'Gainesville',
    'Geneva',
    'Georgetown',
    'Gibsonton',
    'Glen Saint Mary',
    'Glenwood',
    'Goldenrod',
    'Gonzalez',
    'Goodland',
    'Gotha',
    'Graceville',
    'Graham',
    'Grand Island',
    'Grand Ridge',
    'Grandin',
    'Grant',
    'Green Cove Springs',
    'Greensboro',
    'Greenville',
    'Greenwood',
    'Gretna',
    'Grove City',
    'Groveland',
    'Gulf Breeze',
    'Gulf Hammock',
    'Haines City',
    'Hallandale',
    'Hampton',
    'Harold',
    'Hastings',
    'Havana',
    'Hawthorne',
    'Heathrow',
    'Hernando',
    'Hialeah',
    'High Springs',
    'Highland City',
    'Highland Park',
    'Hilliard',
    'Hobe Sound',
    'Holder',
    'Holiday',
    'Hollister',
    'Hollywood',
    'Holmes Beach',
    'Holt',
    'Homeland',
    'Homestead',
    'Homosassa',
    'Homosassa Springs',
    'Horseshoe Beach',
    'Hosford',
    'Howey In The Hills',
    'Hudson',
    'Hunters Creek',
    'Hurlburt Field',
    'Immokalee',
    'Indialantic',
    'Indian Lake Estates',
    'Indian Rocks Beach',
    'Indiantown',
    'Inglis',
    'Intercession City',
    'Interlachen',
    'Inverness',
    'Islamorada',
    'Island Grove',
    'Istachatta',
    'Jacksonville',
    'Jacksonville Beach',
    'Jasper',
    'Jay',
    'Jennings',
    'Jensen Beach',
    'Jupiter',
    'Kathleen',
    'Kenansville',
    'Key Biscayne',
    'Key Colony Beach',
    'Key Largo',
    'Key West',
    'Keystone Heights',
    'Killarney',
    'Kinard',
    'Kissimmee',
    'La Crosse',
    'Labelle',
    'Lacoochee',
    'Lady Lake',
    'Lake Alfred',
    'Lake Butler',
    'Lake Butter',
    'Lake City',
    'Lake Como',
    'Lake Geneva',
    'Lake Hamilton',
    'Lake Harbor',
    'Lake Helen',
    'Lake Lucerne',
    'Lake Mary',
    'Lake Monroe',
    'Lake Panasoffkee',
    'Lake Placid',
    'Lake Wales',
    'Lake Worth',
    'Lakeland',
    'Lamont',
    'Lanark Village',
    'Land O Lakes',
    'Lantana',
    'Largo',
    'Laurel',
    'Laurel Hill',
    'Lawtey',
    'Lecanto',
    'Lee',
    'Leesburg',
    'Lehigh Acres',
    'Lithia',
    'Live Oak',
    'Lloyd',
    'Lochloosa',
    'Long Key',
    'Longboat Key',
    'Longwood',
    'Lorida',
    'Loughman',
    'Lowell',
    'Loxahatchee',
    'Lulu',
    'Lutz',
    'Lynn Haven',
    'Macclenny',
    'Madison',
    'Maitland',
    'Malabar',
    'Malone',
    'Manasota',
    'Mango',
    'Marathon',
    'Marathon Shores',
    'Marco Island',
    'Marianna',
    'Mary Esther',
    'Mascotte',
    'Mayo',
    'McAlpin',
    'McDavid',
    'McIntosh',
    'Melbourne',
    'Melbourne Beach',
    'Melrose',
    'Memphis',
    'Merritt Island',
    'Mexico Beach',
    'Miami',
    'Miami Beach',
    'Micanopy',
    'Miccosukee Cpo',
    'Mid Florida',
    'Middleburg',
    'Midway',
    'Milligan',
    'Milton',
    'Mims',
    'Minneola',
    'Miramar Beach',
    'Molino',
    'Monticello',
    'Montverde',
    'Moore Haven',
    'Morriston',
    'Mossy Head',
    'Mount Dora',
    'Mount Pleasant',
    'Mulberry',
    'Murdock',
    'Myakka City',
    'Myrtle Grove',
    'Nalcrest',
    'Naples',
    'Neptune Beach',
    'New Port Richey',
    'New Smyrna Beach',
    'Newberry',
    'Niceville',
    'Nichols',
    'Nobleton',
    'Nocatee',
    'Nokomis',
    'Noma',
    'North Fort Myers',
    'North Miami Beach',
    'North Palm Beach',
    'North Port',
    'O Brien',
    'Oak Hill',
    'Oakland',
    'Ocala',
    'Ochopee',
    'Ocklawaha',
    'Ocoee',
    'Odessa',
    'Okahumpka',
    'Okeechobee',
    'Old Town',
    'Oldsmar',
    'Olustee',
    'Ona',
    'Oneco',
    'Opa Locka',
    'Orange City',
    'Orange Lake',
    'Orange Park',
    'Orange Springs',
    'Orlando',
    'Ormond Beach',
    'Osprey',
    'Osteen',
    'Otter Creek',
    'Oviedo',
    'Oxford',
    'Ozona',
    'Pahokee',
    'Paisley',
    'Palatka',
    'Palm Bay',
    'Palm Beach',
    'Palm City',
    'Palm Coast',
    'Palm Harbor',
    'Palm River-Clair Mel',
    'Palm Valley',
    'Palmdale',
    'Palmetto',
    'Panacea',
    'Panama City',
    'Panama City Beach',
    'Parrish',
    'Patrick AFB',
    'Paxton',
    'Pembroke Pines',
    'Penney Farms',
    'Pensacola',
    'Perry',
    'Pierson',
    'Pine Island Ridge',
    'Pine Ridge',
    'Pineland',
    'Pinellas Park',
    'Pinetta',
    'Placida',
    'Plant City',
    'Plymouth',
    'Point Washington',
    'Polk City',
    'Pomona Park',
    'Pompano Beach',
    'Ponce De Leon',
    'Ponte Vedra Beach',
    'Port Charlotte',
    'Port Orange',
    'Port Richey',
    'Port Saint Joe',
    'Port Saint Lucie',
    'Port Salerno',
    'Port St. Lucie',
    'Punta Gorda',
    'Putnam Hall',
    'Quincy',
    'Raiford',
    'Reddick',
    'River Ranch',
    'Riverview',
    'Rockledge',
    'Roseland',
    'Rotonda West',
    'Ruskin',
    'Safety Harbor',
    'Saint Augustine',
    'Saint Cloud',
    'Saint James City',
    'Saint Leo',
    'Saint Marks',
    'Saint Petersburg',
    'Salem',
    'San Antonio',
    'San Mateo',
    'Sanderson',
    'Sanford',
    'Sanibel',
    'Santa Rosa Beach',
    'Sarasota',
    'Satellite Beach',
    'Satsuma',
    'Scottsmoor',
    'Sebastian',
    'Sebring',
    'Seffner',
    'Seminole',
    'Seville',
    'Shady Grove',
    'Shalimar',
    'Sharpes',
    'Silver Springs',
    'Sneads',
    'Sopchoppy',
    'Sorrento',
    'South Bay',
    'Sparr',
    'Spring Hill',
    'St. Augustine',
    'St. Leo',
    'Starke',
    'Steinhatchee',
    'Stuart',
    'Sugarloaf Shores',
    'Sumatra',
    'Summerfield',
    'Summerland Key',
    'Sumterville',
    'Sun City',
    'Sun City Center',
    'Sunnyside',
    'Suwannee',
    'Sydney',
    'Tallahassee',
    'Tallevast',
    'Tampa',
    'Tangerine',
    'Tarpon Springs',
    'Tavares',
    'Tavernier',
    'Telogia',
    'Terra Ceia',
    'The Villages',
    'Thonotosassa',
    'Titusville',
    'Trenton',
    'Trilby',
    'Umatilla',
    'Valparaiso',
    'Valrico',
    'Vanderbilt Beach',
    'Venice',
    'Venus',
    'Vernon',
    'Vero Beach',
    'Wabasso',
    'Wacissa',
    'Wakulla Springs',
    'Waldo',
    'Wauchula',
    'Wausau',
    'Waverly',
    'Webster',
    'Weirsdale',
    'Welaka',
    'Wellborn',
    'West Little River',
    'West Palm Beach',
    'Weston',
    'Westville',
    'Wewahitchka',
    'White Springs',
    'Wildwood',
    'Williston',
    'Wimauma',
    'Windermere',
    'Winter Beach',
    'Winter Garden',
    'Winter Haven',
    'Winter Park',
    'Winter Springs',
    'Woodville',
    'Worthington Springs',
    'Yalaha',
    'Yankeetown',
    'Youngstown',
    'Yulee',
    'Zellwood',
    'Zephyrhills',
    'Zolfo Springs'
]
