cities = [
    'Aiea',
    'Anahola',
    'Captain Cook',
    'Eleele',
    'Ewa Beach',
    'Haiku',
    'Hakalau',
    'Haleiwa',
    'Hana',
    'Hanalei',
    'Hanamaulu',
    'Hanapepe',
    'Hauula',
    'Hawaiian Ocean View',
    'Hawi',
    'Hilo',
    'Holualoa',
    'Honaunau',
    'Honokaa',
    'Honolulu',
    'Honomu',
    'Hoolehua',
    'Kaaawa',
    'Kahuku',
    'Kahului',
    'Kailua',
    'Kailua Kona',
    'Kalaheo',
    'Kalaupapa',
    'Kamuela',
    'Kaneohe',
    'Kapaa',
    'Kapaau',
    'Kapolei',
    'Kaumakani',
    'Kaunakakai',
    'Kawela Bay',
    'Keaau',
    'Kealakekua',
    'Kealia',
    'Keauhou',
    'Kekaha',
    'Kihei',
    'Kilauea',
    'Koloa',
    'Kualapuu',
    'Kula',
    'Kunia',
    'Kurtistown',
    'Lahaina',
    'Laie',
    'Lanai City',
    'Laupahoehoe',
    'Lawai',
    'Lihue',
    'Makawao',
    'Makaweli',
    'Maunaloa',
    'Mililani',
    'Mountain View',
    'Naalehu',
    'Ninole',
    'Ocean View',
    'Ookala',
    'Paauhau',
    'Paauilo',
    'Pahala',
    'Pahoa',
    'Paia',
    'Papaaloa',
    'Papaikou',
    'Pearl City',
    'Pearl Harbor',
    'Pepeekeo',
    'Princeville',
    'Pukalani',
    'Puunene',
    'Volcano',
    'Wahiawa',
    'Waialua',
    'Waianae',
    'Waikoloa',
    'Wailuku',
    'Waimanalo',
    'Waimea',
    'Waipahu',
    'Wake Island'
]
