cities = [
    'Aberdeen',
    'Ahsahka',
    'Albion',
    'Almo',
    'American Falls',
    'Arbon',
    'Arco',
    'Arimo',
    'Ashton',
    'Athol',
    'Atlanta',
    'Atomic City',
    'Avery',
    'Bancroft',
    'Banks',
    'Basalt',
    'Bayview',
    'Bellevue',
    'Bern',
    'Blackfoot',
    'Blanchard',
    'Bliss',
    'Bloomington',
    'Boise',
    'Bonners Ferry',
    'Bovill',
    'Bruneau',
    'Buhl',
    'Burley',
    'Calder',
    'Caldwell',
    'Cambridge',
    'Carey',
    'Careywood',
    'Carmen',
    'Cascade',
    'Castleford',
    'Cataldo',
    'Challis',
    'Chester',
    'Clark Fork',
    'Clarkia',
    'Clayton',
    'Clifton',
    'Cobalt',
    'Cocolalla',
    'Coeur D Alene',
    'Colburn',
    'Conda',
    'Coolin',
    'Corral',
    'Cottonwood',
    'Council',
    'Craigmont',
    'Culdesac',
    'Dayton',
    'Deary',
    'Declo',
    'Desmet',
    'Dietrich',
    'Dingle',
    'Donnelly',
    'Dover',
    'Downey',
    'Driggs',
    'Dubois',
    'Eagle',
    'Eastport',
    'Eden',
    'Elk City',
    'Elk River',
    'Ellis',
    'Emmett',
    'Fairfield',
    'Farmington',
    'Felt',
    'Fenn',
    'Ferdinand',
    'Fernwood',
    'Filer',
    'Firth',
    'Fish Haven',
    'Fort Hall',
    'Franklin',
    'Freedom',
    'Fruitland',
    'Fruitvale',
    'Garden Valley',
    'Genesee',
    'Geneva',
    'Georgetown',
    'Gibbonsville',
    'Glenns Ferry',
    'Gooding',
    'Grace',
    'Grand View',
    'Grangeville',
    'Greencreek',
    'Greenleaf',
    'Hagerman',
    'Hailey',
    'Hamer',
    'Hammett',
    'Hansen',
    'Harrison',
    'Harvard',
    'Hayden',
    'Hazelton',
    'Heyburn',
    'Hill City',
    'Holbrook',
    'Homedale',
    'Hope',
    'Horseshoe Bend',
    'Howe',
    'Huston',
    'Idaho City',
    'Idaho Falls',
    'Indian Valley',
    'Inkom',
    'Iona',
    'Irwin',
    'Island Park',
    'Jerome',
    'Jordan Valley',
    'Juliaetta',
    'Kamiah',
    'Kellogg',
    'Kendrick',
    'Ketchum',
    'Kimberly',
    'King Hill',
    'Kingston',
    'Kooskia',
    'Kootenai',
    'Kuna',
    'Laclede',
    'Lake Fork',
    'Lapwai',
    'Lava Hot Springs',
    'Leadore',
    'Lemhi',
    'Lenore',
    'Letha',
    'Lewiston',
    'Lewisville',
    'Lowman',
    'Lucile',
    'Mackay',
    'Macks Inn',
    'Malad City',
    'Malta',
    'Marsing',
    'May',
    'McCall',
    'McCammon',
    'Medimont',
    'Melba',
    'Menan',
    'Meridian',
    'Mesa',
    'Middleton',
    'Midvale',
    'Minidoka',
    'Monteview',
    'Montpelier',
    'Moore',
    'Moreland',
    'Moscow',
    'Mountain Home',
    'Mountain Home A F B',
    'Moyie Springs',
    'Mullan',
    'Murphy',
    'Murray',
    'Murtaugh',
    'Nampa',
    'Naples',
    'New Meadows',
    'New Plymouth',
    'Newdale',
    'Nezperce',
    'Nordman',
    'North Fork',
    'Notus',
    'Nyssa',
    'Oakley',
    'Ola',
    'Oldtown',
    'Orofino',
    'Osburn',
    'Paris',
    'Parker',
    'Parma',
    'Paul',
    'Payette',
    'Peck',
    'Picabo',
    'Pierce',
    'Pinehurst',
    'Pingree',
    'Placerville',
    'Plummer',
    'Pocatello',
    'Pollock',
    'Ponderay',
    'Porthill',
    'Post Falls',
    'Potlatch',
    'Preston',
    'Priest River',
    'Princeton',
    'Rathdrum',
    'Reubens',
    'Rexburg',
    'Richfield',
    'Rigby',
    'Riggins',
    'Ririe',
    'Roberts',
    'Rockland',
    'Rogerson',
    'Rupert',
    'Sagle',
    'Saint Anthony',
    'Saint Charles',
    'Saint Maries',
    'Salmon',
    'Samuels',
    'Sandpoint',
    'Santa',
    'Shelley',
    'Shoshone',
    'Shoup',
    'Silverton',
    'Smelterville',
    'Soda Springs',
    'Spalding',
    'Spencer',
    'Spirit Lake',
    'Springfield',
    'Squirrel',
    'Stanley',
    'Star',
    'Stites',
    'Sugar City',
    'Sun Valley',
    'Swan Valley',
    'Swanlake',
    'Sweet',
    'Tendoy',
    'Tensed',
    'Terreton',
    'Teton',
    'Tetonia',
    'Thatcher',
    'Troy',
    'Twin Falls',
    'Ucon',
    'Victor',
    'Viola',
    'Wallace',
    'Warren',
    'Wayan',
    'Weippe',
    'Weiser',
    'Wendell',
    'Weston',
    'White Bird',
    'Wilder',
    'Winchester',
    'Worley',
    'Yellow Pine'
]
