cities = [
    'Ackley',
    'Ackworth',
    'Adair',
    'Adel',
    'Afton',
    'Agency',
    'Ainsworth',
    'Akron',
    'Albert City',
    'Albia',
    'Albion',
    'Alburnett',
    'Alden',
    'Alexander',
    'Algona',
    'Alleman',
    'Allendorf',
    'Allerton',
    'Allison',
    'Alta',
    'Alta Vista',
    'Alton',
    'Altoona',
    'Alvord',
    'Amana',
    'Ames',
    'Anamosa',
    'Andover',
    'Andrew',
    'Anita',
    'Ankeny',
    'Anthon',
    'Aplington',
    'Arcadia',
    'Archer',
    'Aredale',
    'Argyle',
    'Arion',
    'Arispe',
    'Arlington',
    'Armstrong',
    'Arnolds Park',
    'Arthur',
    'Ashton',
    'Aspinwall',
    'Atalissa',
    'Atkins',
    'Atlantic',
    'Auburn',
    'Audubon',
    'Aurelia',
    'Aurora',
    'Austinville',
    'Avoca',
    'Ayrshire',
    'Badger',
    'Bagley',
    'Baldwin',
    'Bancroft',
    'Barnes City',
    'Barnum',
    'Batavia',
    'Battle Creek',
    'Baxter',
    'Bayard',
    'Beacon',
    'Beaman',
    'Beaver',
    'Bedford',
    'Belle Plaine',
    'Bellevue',
    'Belmond',
    'Bennett',
    'Benton',
    'Bernard',
    'Berwick',
    'Bettendorf',
    'Bevington',
    'Birmingham',
    'Blairsburg',
    'Blairstown',
    'Blakesburg',
    'Blanchard',
    'Blencoe',
    'Blockton',
    'Bloomfield',
    'Blue Grass',
    'Bode',
    'Bonaparte',
    'Bondurant',
    'Boone',
    'Booneville',
    'Bouton',
    'Boxholm',
    'Boyden',
    'Braddyville',
    'Bradford',
    'Bradgate',
    'Brandon',
    'Brayton',
    'Breda',
    'Bridgewater',
    'Brighton',
    'Bristow',
    'Britt',
    'Bronson',
    'Brooklyn',
    'Brunsville',
    'Bryant',
    'Buckeye',
    'Buckingham',
    'Buffalo',
    'Buffalo Center',
    'Burlington',
    'Burnside',
    'Burr Oak',
    'Burt',
    'Bussey',
    'Calamus',
    'Callender',
    'Calmar',
    'Calumet',
    'Camanche',
    'Cambridge',
    'Cantril',
    'Carbon',
    'Carlisle',
    'Carpenter',
    'Carroll',
    'Carson',
    'Carter Lake',
    'Cascade',
    'Casey',
    'Castalia',
    'Castana',
    'Cedar',
    'Cedar Falls',
    'Cedar Rapids',
    'Center Junction',
    'Center Point',
    'Centerville',
    'Central City',
    'Chapin',
    'Chariton',
    'Charles City',
    'Charlotte',
    'Charter Oak',
    'Chatsworth',
    'Chelsea',
    'Cherokee',
    'Chester',
    'Chillicothe',
    'Churdan',
    'Cincinnati',
    'Clare',
    'Clarence',
    'Clarinda',
    'Clarion',
    'Clarksville',
    'Clear Lake',
    'Clearfield',
    'Cleghorn',
    'Clemons',
    'Clermont',
    'Climbing Hill',
    'Clinton',
    'Clio',
    'Clive',
    'Clutier',
    'Coggon',
    'Coin',
    'Colesburg',
    'Colfax',
    'College Springs',
    'Collins',
    'Colo',
    'Columbia',
    'Columbus City',
    'Columbus Junction',
    'Colwell',
    'Conesville',
    'Conrad',
    'Conroy',
    'Coon Rapids',
    'Cooper',
    'Coralville',
    'Corning',
    'Correctionville',
    'Corwith',
    'Corydon',
    'Coulter',
    'Council Bluffs',
    'Craig',
    'Crawfordsville',
    'Crescent',
    'Cresco',
    'Creston',
    'Cromwell',
    'Crystal Lake',
    'Cumberland',
    'Cumming',
    'Curlew',
    'Cushing',
    'Cylinder',
    'Dakota City',
    'Dallas',
    'Dallas Center',
    'Dana',
    'Danbury',
    'Danville',
    'Davenport',
    'Davis City',
    'Dawson',
    'Dayton',
    'De Soto',
    'De Witt',
    'Decatur',
    'Decorah',
    'Dedham',
    'Deep River',
    'Defiance',
    'Delaware',
    'Delhi',
    'Delmar',
    'Deloit',
    'Delta',
    'Denison',
    'Denmark',
    'Denver',
    'Derby',
    'Des Moines',
    'Dewar',
    'Dexter',
    'Diagonal',
    'Dickens',
    'Dike',
    'Dixon',
    'Dolliver',
    'Donahue',
    'Donnellson',
    'Doon',
    'Dorchester',
    'Douds',
    'Dougherty',
    'Dow City',
    'Dows',
    'Drakesville',
    'Dubuque',
    'Dumont',
    'Duncombe',
    'Dundee',
    'Dunkerton',
    'Dunlap',
    'Durango',
    'Durant',
    'Dyersville',
    'Dysart',
    'Eagle Grove',
    'Earlham',
    'Earling',
    'Earlville',
    'Early',
    'Eddyville',
    'Edgewood',
    'Elberon',
    'Eldon',
    'Eldora',
    'Eldridge',
    'Elgin',
    'Elk Horn',
    'Elkader',
    'Elkhart',
    'Elkport',
    'Elliott',
    'Ellston',
    'Ellsworth',
    'Elma',
    'Elmore',
    'Elwood',
    'Ely',
    'Emerson',
    'Emmetsburg',
    'Epworth',
    'Essex',
    'Estherville',
    'Evansdale',
    'Everly',
    'Exira',
    'Exline',
    'Fairbank',
    'Fairfax',
    'Fairfield',
    'Farley',
    'Farmersburg',
    'Farmington',
    'Farnhamville',
    'Farragut',
    'Fayette',
    'Fenton',
    'Ferguson',
    'Fertile',
    'Floris',
    'Floyd',
    'Fonda',
    'Fontanelle',
    'Forest City',
    'Fort Atkinson',
    'Fort Dodge',
    'Fort Madison',
    'Fostoria',
    'Fredericksburg',
    'Frederika',
    'Fremont',
    'Fruitland',
    'Galt',
    'Galva',
    'Garber',
    'Garden City',
    'Garden Grove',
    'Garnavillo',
    'Garner',
    'Garrison',
    'Garwin',
    'Geneva',
    'George',
    'Gibson',
    'Gifford',
    'Gilbert',
    'Gilbertville',
    'Gillett Grove',
    'Gilman',
    'Gilmore City',
    'Gladbrook',
    'Glenwood',
    'Glidden',
    'Goldfield',
    'Goodell',
    'Goose Lake',
    'Gowrie',
    'Graettinger',
    'Grafton',
    'Grand Junction',
    'Grand Mound',
    'Grand River',
    'Grandview',
    'Granger',
    'Grant',
    'Granville',
    'Gravity',
    'Gray',
    'Greeley',
    'Greene',
    'Greenfield',
    'Greenville',
    'Grimes',
    'Grinnell',
    'Griswold',
    'Grundy Center',
    'Gruver',
    'Guernsey',
    'Guthrie Center',
    'Guttenberg',
    'Halbur',
    'Hamburg',
    'Hamilton',
    'Hamlin',
    'Hampton',
    'Hancock',
    'Hanlontown',
    'Harcourt',
    'Hardy',
    'Harlan',
    'Harper',
    'Harpers Ferry',
    'Harris',
    'Hartford',
    'Hartley',
    'Hartwick',
    'Harvey',
    'Hastings',
    'Havelock',
    'Haverhill',
    'Hawarden',
    'Hawkeye',
    'Hayesville',
    'Hazleton',
    'Hedrick',
    'Henderson',
    'Hiawatha',
    'Highlandville',
    'Hills',
    'Hillsboro',
    'Hinton',
    'Holland',
    'Holstein',
    'Holy Cross',
    'Homestead',
    'Honey Creek',
    'Hopkinton',
    'Hornick',
    'Hospers',
    'Houghton',
    'Hubbard',
    'Hudson',
    'Hull',
    'Humboldt',
    'Humeston',
    'Huxley',
    'Ida Grove',
    'Imogene',
    'Independence',
    'Indianola',
    'Inwood',
    'Ionia',
    'Iowa City',
    'Iowa Falls',
    'Ira',
    'Ireton',
    'Irwin',
    'Jamaica',
    'Janesville',
    'Jefferson',
    'Jesup',
    'Jewell',
    'Johnston',
    'Joice',
    'Jolley',
    'Kalona',
    'Kamrar',
    'Kanawha',
    'Kellerton',
    'Kelley',
    'Kellogg',
    'Kensett',
    'Keokuk',
    'Keosauqua',
    'Keota',
    'Kesley',
    'Keswick',
    'Keystone',
    'Killduff',
    'Kimballton',
    'Kingsley',
    'Kirkman',
    'Kirkville',
    'Kiron',
    'Klemme',
    'Knierim',
    'Knoxville',
    'La Motte',
    'La Porte City',
    'Lacona',
    'Ladora',
    'Lake City',
    'Lake Mills',
    'Lake Park',
    'Lake View',
    'Lakota',
    'Lamoni',
    'Lamont',
    'Lanesboro',
    'Langworthy',
    'Lansing',
    'Larchwood',
    'Larrabee',
    'Latimer',
    'Laurel',
    'Laurens',
    'Lawler',
    'Lawton',
    'Le Claire',
    'Le Grand',
    'Le Mars',
    'Ledyard',
    'Lehigh',
    'Leighton',
    'Leland',
    'Lenox',
    'Leon',
    'Lester',
    'Letts',
    'Lewis',
    'Liberty Center',
    'Libertyville',
    'Lidderdale',
    'Lime Springs',
    'Lincoln',
    'Linden',
    'Lineville',
    'Linn Grove',
    'Lisbon',
    'Liscomb',
    'Little Cedar',
    'Little Rock',
    'Little Sioux',
    'Littleport',
    'Livermore',
    'Lockridge',
    'Logan',
    'Lohrville',
    'Lone Rock',
    'Lone Tree',
    'Long Grove',
    'Lorimor',
    'Lost Nation',
    'Lovilia',
    'Low Moor',
    'Lowden',
    'Lu Verne',
    'Luana',
    'Lucas',
    'Luther',
    'Luxemburg',
    'Luzerne',
    'Lynnville',
    'Lytton',
    'Mabel',
    'Macedonia',
    'Macksburg',
    'Madrid',
    'Magnolia',
    'Malcom',
    'Mallard',
    'Malvern',
    'Manchester',
    'Manilla',
    'Manly',
    'Manning',
    'Manson',
    'Mapleton',
    'Maquoketa',
    'Marathon',
    'Marble Rock',
    'Marcus',
    'Marengo',
    'Marion',
    'Marne',
    'Marquette',
    'Marshalltown',
    'Martelle',
    'Martensdale',
    'Martinsburg',
    'Mason City',
    'Masonville',
    'Massena',
    'Matlock',
    'Maurice',
    'Maxwell',
    'May City',
    'Maynard',
    'McCallsburg',
    'McCausland',
    'McClelland',
    'McGregor',
    'McIntire',
    'Mechanicsville',
    'Mediapolis',
    'Melbourne',
    'Melcher',
    'Melrose',
    'Melvin',
    'Menlo',
    'Meriden',
    'Merrill',
    'Meservey',
    'Middle Amana',
    'Middletown',
    'Miles',
    'Milford',
    'Millersburg',
    'Millerton',
    'Milo',
    'Milton',
    'Minburn',
    'Minden',
    'Mineola',
    'Mingo',
    'Missouri Valley',
    'Mitchellville',
    'Modale',
    'Mondamin',
    'Monmouth',
    'Monona',
    'Monroe',
    'Montezuma',
    'Monticello',
    'Montour',
    'Montpelier',
    'Montrose',
    'Moorhead',
    'Moorland',
    'Moravia',
    'Morley',
    'Morning Sun',
    'Morrison',
    'Moscow',
    'Moulton',
    'Mount Auburn',
    'Mount Ayr',
    'Mount Pleasant',
    'Mount Sterling',
    'Mount Union',
    'Mount Vernon',
    'Moville',
    'Murray',
    'Mystic',
    'Nashua',
    'Nemaha',
    'Neola',
    'Nevada',
    'New Albin',
    'New Hampton',
    'New Hartford',
    'New Liberty',
    'New London',
    'New Market',
    'New Providence',
    'New Sharon',
    'New Vienna',
    'New Virginia',
    'Newell',
    'Newhall',
    'Newton',
    'Nichols',
    'Nodaway',
    'Nora Springs',
    'North Buena Vista',
    'North English',
    'North Liberty',
    'North Washington',
    'Northboro',
    'Northwood',
    'Norwalk',
    'Norway',
    'Oakdale',
    'Oakland',
    'Oakville',
    'Ocheyedan',
    'Odebolt',
    'Oelwein',
    'Ogden',
    'Okoboji',
    'Olds',
    'Olin',
    'Ollie',
    'Onawa',
    'Onslow',
    'Oran',
    'Orange City',
    'Orchard',
    'Orient',
    'Osage',
    'Osceola',
    'Oskaloosa',
    'Ossian',
    'Otho',
    'Otley',
    'Oto',
    'Ottosen',
    'Ottumwa',
    'Oxford',
    'Oxford Junction',
    'Oyens',
    'Pacific Junction',
    'Packwood',
    'Palmer',
    'Palo',
    'Panama',
    'Panora',
    'Parkersburg',
    'Parnell',
    'Paton',
    'Patterson',
    'Paullina',
    'Pella',
    'Peosta',
    'Percival',
    'Perry',
    'Persia',
    'Peru',
    'Peterson',
    'Pierson',
    'Pilot Grove',
    'Pilot Mound',
    'Pisgah',
    'Plainfield',
    'Plano',
    'Pleasant Hill',
    'Pleasant Valley',
    'Pleasantville',
    'Plover',
    'Plymouth',
    'Pocahontas',
    'Polk City',
    'Pomeroy',
    'Popejoy',
    'Portsmouth',
    'Postville',
    'Prairie City',
    'Prairieburg',
    'Prescott',
    'Preston',
    'Primghar',
    'Princeton',
    'Prole',
    'Promise City',
    'Protivin',
    'Pulaski',
    'Quasqueton',
    'Quimby',
    'Radcliffe',
    'Rake',
    'Ralston',
    'Randalia',
    'Randall',
    'Randolph',
    'Raymond',
    'Readlyn',
    'Reasnor',
    'Red Oak',
    'Redding',
    'Redfield',
    'Reinbeck',
    'Rembrandt',
    'Remsen',
    'Renwick',
    'Rhodes',
    'Riceville',
    'Richland',
    'Ricketts',
    'Ridgeway',
    'Rinard',
    'Ringsted',
    'Rippey',
    'Riverside',
    'Riverton',
    'Robins',
    'Rock Falls',
    'Rock Rapids',
    'Rock Valley',
    'Rockford',
    'Rockwell',
    'Rockwell City',
    'Rodney',
    'Roland',
    'Rolfe',
    'Rome',
    'Rose Hill',
    'Rowan',
    'Rowley',
    'Royal',
    'Rudd',
    'Runnells',
    'Russell',
    'Ruthven',
    'Rutland',
    'Ryan',
    'Sabula',
    'Sac City',
    'Saint Ansgar',
    'Saint Anthony',
    'Saint Charles',
    'Saint Donatus',
    'Saint Lucas',
    'Saint Marys',
    'Saint Olaf',
    'Saint Paul',
    'Salem',
    'Salix',
    'Sanborn',
    'Scarville',
    'Schaller',
    'Schleswig',
    'Scranton',
    'Searsboro',
    'Selma',
    'Sergeant Bluff',
    'Seymour',
    'Shambaugh',
    'Shannon City',
    'Sharpsburg',
    'Sheffield',
    'Shelby',
    'Sheldahl',
    'Sheldon',
    'Shell Rock',
    'Shellsburg',
    'Shenandoah',
    'Sherrill',
    'Sibley',
    'Sidney',
    'Sigourney',
    'Silver City',
    'Sioux Center',
    'Sioux City',
    'Sioux Rapids',
    'Slater',
    'Sloan',
    'Smithland',
    'Soldier',
    'Solon',
    'Somers',
    'South Amana',
    'South English',
    'Spencer',
    'Sperry',
    'Spillville',
    'Spirit Lake',
    'Spragueville',
    'Springbrook',
    'Springville',
    'Stacyville',
    'Stanhope',
    'Stanley',
    'Stanton',
    'Stanwood',
    'State Center',
    'Steamboat Rock',
    'Stockport',
    'Stockton',
    'Storm Lake',
    'Story City',
    'Stout',
    'Stratford',
    'Strawberry Point',
    'Struble',
    'Stuart',
    'Sully',
    'Sumner',
    'Superior',
    'Sutherland',
    'Swaledale',
    'Swan',
    'Swea City',
    'Swedesburg',
    'Swisher',
    'Tabor',
    'Tama',
    'Teeds Grove',
    'Templeton',
    'Tennant',
    'Terril',
    'Thayer',
    'Thompson',
    'Thor',
    'Thornburg',
    'Thornton',
    'Thurman',
    'Tiffin',
    'Tingley',
    'Tipton',
    'Titonka',
    'Toddville',
    'Toeterville',
    'Toledo',
    'Tracy',
    'Traer',
    'Treynor',
    'Tripoli',
    'Troy Mills',
    'Truesdale',
    'Truro',
    'Turin',
    'Udell',
    'Underwood',
    'Union',
    'Unionville',
    'University Park',
    'Urbana',
    'Urbandale',
    'Ute',
    'Vail',
    'Van Horne',
    'Van Meter',
    'Van Wert',
    'Varina',
    'Ventura',
    'Victor',
    'Villisca',
    'Vincent',
    'Vining',
    'Vinton',
    'Viola',
    'Volga',
    'Wadena',
    'Walcott',
    'Walford',
    'Walker',
    'Wall Lake',
    'Wallingford',
    'Walnut',
    'Wapello',
    'Washington',
    'Washta',
    'Waterloo',
    'Waterville',
    'Watkins',
    'Waucoma',
    'Waukee',
    'Waukon',
    'Waverly',
    'Wayland',
    'Webb',
    'Webster',
    'Webster City',
    'Weldon',
    'Wellman',
    'Wellsburg',
    'Welton',
    'Wesley',
    'West Bend',
    'West Branch',
    'West Burlington',
    'West Chester',
    'West Des Moines',
    'West Grove',
    'West Liberty',
    'West Point',
    'West Union',
    'Westfield',
    'Westgate',
    'Westphalia',
    'Westside',
    'Wever',
    'What Cheer',
    'Wheatland',
    'Whiting',
    'Whittemore',
    'Whitten',
    'Williams',
    'Williamsburg',
    'Williamson',
    'Wilton',
    'Winfield',
    'Winterset',
    'Winthrop',
    'Wiota',
    'Woden',
    'Woodbine',
    'Woodburn',
    'Woodward',
    'Woolstock',
    'Worthington',
    'Wyoming',
    'Yale',
    'Yarmouth',
    'Yorktown',
    'Zearing',
    'Zwingle'
]
