cities = [
    'Abbyville',
    'Abilene',
    'Admire',
    'Agenda',
    'Agra',
    'Albert',
    'Alden',
    'Alexander',
    'Allen',
    'Alma',
    'Almena',
    'Alta Vista',
    'Altamont',
    'Alton',
    'Altoona',
    'Americus',
    'Andale',
    'Andover',
    'Anthony',
    'Arcadia',
    'Argonia',
    'Arkansas City',
    'Arlington',
    'Arma',
    'Arnold',
    'Ashland',
    'Assaria',
    'Atchison',
    'Athol',
    'Atlanta',
    'Attica',
    'Atwood',
    'Auburn',
    'Augusta',
    'Aurora',
    'Axtell',
    'Baileyville',
    'Baldwin City',
    'Barnard',
    'Barnes',
    'Bartlett',
    'Basehor',
    'Baxter Springs',
    'Bazine',
    'Beattie',
    'Beaumont',
    'Beeler',
    'Belle Plaine',
    'Belleville',
    'Beloit',
    'Belpre',
    'Belvue',
    'Bendena',
    'Benedict',
    'Bennington',
    'Bentley',
    'Benton',
    'Bern',
    'Berryton',
    'Beverly',
    'Bird City',
    'Bison',
    'Bloom',
    'Blue Mound',
    'Blue Rapids',
    'Bluff City',
    'Bogue',
    'Bonner Springs',
    'Bremen',
    'Brewster',
    'Bronson',
    'Brookville',
    'Brownell',
    'Bucklin',
    'Bucyrus',
    'Buffalo',
    'Buhler',
    'Bunker Hill',
    'Burden',
    'Burdett',
    'Burdick',
    'Burlingame',
    'Burlington',
    'Burns',
    'Burr Oak',
    'Burrton',
    'Bushton',
    'Byers',
    'Caldwell',
    'Cambridge',
    'Caney',
    'Canton',
    'Carbondale',
    'Cassoday',
    'Catharine',
    'Cawker City',
    'Cedar',
    'Cedar Point',
    'Cedar Vale',
    'Centerville',
    'Centralia',
    'Chanute',
    'Chapman',
    'Chase',
    'Chautauqua',
    'Cheney',
    'Cherokee',
    'Cherryvale',
    'Chetopa',
    'Cimarron',
    'Circleville',
    'Claflin',
    'Clay Center',
    'Clayton',
    'Clearview City',
    'Clearwater',
    'Clifton',
    'Clyde',
    'Coats',
    'Coffeyville',
    'Colby',
    'Coldwater',
    'Colfax',
    'Collyer',
    'Colony',
    'Columbus',
    'Colwich',
    'Concordia',
    'Conway Springs',
    'Coolidge',
    'Copeland',
    'Corning',
    'Cottonwood Falls',
    'Council Grove',
    'Courtland',
    'Coyville',
    'Crestline',
    'Cuba',
    'Cummings',
    'Cunningham',
    'Damar',
    'Danville',
    'De Soto',
    'Dearing',
    'Deerfield',
    'Delia',
    'Delphos',
    'Denison',
    'Dennis',
    'Denton',
    'Derby',
    'Dexter',
    'Dighton',
    'Dodge City',
    'Dorrance',
    'Douglass',
    'Dover',
    'Downs',
    'Dresden',
    'Durham',
    'Dwight',
    'Easton',
    'Edgerton',
    'Edna',
    'Edson',
    'Edwardsville',
    'Effingham',
    'El Dorado',
    'Elbing',
    'Elk City',
    'Elk Falls',
    'Elkhart',
    'Ellinwood',
    'Ellis',
    'Ellsworth',
    'Elmdale',
    'Elsmore',
    'Elwood',
    'Emmett',
    'Emporia',
    'Englewood',
    'Ensign',
    'Enterprise',
    'Erie',
    'Esbon',
    'Eskridge',
    'Eudora',
    'Eureka',
    'Everest',
    'Fairview',
    'Fall River',
    'Falun',
    'Farlington',
    'Florence',
    'Fontana',
    'Ford',
    'Formoso',
    'Fort Leavenworth',
    'Fort Riley',
    'Fort Scott',
    'Fostoria',
    'Fowler',
    'Frankfort',
    'Franklin',
    'Fredonia',
    'Freeport',
    'Frontenac',
    'Fulton',
    'Galena',
    'Galesburg',
    'Galva',
    'Garden City',
    'Garden Plain',
    'Gardner',
    'Garfield',
    'Garnett',
    'Gas',
    'Gaylord',
    'Gem',
    'Geneseo',
    'Geuda Springs',
    'Girard',
    'Glade',
    'Glasco',
    'Glen Elder',
    'Goddard',
    'Goessel',
    'Goff',
    'Goodland',
    'Gorham',
    'Gove',
    'Grainfield',
    'Grantville',
    'Great Bend',
    'Greeley',
    'Green',
    'Greenleaf',
    'Greensburg',
    'Greenwich',
    'Grenola',
    'Gridley',
    'Grinnell',
    'Gypsum',
    'Haddam',
    'Halstead',
    'Hamilton',
    'Hanover',
    'Hanston',
    'Hardtner',
    'Harper',
    'Hartford',
    'Harveyville',
    'Havana',
    'Haven',
    'Havensville',
    'Haviland',
    'Hays',
    'Haysville',
    'Hazelton',
    'Healy',
    'Hepler',
    'Herington',
    'Herndon',
    'Hesston',
    'Hiawatha',
    'Highland',
    'Hill City',
    'Hillsboro',
    'Hillsdale',
    'Hoisington',
    'Holcomb',
    'Hollenberg',
    'Holton',
    'Holyrood',
    'Home',
    'Hope',
    'Horton',
    'Howard',
    'Hoxie',
    'Hoyt',
    'Hudson',
    'Hugoton',
    'Humboldt',
    'Hunter',
    'Hutchinson',
    'Independence',
    'Ingalls',
    'Inman',
    'Iola',
    'Isabel',
    'Iuka',
    'Jamestown',
    'Jennings',
    'Jetmore',
    'Jewell',
    'Johnson',
    'Junction City',
    'Kanopolis',
    'Kanorado',
    'Kansas City',
    'Kechi',
    'Kendall',
    'Kensington',
    'Kincaid',
    'Kingman',
    'Kinsley',
    'Kiowa',
    'Kirwin',
    'Kismet',
    'La Crosse',
    'La Cygne',
    'La Harpe',
    'Lake City',
    'Lakin',
    'Lamont',
    'Lancaster',
    'Lane',
    'Lansing',
    'Larned',
    'Latham',
    'Lawrence',
    'Le Roy',
    'Leavenworth',
    'Lebanon',
    'Lebo',
    'Lecompton',
    'Lehigh',
    'Lenora',
    'Leon',
    'Leonardville',
    'Leoti',
    'Levant',
    'Lewis',
    'Liberal',
    'Liberty',
    'Liebenthal',
    'Lincoln',
    'Lincolnville',
    'Lindsborg',
    'Linn',
    'Linwood',
    'Little River',
    'Logan',
    'Long Island',
    'Longford',
    'Longton',
    'Lorraine',
    'Lost Springs',
    'Louisburg',
    'Louisville',
    'Lucas',
    'Ludell',
    'Luray',
    'Lyndon',
    'Lyons',
    'Macksville',
    'Madison',
    'Mahaska',
    'Maize',
    'Manhattan',
    'Mankato',
    'Manter',
    'Maple City',
    'Maple Hill',
    'Mapleton',
    'Marienthal',
    'Marion',
    'Marquette',
    'Marysville',
    'Matfield Green',
    'Mayetta',
    'Mayfield',
    'McConnell A F B',
    'McCracken',
    'McCune',
    'McDonald',
    'McFarland',
    'McLouth',
    'Mcpherson',
    'Meade',
    'Medicine Lodge',
    'Melvern',
    'Meriden',
    'Milan',
    'Milford',
    'Milton',
    'Miltonvale',
    'Minneapolis',
    'Minneola',
    'Moline',
    'Montezuma',
    'Monument',
    'Moran',
    'Morganville',
    'Morland',
    'Morrill',
    'Morrowville',
    'Moscow',
    'Mound City',
    'Mound Valley',
    'Moundridge',
    'Mount Hope',
    'Mulberry',
    'Mullinville',
    'Mulvane',
    'Munden',
    'Murdock',
    'Muscotah',
    'Narka',
    'Nashville',
    'Natoma',
    'Neal',
    'Nekoma',
    'Neodesha',
    'Neosho Falls',
    'Neosho Rapids',
    'Ness City',
    'Netawaka',
    'New Albany',
    'New Cambria',
    'New Century',
    'Newton',
    'Nickerson',
    'Ninnescah',
    'Niotaze',
    'Norcatur',
    'North Newton',
    'Norton',
    'Nortonville',
    'Norway',
    'Norwich',
    'Oakley',
    'Oberlin',
    'Offerle',
    'Ogallah',
    'Ogden',
    'Oketo',
    'Olathe',
    'Olmitz',
    'Olpe',
    'Olsburg',
    'Onaga',
    'Oneida',
    'Opolis',
    'Osage City',
    'Osawatomie',
    'Osborne',
    'Oskaloosa',
    'Oswego',
    'Otis',
    'Ottawa',
    'Overbrook',
    'Oxford',
    'Ozawkie',
    'Palco',
    'Palmer',
    'Paola',
    'Paradise',
    'Park',
    'Parker',
    'Parsons',
    'Partridge',
    'Pawnee Rock',
    'Paxico',
    'Peabody',
    'Peck',
    'Penokee',
    'Perry',
    'Peru',
    'Pfeifer',
    'Phillipsburg',
    'Piedmont',
    'Pierceville',
    'Piqua',
    'Pittsburg',
    'Plains',
    'Plainville',
    'Pleasanton',
    'Plevna',
    'Pomona',
    'Portis',
    'Potter',
    'Potwin',
    'Powhattan',
    'Prairie View',
    'Pratt',
    'Prescott',
    'Pretty Prairie',
    'Princeton',
    'Protection',
    'Quenemo',
    'Quinter',
    'Rago',
    'Ramona',
    'Randall',
    'Randolph',
    'Ransom',
    'Rantoul',
    'Raymond',
    'Reading',
    'Redfield',
    'Republic',
    'Rexford',
    'Richfield',
    'Richland',
    'Richmond',
    'Riley',
    'Riverton',
    'Robinson',
    'Rock',
    'Rolla',
    'Rosalia',
    'Rose Hill',
    'Ross',
    'Rossville',
    'Roxbury',
    'Rozel',
    'Rush Center',
    'Russell',
    'Sabetha',
    'Saint Francis',
    'Saint George',
    'Saint John',
    'Saint Marys',
    'Saint Paul',
    'Salina',
    'Satanta',
    'Savonburg',
    'Sawyer',
    'Scammon',
    'Scandia',
    'Schoenchen',
    'Scott City',
    'Scranton',
    'Sedan',
    'Sedgwick',
    'Selden',
    'Seneca',
    'Severy',
    'Sharon',
    'Sharon Springs',
    'Shawnee Mission',
    'Silver Lake',
    'Simpson',
    'Smith Center',
    'Smolan',
    'Sodville',
    'Soldier',
    'Solomon',
    'South Haven',
    'South Hutchinson',
    'Spearville',
    'Spivey',
    'Spring Hill',
    'St. George',
    'Stafford',
    'Stark',
    'Sterling',
    'Stilwell',
    'Stockton',
    'Strong City',
    'Stuttgart',
    'Sublette',
    'Summerfield',
    'Sun City',
    'Sycamore',
    'Sylvan Grove',
    'Sylvia',
    'Syracuse',
    'Talmage',
    'Tampa',
    'Tecumseh',
    'Tescott',
    'Thayer',
    'Tipton',
    'Tonganoxie',
    'Topeka',
    'Toronto',
    'Towanda',
    'Treece',
    'Tribune',
    'Troy',
    'Turon',
    'Tyro',
    'Udall',
    'Ulysses',
    'Union',
    'Uniontown',
    'Utica',
    'Valley Center',
    'Valley Falls',
    'Vassar',
    'Vermillion',
    'Victoria',
    'Viola',
    'Virgil',
    'Wa Keeney',
    'Wakarusa',
    'Wakefield',
    'Waldo',
    'Waldron',
    'Walker',
    'Wallace',
    'Walnut',
    'Walton',
    'Wamego',
    'Washington',
    'Waterville',
    'Wathena',
    'Waverly',
    'Webber',
    'Weir',
    'Welda',
    'Wellington',
    'Wellsville',
    'Weskan',
    'West Mineral',
    'Westmoreland',
    'Westphalia',
    'Wetmore',
    'Wheaton',
    'White City',
    'White Cloud',
    'Whitewater',
    'Whiting',
    'Wichita',
    'Williamsburg',
    'Wilmore',
    'Wilsey',
    'Wilson',
    'Winchester',
    'Windom',
    'Winfield',
    'Winona',
    'Wolf River',
    'Woodbine',
    'Woodston',
    'Wright',
    'Yates Center',
    'Yoder',
    'Zenda'
]
