cities = [
    'Abbeville',
    'Abita Springs',
    'Acme',
    'Addis',
    'Aimwell',
    'Akers',
    'Albany',
    'Alexandria',
    'Ama',
    'Amelia',
    'Amite',
    'Anacoco',
    'Angie',
    'Angola',
    'Arabi',
    'Arcadia',
    'Archibald',
    'Arnaudville',
    'Ashland',
    'Athens',
    'Atlanta',
    'Avery Island',
    'Baker',
    'Baldwin',
    'Ball',
    'Barataria',
    'Barksdale AFB',
    'Basile',
    'Baskin',
    'Bastrop',
    'Batchelor',
    'Baton Rouge',
    'Bayou Goula',
    'Belcher',
    'Bell City',
    'Belle Chasse',
    'Belle Rose',
    'Belmont',
    'Bentley',
    'Benton',
    'Bernice',
    'Berwick',
    'Bethany',
    'Bienville',
    'Blanchard',
    'Blanks',
    'Bogalusa',
    'Bonita',
    'Boothville',
    'Bordelonville',
    'Bossier City',
    'Bourg',
    'Boutte',
    'Boyce',
    'Braithwaite',
    'Branch',
    'Breaux Bridge',
    'Brittany',
    'Broussard',
    'Brusly',
    'Bueche',
    'Bunkie',
    'Buras',
    'Burnside',
    'Bush',
    'Cade',
    'Calhoun',
    'Calvin',
    'Cameron',
    'Campti',
    'Cankton',
    'Carencro',
    'Carlisle',
    'Carville',
    'Castor',
    'Cecilia',
    'Center Point',
    'Centerville',
    'Chalmette',
    'Charenton',
    'Chase',
    'Chataignier',
    'Chatham',
    'Chauvin',
    'Cheneyville',
    'Choudrant',
    'Church Point',
    'Clarence',
    'Clarks',
    'Clayton',
    'Clinton',
    'Cloutierville',
    'Colfax',
    'Collinston',
    'Columbia',
    'Convent',
    'Converse',
    'Cotton Valley',
    'Cottonport',
    'Coushatta',
    'Covington',
    'Creole',
    'Crowley',
    'Crowville',
    'Cullen',
    'Cut Off',
    'Darrow',
    'Davant',
    'Delcambre',
    'Delhi',
    'Delta',
    'Denham Springs',
    'Dequincy',
    'Deridder',
    'Des Allemands',
    'Destrehan',
    'Deville',
    'Dodson',
    'Donaldsonville',
    'Donner',
    'Downsville',
    'Doyline',
    'Dry Creek',
    'Dry Prong',
    'Dubach',
    'Dubberly',
    'Dulac',
    'Duplessis',
    'Dupont',
    'Duson',
    'East Point',
    'Echo',
    'Edgard',
    'Effie',
    'Egan',
    'Elizabeth',
    'Elm Grove',
    'Elmer',
    'Elton',
    'Empire',
    'Enterprise',
    'Epps',
    'Erath',
    'Eros',
    'Erwinville',
    'Estherwood',
    'Ethel',
    'Eunice',
    'Evangeline',
    'Evans',
    'Evergreen',
    'Fairbanks',
    'Farmerville',
    'Fenton',
    'Ferriday',
    'Fisher',
    'Flatwoods',
    'Flora',
    'Florien',
    'Fluker',
    'Folsom',
    'Fordoche',
    'Forest',
    'Forest Hill',
    'Fort Necessity',
    'Franklin',
    'Franklinton',
    'French Settlement',
    'Frierson',
    'Fullerton',
    'Galliano',
    'Garden City',
    'Gardner',
    'Garyville',
    'Geismar',
    'Georgetown',
    'Gheens',
    'Gibsland',
    'Gibson',
    'Gilbert',
    'Gilliam',
    'Glenmora',
    'Gloster',
    'Glynn',
    'Golden Meadow',
    'Goldonna',
    'Gonzales',
    'Gorum',
    'Grambling',
    'Gramercy',
    'Grand Cane',
    'Grand Chenier',
    'Grand Coteau',
    'Grand Isle',
    'Grant',
    'Gray',
    'Grayson',
    'Greensburg',
    'Greenwell Springs',
    'Greenwood',
    'Gretna',
    'Grosse Tete',
    'Gueydan',
    'Hackberry',
    'Hahnville',
    'Hall Summit',
    'Hamburg',
    'Hammond',
    'Harmon',
    'Harrisonburg',
    'Harvey',
    'Haughton',
    'Hayes',
    'Haynesville',
    'Heflin',
    'Hessmer',
    'Hester',
    'Hineston',
    'Hodge',
    'Holden',
    'Homer',
    'Hornbeck',
    'Hosston',
    'Houma',
    'Husser',
    'Ida',
    'Independence',
    'Innis',
    'Iota',
    'Iowa',
    'Jackson',
    'Jamestown',
    'Jarreau',
    'Jeanerette',
    'Jefferson',
    'Jena',
    'Jennings',
    'Jigger',
    'Jones',
    'Jonesboro',
    'Jonesville',
    'Joyce',
    'Kaplan',
    'Keatchie',
    'Keithville',
    'Kelly',
    'Kenner',
    'Kentwood',
    'Kilbourne',
    'Killona',
    'Kinder',
    'Kraemer',
    'Krotz Springs',
    'Kurthwood',
    'La Place',
    'Labadieville',
    'Labarre',
    'Lacamp',
    'Lacassine',
    'Lacombe',
    'Lafayette',
    'Lafitte',
    'Lake Arthur',
    'Lake Charles',
    'Lake Providence',
    'Lakeland',
    'Laplace',
    'Larose',
    'Lawtell',
    'Lebeau',
    'Leblanc',
    'Lecompte',
    'Leesville',
    'Lena',
    'Leonville',
    'Lettsworth',
    'Libuse',
    'Lillie',
    'Lisbon',
    'Livingston',
    'Livonia',
    'Lockport',
    'Logansport',
    'Longleaf',
    'Longstreet',
    'Longville',
    'Loranger',
    'Loreauville',
    'Lottie',
    'Luling',
    'Lutcher',
    'Lydia',
    'Madisonville',
    'Mamou',
    'Mandeville',
    'Mangham',
    'Mansfield',
    'Mansura',
    'Many',
    'Maringouin',
    'Marion',
    'Marksville',
    'Marrero',
    'Marthaville',
    'Mathews',
    'Maurepas',
    'Maurice',
    'McNary',
    'Melrose',
    'Melville',
    'Mer Rouge',
    'Meraux',
    'Mermentau',
    'Merryville',
    'Metairie',
    'Milton',
    'Minden',
    'Mittie',
    'Modeste',
    'Monroe',
    'Montegut',
    'Monterey',
    'Montgomery',
    'Mooringsport',
    'Mora',
    'Moreauville',
    'Morgan City',
    'Morganza',
    'Morrow',
    'Morse',
    'Mount Airy',
    'Mount Hermon',
    'Napoleonville',
    'Natalbany',
    'Natchez',
    'Natchitoches',
    'Negreet',
    'New Iberia',
    'New Orleans',
    'New Roads',
    'New Sarpy',
    'Newellton',
    'Newllano',
    'Noble',
    'Norco',
    'Norwood',
    'Oak Grove',
    'Oak Ridge',
    'Oakdale',
    'Oberlin',
    'Oil City',
    'Olla',
    'Opelousas',
    'Oscar',
    'Otis',
    'Paincourtville',
    'Palmetto',
    'Paradis',
    'Patterson',
    'Paulina',
    'Pearl River',
    'Pelican',
    'Perry',
    'Pierre Part',
    'Pilottown',
    'Pine Grove',
    'Pine Prairie',
    'Pineville',
    'Pioneer',
    'Pitkin',
    'Plain Dealing',
    'Plaquemine',
    'Plattenville',
    'Plaucheville',
    'Pleasant Hill',
    'Pointe A La Hache',
    'Pollock',
    'Ponchatoula',
    'Port Allen',
    'Port Barre',
    'Port Sulphur',
    'Powhatan',
    'Prairieville',
    'Pride',
    'Princeton',
    'Provencal',
    'Quitman',
    'Raceland',
    'Ragley',
    'Rayne',
    'Rayville',
    'Reddell',
    'Reeves',
    'Reserve',
    'Rhinehart',
    'Ringgold',
    'Roanoke',
    'Robeline',
    'Robert',
    'Rodessa',
    'Rosedale',
    'Roseland',
    'Rosepine',
    'Rougon',
    'Ruby',
    'Ruston',
    'Saint Amant',
    'Saint Benedict',
    'Saint Bernard',
    'Saint Francisville',
    'Saint Gabriel',
    'Saint James',
    'Saint Joseph',
    'Saint Landry',
    'Saint Martinville',
    'Saint Maurice',
    'Saint Rose',
    'Saline',
    'Sarepta',
    'Schriever',
    'Scott',
    'Shongaloo',
    'Shreveport',
    'Sibley',
    'Sicily Island',
    'Sieper',
    'Sikes',
    'Simmesport',
    'Simpson',
    'Simsboro',
    'Singer',
    'Slagle',
    'Slaughter',
    'Slidell',
    'Sondheimer',
    'Sorrento',
    'South Mansfield',
    'Spearsville',
    'Springfield',
    'Springhill',
    'Starks',
    'Start',
    'Sterlington',
    'Stonewall',
    'Sugartown',
    'Sulphur',
    'Summerfield',
    'Sun',
    'Sunset',
    'Sunshine',
    'Swartz',
    'Talisheek',
    'Tallulah',
    'Tangipahoa',
    'Taylor',
    'Theriot',
    'Thibodaux',
    'Tickfaw',
    'Tioga',
    'Torbert',
    'Transylvania',
    'Trout',
    'Tullos',
    'Tunica',
    'Turkey Creek',
    'Uncle Sam',
    'Urania',
    'Vacherie',
    'Venice',
    'Ventress',
    'Verda',
    'Vidalia',
    'Ville Platte',
    'Vinton',
    'Violet',
    'Vivian',
    'Wakefield',
    'Walker',
    'Washington',
    'Waterproof',
    'Watson',
    'Welsh',
    'West Monroe',
    'Westlake',
    'Westwego',
    'Weyanoke',
    'White Castle',
    'Wildsville',
    'Wilson',
    'Winnfield',
    'Winnsboro',
    'Wisner',
    'Woodworth',
    'Youngsville',
    'Zachary',
    'Zwolle'
]
