cities = [
    'Abbot',
    'Acton',
    'Addison',
    'Albion',
    'Alfred',
    'Alna',
    'Andover',
    'Anson',
    'Ashland',
    'Athens',
    'Auburn',
    'Augusta',
    'Aurora',
    'Bailey Island',
    'Baileyville',
    'Bangor',
    'Bar Harbor',
    'Bar Mills',
    'Bass Harbor',
    'Bath',
    'Bayville',
    'Beals',
    'Belfast',
    'Belgrade',
    'Belgrade Lakes',
    'Benedicta',
    'Bernard',
    'Berwick',
    'Bethel',
    'Biddeford',
    'Biddeford Pool',
    'Bingham',
    'Birch Harbor',
    'Blaine',
    'Blue Hill',
    'Blue Hill Falls',
    'Boothbay',
    'Boothbay Harbor',
    'Bowdoin',
    'Bowdoinham',
    'Bradford',
    'Bradley',
    'Bremen',
    'Brewer',
    'Bridgewater',
    'Bridgton',
    'Bristol',
    'Brooklin',
    'Brooks',
    'Brooksville',
    'Brookton',
    'Brownfield',
    'Brownville',
    'Brownville Junction',
    'Brunswick',
    'Bryant Pond',
    'Buckfield',
    'Bucksport',
    'Burlington',
    'Burnham',
    'Bustins Island',
    'Calais',
    'Cambridge',
    'Camden',
    'Canaan',
    'Canton',
    'Cape Elizabeth',
    'Cape Neddick',
    'Cape Porpoise',
    'Caratunk',
    'Cardville',
    'Caribou',
    'Carmel',
    'Cary',
    'Casco',
    'Castine',
    'Center Lovell',
    'Chamberlain',
    'Charleston',
    'Chebeague Island',
    'Cherryfield',
    'China',
    'Clayton Lake',
    'Cliff Island',
    'Clinton',
    'Columbia Falls',
    'Coopers Mills',
    'Corea',
    'Corinna',
    'Corinth',
    'Cornish',
    'Costigan',
    'Cranberry Isles',
    'Crouseville',
    'Cumberland Center',
    'Cumberland Foreside',
    'Cushing',
    'Cutler',
    'Damariscotta',
    'Danforth',
    'Danville',
    'Deer Isle',
    'Denmark',
    'Dennysville',
    'Detroit',
    'Dexter',
    'Dixfield',
    'Dixmont',
    'Dover Foxcroft',
    'Dresden',
    'Dryden',
    'Durham',
    'Eagle Lake',
    'East Andover',
    'East Baldwin',
    'East Blue Hill',
    'East Boothbay',
    'East Dixfield',
    'East Livermore',
    'East Machias',
    'East Millinocket',
    'East Newport',
    'East Orland',
    'East Parsonfield',
    'East Poland',
    'East Vassalboro',
    'East Waterboro',
    'East Wilton',
    'East Winthrop',
    'Easton',
    'Eastport',
    'Eddington',
    'Edgecomb',
    'Eliot',
    'Ellsworth',
    'Estcourt Station',
    'Etna',
    'Eustis',
    'Exeter',
    'Fairfield',
    'Falmouth',
    'Farmingdale',
    'Farmington',
    'Farmington Falls',
    'Fort Fairfield',
    'Fort Kent',
    'Fort Kent Mills',
    'Frankfort',
    'Franklin',
    'Freedom',
    'Freeport',
    'Frenchboro',
    'Frenchville',
    'Friendship',
    'Fryeburg',
    'Gardiner',
    'Garland',
    'Georgetown',
    'Glen Cove',
    'Gorham',
    'Gouldsboro',
    'Grand Isle',
    'Grand Lake Stream',
    'Gray',
    'Greene',
    'Greenville',
    'Greenville Junction',
    'Guilford',
    'Hallowell',
    'Hampden',
    'Hancock',
    'Hanover',
    'Harborside',
    'Harmony',
    'Harpswell',
    'Harrington',
    'Harrison',
    'Hartland',
    'Hebron',
    'Hinckley',
    'Hiram',
    'Holden',
    'Hollis Center',
    'Hope',
    'Houlton',
    'Howland',
    'Hudson',
    'Hulls Cove',
    'Island Falls',
    'Isle Au Haut',
    'Isle Of Springs',
    'Islesboro',
    'Islesford',
    'Jackman',
    'Jay',
    'Jefferson',
    'Jonesboro',
    'Jonesport',
    'Kenduskeag',
    'Kennebunk',
    'Kennebunkport',
    'Kents Hill',
    'Kingfield',
    'Kingman',
    'Kittery',
    'Kittery Point',
    'Lagrange',
    'Lambert Lake',
    'Lebanon',
    'Lee',
    'Leeds',
    'Levant',
    'Lewiston',
    'Liberty',
    'Limerick',
    'Limestone',
    'Limington',
    'Lincoln',
    'Lincolnville',
    'Lincolnville Center',
    'Lisbon',
    'Lisbon Falls',
    'Litchfield',
    'Little Deer Isle',
    'Livermore',
    'Livermore Falls',
    'Locke Mills',
    'Long Island',
    'Lovell',
    'Lubec',
    'Machias',
    'Machiasport',
    'Madawaska',
    'Madison',
    'Manchester',
    'Manset',
    'Mapleton',
    'Mars Hill',
    'Masardis',
    'Matinicus',
    'Mattawamkeag',
    'Mechanic Falls',
    'Meddybemps',
    'Medway',
    'Merepoint',
    'Mexico',
    'Milbridge',
    'Milford',
    'Millinocket',
    'Milo',
    'Minot',
    'Monhegan',
    'Monmouth',
    'Monroe',
    'Monson',
    'Monticello',
    'Moody',
    'Morrill',
    'Mount Desert',
    'Mount Vernon',
    'Naples',
    'New Gloucester',
    'New Harbor',
    'New Limerick',
    'New Portland',
    'New Sharon',
    'New Sweden',
    'New Vineyard',
    'Newagen',
    'Newcastle',
    'Newfield',
    'Newport',
    'Newry',
    'Nobleboro',
    'Norridgewock',
    'North Anson',
    'North Berwick',
    'North Bridgton',
    'North Haven',
    'North Jay',
    'North Monmouth',
    'North New Portland',
    'North Turner',
    'North Vassalboro',
    'North Waterboro',
    'North Waterford',
    'North Yarmouth',
    'Northeast Harbor',
    'Norway',
    'Oakfield',
    'Oakland',
    'Ocean Park',
    'Ogunquit',
    'Olamon',
    'Old Orchard Beach',
    'Old Town',
    'Oquossoc',
    'Orient',
    'Orland',
    'Orono',
    'Orrington',
    'Orrs Island',
    'Otter Creek',
    'Owls Head',
    'Oxbow',
    'Oxford',
    'Palermo',
    'Palmyra',
    'Paris',
    'Parsonsfield',
    'Passadumkeag',
    'Patten',
    'Peaks Island',
    'Pemaquid',
    'Pembroke',
    'Penobscot',
    'Perham',
    'Perry',
    'Peru',
    'Phillips',
    'Phippsburg',
    'Pittsfield',
    'Plymouth',
    'Poland',
    'Port Clyde',
    'Portage',
    'Porter',
    'Portland',
    'Pownal',
    'Presque Isle',
    'Princeton',
    'Prospect Harbor',
    'Quimby',
    'Randolph',
    'Rangeley',
    'Raymond',
    'Readfield',
    'Richmond',
    'Robbinston',
    'Rockland',
    'Rockport',
    'Rockwood',
    'Round Pond',
    'Roxbury',
    'Rumford',
    'Rumford Center',
    'Sabattus',
    'Saco',
    'Saint Agatha',
    'Saint Albans',
    'Saint David',
    'Saint Francis',
    'Saint George',
    'Salsbury Cove',
    'Sandy Point',
    'Sanford',
    'Sangerville',
    'Sargentville',
    'Scarborough',
    'Seal Cove',
    'Seal Harbor',
    'Searsmont',
    'Searsport',
    'Sebago',
    'Sebago Lake',
    'Sebasco Estates',
    'Sebec',
    'Sedgwick',
    'Shapleigh',
    'Shawmut',
    'Sheridan',
    'Sherman Mills',
    'Sherman Station',
    'Shirley Mills',
    'Sinclair',
    'Skowhegan',
    'Small Point',
    'Smithfield',
    'Smyrna Mills',
    'Soldier Pond',
    'Solon',
    'Sorrento',
    'South Berwick',
    'South Bristol',
    'South Casco',
    'South China',
    'South Freeport',
    'South Gardiner',
    'South Paris',
    'South Portland',
    'South Thomaston',
    'South Waterford',
    'South Windham',
    'Southport',
    'Southwest Harbor',
    'Springfield',
    'Springvale',
    'Spruce Head',
    'Squirrel Island',
    'Stacyville',
    'Standish',
    'Steep Falls',
    'Stetson',
    'Steuben',
    'Stillwater',
    'Stockholm',
    'Stockton Springs',
    'Stoneham',
    'Stonington',
    'Stratton',
    'Strong',
    'Sullivan',
    'Sumner',
    'Sunset',
    'Surry',
    'Swans Island',
    'Temple',
    'Tenants Harbor',
    'Thomaston',
    'Thorndike',
    'Topsfield',
    'Topsham',
    'Trevett',
    'Troy',
    'Turner',
    'Turner Center',
    'Union',
    'Unity',
    'Van Buren',
    'Vanceboro',
    'Vassalboro',
    'Vienna',
    'Vinalhaven',
    'Waite',
    'Waldoboro',
    'Walpole',
    'Warren',
    'Washburn',
    'Washington',
    'Waterboro',
    'Waterford',
    'Waterville',
    'Wayne',
    'Weld',
    'Wells',
    'Wesley',
    'West Baldwin',
    'West Bethel',
    'West Boothbay Harbor',
    'West Buxton',
    'West Enfield',
    'West Farmington',
    'West Forks',
    'West Kennebunk',
    'West Minot',
    'West Newfield',
    'West Paris',
    'West Poland',
    'West Rockport',
    'West Tremont',
    'Westbrook',
    'Westfield',
    'Whitefield',
    'Whiting',
    'Wilton',
    'Windham',
    'Windsor',
    'Winn',
    'Winter Harbor',
    'Winterport',
    'Winterville',
    'Winthrop',
    'Wiscasset',
    'Woolwich',
    'Wytopitlock',
    'Yarmouth',
    'York',
    'York Beach',
    'York Harbor'
]
