cities = [
    'Acme',
    'Ada',
    'Addison',
    'Adrian',
    'Afton',
    'Ahmeek',
    'Akron',
    'Alanson',
    'Alba',
    'Albion',
    'Alden',
    'Alger',
    'Algonac',
    'Allegan',
    'Allen',
    'Allen Park',
    'Allendale',
    'Allenton',
    'Allouez',
    'Alma',
    'Almont',
    'Alpena',
    'Alpha',
    'Alto',
    'Amasa',
    'Anchorville',
    'Ann Arbor',
    'Applegate',
    'Arcadia',
    'Argyle',
    'Armada',
    'Arnold',
    'Ashley',
    'Athens',
    'Atlanta',
    'Atlantic Mine',
    'Atlas',
    'Attica',
    'Au Gres',
    'Au Train',
    'Auburn',
    'Auburn Hills',
    'Augusta',
    'Avoca',
    'Azalia',
    'Bad Axe',
    'Bailey',
    'Baldwin',
    'Bancroft',
    'Bangor',
    'Bannister',
    'Baraga',
    'Barbeau',
    'Bark River',
    'Baroda',
    'Barryton',
    'Barton City',
    'Bath',
    'Battle Creek',
    'Bay City',
    'Bay Port',
    'Bay Shore',
    'Bear Lake',
    'Beaver Island',
    'Beaverton',
    'Bedford',
    'Belding',
    'Bellaire',
    'Belleville',
    'Bellevue',
    'Belmont',
    'Bentley',
    'Benton Harbor',
    'Benzonia',
    'Bergland',
    'Berkley',
    'Berrien Center',
    'Berrien Springs',
    'Bessemer',
    'Beulah',
    'Big Bay',
    'Big Rapids',
    'Birch Run',
    'Birmingham',
    'Bitely',
    'Black River',
    'Blanchard',
    'Blissfield',
    'Bloomfield Hills',
    'Bloomingdale',
    'Boon',
    'Boyne City',
    'Boyne Falls',
    'Bradley',
    'Branch',
    'Brant',
    'Breckenridge',
    'Breedsville',
    'Brethren',
    'Bridgeport',
    'Bridgewater',
    'Bridgman',
    'Brighton',
    'Brimley',
    'Britton',
    'Brohman',
    'Bronson',
    'Brooklyn',
    'Brown City',
    'Bruce Crossing',
    'Brutus',
    'Buchanan',
    'Buckley',
    'Burlington',
    'Burnips',
    'Burr Oak',
    'Burt',
    'Burt Lake',
    'Burton',
    'Byron',
    'Byron Center',
    'Cadillac',
    'Caledonia',
    'Calumet',
    'Camden',
    'Cannonsburg',
    'Canton',
    'Capac',
    'Carleton',
    'Carney',
    'Caro',
    'Carp Lake',
    'Carrollton',
    'Carson City',
    'Carsonville',
    'Casco',
    'Caseville',
    'Casnovia',
    'Caspian',
    'Cass City',
    'Cassopolis',
    'Cedar',
    'Cedar Lake',
    'Cedar River',
    'Cedar Springs',
    'Cedarville',
    'Cement City',
    'Center Line',
    'Central Lake',
    'Centreville',
    'Ceresco',
    'Champion',
    'Channing',
    'Charlevoix',
    'Charlotte',
    'Chase',
    'Chassell',
    'Chatham',
    'Cheboygan',
    'Chelsea',
    'Chesaning',
    'Chippewa Lake',
    'Clare',
    'Clarklake',
    'Clarkston',
    'Clarksville',
    'Clawson',
    'Clayton',
    'Clifford',
    'Climax',
    'Clinton',
    'Clinton Township',
    'Clio',
    'Cloverdale',
    'Cohoctah',
    'Coldwater',
    'Coleman',
    'Colfax',
    'Coloma',
    'Colon',
    'Columbiaville',
    'Columbus',
    'Comins',
    'Commerce Township',
    'Comstock',
    'Comstock Park',
    'Concord',
    'Conklin',
    'Constantine',
    'Conway',
    'Cooks',
    'Coopersville',
    'Copemish',
    'Copper City',
    'Copper Harbor',
    'Coral',
    'Cornell',
    'Corunna',
    'Covert',
    'Covington',
    'Cross Village',
    'Croswell',
    'Crystal',
    'Crystal Falls',
    'Curran',
    'Curtis',
    'Custer',
    'Dafter',
    'Daggett',
    'Dansville',
    'Davisburg',
    'Davison',
    'De Tour Village',
    'Dearborn',
    'Dearborn Heights',
    'Decatur',
    'Decker',
    'Deckerville',
    'Deerfield',
    'Deerton',
    'Deford',
    'Delton',
    'Detroit',
    'Dewitt',
    'Dexter',
    'Dickson',
    'Dimondale',
    'Dodgeville',
    'Dollar Bay',
    'Dorr',
    'Douglas',
    'Dowagiac',
    'Dowling',
    'Drayton Plains',
    'Drummond Island',
    'Dryden',
    'Dundee',
    'Durand',
    'Eagle',
    'East China',
    'East Jordan',
    'East Lansing',
    'East Leroy',
    'East Tawas',
    'Eastlake',
    'Eastpointe',
    'Eastport',
    'Eaton Rapids',
    'Eau Claire',
    'Eben Junction',
    'Eckerman',
    'Ecorse',
    'Edenville',
    'Edmore',
    'Edwardsburg',
    'Elberta',
    'Elk Rapids',
    'Elkton',
    'Ellsworth',
    'Elm Hall',
    'Elmira',
    'Elsie',
    'Elwell',
    'Emmett',
    'Empire',
    'Engadine',
    'Erie',
    'Escanaba',
    'Essexville',
    'Eureka',
    'Evart',
    'Ewen',
    'Fair Haven',
    'Fairgrove',
    'Fairview',
    'Falmouth',
    'Farmington',
    'Farwell',
    'Felch',
    'Fennville',
    'Fenton',
    'Fenwick',
    'Ferndale',
    'Ferrysburg',
    'Fife Lake',
    'Filer City',
    'Filion',
    'Flat Rock',
    'Flint',
    'Flushing',
    'Forest',
    'Forestville',
    'Fort Gratiot',
    'Foster City',
    'Fostoria',
    'Fountain',
    'Fowler',
    'Fowlerville',
    'Frankenmuth',
    'Frankfort',
    'Franklin',
    'Fraser',
    'Frederic',
    'Free Soil',
    'Freeland',
    'Freeport',
    'Fremont',
    'Frontier',
    'Fruitport',
    'Fulton',
    'Gaastra',
    'Gagetown',
    'Gaines',
    'Galesburg',
    'Galien',
    'Garden',
    'Garden City',
    'Gaylord',
    'Genesee',
    'Germfask',
    'Gilford',
    'Gladstone',
    'Gladwin',
    'Glen Arbor',
    'Glenn',
    'Glennie',
    'Gobles',
    'Goetzville',
    'Good Hart',
    'Goodells',
    'Goodrich',
    'Gould City',
    'Gowen',
    'Grand Blanc',
    'Grand Haven',
    'Grand Junction',
    'Grand Ledge',
    'Grand Marais',
    'Grand Rapids',
    'Grandville',
    'Grant',
    'Grass Lake',
    'Grawn',
    'Grayling',
    'Greenbush',
    'Greenland',
    'Greenville',
    'Greenwood',
    'Gregory',
    'Grosse Ile',
    'Grosse Pointe',
    'Gulliver',
    'Gwinn',
    'Hadley',
    'Hagar Shores',
    'Hale',
    'Hamburg',
    'Hamilton',
    'Hamtramck',
    'Hancock',
    'Hanover',
    'Harbert',
    'Harbor Beach',
    'Harbor Springs',
    'Harper Woods',
    'Harrietta',
    'Harris',
    'Harrison',
    'Harrison Township',
    'Harrisville',
    'Harsens Island',
    'Hart',
    'Hartford',
    'Hartland',
    'Haslett',
    'Hastings',
    'Hawks',
    'Hazel Park',
    'Hemlock',
    'Henderson',
    'Hermansville',
    'Herron',
    'Hersey',
    'Hesperia',
    'Hessel',
    'Hickory Corners',
    'Higgins Lake',
    'Highland',
    'Highland Park',
    'Hillman',
    'Hillsdale',
    'Holland',
    'Holly',
    'Holt',
    'Holton',
    'Homer',
    'Honor',
    'Hope',
    'Hopkins',
    'Horton',
    'Houghton',
    'Houghton Lake',
    'Houghton Lake Heights',
    'Howard City',
    'Howell',
    'Hubbard Lake',
    'Hubbardston',
    'Hubbell',
    'Hudson',
    'Hudsonville',
    'Hulbert',
    'Huntington Woods',
    'Ida',
    'Idlewild',
    'Imlay City',
    'Independence',
    'Indian River',
    'Ingalls',
    'Inkster',
    'Interlochen',
    'Ionia',
    'Iron Mountain',
    'Iron River',
    'Irons',
    'Ironwood',
    'Ishpeming',
    'Ithaca',
    'Jackson',
    'Jamestown',
    'Jasper',
    'Jeddo',
    'Jenison',
    'Jerome',
    'Johannesburg',
    'Jones',
    'Jonesville',
    'Kalamazoo',
    'Kaleva',
    'Kalkaska',
    'Kawkawlin',
    'Kearsarge',
    'Keego Harbor',
    'Kendall',
    'Kent City',
    'Kewadin',
    'Kincheloe',
    'Kinde',
    'Kingsford',
    'Kingsley',
    'Kingston',
    'Kinross',
    'La Salle',
    'Lachine',
    'Lacota',
    'Laingsburg',
    'Lake',
    'Lake Ann',
    'Lake City',
    'Lake George',
    'Lake Leelanau',
    'Lake Linden',
    'Lake Odessa',
    'Lake Orion',
    'Lakeland',
    'Lakeside',
    'Lakeview',
    'Lakeville',
    'Lambertville',
    'Lamont',
    'Lanse',
    'Lansing',
    'Lapeer',
    'Lawrence',
    'Lawton',
    'Leland',
    'Lennon',
    'Leonard',
    'Leonidas',
    'Leroy',
    'Leslie',
    'Levering',
    'Lewiston',
    'Lexington',
    'Lincoln',
    'Lincoln Park',
    'Linden',
    'Linwood',
    'Litchfield',
    'Little Lake',
    'Livonia',
    'Long Lake',
    'Loretto',
    'Lowell',
    'Ludington',
    'Luna Pier',
    'Lupton',
    'Luther',
    'Luzerne',
    'Lyndon',
    'Lyons',
    'Macatawa',
    'Mackinac Island',
    'Mackinaw City',
    'Macomb',
    'Madison Heights',
    'Mancelona',
    'Manchester',
    'Manistee',
    'Manistique',
    'Manitou Beach',
    'Manton',
    'Maple City',
    'Maple Rapids',
    'Marcellus',
    'Marenisco',
    'Marine City',
    'Marion',
    'Markey',
    'Marlette',
    'Marne',
    'Marquette',
    'Marshall',
    'Martin',
    'Marysville',
    'Mason',
    'Mass City',
    'Mattawan',
    'Maybee',
    'Mayfield',
    'Mayville',
    'McBain',
    'Mcbrides',
    'McMillan',
    'Mears',
    'Mecosta',
    'Melvin',
    'Melvindale',
    'Memphis',
    'Mendon',
    'Menominee',
    'Merrill',
    'Merritt',
    'Mesick',
    'Metamora',
    'Michigamme',
    'Michigan Center',
    'Middleton',
    'Middleville',
    'Midland',
    'Mikado',
    'Milan',
    'Milford',
    'Millersburg',
    'Millington',
    'Minden City',
    'Mio',
    'Mohawk',
    'Moline',
    'Monroe',
    'Montague',
    'Montgomery',
    'Montrose',
    'Moran',
    'Morenci',
    'Morley',
    'Morrice',
    'Moscow',
    'Mosherville',
    'Mount Clemens',
    'Mount Morris',
    'Mount Pleasant',
    'Muir',
    'Mullett Lake',
    'Mulliken',
    'Munger',
    'Munising',
    'Munith',
    'Muskegon',
    'Nadeau',
    'Nahma',
    'Napoleon',
    'Nashville',
    'National City',
    'National Mine',
    'Naubinway',
    'Nazareth',
    'Negaunee',
    'New Baltimore',
    'New Boston',
    'New Buffalo',
    'New Era',
    'New Haven',
    'New Hudson',
    'New Lothrop',
    'New Troy',
    'Newaygo',
    'Newberry',
    'Newkirk',
    'Newport',
    'Niles',
    'Nisula',
    'North Adams',
    'North Branch',
    'North Star',
    'North Street',
    'Northport',
    'Northville',
    'Norvell',
    'Norway',
    'Nottawa',
    'Novi',
    'Nunica',
    'Oak Grove',
    'Oak Park',
    'Oakland',
    'Oakley',
    'Oden',
    'Okemos',
    'Old Mission',
    'Olivet',
    'Omena',
    'Omer',
    'Onaway',
    'Onekama',
    'Onondaga',
    'Onsted',
    'Ontonagon',
    'Orleans',
    'Ortonville',
    'Oscoda',
    'Oshtemo',
    'Osseo',
    'Ossineke',
    'Otisville',
    'Otsego',
    'Ottawa Lake',
    'Otter Lake',
    'Ovid',
    'Owendale',
    'Owosso',
    'Oxford',
    'Painesdale',
    'Palmer',
    'Palms',
    'Palmyra',
    'Palo',
    'Paradise',
    'Paris',
    'Parma',
    'Paw Paw',
    'Peck',
    'Pelkie',
    'Pellston',
    'Pentwater',
    'Perkins',
    'Perrinton',
    'Perronville',
    'Perry',
    'Petersburg',
    'Petoskey',
    'Pewamo',
    'Pickford',
    'Pierson',
    'Pigeon',
    'Pinckney',
    'Pinconning',
    'Pittsford',
    'Plainwell',
    'Pleasant Lake',
    'Pleasant Ridge',
    'Plymouth',
    'Pointe Aux Pins',
    'Pompeii',
    'Pontiac',
    'Port Austin',
    'Port Hope',
    'Port Huron',
    'Port Sanilac',
    'Portage',
    'Portland',
    'Posen',
    'Potterville',
    'Powers',
    'Prescott',
    'Presque Isle',
    'Prudenville',
    'Pullman',
    'Quincy',
    'Quinnesec',
    'Ralph',
    'Ramsay',
    'Rapid City',
    'Rapid River',
    'Ravenna',
    'Ray',
    'Reading',
    'Redford',
    'Reed City',
    'Reese',
    'Remus',
    'Republic',
    'Rhodes',
    'Richland',
    'Richmond',
    'Richville',
    'Ridgeway',
    'Riga',
    'River Rouge',
    'Riverdale',
    'Riverside',
    'Rives Junction',
    'Rochester',
    'Rock',
    'Rockford',
    'Rockland',
    'Rockwood',
    'Rodney',
    'Rogers City',
    'Rollin',
    'Romeo',
    'Romulus',
    'Roscommon',
    'Rose',
    'Rose City',
    'Rosebush',
    'Roseville',
    'Rothbury',
    'Royal Oak',
    'Rudyard',
    'Rumely',
    'Ruth',
    'Saginaw',
    'Sagola',
    'Saint Charles',
    'Saint Clair',
    'Saint Clair Shores',
    'Saint Helen',
    'Saint Ignace',
    'Saint Johns',
    'Saint Joseph',
    'Saint Louis',
    'Salem',
    'Saline',
    'Samaria',
    'Sand Creek',
    'Sand Lake',
    'Sandusky',
    'Sanford',
    'Saranac',
    'Saugatuck',
    'Sault Sainte Marie',
    'Sawyer',
    'Schoolcraft',
    'Sciota',
    'Scotts',
    'Scottville',
    'Sears',
    'Sebewaing',
    'Seneca',
    'Seney',
    'Shaftsburg',
    'Shelby',
    'Shelbyville',
    'Shepherd',
    'Sheridan',
    'Sherwood',
    'Shingleton',
    'Sidnaw',
    'Sidney',
    'Silverwood',
    'Six Lakes',
    'Skandia',
    'Skanee',
    'Slagle',
    'Smiths Creek',
    'Smyrna',
    'Snover',
    'Sodus',
    'Somerset',
    'Somerset Center',
    'South Boardman',
    'South Branch',
    'South Haven',
    'South Lyon',
    'South Monroe',
    'South Range',
    'South Rockwood',
    'Southfield',
    'Southgate',
    'Spalding',
    'Sparta',
    'Spring Arbor',
    'Spring Lake',
    'Springport',
    'Spruce',
    'Stambaugh',
    'Standish',
    'Stanton',
    'Stanwood',
    'Stephenson',
    'Sterling',
    'Sterling Heights',
    'Stevensville',
    'Stockbridge',
    'Strongs',
    'Sturgis',
    'Sumner',
    'Sunfield',
    'Suttons Bay',
    'Swartz Creek',
    'Tawas City',
    'Taylor',
    'Tecumseh',
    'Tekonsha',
    'Temperance',
    'Thompsonville',
    'Three Oaks',
    'Three Rivers',
    'Tipton',
    'Toivola',
    'Topinabee',
    'Tower',
    'Traverse City',
    'Trenary',
    'Trenton',
    'Trout Creek',
    'Trout Lake',
    'Troy',
    'Trufant',
    'Turner',
    'Tuscola',
    'Tustin',
    'Twin Lake',
    'Twining',
    'Ubly',
    'Union',
    'Union City',
    'Union Lake',
    'Union Pier',
    'Unionville',
    'University Center',
    'Utica',
    'Vandalia',
    'Vanderbilt',
    'Vassar',
    'Vermontville',
    'Vernon',
    'Vestaburg',
    'Vicksburg',
    'Vulcan',
    'Wabaningo',
    'Wakefield',
    'Waldron',
    'Walhalla',
    'Walkerville',
    'Wallace',
    'Walled Lake',
    'Walloon Lake',
    'Warren',
    'Washington',
    'Waterford',
    'Waters',
    'Watersmeet',
    'Watervliet',
    'Watton',
    'Wayland',
    'Wayne',
    'Webberville',
    'Weidman',
    'Wells',
    'Wellston',
    'West Bloomfield',
    'West Branch',
    'West Olive',
    'Westland',
    'Weston',
    'Westphalia',
    'Wetmore',
    'Wheeler',
    'White Cloud',
    'White Lake',
    'White Pigeon',
    'White Pine',
    'Whitehall',
    'Whitewater',
    'Whitmore Lake',
    'Whittaker',
    'Whittemore',
    'Williamsburg',
    'Williamston',
    'Willis',
    'Wilson',
    'Winn',
    'Wixom',
    'Wolverine',
    'Woodland',
    'Wyandotte',
    'Yale',
    'Yates',
    'Ypsilanti',
    'Zeeland'
]
