cities = [
    'Abbeville',
    'Aberdeen',
    'Ackerman',
    'Algoma',
    'Alligator',
    'Amory',
    'Anguilla',
    'Arcola',
    'Arkabutla',
    'Artesia',
    'Ashland',
    'Avalon',
    'Avon',
    'Bailey',
    'Baldwyn',
    'Banner',
    'Bassfield',
    'Batesville',
    'Bay Saint Louis',
    'Bay Springs',
    'Beaumont',
    'Becker',
    'Belden',
    'Belen',
    'Bellefontaine',
    'Belmont',
    'Belzoni',
    'Benoit',
    'Benton',
    'Bentonia',
    'Beulah',
    'Big Creek',
    'Biloxi',
    'Blue Mountain',
    'Blue Springs',
    'Bogue Chitto',
    'Bolton',
    'Booneville',
    'Boyle',
    'Brandon',
    'Braxton',
    'Brookhaven',
    'Brooklyn',
    'Brooksville',
    'Bruce',
    'Buckatunna',
    'Bude',
    'Burnsville',
    'Byhalia',
    'Caledonia',
    'Calhoun City',
    'Camden',
    'Canton',
    'Carriere',
    'Carrollton',
    'Carson',
    'Carthage',
    'Cary',
    'Cascilla',
    'Cedarbluff',
    'Centreville',
    'Charleston',
    'Chatawa',
    'Chatham',
    'Chunky',
    'Clara',
    'Clarksdale',
    'Cleveland',
    'Clinton',
    'Coahoma',
    'Coffeeville',
    'Coila',
    'Coldwater',
    'Collins',
    'Collinsville',
    'Columbia',
    'Columbus',
    'Como',
    'Conehatta',
    'Corinth',
    'Courtland',
    'Crawford',
    'Crenshaw',
    'Crosby',
    'Crowder',
    'Cruger',
    'Crystal Springs',
    'D Iberville',
    'D Lo',
    'Daleville',
    'Darling',
    'De Kalb',
    'Decatur',
    'Delta City',
    'Dennis',
    'Derma',
    'Diamondhead',
    'Doddsville',
    'Drew',
    'Dublin',
    'Duck Hill',
    'Dumas',
    'Duncan',
    'Dundee',
    'Durant',
    'Eastabuchie',
    'Ecru',
    'Edwards',
    'Elliott',
    'Ellisville',
    'Enid',
    'Enterprise',
    'Escatawpa',
    'Ethel',
    'Etta',
    'Eupora',
    'Falcon',
    'Falkner',
    'Farrell',
    'Fayette',
    'Fernwood',
    'Flora',
    'Florence',
    'Forest',
    'Foxworth',
    'French Camp',
    'Friars Point',
    'Fulton',
    'Gallman',
    'Gattman',
    'Gautier',
    'Georgetown',
    'Glen',
    'Glen Allan',
    'Glendora',
    'Gloster',
    'Golden',
    'Goodman',
    'Gore Springs',
    'Grace',
    'Greenville',
    'Greenwood',
    'Greenwood Springs',
    'Grenada',
    'Gulfport',
    'Gunnison',
    'Guntown',
    'Hamilton',
    'Harperville',
    'Harriston',
    'Harrisville',
    'Hattiesburg',
    'Hazlehurst',
    'Heidelberg',
    'Hermanville',
    'Hernando',
    'Hickory',
    'Hickory Flat',
    'Hillsboro',
    'Holcomb',
    'Hollandale',
    'Holly Bluff',
    'Holly Ridge',
    'Holly Springs',
    'Horn Lake',
    'Houlka',
    'Houston',
    'Hurley',
    'Independence',
    'Indianola',
    'Inverness',
    'Isola',
    'Itta Bena',
    'Jackson',
    'Jayess',
    'Jonestown',
    'Kilmichael',
    'Kiln',
    'Kokomo',
    'Kosciusko',
    'Lake',
    'Lake Cormorant',
    'Lakeshore',
    'Lamar',
    'Lambert',
    'Lauderdale',
    'Laurel',
    'Lawrence',
    'Leakesville',
    'Leland',
    'Lena',
    'Lexington',
    'Liberty',
    'Little Rock',
    'Long Beach',
    'Lorman',
    'Louin',
    'Louise',
    'Louisville',
    'Lucedale',
    'Ludlow',
    'Lula',
    'Lumberton',
    'Lyon',
    'Maben',
    'Macon',
    'Madden',
    'Madison',
    'Magee',
    'Magnolia',
    'Mantachie',
    'Mantee',
    'Marietta',
    'Marion',
    'Marks',
    'Mathiston',
    'Mattson',
    'Mayersville',
    'Mayhew',
    'McAdams',
    'McCall Creek',
    'McCarley',
    'Mccomb',
    'McCondy',
    'McCool',
    'McHenry',
    'McLain',
    'McNeill',
    'Meadville',
    'Mendenhall',
    'Meridian',
    'Merigold',
    'Metcalfe',
    'Michigan City',
    'Midnight',
    'Minter City',
    'Mississippi State',
    'Mize',
    'Money',
    'Monticello',
    'Montpelier',
    'Mooreville',
    'Moorhead',
    'Morgan City',
    'Morton',
    'Moselle',
    'Moss',
    'Moss Point',
    'Mound Bayou',
    'Mount Olive',
    'Mount Pleasant',
    'Myrtle',
    'Natchez',
    'Neely',
    'Nesbit',
    'Nettleton',
    'New Albany',
    'New Augusta',
    'New Site',
    'Newhebron',
    'Newton',
    'Nicholson',
    'Nitta Yuma',
    'North Carrollton',
    'Noxapater',
    'Oak Vale',
    'Oakland',
    'Ocean Springs',
    'Okolona',
    'Olive Branch',
    'Osyka',
    'Ovett',
    'Oxford',
    'Pace',
    'Pachuta',
    'Panther Burn',
    'Parchman',
    'Paris',
    'Pascagoula',
    'Pass Christian',
    'Pattison',
    'Paulding',
    'Pearlington',
    'Pelahatchie',
    'Perkinston',
    'Petal',
    'Pheba',
    'Philadelphia',
    'Philipp',
    'Picayune',
    'Pickens',
    'Piney Woods',
    'Pinola',
    'Pittsboro',
    'Plantersville',
    'Pocahontas',
    'Pontotoc',
    'Pope',
    'Poplarville',
    'Port Gibson',
    'Porterville',
    'Potts Camp',
    'Prairie',
    'Prentiss',
    'Preston',
    'Puckett',
    'Pulaski',
    'Purvis',
    'Quitman',
    'Raleigh',
    'Randolph',
    'Raymond',
    'Red Banks',
    'Redwood',
    'Rena Lara',
    'Richton',
    'Ridgeland',
    'Rienzi',
    'Ripley',
    'Robinsonville',
    'Rolling Fork',
    'Rome',
    'Rose Hill',
    'Rosedale',
    'Roxie',
    'Ruleville',
    'Ruth',
    'Sallis',
    'Saltillo',
    'Sanatorium',
    'Sandersville',
    'Sandhill',
    'Sandy Hook',
    'Sarah',
    'Sardis',
    'Satartia',
    'Saucier',
    'Schlater',
    'Scobey',
    'Scooba',
    'Scott',
    'Sebastopol',
    'Seminary',
    'Senatobia',
    'Shannon',
    'Sharon',
    'Shaw',
    'Shelby',
    'Sherard',
    'Sherman',
    'Shubuta',
    'Shuqualak',
    'Sibley',
    'Sidon',
    'Silver City',
    'Silver Creek',
    'Slate Spring',
    'Sledge',
    'Smithdale',
    'Smithville',
    'Sontag',
    'Soso',
    'Southaven',
    'Star',
    'Starkville',
    'State Line',
    'Steens',
    'Stennis Space Center',
    'Stewart',
    'Stoneville',
    'Stonewall',
    'Stringer',
    'Sturgis',
    'Summit',
    'Sumner',
    'Sumrall',
    'Sunflower',
    'Swan Lake',
    'Swiftown',
    'Taylor',
    'Taylorsville',
    'Tchula',
    'Terry',
    'Thaxton',
    'Thomastown',
    'Tie Plant',
    'Tillatoba',
    'Tinsley',
    'Tiplersville',
    'Tippo',
    'Tishomingo',
    'Toccopola',
    'Toomsuba',
    'Tougaloo',
    'Trebloc',
    'Tremont',
    'Tula',
    'Tunica',
    'Tupelo',
    'Tutwiler',
    'Tylertown',
    'Union',
    'Union Church',
    'University',
    'Utica',
    'Vaiden',
    'Valley Park',
    'Van Vleet',
    'Vance',
    'Vardaman',
    'Vaughan',
    'Verona',
    'Vicksburg',
    'Victoria',
    'Vossburg',
    'Walls',
    'Walnut',
    'Walnut Grove',
    'Walthall',
    'Washington',
    'Water Valley',
    'Waterford',
    'Waveland',
    'Waynesboro',
    'Wayside',
    'Webb',
    'Weir',
    'Wesson',
    'West',
    'West Point',
    'Wheeler',
    'Whitfield',
    'Wiggins',
    'Winona',
    'Winstonville',
    'Winterville',
    'Woodland',
    'Woodville',
    'Yazoo City'
]
