cities = [
    'Adrian',
    'Advance',
    'Agency',
    'Alba',
    'Albany',
    'Aldrich',
    'Alexandria',
    'Allendale',
    'Allenton',
    'Alma',
    'Altamont',
    'Altenburg',
    'Alton',
    'Amazonia',
    'Amity',
    'Amoret',
    'Amsterdam',
    'Anabel',
    'Anderson',
    'Annada',
    'Annapolis',
    'Anniston',
    'Appleton City',
    'Arbela',
    'Arbyrd',
    'Arcadia',
    'Archie',
    'Arcola',
    'Argyle',
    'Armstrong',
    'Arnold',
    'Arrow Rock',
    'Asbury',
    'Ash Grove',
    'Ashburn',
    'Ashland',
    'Atlanta',
    'Augusta',
    'Aurora',
    'Auxvasse',
    'Ava',
    'Avilla',
    'Bakersfield',
    'Ballwin',
    'Baring',
    'Barnard',
    'Barnett',
    'Barnhart',
    'Bates City',
    'Beaufort',
    'Belgrade',
    'Bell City',
    'Belle',
    'Belleview',
    'Bellflower',
    'Belton',
    'Bendavis',
    'Benton',
    'Benton City',
    'Berger',
    'Bernie',
    'Bertrand',
    'Bethany',
    'Bethel',
    'Beulah',
    'Bevier',
    'Billings',
    'Birch Tree',
    'Bismarck',
    'Bixby',
    'Black',
    'Blackburn',
    'Blackwater',
    'Blackwell',
    'Blairstown',
    'Bland',
    'Blodgett',
    'Bloomfield',
    'Bloomsdale',
    'Blue Eye',
    'Blue Mound',
    'Blue Springs',
    'Blythedale',
    'Bogard',
    'Bois D Arc',
    'Bolckow',
    'Bolivar',
    'Bonne Terre',
    'Bonnots Mill',
    'Boonville',
    'Boss',
    'Bosworth',
    'Bourbon',
    'Bowling Green',
    'Bradleyville',
    'Bragg City',
    'Braggadocio',
    'Brandsville',
    'Branson',
    'Brashear',
    'Braymer',
    'Brazeau',
    'Breckenridge',
    'Briar',
    'Bridgeton',
    'Brighton',
    'Brinktown',
    'Brixey',
    'Bronaugh',
    'Brookfield',
    'Brookline Station',
    'Broseley',
    'Browning',
    'Brownwood',
    'Brumley',
    'Bruner',
    'Brunswick',
    'Bucklin',
    'Buckner',
    'Bucyrus',
    'Buffalo',
    'Bunceton',
    'Bunker',
    'Burfordville',
    'Burlington Junction',
    'Butler',
    'Butterfield',
    'Cabool',
    'Cadet',
    'Cainsville',
    'Cairo',
    'Caledonia',
    'Calhoun',
    'California',
    'Callao',
    'Camden',
    'Camden Point',
    'Camdenton',
    'Cameron',
    'Campbell',
    'Canalou',
    'Canton',
    'Cape Fair',
    'Cape Girardeau',
    'Caplinger Mills',
    'Cardwell',
    'Carl Junction',
    'Carrollton',
    'Carterville',
    'Carthage',
    'Caruthersville',
    'Cascade',
    'Cassville',
    'Catawissa',
    'Catron',
    'Caulfield',
    'Cedar City',
    'Cedar Hill',
    'Cedarcreek',
    'Center',
    'Centertown',
    'Centerview',
    'Centerville',
    'Centralia',
    'Chadwick',
    'Chaffee',
    'Chamois',
    'Charleston',
    'Cherryville',
    'Chesterfield',
    'Chestnutridge',
    'Chilhowee',
    'Chillicothe',
    'Chula',
    'Clarence',
    'Clark',
    'Clarksburg',
    'Clarksdale',
    'Clarksville',
    'Clarkton',
    'Clay',
    'Clearmont',
    'Cleveland',
    'Clever',
    'Clifton Hill',
    'Climax Springs',
    'Clinton',
    'Clubb',
    'Clyde',
    'Coatsville',
    'Coffey',
    'Cole Camp',
    'Collins',
    'Columbia',
    'Commerce',
    'Conception',
    'Conception Junction',
    'Concordia',
    'Conran',
    'Conway',
    'Cook Station',
    'Cooter',
    'Corder',
    'Cosby',
    'Cottleville',
    'Couch',
    'Cowgill',
    'Craig',
    'Crane',
    'Creighton',
    'Crocker',
    'Cross Timbers',
    'Crystal City',
    'Cuba',
    'Curryville',
    'Dadeville',
    'Daisy',
    'Dalton',
    'Darlington',
    'Davisville',
    'Dawn',
    'De Kalb',
    'De Soto',
    'De Witt',
    'Dearborn',
    'Deepwater',
    'Deerfield',
    'Deering',
    'Defiance',
    'Delta',
    'Denver',
    'Des Arc',
    'Devils Elbow',
    'Dexter',
    'Diamond',
    'Diggins',
    'Dittmer',
    'Dixon',
    'Doe Run',
    'Doniphan',
    'Dora',
    'Dover',
    'Downing',
    'Drexel',
    'Drury',
    'Dudley',
    'Duenweg',
    'Duke',
    'Dunnegan',
    'Durham',
    'Dutchtown',
    'Dutzow',
    'Eagle Rock',
    'Eagleville',
    'Earth City',
    'East Lynne',
    'East Prairie',
    'Easton',
    'Edgar Springs',
    'Edgerton',
    'Edina',
    'Edwards',
    'El Dorado Springs',
    'Eldon',
    'Eldridge',
    'Elk Creek',
    'Elkland',
    'Ellington',
    'Ellsinore',
    'Elmer',
    'Elmo',
    'Elsberry',
    'Emden',
    'Eminence',
    'Emma',
    'Eolia',
    'Essex',
    'Ethel',
    'Etterville',
    'Eudora',
    'Eugene',
    'Eunice',
    'Eureka',
    'Everton',
    'Ewing',
    'Excello',
    'Excelsior Springs',
    'Exeter',
    'Fagus',
    'Fair Grove',
    'Fair Play',
    'Fairdealing',
    'Fairfax',
    'Fairport',
    'Fairview',
    'Falcon',
    'Farber',
    'Farley',
    'Farmington',
    'Farrar',
    'Faucett',
    'Fayette',
    'Fenton',
    'Festus',
    'Fillmore',
    'Fisk',
    'Flemington',
    'Fletcher',
    'Flinthill',
    'Florence',
    'Florissant',
    'Foley',
    'Fordland',
    'Forest City',
    'Foristell',
    'Forsyth',
    'Fort Leonard Wood',
    'Fortuna',
    'Foster',
    'Frankford',
    'Franklin',
    'Fredericktown',
    'Freeburg',
    'Freeman',
    'Freistatt',
    'Fremont',
    'French Village',
    'Friedheim',
    'Frohna',
    'Fulton',
    'Gainesville',
    'Galena',
    'Gallatin',
    'Galt',
    'Garden City',
    'Garrison',
    'Gasconade',
    'Gatewood',
    'Gentry',
    'Gerald',
    'Gibbs',
    'Gibson',
    'Gideon',
    'Gilliam',
    'Gilman City',
    'Gipsy',
    'Glasgow',
    'Glenallen',
    'Glencoe',
    'Glenwood',
    'Glover',
    'Gobler',
    'Golden',
    'Golden City',
    'Goodman',
    'Goodson',
    'Gordonville',
    'Gorin',
    'Gower',
    'Graff',
    'Graham',
    'Grain Valley',
    'Granby',
    'Grandin',
    'Grandview',
    'Granger',
    'Grant City',
    'Grassy',
    'Gravois Mills',
    'Gray Summit',
    'Grayridge',
    'Green Castle',
    'Green City',
    'Green Ridge',
    'Greenfield',
    'Greentop',
    'Greenville',
    'Greenwood',
    'Grover',
    'Grovespring',
    'Grubville',
    'Guilford',
    'Hale',
    'Half Way',
    'Hallsville',
    'Halltown',
    'Hamilton',
    'Hannibal',
    'Hardenville',
    'Hardin',
    'Harris',
    'Harrisburg',
    'Harrisonville',
    'Hartsburg',
    'Hartshorn',
    'Hartville',
    'Harviell',
    'Harwood',
    'Hatfield',
    'Hawk Point',
    'Hayti',
    'Hazelwood',
    'Helena',
    'Hematite',
    'Henley',
    'Henrietta',
    'Herculaneum',
    'Hermann',
    'Hermitage',
    'Higbee',
    'Higginsville',
    'High Hill',
    'High Point',
    'High Ridge',
    'Highlandville',
    'Hillsboro',
    'Hiram',
    'Holcomb',
    'Holden',
    'Holland',
    'Holliday',
    'Hollister',
    'Holt',
    'Holts Summit',
    'Hopkins',
    'Hornersville',
    'Horton',
    'House Springs',
    'Houston',
    'Houstonia',
    'Huggins',
    'Hughesville',
    'Humansville',
    'Hume',
    'Humphreys',
    'Hunnewell',
    'Huntsville',
    'Hurdland',
    'Hurley',
    'Iberia',
    'Imperial',
    'Independence',
    'Ionia',
    'Irondale',
    'Ironton',
    'Isabella',
    'Jackson',
    'Jacksonville',
    'Jadwin',
    'Jameson',
    'Jamesport',
    'Jamestown',
    'Jasper',
    'Jefferson City',
    'Jerico Springs',
    'Jerome',
    'Jonesburg',
    'Joplin',
    'Kahoka',
    'Kaiser',
    'Kansas City',
    'Kearney',
    'Kelso',
    'Kennett',
    'Kewanee',
    'Keytesville',
    'Kidder',
    'Kimberling City',
    'Kimmswick',
    'King City',
    'Kingdom City',
    'Kingston',
    'Kingsville',
    'Kirbyville',
    'Kirksville',
    'Kissee Mills',
    'Knob Lick',
    'Knob Noster',
    'Knox City',
    'Koeltztown',
    'Koshkonong',
    'La Belle',
    'La Grange',
    'La Monte',
    'La Plata',
    'La Russell',
    'Labadie',
    'Laclede',
    'Laddonia',
    'Lake Ozark',
    'Lake Saint Louis',
    'Lake Spring',
    'Lamar',
    'Lampe',
    'Lanagan',
    'Lancaster',
    'Laquey',
    'Laredo',
    'Latham',
    'Lathrop',
    'Laurie',
    'Lawson',
    'Leadwood',
    'Leasburg',
    'Lebanon',
    'Lecoma',
    "Lee's Summit",
    'Leeton',
    'Lenox',
    'Lentner',
    'Leonard',
    'Leopold',
    'Leslie',
    'Lesterville',
    'Levasy',
    'Lewistown',
    'Lexington',
    'Liberal',
    'Liberty',
    'Licking',
    'Liguori',
    'Lilbourn',
    'Lincoln',
    'Linn',
    'Linn Creek',
    'Linneus',
    'Livonia',
    'Lock Springs',
    'Lockwood',
    'Lodi',
    'Lohman',
    'Lone Jack',
    'Lonedell',
    'Long Lane',
    'Loose Creek',
    'Louisburg',
    'Louisiana',
    'Lowndes',
    'Lowry City',
    'Lucerne',
    'Ludlow',
    'Luebbering',
    'Luray',
    'Lynchburg',
    'Macks Creek',
    'Macomb',
    'Macon',
    'Madison',
    'Maitland',
    'Malden',
    'Malta Bend',
    'Mansfield',
    'Mapaville',
    'Marble Hill',
    'Marceline',
    'Marionville',
    'Marquand',
    'Marshall',
    'Marshfield',
    'Marston',
    'Marthasville',
    'Martinsburg',
    'Martinsville',
    'Maryland Heights',
    'Maryville',
    'Matthews',
    'Maysville',
    'Mayview',
    'Maywood',
    'McBride',
    'McClurg',
    'McFall',
    'McGee',
    'McGirk',
    'Meadville',
    'Memphis',
    'Mendon',
    'Mercer',
    'Meta',
    'Metz',
    'Mexico',
    'Miami',
    'Mid Missouri',
    'Middle Brook',
    'Middletown',
    'Milan',
    'Milford',
    'Mill Spring',
    'Miller',
    'Millersville',
    'Milo',
    'Mindenmines',
    'Mineral Point',
    'Missouri City',
    'Moberly',
    'Mokane',
    'Monett',
    'Monroe City',
    'Montgomery City',
    'Monticello',
    'Montier',
    'Montreal',
    'Montrose',
    'Moody',
    'Mooresville',
    'Mora',
    'Morehouse',
    'Morley',
    'Morris',
    'Morrison',
    'Morrisville',
    'Morse Mill',
    'Mosby',
    'Moscow Mills',
    'Mound City',
    'Moundville',
    'Mount Moriah',
    'Mount Sterling',
    'Mount Vernon',
    'Mountain Grove',
    'Mountain View',
    'Myrtle',
    'Napoleon',
    'Naylor',
    'Neck City',
    'Neelyville',
    'Nelson',
    'Neosho',
    'Nevada',
    'New Bloomfield',
    'New Boston',
    'New Cambria',
    'New Florence',
    'New Franklin',
    'New Hampton',
    'New Haven',
    'New London',
    'New Madrid',
    'New Melle',
    'New Offenburg',
    'Newark',
    'Newburg',
    'Newtonia',
    'Newtown',
    'Niangua',
    'Nixa',
    'Noble',
    'Noel',
    'Norborne',
    'Norwood',
    'Novelty',
    'Novinger',
    'O Fallon',
    'Oak Grove',
    'Oak Ridge',
    'Odessa',
    'Old Appleton',
    'Old Monroe',
    'Oldfield',
    'Olean',
    'Olney',
    'Oran',
    'Oregon',
    'Oronogo',
    'Orrick',
    'Osage Beach',
    'Osborn',
    'Osceola',
    'Otterville',
    'Owensville',
    'Oxly',
    'Ozark',
    'Pacific',
    'Painton',
    'Palmyra',
    'Paris',
    'Park Hills',
    'Parma',
    'Parnell',
    'Pascola',
    'Passaic',
    'Patterson',
    'Patton',
    'Pattonsburg',
    'Paynesville',
    'Peace Valley',
    'Peculiar',
    'Perkins',
    'Perry',
    'Perryville',
    'Pevely',
    'Philadelphia',
    'Phillipsburg',
    'Pickering',
    'Piedmont',
    'Pierce City',
    'Pilot Grove',
    'Pilot Knob',
    'Pineville',
    'Pittsburg',
    'Plato',
    'Platte City',
    'Plattsburg',
    'Pleasant Hill',
    'Pleasant Hope',
    'Plevna',
    'Pocahontas',
    'Point Lookout',
    'Polk',
    'Pollock',
    'Polo',
    'Pomona',
    'Ponce De Leon',
    'Pontiac',
    'Poplar Bluff',
    'Portage Des Sioux',
    'Portageville',
    'Portland',
    'Potosi',
    'Pottersville',
    'Powell',
    'Powersite',
    'Powersville',
    'Prairie Home',
    'Preston',
    'Princeton',
    'Purcell',
    'Purdin',
    'Purdy',
    'Puxico',
    'Queen City',
    'Quincy',
    'Quitman',
    'Qulin',
    'Racine',
    'Ravenwood',
    'Raymondville',
    'Raymore',
    'Rayville',
    'Rea',
    'Redford',
    'Reeds',
    'Reeds Spring',
    'Renick',
    'Republic',
    'Revere',
    'Reynolds',
    'Rhineland',
    'Rich Hill',
    'Richards',
    'Richland',
    'Richmond',
    'Richwoods',
    'Ridgedale',
    'Ridgeway',
    'Risco',
    'Riverside',
    'Rives',
    'Roach',
    'Robertsville',
    'Roby',
    'Rocheport',
    'Rock Port',
    'Rockaway Beach',
    'Rockbridge',
    'Rockville',
    'Rocky Comfort',
    'Rocky Mount',
    'Rogersville',
    'Rolla',
    'Rombauer',
    'Roscoe',
    'Rosebud',
    'Rosendale',
    'Rothville',
    'Rueter',
    'Rush Hill',
    'Rushville',
    'Russellville',
    'Rutledge',
    'Saginaw',
    'Saint Albans',
    'Saint Ann',
    'Saint Charles',
    'Saint Clair',
    'Saint Elizabeth',
    'Saint James',
    'Saint Joseph',
    'Saint Louis',
    'Saint Mary',
    'Saint Patrick',
    'Saint Peters',
    'Saint Thomas',
    'Sainte Genevieve',
    'Salem',
    'Salisbury',
    'Santa Fe',
    'Sarcoxie',
    'Savannah',
    'Saverton',
    'Schell City',
    'Scott City',
    'Sedalia',
    'Sedgewickville',
    'Seligman',
    'Senath',
    'Seneca',
    'Seymour',
    'Shelbina',
    'Shelbyville',
    'Sheldon',
    'Shell Knob',
    'Sheridan',
    'Shook',
    'Sibley',
    'Sikeston',
    'Silex',
    'Silva',
    'Skidmore',
    'Slater',
    'Smithton',
    'Smithville',
    'Solo',
    'South Fork',
    'South Greenfield',
    'South West City',
    'Sparta',
    'Spickard',
    'Spokane',
    'Springfield',
    'Squires',
    'St. Robert',
    'Stanberry',
    'Stanton',
    'Stark City',
    'Steedman',
    'Steele',
    'Steelville',
    'Stella',
    'Stet',
    'Stewartsville',
    'Stockton',
    'Stotts City',
    'Stoutland',
    'Stoutsville',
    'Stover',
    'Strafford',
    'Strasburg',
    'Sturdivant',
    'Sturgeon',
    'Success',
    'Sullivan',
    'Summersville',
    'Sumner',
    'Sunrise Beach',
    'Swedeborg',
    'Sweet Springs',
    'Syracuse',
    'Tallapoosa',
    'Taneyville',
    'Tarkio',
    'Taylor',
    'Tebbetts',
    'Tecumseh',
    'Teresita',
    'Thayer',
    'Thompson',
    'Thornfield',
    'Tiff',
    'Tiff City',
    'Tina',
    'Tipton',
    'Treloar',
    'Trenton',
    'Trimble',
    'Triplett',
    'Troy',
    'Truxton',
    'Tunas',
    'Turners',
    'Turney',
    'Tuscumbia',
    'Udall',
    'Ulman',
    'Union',
    'Union Star',
    'Uniontown',
    'Unionville',
    'Urbana',
    'Urich',
    'Utica',
    'Valles Mines',
    'Valley Park',
    'Van Buren',
    'Vandalia',
    'Vanduser',
    'Vanzant',
    'Verona',
    'Versailles',
    'Viburnum',
    'Vichy',
    'Vienna',
    'Villa Ridge',
    'Vista',
    'Vulcan',
    'Waco',
    'Wakenda',
    'Waldron',
    'Walker',
    'Walnut Grove',
    'Walnut Shade',
    'Wappapello',
    'Wardell',
    'Warrensburg',
    'Warrenton',
    'Warsaw',
    'Washburn',
    'Washington',
    'Wasola',
    'Watson',
    'Waverly',
    'Wayland',
    'Waynesville',
    'Weatherby',
    'Weaubleau',
    'Webb City',
    'Wellington',
    'Wellsville',
    'Wentworth',
    'Wentzville',
    'Wesco',
    'West Alton',
    'West Plains',
    'Westboro',
    'Weston',
    'Westphalia',
    'Wheatland',
    'Wheaton',
    'Wheeling',
    'Whiteman Air Force Base',
    'Whiteoak',
    'Whiteside',
    'Whitewater',
    'Willard',
    'Williamsburg',
    'Williamstown',
    'Williamsville',
    'Willow Springs',
    'Windsor',
    'Windyville',
    'Winfield',
    'Winigan',
    'Winona',
    'Winston',
    'Wolf Island',
    'Wooldridge',
    'Worth',
    'Worthington',
    'Wright City',
    'Wyaconda',
    'Wyatt',
    'Yukon',
    'Zalma',
    'Zanoni'
]
