cities = [
    'Alamo',
    'Amargosa Valley',
    'Austin',
    'Baker',
    'Battle Mountain',
    'Beatty',
    'Blue Diamond',
    'Boulder City',
    'Bunkerville',
    'Cal Nev Ari',
    'Caliente',
    'Carlin',
    'Carson City',
    'Crescent Valley',
    'Crystal Bay',
    'Dayton',
    'Deeth',
    'Denio',
    'Duckwater',
    'Dyer',
    'Elko',
    'Ely',
    'Empire',
    'Eureka',
    'Fallon',
    'Fernley',
    'Gabbs',
    'Gardnerville',
    'Gardnerville Ranchos',
    'Genoa',
    'Gerlach',
    'Gerlach-Empire',
    'Glenbrook',
    'Golconda',
    'Goldfield',
    'Halleck',
    'Hawthorne',
    'Henderson',
    'Hiko',
    'Imlay',
    'Incline Village',
    'Indian Springs',
    'Jackpot',
    'Jarbidge',
    'Jean',
    'Kingsbury',
    'Lamoille',
    'Las Vegas',
    'Laughlin',
    'Logandale',
    'Lovelock',
    'Lund',
    'Luning',
    'Manhattan',
    'McDermitt',
    'McGill',
    'Mercury',
    'Mesquite',
    'Mina',
    'Minden',
    'Moapa',
    'Montello',
    'Mountain City',
    'Nellis AFB',
    'Nixon',
    'North Las Vegas',
    'Orovada',
    'Overton',
    'Owyhee',
    'Pahrump',
    'Panaca',
    'Paradise Valley',
    'Pioche',
    'Reno',
    'Round Mountain',
    'Ruby Valley',
    'Ruth',
    'Schurz',
    'Searchlight',
    'Silver City',
    'Silver Springs',
    'Silverpeak',
    'Smith',
    'Sparks',
    'Spring Creek',
    'Stateline',
    'Summerlin South',
    'Sun Valley',
    'The Lakes',
    'Tonopah',
    'Tuscarora',
    'Valmy',
    'Virginia City',
    'Wadsworth',
    'Washoe Valley',
    'Wellington',
    'Wells',
    'West Wendover',
    'Winnemucca',
    'Yerington',
    'Zephyr Cove'
]
