cities = [
    'Absecon',
    'Adelphia',
    'Allamuchy',
    'Allendale',
    'Allenhurst',
    'Allentown',
    'Allenwood',
    'Alloway',
    'Alpine',
    'Andover',
    'Annandale',
    'Asbury',
    'Asbury Park',
    'Atco',
    'Atlantic City',
    'Atlantic Highlands',
    'Audubon',
    'Augusta',
    'Avalon',
    'Avenel',
    'Avon By The Sea',
    'Baptistown',
    'Barnegat',
    'Barnegat Light',
    'Barrington',
    'Basking Ridge',
    'Bass River',
    'Bayonne',
    'Bayville',
    'Beach Haven',
    'Beachwood',
    'Bedminster',
    'Belford',
    'Belle Mead',
    'Belleville',
    'Bellmawr',
    'Belmar',
    'Belvidere',
    'Bergenfield',
    'Berkeley',
    'Berkeley Heights',
    'Berlin',
    'Bernards',
    'Bernardsville',
    'Beverly',
    'Birmingham',
    'Blackwood',
    'Blairstown',
    'Blawenburg',
    'Bloomfield',
    'Bloomingdale',
    'Bloomsbury',
    'Bogota',
    'Boonton',
    'Bordentown',
    'Bound Brook',
    'Bradley Beach',
    'Branchville',
    'Brick',
    'Bridgeport',
    'Bridgeton',
    'Bridgewater',
    'Brielle',
    'Brigantine',
    'Broadway',
    'Brookside',
    'Browns Mills',
    'Budd Lake',
    'Buena',
    'Burlington',
    'Butler',
    'Buttzville',
    'Caldwell',
    'Califon',
    'Camden',
    'Cape May',
    'Cape May Court House',
    'Cape May Point',
    'Carlstadt',
    'Carteret',
    'Cedar Brook',
    'Cedar Grove',
    'Cedar Knolls',
    'Cedarville',
    'Changewater',
    'Chatham',
    'Chatsworth',
    'Cherry Hill',
    'Chester',
    'Clark',
    'Clarksboro',
    'Clarksburg',
    'Clayton',
    'Clementon',
    'Cliffside Park',
    'Cliffwood',
    'Clifton',
    'Clinton',
    'Closter',
    'Collingswood',
    'Cologne',
    'Colonia',
    'Colts Neck',
    'Columbia',
    'Columbus',
    'Cookstown',
    'Cranbury',
    'Cranford',
    'Cream Ridge',
    'Cresskill',
    'Crosswicks',
    'Dayton',
    'Deal',
    'Deepwater',
    'Deerfield Street',
    'Delaware',
    'Delmont',
    'Demarest',
    'Dennisville',
    'Denville',
    'Dividing Creek',
    'Dorchester',
    'Dorothy',
    'Dover',
    'Downe',
    'Dumont',
    'Dunellen',
    'East Amwell',
    'East Brunswick',
    'East Hanover',
    'East Orange',
    'East Rutherford',
    'Eatontown',
    'Edgewater',
    'Edison',
    'Egg Harbor City',
    'Egg Harbor Township',
    'Elizabeth',
    'Elmer',
    'Elmwood Park',
    'Elwood',
    'Elwood-Magnolia',
    'Emerson',
    'Englewood',
    'Englewood Cliffs',
    'Englishtown',
    'Essex Fells',
    'Estell Manor',
    'Ewan',
    'Fair Haven',
    'Fair Lawn',
    'Fairfield',
    'Fairton',
    'Fairview',
    'Fanwood',
    'Far Hills',
    'Farmingdale',
    'Flagtown',
    'Flanders',
    'Flemington',
    'Florence',
    'Florham Park',
    'Fords',
    'Forked River',
    'Fort Lee',
    'Fort Monmouth',
    'Fortescue',
    'Franklin',
    'Franklin Lakes',
    'Franklin Park',
    'Franklinville',
    'Freehold',
    'Frenchtown',
    'Garfield',
    'Garwood',
    'Gibbsboro',
    'Gibbstown',
    'Gillette',
    'Gladstone',
    'Glassboro',
    'Glasser',
    'Glen Gardner',
    'Glen Ridge',
    'Glen Rock',
    'Glendora',
    'Glenwood',
    'Gloucester City',
    'Goshen',
    'Great Meadows',
    'Great Meadows-Vienna',
    'Green Creek',
    'Green Village',
    'Greendell',
    'Greenwich',
    'Grenloch',
    'Hackensack',
    'Hackettstown',
    'Haddon Heights',
    'Haddonfield',
    'Hainesport',
    'Haledon',
    'Hamburg',
    'Hammonton',
    'Hampton',
    'Hancocks Bridge',
    'Hardyston',
    'Harrington Park',
    'Harrison',
    'Harrisonville',
    'Hasbrouck Heights',
    'Haskell',
    'Haworth',
    'Hawthorne',
    'Hazlet',
    'Heislerville',
    'Helmetta',
    'Hewitt',
    'Hibernia',
    'High Bridge',
    'Highland Lakes',
    'Highland Park',
    'Highlands',
    'Hightstown',
    'Hillsdale',
    'Hillside',
    'Ho Ho Kus',
    'Ho-Ho-Kus',
    'Hoboken',
    'Holmdel',
    'Hopatcong',
    'Hope',
    'Hopewell',
    'Howell',
    'Imlaystown',
    'Ironia',
    'Irvington',
    'Iselin',
    'Island Heights',
    'Jackson',
    'Jamesburg',
    'Jersey City',
    'Jobstown',
    'Johnsonburg',
    'Juliustown',
    'Keansburg',
    'Kearny',
    'Keasbey',
    'Kendall Park',
    'Kenilworth',
    'Kenvil',
    'Keyport',
    'Kingston',
    'Lafayette',
    'Lake Hiawatha',
    'Lake Hopatcong',
    'Lakehurst',
    'Lakewood',
    'Lambertville',
    'Landing',
    'Landisville',
    'Lanoka Harbor',
    'Lavallette',
    'Lawnside',
    'Layton',
    'Lebanon',
    'Ledgewood',
    'Leeds Point',
    'Leesburg',
    'Leonardo',
    'Leonia',
    'Liberty Corner',
    'Lincoln Park',
    'Lincroft',
    'Linden',
    'Linwood',
    'Little Falls',
    'Little Ferry',
    'Little Silver',
    'Little York',
    'Livingston',
    'Lodi',
    'Long Branch',
    'Long Valley',
    'Longport',
    'Lumberton',
    'Lyndhurst',
    'Lyons',
    'Madison',
    'Magnolia',
    'Mahwah',
    'Malaga',
    'Manahawkin',
    'Manasquan',
    'Mantoloking',
    'Mantua',
    'Manville',
    'Maple Shade',
    'Maplewood',
    'Margate City',
    'Marlboro',
    'Marlton',
    'Marmora',
    'Martinsville',
    'Matawan',
    'Maurice River',
    'Mauricetown',
    'Mays Landing',
    'Maywood',
    'McAfee',
    'Medford',
    'Mendham',
    'Merchantville',
    'Metuchen',
    'Mickleton',
    'Middlesex',
    'Middletown',
    'Middleville',
    'Midland Park',
    'Milford',
    'Millburn',
    'Millington',
    'Millstone',
    'Milltown',
    'Millville',
    'Milmay',
    'Mine Hill',
    'Minotola',
    'Mizpah',
    'Monmouth Beach',
    'Monmouth Junction',
    'Monroeville',
    'Montague',
    'Montclair',
    'Montvale',
    'Montville',
    'Moonachie',
    'Moorestown',
    'Morganville',
    'Morris Plains',
    'Morristown',
    'Mount Arlington',
    'Mount Ephraim',
    'Mount Freedom',
    'Mount Holly',
    'Mount Laurel',
    'Mount Royal',
    'Mount Tabor',
    'Mountain Lakes',
    'Mountainside',
    'Mullica Hill',
    'National Park',
    'Navesink',
    'Neptune',
    'Neshanic Station',
    'Netcong',
    'New Brunswick',
    'New Egypt',
    'New Gretna',
    'New Lisbon',
    'New Milford',
    'New Providence',
    'New Vernon',
    'New York',
    'Newark',
    'Newfield',
    'Newfoundland',
    'Newport',
    'Newton',
    'Newtonville',
    'Norma',
    'Normandy Beach',
    'North Arlington',
    'North Bergen',
    'North Brunswick',
    'Northfield',
    'Northvale',
    'Norwood',
    'Nutley',
    'Oak Ridge',
    'Oakhurst',
    'Oakland',
    'Oaklyn',
    'Ocean City',
    'Ocean Gate',
    'Ocean Grove',
    'Ocean View',
    'Oceanport',
    'Oceanville',
    'Ogdensburg',
    'Old Bridge',
    'Oldwick',
    'Oradell',
    'Orange',
    'Oxford',
    'Palisades Park',
    'Palmyra',
    'Paramus',
    'Park Ridge',
    'Parlin',
    'Parsippany',
    'Passaic',
    'Paterson',
    'Paulsboro',
    'Peapack',
    'Peapack and Gladstone',
    'Pedricktown',
    'Pemberton',
    'Pennington',
    'Penns Grove',
    'Pennsauken',
    'Pennsville',
    'Pequannock',
    'Perrineville',
    'Perth Amboy',
    'Phillipsburg',
    'Picatinny Arsenal',
    'Pine Beach',
    'Pine Brook',
    'Piscataway',
    'Pitman',
    'Pittstown',
    'Plainfield',
    'Plainsboro',
    'Pleasantville',
    'Pluckemin',
    'Point Pleasant Beach',
    'Pomona',
    'Pompton Lakes',
    'Pompton Plains',
    'Port Elizabeth',
    'Port Monmouth',
    'Port Murray',
    'Port Norris',
    'Port Reading',
    'Port Republic',
    'Pottersville',
    'Princeton',
    'Princeton Junction',
    'Quakertown',
    'Quinton',
    'Rahway',
    'Ramsey',
    'Rancocas',
    'Randolph',
    'Raritan',
    'Readington',
    'Red Bank',
    'Richland',
    'Richwood',
    'Ridgefield',
    'Ridgefield Park',
    'Ridgewood',
    'Ringoes',
    'Ringwood',
    'Rio Grande',
    'River Edge',
    'Riverdale',
    'Riverside',
    'Riverton',
    'Rochelle Park',
    'Rockaway',
    'Rocky Hill',
    'Roebling',
    'Roosevelt',
    'Roseland',
    'Roselle',
    'Roselle Park',
    'Rosemont',
    'Rosenhayn',
    'Rumson',
    'Runnemede',
    'Rutherford',
    'Saddle Brook',
    'Saddle River',
    'Salem',
    'Sayreville',
    'Schooleys Mountain',
    'Scotch Plains',
    'Sea Girt',
    'Sea Isle City',
    'Seaside Heights',
    'Seaside Park',
    'Secaucus',
    'Sergeantsville',
    'Sewaren',
    'Sewell',
    'Shiloh',
    'Short Hills',
    'Shrewsbury',
    'Sicklerville',
    'Skillman',
    'Somerdale',
    'Somers Point',
    'Somerset',
    'Somerville',
    'South Amboy',
    'South Bound Brook',
    'South Dennis',
    'South Hackensack',
    'South Orange',
    'South Plainfield',
    'South River',
    'South Seaville',
    'Sparta',
    'Spotswood',
    'Spring Lake',
    'Springfield',
    'Stanhope',
    'Stanton',
    'Stewartsville',
    'Stillwater',
    'Stirling',
    'Stockholm',
    'Stockton',
    'Stone Harbor',
    'Stratford',
    'Strathmere',
    'Succasunna',
    'Summit',
    'Sussex',
    'Swartswood',
    'Swedesboro',
    'Teaneck',
    'Tenafly',
    'Tennent',
    'Teterboro',
    'Thorofare',
    'Three Bridges',
    'Titusville',
    'Toms River',
    'Totowa',
    'Towaco',
    'Tranquility',
    'Trenton',
    'Tuckahoe',
    'Tuckerton',
    'Union',
    'Union City',
    'Vauxhall',
    'Ventnor City',
    'Vernon',
    'Verona',
    'Vienna',
    'Villas',
    'Vincentown',
    'Vineland',
    'Voorhees',
    'Waldwick',
    'Wallington',
    'Wallpack Center',
    'Wanaque',
    'Waretown',
    'Warren',
    'Washington',
    'Watchung',
    'Waterford Works',
    'Wayne',
    'Wenonah',
    'West Berlin',
    'West Creek',
    'West Long Branch',
    'West Milford',
    'West New York',
    'West Orange',
    'West Paterson',
    'Westfield',
    'Westville',
    'Westwood',
    'Wharton',
    'Whippany',
    'Whitehouse',
    'Whitehouse Station',
    'Whitesboro',
    'Whiting',
    'Wickatunk',
    'Wildwood',
    'Williamstown',
    'Willingboro',
    'Windsor',
    'Winslow',
    'Wood Ridge',
    'Woodbine',
    'Woodbridge',
    'Woodbury',
    'Woodbury Heights',
    'Woodcliff Lake',
    'Woodstown',
    'Wrightstown',
    'Wyckoff'
]
