cities = [
    'Abercrombie',
    'Absaraka',
    'Adams',
    'Agate',
    'Alamo',
    'Alexander',
    'Almont',
    'Alsen',
    'Ambrose',
    'Amenia',
    'Amidon',
    'Anamoose',
    'Aneta',
    'Antler',
    'Ardoch',
    'Argusville',
    'Arnegard',
    'Arthur',
    'Arvilla',
    'Ashley',
    'Ayr',
    'Baldwin',
    'Balfour',
    'Balta',
    'Bantry',
    'Barney',
    'Bathgate',
    'Beach',
    'Belcourt',
    'Belfield',
    'Benedict',
    'Berlin',
    'Berthold',
    'Beulah',
    'Binford',
    'Bisbee',
    'Bismarck',
    'Blanchard',
    'Bottineau',
    'Bowbells',
    'Bowdon',
    'Bowman',
    'Braddock',
    'Bremen',
    'Brinsmade',
    'Brocket',
    'Buchanan',
    'Buffalo',
    'Burlington',
    'Butte',
    'Buxton',
    'Caledonia',
    'Calvin',
    'Cando',
    'Cannon Ball',
    'Carpio',
    'Carrington',
    'Carson',
    'Cartwright',
    'Casselton',
    'Cathay',
    'Cavalier',
    'Cayuga',
    'Center',
    'Chaffee',
    'Chaseley',
    'Christine',
    'Churchs Ferry',
    'Clay',
    'Cleveland',
    'Clifford',
    'Cogswell',
    'Coleharbor',
    'Colfax',
    'Colquhoun',
    'Columbus',
    'Cooperstown',
    'Courtenay',
    'Crary',
    'Crosby',
    'Crystal',
    'Cummings',
    'Dahlen',
    'Davenport',
    'Dawson',
    'Dazey',
    'Deering',
    'Denhoff',
    'Des Lacs',
    'Devils Lake',
    'Dickey',
    'Dickinson',
    'Dodge',
    'Donnybrook',
    'Douglas',
    'Drake',
    'Drayton',
    'Driscoll',
    'Dunn Center',
    'Dunseith',
    'Eckelson',
    'Edgeley',
    'Edinburg',
    'Edmore',
    'Egeland',
    'Elgin',
    'Ellendale',
    'Emerado',
    'Enderlin',
    'Epping',
    'Erie',
    'Esmond',
    'Fairdale',
    'Fairfield',
    'Fairmount',
    'Fargo',
    'Farmington',
    'Fessenden',
    'Fingal',
    'Finley',
    'Flasher',
    'Flaxton',
    'Forbes',
    'Fordville',
    'Forest River',
    'Forman',
    'Fort Ransom',
    'Fort Totten',
    'Fort Yates',
    'Fortuna',
    'Fredonia',
    'Fullerton',
    'Gackle',
    'Galesburg',
    'Gardner',
    'Garrison',
    'Gilby',
    'Gladstone',
    'Glasston',
    'Glen Ullin',
    'Glenburn',
    'Glenfield',
    'Golden Valley',
    'Golva',
    'Goodrich',
    'Grace City',
    'Grafton',
    'Grand Forks',
    'Grand Forks AFB',
    'Grandfield',
    'Grandin',
    'Granville',
    'Grassy Butte',
    'Great Bend',
    'Grenora',
    'Gwinner',
    'Hague',
    'Halliday',
    'Hamberg',
    'Hamilton',
    'Hampden',
    'Hankinson',
    'Hannaford',
    'Hannah',
    'Hansboro',
    'Harvey',
    'Harwood',
    'Hatton',
    'Havana',
    'Hazelton',
    'Hazen',
    'Hebron',
    'Hensel',
    'Hettinger',
    'Hillsboro',
    'Hoople',
    'Hope',
    'Horace',
    'Hunter',
    'Hurdsfield',
    'Inkster',
    'Jamestown',
    'Jessie',
    'Jud',
    'Karlsruhe',
    'Kathryn',
    'Keene',
    'Kenmare',
    'Kensal',
    'Kief',
    'Killdeer',
    'Kindred',
    'Kintyre',
    'Knox',
    'Kramer',
    'Kulm',
    'Lakota',
    'Lamoure',
    'Langdon',
    'Lankin',
    'Lansford',
    'Larimore',
    'Lawton',
    'Leeds',
    'Lefor',
    'Lehr',
    'Lemmon',
    'Leonard',
    'Lidgerwood',
    'Lignite',
    'Linton',
    'Lisbon',
    'Litchville',
    'Luverne',
    'Maddock',
    'Maida',
    'Makoti',
    'Mandan',
    'Mandaree',
    'Manning',
    'Mantador',
    'Manvel',
    'Mapleton',
    'Marion',
    'Marmarth',
    'Marshall',
    'Martin',
    'Max',
    'Maxbass',
    'Mayville',
    'Mcclusky',
    'Mcgregor',
    'Mchenry',
    'Mckenzie',
    'Mcleod',
    'Mcville',
    'Medina',
    'Medora',
    'Mekinock',
    'Menoken',
    'Mercer',
    'Michigan',
    'Milnor',
    'Milton',
    'Minnewaukan',
    'Minot',
    'Minot AFB',
    'Minto',
    'Moffit',
    'Mohall',
    'Montpelier',
    'Mooreton',
    'Mott',
    'Mountain',
    'Munich',
    'Mylo',
    'Napoleon',
    'Neche',
    'Nekoma',
    'New England',
    'New Leipzig',
    'New Rockford',
    'New Salem',
    'New Town',
    'Newburg',
    'Niagara',
    'Nome',
    'Noonan',
    'Northwood',
    'Norwich',
    'Oakes',
    'Oberon',
    'Orange',
    'Oriska',
    'Orrin',
    'Osnabrock',
    'Page',
    'Palermo',
    'Park River',
    'Parshall',
    'Pekin',
    'Pembina',
    'Penn',
    'Perth',
    'Petersburg',
    'Pettibone',
    'Pillsbury',
    'Pingree',
    'Pisek',
    'Plaza',
    'Poplar Grove',
    'Portal',
    'Portland',
    'Powers Lake',
    'Raleigh',
    'Ray',
    'Reeder',
    'Regan',
    'Regent',
    'Reynolds',
    'Rhame',
    'Richardton',
    'Riverdale',
    'Robinson',
    'Rocklake',
    'Rogers',
    'Rolette',
    'Rolla',
    'Roseglen',
    'Ross',
    'Rugby',
    'Ruso',
    'Rutland',
    'Ryder',
    'Saint Anthony',
    'Saint John',
    'Saint Michael',
    'Saint Thomas',
    'Sanborn',
    'Sarles',
    'Sawyer',
    'Scranton',
    'Selfridge',
    'Sentinel Butte',
    'Sharon',
    'Sheldon',
    'Sherwood',
    'Sheyenne',
    'Shields',
    'Solen',
    'Souris',
    'South Heart',
    'Spiritwood',
    'Stanley',
    'Stanton',
    'Starkweather',
    'Steele',
    'Sterling',
    'Stirum',
    'Strasburg',
    'Streeter',
    'Surrey',
    'Sutton',
    'Sykeston',
    'Tappen',
    'Taylor',
    'Thompson',
    'Tioga',
    'Tokio',
    'Tolley',
    'Tolna',
    'Tower City',
    'Towner',
    'Trenton',
    'Turtle Lake',
    'Tuttle',
    'Underwood',
    'Upham',
    'Valley City',
    'Velva',
    'Venturia',
    'Verona',
    'Voltaire',
    'Wahpeton',
    'Walcott',
    'Wales',
    'Walhalla',
    'Warwick',
    'Washburn',
    'Watford City',
    'Webster',
    'West Fargo',
    'Westby',
    'Westhope',
    'Wheatland',
    'White Earth',
    'Wildrose',
    'Williston',
    'Willow City',
    'Wilton',
    'Wimbledon',
    'Wing',
    'Wishek',
    'Wolford',
    'Woodworth',
    'Wyndmere',
    'York',
    'Ypsilanti',
    'Zahl',
    'Zap',
    'Zeeland'
]
