cities = [
    'Adamsville',
    'Albion',
    'Ashaway',
    'Barrington',
    'Block Island',
    'Bradford',
    'Bristol',
    'Carolina',
    'Central Falls',
    'Charlestown',
    'Chepachet',
    'Clayville',
    'Coventry',
    'Cranston',
    'Cumberland',
    'East Greenwich',
    'East Providence',
    'Exeter',
    'Fiskeville',
    'Forestdale',
    'Foster',
    'Glendale',
    'Greene',
    'Greenville',
    'Harmony',
    'Harrisville',
    'Hope',
    'Hope Valley',
    'Hopkinton',
    'Jamestown',
    'Johnston',
    'Kenyon',
    'Kingston',
    'Lincoln',
    'Little Compton',
    'Manville',
    'Mapleville',
    'Middletown',
    'Narragansett',
    'Newport',
    'North Kingstown',
    'North Providence',
    'North Scituate',
    'North Smithfield',
    'Oakland',
    'Pascoag',
    'Pawtucket',
    'Peace Dale',
    'Portsmouth',
    'Providence',
    'Prudence Island',
    'Riverside',
    'Rockville',
    'Rumford',
    'Saunderstown',
    'Shannock',
    'Slatersville',
    'Slocum',
    'Smithfield',
    'South Kingstown',
    'Tiverton',
    'Wakefield',
    'Warren',
    'Warwick',
    'West Greenwich',
    'West Kingston',
    'West Warwick',
    'Westerly',
    'Wood River Junction',
    'Woonsocket',
    'Wyoming'
]
