cities = [
    'Abbott',
    'Abernathy',
    'Abilene',
    'Ace',
    'Ackerly',
    'Addison',
    'Adkins',
    'Adrian',
    'Afton',
    'Agua Dulce',
    'Aiken',
    'Alamo',
    'Alanreed',
    'Alba',
    'Albany',
    'Aledo',
    'Alice',
    'Alief',
    'Allen',
    'Alleyton',
    'Allison',
    'Alpine',
    'Altair',
    'Alto',
    'Alvarado',
    'Alvin',
    'Alvord',
    'Amarillo',
    'Amherst',
    'Anahuac',
    'Anderson',
    'Andrews',
    'Angleton',
    'Angus',
    'Anna',
    'Annona',
    'Anson',
    'Anthony',
    'Anton',
    'Apple Springs',
    'Aquilla',
    'Aransas Pass',
    'Archer City',
    'Argyle',
    'Arlington',
    'Armstrong',
    'Arp',
    'Art',
    'Artesia Wells',
    'Arthur City',
    'Asherton',
    'Aspermont',
    'Atascosa',
    'Athens',
    'Atlanta',
    'Aubrey',
    'Austin',
    'Austwell',
    'Avalon',
    'Avery',
    'Avinger',
    'Avoca',
    'Axtell',
    'Azle',
    'Bacliff',
    'Bagwell',
    'Bailey',
    'Baird',
    'Ballinger',
    'Balmorhea',
    'Bandera',
    'Bangs',
    'Banquete',
    'Bardwell',
    'Barker',
    'Barksdale',
    'Barnhart',
    'Barry',
    'Barstow',
    'Bartlett',
    'Bastrop',
    'Batesville',
    'Batson',
    'Bay City',
    'Bayside',
    'Baytown',
    'Beasley',
    'Beaumont',
    'Bebe',
    'Beckville',
    'Bedford',
    'Bedias',
    'Beeville',
    'Bellaire',
    'Bellevue',
    'Bells',
    'Bellville',
    'Belmont',
    'Belton',
    'Ben Bolt',
    'Ben Franklin',
    'Ben Wheeler',
    'Benavides',
    'Bend',
    'Benjamin',
    'Berclair',
    'Bergheim',
    'Bertram',
    'Big Bend National Park',
    'Big Lake',
    'Big Sandy',
    'Big Spring',
    'Big Wells',
    'Bigfoot',
    'Bishop',
    'Bivins',
    'Blackwell',
    'Blanco',
    'Blanket',
    'Bledsoe',
    'Bleiblerville',
    'Blessing',
    'Bloomburg',
    'Blooming Grove',
    'Bloomington',
    'Blossom',
    'Blue Ridge',
    'Bluegrove',
    'Bluff Dale',
    'Bluffton',
    'Blum',
    'Boerne',
    'Bogata',
    'Boling',
    'Bon Wier',
    'Bonham',
    'Booker',
    'Borger',
    'Bovina',
    'Bowie',
    'Boyd',
    'Boys Ranch',
    'Brackettville',
    'Brady',
    'Brandon',
    'Brashear',
    'Brazoria',
    'Breckenridge',
    'Bremond',
    'Brenham',
    'Bridge City',
    'Bridgeport',
    'Briggs',
    'Briscoe',
    'Broaddus',
    'Bronson',
    'Bronte',
    'Brookeland',
    'Brookesmith',
    'Brookshire',
    'Brookston',
    'Brownfield',
    'Brownsboro',
    'Brownsville',
    'Brownwood',
    'Bruceville',
    'Bruni',
    'Bryan',
    'Bryson',
    'Buchanan Dam',
    'Buckholts',
    'Buda',
    'Buffalo',
    'Buffalo Gap',
    'Bula',
    'Bullard',
    'Bulverde',
    'Buna',
    'Burkburnett',
    'Burkett',
    'Burkeville',
    'Burleson',
    'Burlington',
    'Burnet',
    'Burton',
    'Bushland',
    'Byers',
    'Bynum',
    'Cactus',
    'Caddo',
    'Caddo Mills',
    'Caldwell',
    'Call',
    'Calliham',
    'Calvert',
    'Camden',
    'Cameron',
    'Camp Wood',
    'Campbell',
    'Campbellton',
    'Canadian',
    'Canton',
    'Canutillo',
    'Canyon',
    'Canyon Lake',
    'Carbon',
    'Carey',
    'Carlsbad',
    'Carlton',
    'Carmine',
    'Carrizo Springs',
    'Carrollton',
    'Carthage',
    'Cason',
    'Castell',
    'Castroville',
    'Cat Spring',
    'Catarina',
    'Cayuga',
    'Cedar Creek',
    'Cedar Hill',
    'Cedar Lane',
    'Cedar Park',
    'Cee Vee',
    'Celeste',
    'Celina',
    'Center',
    'Center Point',
    'Centerville',
    'Centralia',
    'Chalk',
    'Chandler',
    'Channelview',
    'Channing',
    'Chapman Ranch',
    'Chappell Hill',
    'Charlotte',
    'Chatfield',
    'Cherokee',
    'Chester',
    'Chico',
    'Chicota',
    'Childress',
    'Chillicothe',
    'Chilton',
    'China',
    'China Spring',
    'Chireno',
    'Chriesman',
    'Christine',
    'Christoval',
    'Cibolo',
    'Cisco',
    'Clarendon',
    'Clarksville',
    'Claude',
    'Clay',
    'Clayton',
    'Cleburne',
    'Cleveland',
    'Clifton',
    'Clint',
    'Clute',
    'Clyde',
    'Coahoma',
    'Coldspring',
    'Coleman',
    'College Station',
    'Collegeport',
    'Colleyville',
    'Collinsville',
    'Colmesneil',
    'Colorado City',
    'Columbus',
    'Comanche',
    'Combes',
    'Comfort',
    'Commerce',
    'Como',
    'Comstock',
    'Concan',
    'Concepcion',
    'Concord',
    'Conroe',
    'Converse',
    'Cookville',
    'Coolidge',
    'Cooper',
    'Copeville',
    'Coppell',
    'Copperas Cove',
    'Corinth',
    'Corpus Christi',
    'Corrigan',
    'Corsicana',
    'Cost',
    'Cotton Center',
    'Cotulla',
    'Coupland',
    'Covington',
    'Coyanosa',
    'Crandall',
    'Crane',
    'Cranfills Gap',
    'Crawford',
    'Cresson',
    'Crockett',
    'Crosby',
    'Crosbyton',
    'Cross Plains',
    'Crowell',
    'Crowley',
    'Crystal City',
    'Cuero',
    'Cumby',
    'Cuney',
    'Cunningham',
    'Cushing',
    'Cypress',
    'D Hanis',
    'Daingerfield',
    'Daisetta',
    'Dale',
    'Dalhart',
    'Dallardsville',
    'Dallas',
    'Damon',
    'Danbury',
    'Danciger',
    'Danevang',
    'Darrouzett',
    'Davilla',
    'Dawn',
    'Dawson',
    'Dayton',
    'De Berry',
    'De Kalb',
    'De Leon',
    'Deanville',
    'Decatur',
    'Deer Park',
    'Del Rio',
    'Del Valle',
    'Dell City',
    'Delmita',
    'Denison',
    'Dennis',
    'Denton',
    'Denver City',
    'Deport',
    'Desdemona',
    'Desoto',
    'Detroit',
    'Devers',
    'Devine',
    'Deweyville',
    'Diana',
    'Diboll',
    'Dickens',
    'Dickinson',
    'Dike',
    'Dilley',
    'Dime Box',
    'Dimmitt',
    'Dinero',
    'Dobbin',
    'Dodd City',
    'Dodge',
    'Dodson',
    'Donie',
    'Donna',
    'Doole',
    'Doss',
    'Doucette',
    'Dougherty',
    'Douglass',
    'Douglassville',
    'Driftwood',
    'Dripping Springs',
    'Driscoll',
    'Dryden',
    'Dublin',
    'Dumas',
    'Dumont',
    'Duncanville',
    'Dunn',
    'Dyess AFB',
    'Eagle Lake',
    'Eagle Pass',
    'Early',
    'Earth',
    'East Bernard',
    'Eastland',
    'Easton',
    'Ecleto',
    'Ector',
    'Edcouch',
    'Eddy',
    'Eden',
    'Edgewood',
    'Edinburg',
    'Edmonson',
    'Edna',
    'Edroy',
    'Egypt',
    'El Campo',
    'El Indio',
    'El Paso',
    'Eldorado',
    'Electra',
    'Elgin',
    'Elkhart',
    'Ellinger',
    'Elm Mott',
    'Elmaton',
    'Elmendorf',
    'Elmo',
    'Elsa',
    'Elysian Fields',
    'Emory',
    'Encinal',
    'Encino',
    'Energy',
    'Enloe',
    'Ennis',
    'Enochs',
    'Eola',
    'Era',
    'Estelline',
    'Etoile',
    'Euless',
    'Eustace',
    'Evadale',
    'Evant',
    'Fabens',
    'Fairfield',
    'Falcon Heights',
    'Falfurrias',
    'Falls City',
    'Fannin',
    'Farmersville',
    'Farnsworth',
    'Farwell',
    'Fate',
    'Fayetteville',
    'Fentress',
    'Ferris',
    'Fieldton',
    'Fischer',
    'Flat',
    'Flatonia',
    'Flint',
    'Flomot',
    'Florence',
    'Floresville',
    'Flower Mound',
    'Floydada',
    'Fluvanna',
    'Flynn',
    'Follett',
    'Forestburg',
    'Forney',
    'Forreston',
    'Forsan',
    'Fort Davis',
    'Fort Hancock',
    'Fort McKavett',
    'Fort Stockton',
    'Fort Worth',
    'Fowlerton',
    'Francitas',
    'Franklin',
    'Frankston',
    'Fred',
    'Fredericksburg',
    'Fredonia',
    'Freeport',
    'Freer',
    'Fresno',
    'Friendswood',
    'Friona',
    'Frisco',
    'Fritch',
    'Frost',
    'Fruitvale',
    'Fulshear',
    'Fulton',
    'Gail',
    'Gainesville',
    'Galena Park',
    'Gallatin',
    'Galveston',
    'Ganado',
    'Garciasville',
    'Garden City',
    'Gardendale',
    'Garland',
    'Garrison',
    'Garwood',
    'Gary',
    'Gatesville',
    'Gause',
    'Geneva',
    'George West',
    'Georgetown',
    'Geronimo',
    'Giddings',
    'Gilchrist',
    'Gillett',
    'Gilmer',
    'Girard',
    'Girvin',
    'Gladewater',
    'Glen Flora',
    'Glen Rose',
    'Glidden',
    'Gober',
    'Godley',
    'Golden',
    'Goldsboro',
    'Goldsmith',
    'Goldthwaite',
    'Goliad',
    'Gonzales',
    'Goodfellow AFB',
    'Goodrich',
    'Gordon',
    'Gordonville',
    'Goree',
    'Gorman',
    'Gouldbusk',
    'Graford',
    'Graham',
    'Granbury',
    'Grand Prairie',
    'Grand Saline',
    'Grandfalls',
    'Grandview',
    'Granger',
    'Grapeland',
    'Grapevine',
    'Greenville',
    'Greenwood',
    'Gregory',
    'Groesbeck',
    'Groom',
    'Groves',
    'Groveton',
    'Grulla',
    'Gruver',
    'Guerra',
    'Gun Barrel City',
    'Gunter',
    'Gustine',
    'Guthrie',
    'Guy',
    'Hale Center',
    'Hallettsville',
    'Hallsville',
    'Haltom City',
    'Hamilton',
    'Hamlin',
    'Hamshire',
    'Hankamer',
    'Happy',
    'Hardin',
    'Hargill',
    'Harker Heights',
    'Harleton',
    'Harlingen',
    'Harper',
    'Harrold',
    'Hart',
    'Hartley',
    'Harwood',
    'Haskell',
    'Haslet',
    'Hawkins',
    'Hawley',
    'Hearne',
    'Hebbronville',
    'Hedley',
    'Heidenheimer',
    'Helotes',
    'Hemphill',
    'Hempstead',
    'Henderson',
    'Henrietta',
    'Hereford',
    'Hermleigh',
    'Hewitt',
    'Hext',
    'Hico',
    'Hidalgo',
    'Higgins',
    'High Island',
    'Highlands',
    'Hillister',
    'Hillsboro',
    'Hitchcock',
    'Hobson',
    'Hochheim',
    'Hockley',
    'Holland',
    'Holliday',
    'Hondo',
    'Honey Grove',
    'Hooks',
    'Houston',
    'Howe',
    'Hubbard',
    'Huffman',
    'Hufsmith',
    'Hughes Springs',
    'Hull',
    'Humble',
    'Hungerford',
    'Hunt',
    'Huntington',
    'Huntsville',
    'Hurst',
    'Hutchins',
    'Hutto',
    'Hye',
    'Idalou',
    'Imperial',
    'Industry',
    'Inez',
    'Ingleside',
    'Ingram',
    'Iola',
    'Iowa Park',
    'Ira',
    'Iraan',
    'Iredell',
    'Irene',
    'Irving',
    'Italy',
    'Itasca',
    'Ivanhoe',
    'Jacksboro',
    'Jacksonville',
    'Jarrell',
    'Jasper',
    'Jayton',
    'Jefferson',
    'Jermyn',
    'Jewett',
    'Joaquin',
    'Johnson City',
    'Joinerville',
    'Jonesboro',
    'Jonesville',
    'Josephine',
    'Joshua',
    'Jourdanton',
    'Judson',
    'Junction',
    'Justiceburg',
    'Justin',
    'Kamay',
    'Karnack',
    'Karnes City',
    'Katy',
    'Kaufman',
    'Keene',
    'Keller',
    'Kemah',
    'Kemp',
    'Kempner',
    'Kendalia',
    'Kendleton',
    'Kenedy',
    'Kennard',
    'Kennedale',
    'Kenney',
    'Kerens',
    'Kermit',
    'Kerrville',
    'Kildare',
    'Kilgore',
    'Killeen',
    'Kingsbury',
    'Kingsland',
    'Kingsville',
    'Kirbyville',
    'Kirkland',
    'Kirvin',
    'Klondike',
    'Knickerbocker',
    'Knippa',
    'Knott',
    'Knox City',
    'Kopperl',
    'Kosse',
    'Kountze',
    'Kress',
    'Krum',
    'Kurten',
    'Kyle',
    'La Blanca',
    'La Coste',
    'La Feria',
    'La Grange',
    'La Joya',
    'La Marque',
    'La Porte',
    'La Pryor',
    'La Salle',
    'La Vernia',
    'La Victoria',
    'La Villa',
    'La Ward',
    'Ladonia',
    'Laguna Park',
    'Laird Hill',
    'Lake Creek',
    'Lake Dallas',
    'Lake Jackson',
    'Lakeview',
    'Lamesa',
    'Lampasas',
    'Lancaster',
    'Lane City',
    'Laneville',
    'Langtry',
    'Laredo',
    'Larue',
    'Lasara',
    'Latexo',
    'Laughlin A F B',
    'Lavon',
    'Lawn',
    'Lazbuddie',
    'League City',
    'Leakey',
    'Leander',
    'Ledbetter',
    'Leesburg',
    'Leesville',
    'Lefors',
    'Leggett',
    'Lelia Lake',
    'Leming',
    'Lenorah',
    'Leon Junction',
    'Leona',
    'Leonard',
    'Leroy',
    'Levelland',
    'Lewisville',
    'Lexington',
    'Liberty',
    'Liberty Hill',
    'Lillian',
    'Lincoln',
    'Lindale',
    'Linden',
    'Lindsay',
    'Lingleville',
    'Linn',
    'Lipan',
    'Lipscomb',
    'Lissie',
    'Little Elm',
    'Little River',
    'Littlefield',
    'Liverpool',
    'Livingston',
    'Llano',
    'Lockhart',
    'Lockney',
    'Lodi',
    'Lohn',
    'Lolita',
    'Lometa',
    'London',
    'Lone Oak',
    'Lone Star',
    'Long Branch',
    'Long Mott',
    'Longview',
    'Loop',
    'Lopeno',
    'Loraine',
    'Lorena',
    'Lorenzo',
    'Los Ebanos',
    'Los Fresnos',
    'Los Indios',
    'Lott',
    'Louise',
    'Lovelady',
    'Loving',
    'Lowake',
    'Lozano',
    'Lubbock',
    'Lueders',
    'Lufkin',
    'Luling',
    'Lumberton',
    'Lyford',
    'Lyons',
    'Lytle',
    'Mabank',
    'Macdona',
    'Madisonville',
    'Magnolia',
    'Malakoff',
    'Malone',
    'Manchaca',
    'Manor',
    'Mansfield',
    'Manvel',
    'Maple',
    'Marathon',
    'Marble Falls',
    'Marfa',
    'Marietta',
    'Marion',
    'Markham',
    'Marlin',
    'Marquez',
    'Marshall',
    'Mart',
    'Martindale',
    'Martinsville',
    'Maryneal',
    'Mason',
    'Masterson',
    'Matador',
    'Matagorda',
    'Mathis',
    'Maud',
    'Mauriceville',
    'Maxwell',
    'May',
    'Maydelle',
    'Maypearl',
    'Maysfield',
    'Mcadoo',
    'McAllen',
    'McCamey',
    'McCaulley',
    'McCoy',
    'McDade',
    'Mcfaddin',
    'McGregor',
    'McKinney',
    'Mclean',
    'McLeod',
    'McNeil',
    'McQueeney',
    'Meadow',
    'Medina',
    'Megargel',
    'Melissa',
    'Melvin',
    'Memphis',
    'Menard',
    'Mentone',
    'Mercedes',
    'Mereta',
    'Meridian',
    'Merit',
    'Merkel',
    'Mertens',
    'Mertzon',
    'Mesquite',
    'Mexia',
    'Meyersville',
    'Miami',
    'Mico',
    'Midfield',
    'Midkiff',
    'Midland',
    'Midlothian',
    'Midway',
    'Milam',
    'Milano',
    'Miles',
    'Milford',
    'Millersview',
    'Millican',
    'Millsap',
    'Minden',
    'Mineola',
    'Mineral',
    'Mineral Wells',
    'Mingus',
    'Mirando City',
    'Mission',
    'Missouri City',
    'Mobeetie',
    'Monahans',
    'Mont Belvieu',
    'Montague',
    'Montalba',
    'Montgomery',
    'Moody',
    'Moore',
    'Moran',
    'Morgan',
    'Morgan Mill',
    'Morse',
    'Morton',
    'Moscow',
    'Moulton',
    'Mound',
    'Mount Calm',
    'Mount Enterprise',
    'Mount Pleasant',
    'Mount Vernon',
    'Mountain Home',
    'Muenster',
    'Muldoon',
    'Muleshoe',
    'Mullin',
    'Mumford',
    'Munday',
    'Murchison',
    'Myra',
    'Nacogdoches',
    'Nada',
    'Naples',
    'Nash',
    'Natalia',
    'Naval Air Station/ Jrb',
    'Navasota',
    'Nazareth',
    'Neches',
    'Nederland',
    'Needville',
    'Nemo',
    'Nevada',
    'New Baden',
    'New Boston',
    'New Braunfels',
    'New Caney',
    'New Deal',
    'New Home',
    'New London',
    'New Summerfield',
    'New Ulm',
    'New Waverly',
    'Newark',
    'Newcastle',
    'Newgulf',
    'Newton',
    'Nixon',
    'Nocona',
    'Nolan',
    'Nolanville',
    'Nome',
    'Nordheim',
    'Normangee',
    'Normanna',
    'North Houston',
    'North Richland Hills',
    'North Zulch',
    'Norton',
    'Notrees',
    'Novice',
    'Nursery',
    'O Brien',
    'Oakhurst',
    'Oakland',
    'Oakville',
    'Oakwood',
    'Odell',
    'Odem',
    'Odessa',
    'Odonnell',
    'Oglesby',
    'Oilton',
    'Oklaunion',
    'Old Glory',
    'Old Ocean',
    'Olden',
    'Olmito',
    'Olney',
    'Olton',
    'Omaha',
    'Onalaska',
    'Orange',
    'Orange Grove',
    'Orangefield',
    'Orchard',
    'Ore City',
    'Orla',
    'Ottine',
    'Otto',
    'Ovalo',
    'Overton',
    'Ozona',
    'Paducah',
    'Paige',
    'Paint Rock',
    'Palacios',
    'Palestine',
    'Palmer',
    'Palo Pinto',
    'Paluxy',
    'Pampa',
    'Pandora',
    'Panhandle',
    'Panna Maria',
    'Panola',
    'Paradise',
    'Paris',
    'Pasadena',
    'Pattison',
    'Pattonville',
    'Pawnee',
    'Pear Valley',
    'Pearland',
    'Pearsall',
    'Peaster',
    'Pecan Gap',
    'Pecos',
    'Peggy',
    'Pendleton',
    'Penelope',
    'Penitas',
    'Pennington',
    'Penwell',
    'Pep',
    'Perrin',
    'Perry',
    'Perryton',
    'Petersburg',
    'Petrolia',
    'Pettus',
    'Petty',
    'Pflugerville',
    'Pharr',
    'Pickton',
    'Pierce',
    'Pilot Point',
    'Pinehurst',
    'Pineland',
    'Pipe Creek',
    'Pittsburg',
    'Placedo',
    'Plains',
    'Plainview',
    'Plano',
    'Plantersville',
    'Pleasanton',
    'Pledger',
    'Plum',
    'Point',
    'Point Comfort',
    'Pointblank',
    'Pollok',
    'Ponder',
    'Pontotoc',
    'Poolville',
    'Port Aransas',
    'Port Arthur',
    'Port Bolivar',
    'Port Isabel',
    'Port Lavaca',
    'Port Mansfield',
    'Port Neches',
    'Port O Connor',
    'Porter',
    'Portland',
    'Post',
    'Poteet',
    'Poth',
    'Pottsboro',
    'Pottsville',
    'Powderly',
    'Powell',
    'Poynor',
    'Prairie Hill',
    'Prairie Lea',
    'Prairie View',
    'Premont',
    'Presidio',
    'Price',
    'Priddy',
    'Princeton',
    'Proctor',
    'Progreso',
    'Prosper',
    'Purdon',
    'Purmela',
    'Putnam',
    'Pyote',
    'Quail',
    'Quanah',
    'Queen City',
    'Quemado',
    'Quinlan',
    'Quitaque',
    'Quitman',
    'Rainbow',
    'Ralls',
    'Rancho Alegre',
    'Randolph',
    'Ranger',
    'Rankin',
    'Ransom Canyon',
    'Ratcliff',
    'Ravenna',
    'Raymondville',
    'Raywood',
    'Reagan',
    'Realitos',
    'Red Oak',
    'Red Rock',
    'Redford',
    'Redwater',
    'Refugio',
    'Reklaw',
    'Rhome',
    'Rice',
    'Richards',
    'Richardson',
    'Richland',
    'Richland Springs',
    'Richmond',
    'Riesel',
    'Ringgold',
    'Rio Frio',
    'Rio Grande City',
    'Rio Hondo',
    'Rio Medina',
    'Rio Vista',
    'Rising Star',
    'Riverside',
    'Riviera',
    'Roanoke',
    'Roans Prairie',
    'Roaring Springs',
    'Robert Lee',
    'Robstown',
    'Roby',
    'Rochelle',
    'Rochester',
    'Rock Island',
    'Rockdale',
    'Rockport',
    'Rocksprings',
    'Rockwall',
    'Rockwood',
    'Rogers',
    'Roma',
    'Romayor',
    'Roosevelt',
    'Ropesville',
    'Rosanky',
    'Roscoe',
    'Rosebud',
    'Rosenberg',
    'Rosharon',
    'Ross',
    'Rosser',
    'Rosston',
    'Rotan',
    'Round Mountain',
    'Round Rock',
    'Round Top',
    'Rowena',
    'Rowlett',
    'Roxton',
    'Royalty',
    'Royse City',
    'Rule',
    'Runge',
    'Rusk',
    'Rye',
    'Sabinal',
    'Sabine Pass',
    'Sacul',
    'Sadler',
    'Saint Hedwig',
    'Saint Jo',
    'Salado',
    'Salineno',
    'Salt Flat',
    'Saltillo',
    'Samnorwood',
    'San Angelo',
    'San Antonio',
    'San Augustine',
    'San Benito',
    'San Diego',
    'San Elizario',
    'San Felipe',
    'San Isidro',
    'San Juan',
    'San Leon',
    'San Marcos',
    'San Perlita',
    'San Saba',
    'San Ygnacio',
    'Sanderson',
    'Sandia',
    'Sandy',
    'Sanford',
    'Sanger',
    'Santa Anna',
    'Santa Elena',
    'Santa Fe',
    'Santa Maria',
    'Santa Rosa',
    'Santo',
    'Saragosa',
    'Saratoga',
    'Sarita',
    'Satin',
    'Savoy',
    'Schertz',
    'Schulenburg',
    'Schwertner',
    'Scotland',
    'Scottsville',
    'Scroggins',
    'Scurry',
    'Seabrook',
    'Seadrift',
    'Seagoville',
    'Seagraves',
    'Sealy',
    'Sebastian',
    'Seguin',
    'Selman City',
    'Seminole',
    'Seymour',
    'Shafter',
    'Shallowater',
    'Shamrock',
    'Sheffield',
    'Shelbyville',
    'Shepherd',
    'Sheppard AFB',
    'Sheridan',
    'Sherman',
    'Shiner',
    'Shiro',
    'Sidney',
    'Sienna Plantation',
    'Sierra Blanca',
    'Silsbee',
    'Silver',
    'Silverton',
    'Simms',
    'Simonton',
    'Sinton',
    'Skellytown',
    'Skidmore',
    'Slaton',
    'Slidell',
    'Smiley',
    'Smithville',
    'Smyer',
    'Snook',
    'Snyder',
    'Somerset',
    'Somerville',
    'Sonora',
    'Sour Lake',
    'South Bend',
    'South Houston',
    'South Padre Island',
    'South Plains',
    'Southlake',
    'Southmayd',
    'Spade',
    'Speaks',
    'Spearman',
    'Spicewood',
    'Splendora',
    'Spring',
    'Spring Branch',
    'Springlake',
    'Springtown',
    'Spur',
    'Spurger',
    'Stafford',
    'Stamford',
    'Stanton',
    'Staples',
    'Star',
    'Stephenville',
    'Sterling City',
    'Stinnett',
    'Stockdale',
    'Stonewall',
    'Stowell',
    'Stratford',
    'Strawn',
    'Streetman',
    'Sublime',
    'Sudan',
    'Sugar Land',
    'Sullivan City',
    'Sulphur Bluff',
    'Sulphur Springs',
    'Summerfield',
    'Sumner',
    'Sundown',
    'Sunnyvale',
    'Sunray',
    'Sunset',
    'Sutherland Springs',
    'Sweeny',
    'Sweet Home',
    'Sweetwater',
    'Sylvester',
    'Taft',
    'Tahoka',
    'Talco',
    'Talpa',
    'Tarpley',
    'Tarzan',
    'Tatum',
    'Taylor',
    'Teague',
    'Tehuacana',
    'Telegraph',
    'Telephone',
    'Telferner',
    'Tell',
    'Temple',
    'Tenaha',
    'Tennessee Colony',
    'Tennyson',
    'Terlingua',
    'Terrell',
    'Texarkana',
    'Texas City',
    'Texline',
    'The Colony',
    'Thicket',
    'Thomaston',
    'Thompsons',
    'Thorndale',
    'Thornton',
    'Thrall',
    'Three Rivers',
    'Throckmorton',
    'Tilden',
    'Timpson',
    'Tioga',
    'Tivoli',
    'Tokio',
    'Tolar',
    'Tom Bean',
    'Tomball',
    'Tornillo',
    'Tow',
    'Toyah',
    'Toyahvale',
    'Trent',
    'Trenton',
    'Trinidad',
    'Trinity',
    'Troup',
    'Troy',
    'Tuleta',
    'Tulia',
    'Turkey',
    'Tuscola',
    'Tye',
    'Tyler',
    'Tynan',
    'Umbarger',
    'Universal City',
    'Utopia',
    'Uvalde',
    'Valentine',
    'Valera',
    'Valley Mills',
    'Valley Spring',
    'Valley View',
    'Van',
    'Van Alstyne',
    'Van Horn',
    'Van Vleck',
    'Vancourt',
    'Vanderbilt',
    'Vanderpool',
    'Vega',
    'Venus',
    'Veribest',
    'Vernon',
    'Victoria',
    'Vidor',
    'Village Mills',
    'Voca',
    'Von Ormy',
    'Voss',
    'Votaw',
    'Voth',
    'Waco',
    'Wadsworth',
    'Waelder',
    'Waka',
    'Walburg',
    'Wall',
    'Waller',
    'Wallis',
    'Wallisville',
    'Walnut Springs',
    'Warda',
    'Waring',
    'Warren',
    'Washington',
    'Waskom',
    'Water Valley',
    'Waxahachie',
    'Wayside',
    'Weatherford',
    'Webster',
    'Weesatche',
    'Weimar',
    'Weinert',
    'Weir',
    'Welch',
    'Wellborn',
    'Wellington',
    'Wellman',
    'Wells',
    'Weslaco',
    'West',
    'West Columbia',
    'West Point',
    'Westbrook',
    'Westhoff',
    'Westminster',
    'Weston',
    'Wharton',
    'Wheeler',
    'Wheelock',
    'White Deer',
    'White Oak',
    'Whiteface',
    'Whitehouse',
    'Whitesboro',
    'Whitewright',
    'Whitharral',
    'Whitney',
    'Whitsett',
    'Whitt',
    'Wichita Falls',
    'Wickett',
    'Wiergate',
    'Wildorado',
    'Willis',
    'Willow City',
    'Wills Point',
    'Wilmer',
    'Wilson',
    'Wimberley',
    'Windom',
    'Windthorst',
    'Winfield',
    'Wingate',
    'Wink',
    'Winnie',
    'Winnsboro',
    'Winona',
    'Winters',
    'Woden',
    'Wolfe City',
    'Wolfforth',
    'Woodlake',
    'Woodlawn',
    'Woodsboro',
    'Woodson',
    'Woodville',
    'Woodway',
    'Wortham',
    'Wrightsboro',
    'Wylie',
    'Yancey',
    'Yantis',
    'Yoakum',
    'Yorktown',
    'Zapata',
    'Zavalla',
    'Zephyr'
]
