cities = [
    'Abingdon',
    'Accomac',
    'Achilles',
    'Afton',
    'Alberta',
    'Aldie',
    'Alexandria',
    'Altavista',
    'Alton',
    'Amelia Court House',
    'Amherst',
    'Amissville',
    'Ammon',
    'Amonate',
    'Andover',
    'Annandale',
    'Appalachia',
    'Appomattox',
    'Ararat',
    'Arcola',
    'Ark',
    'Arlington',
    'Aroda',
    'Arrington',
    'Arvonia',
    'Ashburn',
    'Ashland',
    'Assawoman',
    'Atkins',
    'Atlantic',
    'Augusta Springs',
    'Austinville',
    'Axton',
    'Aylett',
    'Bacova',
    'Banco',
    'Bandy',
    'Barboursville',
    'Barhamsville',
    'Barren Springs',
    'Baskerville',
    'Bassett',
    'Bastian',
    'Basye',
    'Batesville',
    'Battery Park',
    'Bealeton',
    'Beaumont',
    'Beaverdam',
    'Bedford',
    'Bee',
    'Bellamy',
    'Belle Haven',
    'Belspring',
    'Ben Hur',
    'Bena',
    'Bent Mountain',
    'Bentonville',
    'Bergton',
    'Berryville',
    'Big Island',
    'Big Rock',
    'Big Stone Gap',
    'Birchleaf',
    'Birdsnest',
    'Bishop',
    'Blacksburg',
    'Blackstone',
    'Blackwater',
    'Blairs',
    'Bland',
    'Bloxom',
    'Blue Grass',
    'Blue Ridge',
    'Bluefield',
    'Bluemont',
    'Bohannon',
    'Boissevain',
    'Boones Mill',
    'Boston',
    'Bowling Green',
    'Boyce',
    'Boydton',
    'Boykins',
    'Bracey',
    'Branchville',
    'Brandy Station',
    'Breaks',
    'Bremo Bluff',
    'Bridgewater',
    'Brightwood',
    'Bristol',
    'Bristow',
    'Broad Run',
    'Broadford',
    'Broadway',
    'Brodnax',
    'Brooke',
    'Brookneal',
    'Brownsburg',
    'Brucetown',
    'Bruington',
    'Buchanan',
    'Buckingham',
    'Buena Vista',
    'Buffalo Junction',
    'Bumpass',
    'Burgess',
    'Burke',
    'Burkes Garden',
    'Burkeville',
    'Burr Hill',
    'Callands',
    'Callao',
    'Callaway',
    'Calverton',
    'Cana',
    'Cape Charles',
    'Capeville',
    'Capron',
    'Cardinal',
    'Caret',
    'Carrollton',
    'Carrsville',
    'Carson',
    'Cartersville',
    'Casanova',
    'Cascade',
    'Castleton',
    'Castlewood',
    'Catawba',
    'Catharpin',
    'Catlett',
    'Cedar Bluff',
    'Center Cross',
    'Centreville',
    'Ceres',
    'Champlain',
    'Chantilly',
    'Charles City',
    'Charlotte Court House',
    'Charlottesville',
    'Chase City',
    'Chatham',
    'Check',
    'Cheriton',
    'Chesapeake',
    'Chester',
    'Chester Gap',
    'Chesterfield',
    'Chilhowie',
    'Chincoteague Island',
    'Christchurch',
    'Christiansburg',
    'Church Road',
    'Church View',
    'Churchville',
    'Claremont',
    'Clarksville',
    'Claudville',
    'Clear Brook',
    'Cleveland',
    'Clifford',
    'Clifton',
    'Clifton Forge',
    'Clinchco',
    'Clintwood',
    'Clover',
    'Cloverdale',
    'Cluster Springs',
    'Cobbs Creek',
    'Coeburn',
    'Coleman Falls',
    'Coles Point',
    'Collinsville',
    'Colonial Beach',
    'Colonial Heights',
    'Columbia',
    'Concord',
    'Copper Hill',
    'Corbin',
    'Courtland',
    'Covesville',
    'Covington',
    'Craddockville',
    'Craigsville',
    'Crewe',
    'Criders',
    'Crimora',
    'Cripple Creek',
    'Critz',
    'Crockett',
    'Cross Junction',
    'Crozet',
    'Crozier',
    'Crystal Hill',
    'Cullen',
    'Culpeper',
    'Cumberland',
    'Dahlgren',
    'Daleville',
    'Damascus',
    'Dante',
    'Danville',
    'Davenport',
    'Davis Wharf',
    'Dayton',
    'Deerfield',
    'Delaplane',
    'Deltaville',
    'Dendron',
    'Dewitt',
    'Diggs',
    'Dillwyn',
    'Dinwiddie',
    'Disputanta',
    'Doe Hill',
    'Dogue',
    'Dolphin',
    'Doran',
    'Doswell',
    'Drakes Branch',
    'Draper',
    'Drewryville',
    'Dry Fork',
    'Dryden',
    'Dublin',
    'Duffield',
    'Dugspur',
    'Dulles',
    'Dumfries',
    'Dundas',
    'Dungannon',
    'Dunn Loring',
    'Dunnsville',
    'Dutton',
    'Dyke',
    'Eagle Rock',
    'Earlysville',
    'East Stone Gap',
    'Eastville',
    'Ebony',
    'Edinburg',
    'Edwardsville',
    'Eggleston',
    'Elberon',
    'Elk Creek',
    'Elkton',
    'Elkwood',
    'Elliston',
    'Emory',
    'Emporia',
    'Esmont',
    'Etlan',
    'Evergreen',
    'Evington',
    'Ewing',
    'Exmore',
    'Faber',
    'Fairfax',
    'Fairfax Station',
    'Fairfield',
    'Falls Church',
    'Falls Mills',
    'Fancy Gap',
    'Farmville',
    'Farnham',
    'Ferrum',
    'Fieldale',
    'Fife',
    'Fincastle',
    'Fishers Hill',
    'Fishersville',
    'Flint Hill',
    'Floyd',
    'Ford',
    'Forest',
    'Fork Union',
    'Fort Belvoir',
    'Fort Blackmore',
    'Fort Defiance',
    'Fort Eustis',
    'Fort Lee',
    'Fort Mitchell',
    'Fort Monroe',
    'Fort Valley',
    'Foster',
    'Franklin',
    'Franktown',
    'Fredericksburg',
    'Free Union',
    'Freeman',
    'Fries',
    'Front Royal',
    'Ft Myer',
    'Fulks Run',
    'Gainesville',
    'Galax',
    'Garrisonville',
    'Gasburg',
    'Gate City',
    'Glade Hill',
    'Glade Spring',
    'Gladstone',
    'Gladys',
    'Glasgow',
    'Glen Allen',
    'Glen Lyn',
    'Glen Wilton',
    'Gloucester',
    'Gloucester Point',
    'Goldbond',
    'Goldvein',
    'Goochland',
    'Goode',
    'Goodview',
    'Gordonsville',
    'Gore',
    'Goshen',
    'Graves Mill',
    'Great Falls',
    'Green Bay',
    'Greenbackville',
    'Greenbush',
    'Greenville',
    'Greenway',
    'Greenwood',
    'Gretna',
    'Grimstead',
    'Grottoes',
    'Grundy',
    'Gum Spring',
    'Gwynn',
    'Hacksneck',
    'Hadensville',
    'Hague',
    'Halifax',
    'Hallieford',
    'Hallwood',
    'Hamilton',
    'Hampden Sydney',
    'Hampton',
    'Hanover',
    'Harborton',
    'Hardy',
    'Hardyville',
    'Harman',
    'Harrisonburg',
    'Hartfield',
    'Hartwood',
    'Hayes',
    'Haymarket',
    'Haynesville',
    'Haysi',
    'Haywood',
    'Head Waters',
    'Heathsville',
    'Henry',
    'Herndon',
    'Highland Springs',
    'Hillsville',
    'Hiltons',
    'Hinton',
    'Hiwassee',
    'Honaker',
    'Hood',
    'Hopewell',
    'Horntown',
    'Horsepen',
    'Hot Springs',
    'Howardsville',
    'Huddleston',
    'Hudgins',
    'Hume',
    'Huntly',
    'Hurley',
    'Hurt',
    'Hustle',
    'Independence',
    'Indian Valley',
    'Iron Gate',
    'Irvington',
    'Isle Of Wight',
    'Ivanhoe',
    'Ivor',
    'Ivy',
    'Jamaica',
    'Jamestown',
    'Jamesville',
    'Jarratt',
    'Java',
    'Jeffersonton',
    'Jenkins Bridge',
    'Jersey',
    'Jetersville',
    'Jewell Ridge',
    'Jonesville',
    'Keeling',
    'Keen Mountain',
    'Keene',
    'Keezletown',
    'Keller',
    'Kenbridge',
    'Kents Store',
    'Keokee',
    'Keswick',
    'Keysville',
    'Kilmarnock',
    'King And Queen Court Hous',
    'King George',
    'King William',
    'Kinsale',
    'La Crosse',
    'Lacey Spring',
    'Lackey',
    'Ladysmith',
    'Lambsburg',
    'Lancaster',
    'Laneview',
    'Lanexa',
    'Laurel Fork',
    'Lawrenceville',
    'Lebanon',
    'Leesburg',
    'Leon',
    'Lexington',
    'Lightfoot',
    'Lignum',
    'Lincoln',
    'Linden',
    'Linville',
    'Little Plymouth',
    'Lively',
    'Locust Dale',
    'Locust Grove',
    'Locust Hill',
    'Locustville',
    'Long Island',
    'Loretto',
    'Lorton',
    'Lottsburg',
    'Louisa',
    'Lovettsville',
    'Lovingston',
    'Low Moor',
    'Lowry',
    'Lunenburg',
    'Luray',
    'Lynch Station',
    'Lynchburg',
    'Lyndhurst',
    'Machipongo',
    'Macon',
    'Madison',
    'Madison Heights',
    'Madison Mills',
    'Maidens',
    'Manakin Sabot',
    'Manassas',
    'Mannboro',
    'Manquin',
    'Mappsville',
    'Marion',
    'Marionville',
    'Markham',
    'Marshall',
    'Martinsville',
    'Maryus',
    'Mascot',
    'Massies Mill',
    'Mathews',
    'Mattaponi',
    'Maurertown',
    'Mavisdale',
    'Max Meadows',
    'Maxie',
    'McClure',
    'McCoy',
    'McDowell',
    'McGaheysville',
    'McKenney',
    'McLean',
    'Meadows Of Dan',
    'Meadowview',
    'Mears',
    'Mechanicsville',
    'Meherrin',
    'Melfa',
    'Mendota',
    'Meredithville',
    'Merrifield',
    'Merry Point',
    'Middlebrook',
    'Middleburg',
    'Middletown',
    'Midland',
    'Midlothian',
    'Milford',
    'Millboro',
    'Millers Tavern',
    'Millwood',
    'Mineral',
    'Mint Spring',
    'Mitchells',
    'Modest Town',
    'Mollusk',
    'Moneta',
    'Monroe',
    'Montebello',
    'Monterey',
    'Montpelier',
    'Montpelier Station',
    'Montross',
    'Montvale',
    'Moon',
    'Morattico',
    'Moseley',
    'Mount Crawford',
    'Mount Holly',
    'Mount Jackson',
    'Mount Sidney',
    'Mount Solon',
    'Mount Vernon',
    'Mouth Of Wilson',
    'Mustoe',
    'Narrows',
    'Naruna',
    'Nassawadox',
    'Nathalie',
    'Natural Bridge',
    'Natural Bridge Station',
    'Nellysford',
    'Nelson',
    'Nelsonia',
    'New Canton',
    'New Castle',
    'New Church',
    'New Hope',
    'New Kent',
    'New Market',
    'New Point',
    'New River',
    'Newbern',
    'Newington',
    'Newport',
    'Newport News',
    'Newsoms',
    'Newtown',
    'Nickelsville',
    'Ninde',
    'Nokesville',
    'Nora',
    'Norfolk',
    'Norge',
    'North',
    'North Garden',
    'North Tazewell',
    'Norton',
    'Norwood',
    'Nottoway',
    'Nuttsville',
    'Oak Hall',
    'Oakpark',
    'Oakton',
    'Oakwood',
    'Occoquan',
    'Oilville',
    'Oldhams',
    'Onancock',
    'Onemo',
    'Onley',
    'Ophelia',
    'Orange',
    'Ordinary',
    'Oriskany',
    'Orkney Springs',
    'Orlean',
    'Oyster',
    'Paeonian Springs',
    'Paint Bank',
    'Painter',
    'Palmyra',
    'Pamplin',
    'Paris',
    'Parksley',
    'Parrott',
    'Partlow',
    'Patrick Springs',
    'Pearisburg',
    'Pembroke',
    'Penhook',
    'Penn Laird',
    'Pennington Gap',
    'Petersburg',
    'Phenix',
    'Philomont',
    'Pilgrims Knob',
    'Pilot',
    'Piney River',
    'Pittsville',
    'Pleasant Valley',
    'Pocahontas',
    'Poquoson',
    'Port Haywood',
    'Port Republic',
    'Port Royal',
    'Portsmouth',
    'Pound',
    'Pounding Mill',
    'Powhatan',
    'Pratts',
    'Prince George',
    'Prospect',
    'Providence Forge',
    'Pulaski',
    'Pungoteague',
    'Purcellville',
    'Quantico',
    'Quicksburg',
    'Quinby',
    'Quinque',
    'Quinton',
    'Radford',
    'Radiant',
    'Randolph',
    'Raphine',
    'Rapidan',
    'Rappahannock Academy',
    'Raven',
    'Rawlings',
    'Rectortown',
    'Red Ash',
    'Red House',
    'Red Oak',
    'Redwood',
    'Reedville',
    'Remington',
    'Republican Grove',
    'Rescue',
    'Reston',
    'Reva',
    'Rhoadesville',
    'Rice',
    'Rich Creek',
    'Richardsville',
    'Richlands',
    'Richmond',
    'Ridgeway',
    'Rileyville',
    'Riner',
    'Ringgold',
    'Ripplemead',
    'Rixeyville',
    'Roanoke',
    'Rochelle',
    'Rockbridge Baths',
    'Rockville',
    'Rocky Gap',
    'Rocky Mount',
    'Rollins Fork',
    'Rose Hill',
    'Rosedale',
    'Roseland',
    'Round Hill',
    'Rowe',
    'Ruby',
    'Ruckersville',
    'Rural Retreat',
    'Rustburg',
    'Ruther Glen',
    'Ruthville',
    'Saint Charles',
    'Saint Paul',
    'Saint Stephens Church',
    'Salem',
    'Saltville',
    'Saluda',
    'Sandston',
    'Sandy Hook',
    'Sandy Level',
    'Sandy Point',
    'Sanford',
    'Saxe',
    'Saxis',
    'Schley',
    'Schuyler',
    'Scottsburg',
    'Scottsville',
    'Seaford',
    'Sealston',
    'Seaview',
    'Sedley',
    'Selma',
    'Seven Mile Ford',
    'Severn',
    'Shacklefords',
    'Sharps',
    'Shawsville',
    'Shenandoah',
    'Shipman',
    'Shortt Gap',
    'Singers Glen',
    'Skippers',
    'Skipwith',
    'Smithfield',
    'Somerset',
    'Somerville',
    'South Boston',
    'South Hill',
    'Sparta',
    'Speedwell',
    'Spencer',
    'Sperryville',
    'Spotsylvania',
    'Spottswood',
    'Spout Spring',
    'Spring Grove',
    'Springfield',
    'Stafford',
    'Staffordsville',
    'Stanardsville',
    'Stanley',
    'Stanleytown',
    'Star Tannery',
    'State Farm',
    'Staunton',
    'Steeles Tavern',
    'Stephens City',
    'Stephenson',
    'Sterling',
    'Stevensburg',
    'Stevensville',
    'Stonega',
    'Stony Creek',
    'Strasburg',
    'Stratford',
    'Stuart',
    'Stuarts Draft',
    'Studley',
    'Suffolk',
    'Sugar Grove',
    'Sumerduck',
    'Surry',
    'Susan',
    'Sussex',
    'Sutherland',
    'Sutherlin',
    'Sweet Briar',
    'Swoope',
    'Swords Creek',
    'Syria',
    'Tangier',
    'Tannersville',
    'Tappahannock',
    'Tasley',
    'Tazewell',
    'Temperanceville',
    'Thaxton',
    'The Plains',
    'Thornburg',
    'Timberville',
    'Toano',
    'Toms Brook',
    'Topping',
    'Townsend',
    'Trammel',
    'Trevilians',
    'Triangle',
    'Trout Dale',
    'Troutville',
    'Troy',
    'Tyro',
    'Union Hall',
    'Unionville',
    'University Of Richmond',
    'Upperville',
    'Urbanna',
    'Valentines',
    'Vansant',
    'Vernon Hill',
    'Verona',
    'Vesta',
    'Vesuvius',
    'Victoria',
    'Vienna',
    'Viewtown',
    'Village',
    'Villamont',
    'Vinton',
    'Virgilina',
    'Virginia Beach',
    'Volney',
    'Wachapreague',
    'Wake',
    'Wakefield',
    'Walkerton',
    'Wallops Island',
    'Wardtown',
    'Ware Neck',
    'Warfield',
    'Warm Springs',
    'Warrenton',
    'Warsaw',
    'Washington',
    'Water View',
    'Waterford',
    'Wattsville',
    'Waverly',
    'Waynesboro',
    'Weber City',
    'Weems',
    'West Augusta',
    'West Mclean',
    'West Point',
    'Weyers Cave',
    'White Hall',
    'White Marsh',
    'White Plains',
    'White Post',
    'White Stone',
    'Whitetop',
    'Whitewood',
    'Wicomico',
    'Wicomico Church',
    'Williamsburg',
    'Williamsville',
    'Willis',
    'Willis Wharf',
    'Wilsons',
    'Winchester',
    'Windsor',
    'Wingina',
    'Wirtz',
    'Wise',
    'Withams',
    'Wolford',
    'Wolftown',
    'Woodberry Forest',
    'Woodbridge',
    'Woodford',
    'Woodlawn',
    'Woods Cross Roads',
    'Woodstock',
    'Woodville',
    'Woolwine',
    'Wylliesburg',
    'Wytheville',
    'Yale',
    'Yorktown',
    'Zacata',
    'Zanoni',
    'Zuni'
]
