cities = [
    'Accoville',
    'Adrian',
    'Advent',
    'Albright',
    'Alderson',
    'Alkol',
    'Allen Junction',
    'Alloy',
    'Alma',
    'Alum Bridge',
    'Alum Creek',
    'Ameagle',
    'Amherstdale',
    'Amherstdale-Robinette',
    'Amigo',
    'Amma',
    'Anawalt',
    'Anmoore',
    'Ansted',
    'Apple Grove',
    'Arbovale',
    'Arnett',
    'Arnoldsburg',
    'Arthurdale',
    'Artie',
    'Asbury',
    'Ashford',
    'Ashton',
    'Athens',
    'Auburn',
    'Augusta',
    'Aurora',
    'Auto',
    'Avondale',
    'Baisden',
    'Baker',
    'Bakerton',
    'Bald Knob',
    'Ballard',
    'Ballengee',
    'Bancroft',
    'Barboursville',
    'Barrackville',
    'Bartley',
    'Bartow',
    'Baxter',
    'Bayard',
    'Beaver',
    'Beckley',
    'Beech Bottom',
    'Beeson',
    'Belington',
    'Belle',
    'Belleville',
    'Belmont',
    'Belva',
    'Bens Run',
    'Bentree',
    'Benwood',
    'Berea',
    'Bergoo',
    'Berkeley Springs',
    'Berwind',
    'Bethany',
    'Beverly',
    'Bickmore',
    'Big Bend',
    'Big Creek',
    'Big Run',
    'Big Sandy',
    'Big Springs',
    'Bim',
    'Birch River',
    'Blacksville',
    'Blair',
    'Blandville',
    'Bloomery',
    'Bloomingrose',
    'Blount',
    'Blue Creek',
    'Blue Jay',
    'Bluefield',
    'Bob White',
    'Bolt',
    'Bomont',
    'Boomer',
    'Booth',
    'Borderland',
    'Bowden',
    'Bradley',
    'Bradshaw',
    'Bramwell',
    'Branchland',
    'Brandywine',
    'Breeden',
    'Brenton',
    'Bretz',
    'Bridgeport',
    'Bristol',
    'Brohard',
    'Brownton',
    'Bruceton Mills',
    'Bruno',
    'Buckeye',
    'Buckhannon',
    'Bud',
    'Buffalo',
    'Bunker Hill',
    'Burlington',
    'Burnsville',
    'Burton',
    'Cabin Creek',
    'Cabins',
    'Cairo',
    'Caldwell',
    'Calvin',
    'Camden',
    'Camden On Gauley',
    'Cameron',
    'Camp Creek',
    'Cannelton',
    'Canvas',
    'Capels',
    'Capon Bridge',
    'Capon Springs',
    'Caretta',
    'Carolina',
    'Cass',
    'Cassville',
    'Cedar Grove',
    'Cedarville',
    'Center Point',
    'Centralia',
    'Ceredo',
    'Chapmanville',
    'Charles Town',
    'Charleston',
    'Charlton Heights',
    'Charmco',
    'Chattaroy',
    'Chauncey',
    'Chester',
    'Chloe',
    'Circleville',
    'Clarksburg',
    'Clay',
    'Clear Creek',
    'Clear Fork',
    'Clendenin',
    'Cleveland',
    'Clio',
    'Clothier',
    'Coal City',
    'Coal Mountain',
    'Coalton',
    'Coalwood',
    'Colcord',
    'Colfax',
    'Colliers',
    'Comfort',
    'Cool Ridge',
    'Copen',
    'Cora',
    'Core',
    'Corinne',
    'Costa',
    'Cottageville',
    'Covel',
    'Cowen',
    'Coxs Mills',
    'Crab Orchard',
    'Craigsville',
    'Crawford',
    'Crawley',
    'Creston',
    'Crichton',
    'Crum',
    'Crumpler',
    'Cucumber',
    'Culloden',
    'Cyclone',
    'Dailey',
    'Dallas',
    'Danese',
    'Daniels',
    'Danville',
    'Davin',
    'Davis',
    'Davisville',
    'Davy',
    'Dawes',
    'Deep Water',
    'Delbarton',
    'Dellslow',
    'Delray',
    'Diana',
    'Dille',
    'Dingess',
    'Dixie',
    'Dorothy',
    'Dothan',
    'Drennen',
    'Dry Creek',
    'Drybranch',
    'Dryfork',
    'Duck',
    'Dunbar',
    'Dunlow',
    'Dunmore',
    'Durbin',
    'East Bank',
    'East Lynn',
    'Eccles',
    'Eckman',
    'Edgarton',
    'Edmond',
    'Eglon',
    'Elbert',
    'Eleanor',
    'Elizabeth',
    'Elk Garden',
    'Elkhorn',
    'Elkins',
    'Elkview',
    'Ellamore',
    'Ellenboro',
    'Elmira',
    'Elton',
    'English',
    'Enterprise',
    'Erbacon',
    'Eskdale',
    'Ethel',
    'Evans',
    'Everettville',
    'Exchange',
    'Fairdale',
    'Fairlea',
    'Fairmont',
    'Fairview',
    'Falling Rock',
    'Falling Waters',
    'Fanrock',
    'Farmington',
    'Fayetteville',
    'Fenwick',
    'Fisher',
    'Flat Top',
    'Flatwoods',
    'Flemington',
    'Follansbee',
    'Folsom',
    'Forest Hill',
    'Fort Ashby',
    'Fort Gay',
    'Fort Spring',
    'Foster',
    'Four States',
    'Frametown',
    'Frankford',
    'Franklin',
    'Fraziers Bottom',
    'Freeman',
    'French Creek',
    'Frenchton',
    'Friendly',
    'Gallagher',
    'Gallipolis Ferry',
    'Galloway',
    'Gandeeville',
    'Gap Mills',
    'Gary',
    'Gassaway',
    'Gauley Bridge',
    'Gay',
    'Genoa',
    'Gerrardstown',
    'Ghent',
    'Gilbert',
    'Gilboa',
    'Gilmer',
    'Given',
    'Glace',
    'Glady',
    'Glasgow',
    'Glen',
    'Glen Dale',
    'Glen Daniel',
    'Glen Easton',
    'Glen Ferris',
    'Glen Fork',
    'Glen Jean',
    'Glen Morgan',
    'Glen Rogers',
    'Glen White',
    'Glengary',
    'Glenhayes',
    'Glenville',
    'Glenwood',
    'Gordon',
    'Gormania',
    'Grafton',
    'Grant Town',
    'Grantsville',
    'Granville',
    'Grassy Meadows',
    'Great Cacapon',
    'Green Bank',
    'Green Spring',
    'Green Sulphur Springs',
    'Greenville',
    'Griffithsville',
    'Grimms Landing',
    'Gypsy',
    'Hacker Valley',
    'Halltown',
    'Hambleton',
    'Hamlin',
    'Hampden',
    'Handley',
    'Hanover',
    'Hansford',
    'Harman',
    'Harper',
    'Harpers Ferry',
    'Harrisville',
    'Hartford',
    'Harts',
    'Havaco',
    'Haywood',
    'Hazelton',
    'Heaters',
    'Hedgesville',
    'Helen',
    'Helvetia',
    'Hemphill',
    'Henderson',
    'Hendricks',
    'Henlawson',
    'Hensley',
    'Hepzibah',
    'Herndon',
    'Hernshaw',
    'Hewett',
    'Hiawatha',
    'Hico',
    'High View',
    'Hillsboro',
    'Hilltop',
    'Hines',
    'Hinton',
    'Holden',
    'Hometown',
    'Horner',
    'Hugheston',
    'Hundred',
    'Huntington',
    'Hurricane',
    'Huttonsville',
    'Iaeger',
    'Idamay',
    'Ikes Fork',
    'Independence',
    'Indore',
    'Industrial',
    'Institute',
    'Inwood',
    'Ireland',
    'Isaban',
    'Itmann',
    'Ivydale',
    'Jacksonburg',
    'Jane Lew',
    'Jeffrey',
    'Jenkinjones',
    'Jesse',
    'Jodie',
    'Jolo',
    'Jonben',
    'Josephine',
    'Julian',
    'Jumping Branch',
    'Junction',
    'Junior',
    'Justice',
    'Kanawha Falls',
    'Kanawha Head',
    'Kearneysville',
    'Kegley',
    'Kellysville',
    'Kenna',
    'Kenova',
    'Kerens',
    'Kermit',
    'Keslers Cross Lanes',
    'Keyser',
    'Keystone',
    'Kiahsville',
    'Kieffer',
    'Kilsyth',
    'Kimball',
    'Kimberly',
    'Kincaid',
    'Kingmont',
    'Kingwood',
    'Kistler',
    'Kopperston',
    'Kyle',
    'Lahmansville',
    'Lake',
    'Lakin',
    'Lanark',
    'Lansing',
    'Lashmeet',
    'Lavalette',
    'Layland',
    'Le Roy',
    'Leckie',
    'Leewood',
    'Left Hand',
    'Leivasy',
    'Lenore',
    'Leon',
    'Lerona',
    'Lesage',
    'Leslie',
    'Lester',
    'Letart',
    'Levels',
    'Lewisburg',
    'Liberty',
    'Linden',
    'Lindside',
    'Linn',
    'Little Birch',
    'Littleton',
    'Lizemores',
    'Lochgelly',
    'Lockney',
    'Logan',
    'London',
    'Lookout',
    'Looneyville',
    'Lorado',
    'Lorentz',
    'Lost City',
    'Lost Creek',
    'Lumberport',
    'Lyburn',
    'Lynco',
    'Maben',
    'Mabie',
    'Mabscott',
    'Mac Arthur',
    'Macfarlan',
    'Madison',
    'Maidsville',
    'Mallory',
    'Mammoth',
    'Man',
    'Mannington',
    'Marianna',
    'Marlinton',
    'Martinsburg',
    'Mason',
    'Masontown',
    'Matewan',
    'Matheny',
    'Mathias',
    'Matoaka',
    'Maxwelton',
    'Maybeury',
    'Maysel',
    'Maysville',
    'McGraws',
    'McMechen',
    'Meador',
    'Meadow Bluff',
    'Meadow Bridge',
    'Meadow Creek',
    'Meadowbrook',
    'Medley',
    'Metz',
    'Miami',
    'Middlebourne',
    'Midkiff',
    'Midway',
    'Milam',
    'Mill Creek',
    'Millstone',
    'Millville',
    'Millwood',
    'Milton',
    'Minden',
    'Mineral Wells',
    'Moatsville',
    'Mohawk',
    'Monaville',
    'Montana Mines',
    'Montcalm',
    'Monterville',
    'Montgomery',
    'Montrose',
    'Moorefield',
    'Morgantown',
    'Moundsville',
    'Mount Alto',
    'Mount Carbon',
    'Mount Clare',
    'Mount Gay',
    'Mount Hope',
    'Mount Lookout',
    'Mount Nebo',
    'Mount Olive',
    'Mount Storm',
    'Mount Zion',
    'Mountain',
    'Mullens',
    'Munday',
    'Myra',
    'Nallen',
    'Naoma',
    'Napier',
    'Naugatuck',
    'Nebo',
    'Nellis',
    'Nemours',
    'Neola',
    'Nettie',
    'New Creek',
    'New Cumberland',
    'New Haven',
    'New Manchester',
    'New Martinsville',
    'New Milton',
    'New Richmond',
    'Newburg',
    'Newell',
    'Newhall',
    'Newton',
    'Newtown',
    'Nimitz',
    'Nitro',
    'Nolan',
    'Normantown',
    'North Matewan',
    'North Spring',
    'Northfork',
    'Norton',
    'Oak Hill',
    'Oakvale',
    'Oceana',
    'Odd',
    'Ohley',
    'Old Fields',
    'Omar',
    'Ona',
    'Onego',
    'Orgas',
    'Orlando',
    'Orma',
    'Osage',
    'Ottawa',
    'Ovapa',
    'Paden City',
    'Page',
    'Pageton',
    'Palestine',
    'Panther',
    'Parkersburg',
    'Parsons',
    'Paw Paw',
    'Pax',
    'Paynesville',
    'Peach Creek',
    'Pecks Mill',
    'Pence Springs',
    'Pennsboro',
    'Pentress',
    'Perkins',
    'Petersburg',
    'Peterstown',
    'Petroleum',
    'Peytona',
    'Philippi',
    'Pickens',
    'Piedmont',
    'Pinch',
    'Pine Grove',
    'Pineville',
    'Piney View',
    'Pipestem',
    'Poca',
    'Point Pleasant',
    'Points',
    'Pond Gap',
    'Pool',
    'Porters Falls',
    'Powellton',
    'Powhatan',
    'Pratt',
    'Premier',
    'Prichard',
    'Prince',
    'Princeton',
    'Princewick',
    'Procious',
    'Proctor',
    'Prosperity',
    'Pullman',
    'Purgitsville',
    'Pursglove',
    'Quinwood',
    'Rachel',
    'Racine',
    'Ragland',
    'Rainelle',
    'Raleigh',
    'Ramsey',
    'Ranger',
    'Ranson',
    'Ravencliff',
    'Ravenswood',
    'Rawl',
    'Raysal',
    'Reader',
    'Red Creek',
    'Red House',
    'Red Jacket',
    'Redstar',
    'Reedsville',
    'Reedy',
    'Renick',
    'Reynoldsville',
    'Rhodell',
    'Richwood',
    'Ridgeley',
    'Ridgeview',
    'Ridgeway',
    'Rio',
    'Ripley',
    'Rippon',
    'Riverton',
    'Rivesville',
    'Robson',
    'Rock',
    'Rock Cave',
    'Rock Creek',
    'Rock View',
    'Rockport',
    'Roderfield',
    'Romney',
    'Ronceverte',
    'Rosedale',
    'Rosemont',
    'Rowlesburg',
    'Rupert',
    'Sabine',
    'Saint Albans',
    'Saint Marys',
    'Salem',
    'Salt Rock',
    'Sand Fork',
    'Sandstone',
    'Sandyville',
    'Sarah Ann',
    'Saulsville',
    'Saxon',
    'Scarbro',
    'Scott Depot',
    'Secondcreek',
    'Selbyville',
    'Seneca Rocks',
    'Seth',
    'Shady Spring',
    'Shanks',
    'Sharon',
    'Sharples',
    'Shenandoah Junction',
    'Shepherdstown',
    'Sherman',
    'Shinnston',
    'Shirley',
    'Shoals',
    'Shock',
    'Short Creek',
    'Simon',
    'Simpson',
    'Sinks Grove',
    'Sistersville',
    'Skelton',
    'Skygusty',
    'Slab Fork',
    'Slanesville',
    'Slatyfork',
    'Smithburg',
    'Smithers',
    'Smithfield',
    'Smithville',
    'Smoot',
    'Snowshoe',
    'Sod',
    'Sophia',
    'Southside',
    'Spanishburg',
    'Spelter',
    'Spencer',
    'Sprague',
    'Spring Dale',
    'Springfield',
    'Spurlockville',
    'Squire',
    'Stanaford',
    'Statts Mills',
    'Stephenson',
    'Stirrat',
    'Stollings',
    'Strange Creek',
    'Sugar Grove',
    'Sumerco',
    'Summerlee',
    'Summersville',
    'Summit Point',
    'Surveyor',
    'Sutton',
    'Swiss',
    'Switchback',
    'Switzer',
    'Sylvester',
    'Tad',
    'Talcott',
    'Tallmansville',
    'Tariff',
    'Teays',
    'Terra Alta',
    'Terry',
    'Thacker',
    'Thomas',
    'Thornton',
    'Thorpe',
    'Thurmond',
    'Tioga',
    'Tornado',
    'Triadelphia',
    'Troy',
    'True',
    'Tunnelton',
    'Turtle Creek',
    'Twilight',
    'Twin Branch',
    'Uneeda',
    'Union',
    'Upper Tract',
    'Upperglade',
    'Valley Bend',
    'Valley Fork',
    'Valley Grove',
    'Valley Head',
    'Van',
    'Varney',
    'Verdunville',
    'Verner',
    'Victor',
    'Vienna',
    'Volga',
    'Vulcan',
    'Wadestown',
    'Waiteville',
    'Walker',
    'Walkersville',
    'Wallace',
    'Wallback',
    'Walton',
    'Wana',
    'War',
    'Wardensville',
    'Warriormine',
    'Washington',
    'Waverly',
    'Wayne',
    'Wayside',
    'Webster Springs',
    'Weirton',
    'Welch',
    'Wellsburg',
    'West Columbia',
    'West Hamlin',
    'West Liberty',
    'West Milford',
    'West Union',
    'Weston',
    'Wharncliffe',
    'Wharton',
    'Wheeling',
    'White Oak',
    'White Sulphur Springs',
    'Whitesville',
    'Whitman',
    'Whitmer',
    'Widen',
    'Wilcoe',
    'Wiley Ford',
    'Wileyville',
    'Wilkinson',
    'Williamsburg',
    'Williamson',
    'Williamstown',
    'Wilsie',
    'Wilsonburg',
    'Wilsondale',
    'Windsor Heights',
    'Winfield',
    'Winifrede',
    'Winona',
    'Wolf Pen',
    'Wolfcreek',
    'Wolfe',
    'Woodville',
    'Worth',
    'Worthington',
    'Wyatt',
    'Wyco',
    'Wyoming',
    'Yawkey',
    'Yellow Spring',
    'Yolyn',
    'Yukon'
]
