cities = [
    'Afton',
    'Aladdin',
    'Albin',
    'Alcova',
    'Alpine',
    'Alva',
    'Arapahoe',
    'Arminto',
    'Arvada',
    'Auburn',
    'Baggs',
    'Bairoil',
    'Banner',
    'Basin',
    'Bedford',
    'Beulah',
    'Big Horn',
    'Big Piney',
    'Bill',
    'Bondurant',
    'Bosler',
    'Boulder',
    'Buffalo',
    'Buford',
    'Burlington',
    'Burns',
    'Byron',
    'Carlile',
    'Carpenter',
    'Casper',
    'Centennial',
    'Cheyenne',
    'Chugwater',
    'Clearmont',
    'Cody',
    'Cokeville',
    'Cora',
    'Cowley',
    'Crowheart',
    'Daniel',
    'Dayton',
    'Deaver',
    'Devils Tower',
    'Diamondville',
    'Dixon',
    'Douglas',
    'Dubois',
    'Edgerton',
    'Elk Mountain',
    'Emblem',
    'Encampment',
    'Etna',
    'Evanston',
    'Evansville',
    'Fairview',
    'Farson',
    'Fe Warren AFB',
    'Fort Bridger',
    'Fort Laramie',
    'Fort Washakie',
    'Four Corners',
    'Frannie',
    'Frontier',
    'Garrett',
    'Gillette',
    'Glendo',
    'Glenrock',
    'Granger',
    'Granite Canon',
    'Green River',
    'Greybull',
    'Grover',
    'Guernsey',
    'Hamilton Dome',
    'Hanna',
    'Hartville',
    'Hawk Springs',
    'Hiland',
    'Hillsdale',
    'Horse Creek',
    'Hudson',
    'Hulett',
    'Huntley',
    'Hyattville',
    'Jackson',
    'Jay Em',
    'Jeffrey City',
    'Kaycee',
    'Kelly',
    'Kemmerer',
    'Kinnear',
    'Kirby',
    'La Barge',
    'Lagrange',
    'Lance Creek',
    'Lander',
    'Laramie',
    'Leiter',
    'Linch',
    'Lingle',
    'Little America',
    'Lontetree',
    'Lost Springs',
    'Lovell',
    'Lusk',
    'Lyman',
    'Lysite',
    'Manderson',
    'Manville',
    'McKinnon',
    'Medicine Bow',
    'Meeteetse',
    'Meriden',
    'Midwest',
    'Mills',
    'Moorcroft',
    'Moose',
    'Moran',
    'Mountain View',
    'Natrona',
    'Newcastle',
    'Opal',
    'Osage',
    'Otto',
    'Parkman',
    'Pavillion',
    'Pinedale',
    'Point Of Rocks',
    'Powder River',
    'Powell',
    'Ralston',
    'Ranchester',
    'Rawlins',
    'Recluse',
    'Reliance',
    'Riverton',
    'Robertson',
    'Rock River',
    'Rock Springs',
    'Rozet',
    'Saddlestring',
    'Saint Stephens',
    'Saratoga',
    'Savery',
    'Shawnee',
    'Shell',
    'Sheridan',
    'Shirley Basin',
    'Shoshoni',
    'Sinclair',
    'Smoot',
    'Story',
    'Sundance',
    'Superior',
    'Ten Sleep',
    'Teton Village',
    'Thayne',
    'Thermopolis',
    'Tie Siding',
    'Torrington',
    'Upton',
    'Van Tassell',
    'Veteran',
    'Vista West',
    'Walcott',
    'Wamsutter',
    'Wapiti',
    'Weston',
    'Wheatland',
    'Wilson',
    'Wolf',
    'Worland',
    'Wright',
    'Wyarno',
    'Yoder'
]
