cities = [
    'Buenos Aires',
    'Cordoba',
    'Rosario',
    'Mendoza',
    'San Miguel de Tucuman',
    'La Plata',
    'Mar del Plata',
    'Quilmes',
    'Salta',
    'Santa Fe de la Vera Cruz',
    'San Juan',
    'Resistencia',
    'Santiago del Estero',
    'Corrientes',
    'Posadas',
    'Moron',
    'San Salvador de Jujuy',
    'Bahia Blanca',
    'Parana',
    'Neuquen',
    'Pilar',
    'Formosa',
    'San Fernando del Valle de Catamarca',
    'San Luis',
    'Berazategui',
    'La Rioja',
    'Rio Cuarto',
    'Balvanera',
    'Concordia',
    'Comodoro Rivadavia',
    'Belgrano',
    'San Nicolas de los Arroyos',
    'Villa Lugano',
    'Santa Rosa',
    'San Rafael',
    'Tandil',
    'Villa Mercedes',
    'San Carlos de Bariloche',
    'Trelew',
    'Villa Maria',
    'Reconquista',
    'Zarate',
    'Rafaela',
    'Pergamino',
    'Olavarria',
    'Rio Gallegos',
    'Junin',
    'San Martin',
    'Presidencia Roque Saenz Pena',
    'Lujan',
    'Campana',
    'Necochea',
    'Gualeguaychu',
    'Barracas',
    'Cipolletti',
    'Gobernador Galvez',
    'San Ramon de la Nueva Oran',
    'Chimbas',
    'General Roca',
    'Venado Tuerto',
    'Goya',
    'Villa Carlos Paz',
    'Concepcion del Uruguay',
    'Puerto Madryn',
    'Tartagal',
    'Santo Tome',
    'San Francisco',
    'San Pedro',
    'Ushuaia',
    'Punta Alta',
    'General Pico',
    'Colegiales',
    'Obera',
    'Chivilcoy',
    'Puerto Eldorado',
    'Azul',
    'Rio Tercero',
    'Mercedes',
    'Rio Grande',
    'Barranqueras',
    'Yerba Buena',
    'Libertador General San Martin',
    'Viedma',
    'Tafi Viejo',
    'Boedo',
    'Palpala',
    'San Lorenzo',
    'San Pedro',
    'Cutral-Co',
    'Tres Arroyos',
    'San Isidro',
    'Villa Constitucion',
    'Paso de los Libres',
    'Santa Lucia',
    'Villa Angela',
    'Chilecito',
    'Lincoln',
    'Pocito',
    'Alta Gracia',
    'Retiro',
    'Alderetes',
    'San Vicente',
    'Castelli',
    'Curuzu Cuatia',
    'Caleta Olivia',
    'Canada de Gomez',
    'Esperanza',
    'Bell Ville',
    'Nueve de Julio',
    'Chacabuco',
    'Villa Santa Rita',
    'Caucete',
    'Pontevedra',
    'Gualeguay',
    'Aguilares',
    'Granadero Baigorria',
    'Quitilipi',
    'Puerto Iguazu',
    'Villaguay',
    'Casilda',
    'General Jose de San Martin',
    'Zapala',
    'Villa Regina',
    'Tigre',
    'Famailla',
    'Chajari',
    'Mercedes',
    'Centenario',
    'Garupa',
    'Gobernador Ingeniero Valentin Virasoro',
    'Esquel',
    'Adrogue',
    'Cruz del Eje',
    'Machagai',
    'Villa Dolores',
    'Termas de Rio Hondo',
    'Charata',
    'Capitan Bermudez',
    'Coronel Suarez',
    'Las Brenas',
    'Jesus Maria',
    'Fontana',
    'Esquina',
    'Rawson',
    'Allen',
    'Dolores',
    'Plottier',
    'Victoria',
    'Jardin America',
    'La Calera',
    'Tres Isletas',
    'La Paz',
    'Monte Caseros',
    'Veinticinco de Mayo',
    'Perez',
    'Marcos Juarez',
    'Embarcacion',
    'Monteros',
    'San Pedro',
    'San Martin de los Andes',
    'Villa Gesell',
    'Avellaneda',
    'Santo Tome',
    'Villa Ortuzar',
    'Montecarlo',
    'San Justo',
    'Villa Allende',
    'San Jose de Jachal',
    'Aristobulo del Valle',
    'Albardon',
    'Anatuya',
    'Dean Funes',
    'Arroyo Seco',
    'Laboulaye',
    'Cinco Saltos',
    'General Enrique Mosconi',
    'Vera',
    'Arroyito',
    'El Soberbio',
    'Diamante',
    'Joaquin V. Gonzalez',
    'Pirane',
    'Villa Ocampo',
    'Villa Paula de Sarmiento',
    'Cosquin',
    'Sunchales',
    'Santa Elena',
    'Galvez',
    'Rufino',
    'Saladas',
    'Crespo',
    'Firmat',
    'Rio Segundo',
    'Puerto Rico',
    'Coronda',
    'San Antonio Oeste',
    'San Jorge',
    'Villa Nueva',
    'Rio Ceballos',
    'Federal',
    'General Villegas',
    'Embalse',
    'General Pinedo',
    'Carcarana',
    'San Javier',
    'Puerto Esperanza',
    'El Bolson',
    'Wanda',
    'Unquillo',
    'San Luis del Palmar',
    'Catriel',
    'Morteros',
    'Bella Vista',
    'La Falda',
    'La Punta',
    'Clorinda',
    'Pico Truncado',
    'La Quiaca',
    'Funes',
    'Las Varillas',
    'Dos de Mayo',
    'Tinogasta',
    'Fray Luis A. Beltran',
    'San Cristobal',
    'Recreo',
    'Andalgala',
    'Santa Lucia',
    'Tostado',
    'Rosario del Tala',
    'Federacion',
    'Arauco',
    'Fraile Pintado',
    'Chamical',
    'Ceres',
    'Recreo',
    'Las Rosas',
    'El Colorado',
    'Oncativo',
    'General Acha',
    'Pilar',
    'Roldan',
    'Plaza Huincul',
    'Laguna Paiva',
    'Presidencia de la Plaza',
    'Campo Grande',
    'Villa Berthet',
    'Veinticinco de Mayo',
    'Las Toscas',
    'Cafayate',
    'Chos Malal',
    'Coronel Dorrego',
    'Oliva',
    'San Salvador',
    'Pampa del Indio',
    'La Carlota',
    'Humahuaca',
    'Las Parejas',
    'San Clemente del Tuyu',
    'Merlo',
    'San Jose de Feliciano',
    'San Bernardo',
    'Candelaria',
    'Quimili',
    'Bernardo de Irigoyen',
    'El Trebol',
    'Campo Largo',
    'Junin de los Andes',
    'Almafuerte',
    'Hernando',
    'Corzuela',
    'San Carlos Centro',
    'Armstrong',
    'Ingeniero Guillermo N. Juarez',
    'Las Lomitas',
    'General Cabrera',
    'El Quebrachal',
    'Puerto Deseado',
    'Calchaqui',
    'San Martin',
    'Campo Ramon',
    'La Leonesa',
    'Leones',
    'Corral de Bustos',
    'Eduardo Castex',
    'Choele Choel',
    'El Carril',
    'Puerto Tirol',
    'Justo Daract',
    'Totoras',
    'Santa Rosa de Calamuchita',
    'Abra Pampa',
    'Malagueno',
    'Villa Elisa',
    'Villa Canas',
    'Las Heras',
    'Campo Viera',
    'Las Lajitas',
    'Coronel Du Graty',
    'Capilla del Monte',
    'Clodomira',
    'Santa Sylvina',
    'Mburucuya',
    'Vicuna Mackenna',
    'Viale',
    'Ibarreta',
    'Huinca Renanco',
    'Malvinas Argentinas',
    'General Ramirez',
    'Apolinario Saravia',
    'La Cruz',
    'Puerto Piray',
    'Taco Pozo',
    'Chicoana',
    'Puerto Vilelas',
    'Colonia Aurora',
    'El Galpon',
    'Canals',
    'Santa Rosa',
    'Sarmiento',
    'Garuhape',
    'Brinkmann',
    'Calingasta',
    'Pampa del Infierno',
    'Coronel Moldes',
    'Fiambala',
    'El Calafate',
    'Urdinarrain',
    'Bovril',
    'Simoca',
    'Alvear',
    'Itati',
    'Lamarque',
    'Huillapima',
    'Yuto',
    'Nueve de Julio',
    'Nuestra Senora del Rosario de Caa Cati',
    'Villa La Angostura',
    'Hermoso Campo',
    'Justiniano Posse',
    'Concepcion de la Sierra',
    'San Miguel',
    'Villa de Soto',
    'Sampacho',
    'La Cumbre',
    'Realico',
    'Laguna Larga',
    'Villa del Totoral',
    'Villa Maria Grande',
    'La Cocha',
    'Malabrigo',
    'Intendente Alvear',
    'Sierra Grande',
    'Veinticinco de Mayo',
    'Arias',
    'Monte Maiz',
    'Monte Cristo',
    'San Agustin de Valle Fertil',
    'Cruz Alta',
    'Icano',
    'Mina Clavero',
    'Avia Terai',
    'General Fernandez Oro',
    'Santa Rosa de Rio Primero',
    'San Benito',
    'La Toma',
    'Trancas',
    'Alba Posse',
    'Rio Turbio',
    'Yacimiento Rio Turbio',
    'Los Frentones',
    'Victorica',
    'Ingeniero Luis A. Huergo',
    'San Jose',
    'Berrotaran',
    'Adelia Maria',
    'Los Altos',
    'Salsipuedes',
    'Fray Luis Beltran',
    'Trevelin',
    'Senillosa',
    'Capayan',
    'Gobernador Roca',
    'Rada Tilly',
    'Larroque',
    'San Julian',
    'Puerto Libertad',
    'Mocoreta',
    'Suncho Corral',
    'Panambi',
    'Villa General Belgrano',
    'Capiovi',
    'Villa Ojo de Agua',
    'Concepcion del Bermejo',
    'Paso de la Patria',
    'Macia',
    'Ingeniero Jacobacci',
    'Gaiman',
    'Perugorria',
    'Comandante Fontana',
    'Despenaderos'
]
