cities = [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Canberra',
    'Newcastle',
    'Wollongong',
    'Logan City',
    'Geelong',
    'Hobart',
    'Townsville',
    'Cairns',
    'Toowoomba',
    'Darwin',
    'Rockingham',
    'Launceston',
    'Bendigo',
    'Ballarat',
    'Mandurah',
    'Mackay',
    'Bundaberg',
    'Bunbury',
    'Maitland',
    'Armadale',
    'Rockhampton',
    'Adelaide Hills',
    'South Brisbane',
    'Hervey Bay',
    'Reservoir',
    'Tamworth',
    'Wagga Wagga',
    'Albury',
    'Berwick',
    'Port Macquarie',
    'Queanbeyan',
    'Orange',
    'Blacktown',
    'Shepparton',
    'Caloundra',
    'Hoppers Crossing',
    'Werribee',
    'Melton',
    'Castle Hill',
    'Saint Albans',
    'Nowra',
    'Frankston',
    'Frankston East',
    'Rowville',
    'Warrnambool',
    'Baulkham Hills',
    'Albany',
    'Mount Waverley',
    'St Albans',
    'Auburn',
    'Bathurst',
    'Pakenham South',
    'Point Cook',
    'Dubbo',
    'Epping',
    'Wodonga',
    'Kalgoorlie',
    'Bankstown',
    'Mill Park',
    'Gladstone',
    'Kwinana',
    'Lismore',
    'Mildura',
    'Preston',
    'Sunbury',
    'Hurstville',
    'Narre Warren South',
    'Noble Park',
    'Southport',
    'Kellyville',
    'Port Stephens',
    'Banora Point',
    'Doncaster East',
    'Croydon',
    'Geraldton',
    'Maroubra',
    'Coffs Harbour',
    'Mosman',
    'Richmond',
    'Narre Warren',
    'Randwick',
    'Strathfield',
    'Bundoora',
    'Alice Springs',
    'Quakers Hill',
    'Endeavour Hills',
    'Palmerston',
    'Coburg',
    'Dandenong',
    'Fremantle',
    'Ferntree Gully',
    'Campsie',
    'Kew',
    'Hampton Park',
    'Canning Vale',
    'Glen Iris',
    'Mount Gambier',
    'Marrickville',
    'Northcote',
    'Granville',
    'Mount Isa',
    'Keysborough',
    'Armidale',
    'Morphett Vale',
    'Dianella',
    'Forest Lake',
    'Mornington',
    'Thornlie',
    'Ashfield',
    'Traralgon',
    'Dandenong North',
    'Busselton',
    'Cabramatta',
    'Greystanes',
    'Tarneit',
    'Maryborough',
    'Caboolture',
    'Kirwan',
    'Langwarrin',
    'Carlingford',
    'Liverpool',
    'Caringbah',
    'Brighton',
    'Glenferrie',
    'Hawthorn',
    'Hawthorn South',
    'Goulburn',
    'Boronia',
    'Woodridge',
    'Booval',
    'Thomastown',
    'Cheltenham',
    'Punchbowl',
    'Prospect',
    'Greensborough',
    'Gawler',
    'Burnie',
    'Balwyn North',
    'Lalor',
    'Brunswick',
    'Hornsby',
    'St Clair',
    'Springvale',
    'Wheelers Hill',
    'Craigieburn',
    'Whyalla',
    'Glenroy',
    'Camberwell',
    'Malvern East',
    'Murray Bridge',
    'Echuca',
    'Devonport',
    'Roxburgh Park',
    'Glenmore Park',
    'Epping',
    'Ballajura',
    'Essendon',
    'Cherrybrook',
    'Altona Meadows',
    'Cranbourne',
    'Katoomba',
    'Surfers Paradise',
    'Parramatta',
    'Broken Hill',
    'Doncaster',
    'Eltham',
    'Fairfield',
    'Morayfield',
    'Engadine',
    'Eastwood',
    'Saint Kilda',
    'Highton',
    'Mulgrave',
    'Forster',
    'Wantirna South',
    'Dee Why',
    'Thornbury',
    'Wahroonga',
    'Frankston South',
    'Wyndham Vale',
    'Gosnells',
    'Mount Eliza',
    'Willetton',
    'Carrum Downs',
    'North Ryde',
    'Mount Martha',
    'Wangaratta',
    'Sunnybank Hills',
    'Cronulla',
    'Sunshine West',
    'Taree',
    'Earlwood',
    'Sunnybank',
    'South Grafton',
    'Cessnock',
    'Hillside',
    'Westmead',
    'Carnegie',
    'Nerang',
    'Narangba',
    'Deer Park',
    'Taylors Lakes',
    'Deception Bay',
    'Umina',
    'Seaford',
    'Burwood',
    'Yagoona',
    'West Pennant Hills',
    'Paralowie',
    'Lilydale',
    'Moe',
    'Clayton',
    'Lara',
    'Griffith',
    'Bracken Ridge',
    'Eight Mile Plains',
    'Parafield Gardens',
    'Prestons',
    'Buderim',
    'Brighton East',
    'Carindale',
    'Port Hedland',
    'Duncraig',
    'Pascoe Vale',
    'Rochedale South',
    'Coorparoo',
    'Meadow Heights',
    'Mitcham',
    'Casula',
    'Bossley Park',
    'Cranbourne North',
    'Caulfield North',
    'Lakemba',
    'Kingston',
    'Grovedale',
    'Horsham',
    'Bentleigh',
    'Ballina',
    'Kingsford',
    'Lidcombe',
    'Carlton',
    'Wantirna',
    'Manly',
    'Ingleburn',
    'Burleigh Waters',
    'Elwood',
    'Cleveland',
    'Victoria Point',
    'Yarraville',
    'Singleton',
    'Bongaree',
    'Raymond Terrace',
    'Mount Druitt',
    'Bacchus Marsh',
    'Newtown',
    'Moonee Ponds',
    'Palm Beach',
    'Ascot Vale',
    'Morwell',
    'Port Melbourne',
    'Yeppoon',
    'Keilor East',
    'Port Augusta',
    'Port Pirie',
    'Footscray',
    'Williamstown',
    'Sale',
    'Coogee',
    'Templestowe Lower',
    'Brunswick West',
    'Hawthorn East',
    'Surrey Hills',
    'Port Lincoln',
    'Doonside',
    'Concord',
    'Toongabbie',
    'Dulwich Hill',
    'Balwyn',
    'Miranda',
    'Toorak',
    'Beaumaris',
    'Port Kennedy',
    'Broome',
    'Fawkner',
    'Scarborough',
    'St Kilda East',
    'Inala',
    'Warwick',
    'Rosebud',
    'Hampton',
    'Como',
    'Ashwood',
    'Chadstone',
    'Marsfield',
    'Kiama',
    'Mayfield',
    'Leichhardt',
    'Springvale South',
    'Goonellabah',
    'Port Augusta West',
    'Geelong West',
    'Lavington',
    'Doreen',
    'Newport',
    'Greenvale',
    'Blackburn',
    'Burwood',
    'West Ryde',
    'Kingswood Park',
    'Penrith',
    'Varsity Lakes',
    'Donvale',
    'Muswellbrook',
    'Taylors Hill',
    'Bateau Bay',
    'North Melbourne',
    'Wynnum West',
    'Karratha',
    'Charlestown',
    'Wynnum',
    'Penshurst',
    'Mentone',
    'Paddington',
    'Caringbah South',
    'Clayton South',
    'Happy Valley',
    'Diamond Creek',
    'Redfern',
    'North Fitzroy',
    'Warnbro',
    'Vermont South',
    'Sandy Bay',
    'East Maitland',
    'South Perth',
    'Lithgow',
    'Bayswater',
    'Manly West',
    'Parkdale',
    'Caulfield South',
    'Gympie',
    'Bairnsdale',
    'Bowen',
    'Nunawading',
    'Samford Valley',
    'Wanneroo',
    'Mount Gravatt East',
    'Altona North',
    'Caroline Springs',
    'Bulleen',
    'Kensington',
    'Gladesville',
    'Menai',
    'Bondi Beach',
    'Wellington Point',
    'Mount Lawley',
    'Annerley',
    'Tewantin',
    'Box Hill North',
    'Sunshine North',
    'Yokine',
    'Batemans Bay',
    'Camp Hill',
    'Marangaroo',
    'Dapto',
    'Maylands',
    'Drummoyne',
    'Melton West',
    'Bondi',
    'Sydenham',
    'Keilor Downs',
    'Neutral Bay',
    'Highett',
    'West Footscray',
    'Nambour',
    'Rutherford',
    'Maribyrnong',
    'Hallam',
    'Hillarys',
    'Burwood East',
    'Blackburn South',
    'Darlinghurst',
    'Hamilton',
    'Dingley Village',
    'Glenorchy',
    'Forest Hill',
    'Kilsyth',
    'Parkes',
    'Nedlands',
    'Moranbah',
    'Broadmeadows',
    'Grafton',
    'Altona',
    'Vermont',
    'Dalby'
]
