cities = [
    'Santa Cruz de la Sierra',
    'Cochabamba',
    'La Paz',
    'Sucre',
    'Oruro',
    'Tarija',
    'Potosi',
    'Sacaba',
    'Montero',
    'Quillacollo',
    'Trinidad',
    'Yacuiba',
    'Riberalta',
    'Tiquipaya',
    'Guayaramerin',
    'Bermejo',
    'Mizque',
    'Villazon',
    'Llallagua',
    'Camiri',
    'Cobija',
    'San Borja',
    'San Ignacio de Velasco',
    'Tupiza',
    'Warnes',
    'San Borja',
    'Ascencion de Guarayos',
    'Villamontes',
    'Cotoca',
    'Villa Yapacani',
    'Santiago del Torno',
    'Huanuni',
    'Punata',
    'Ascension',
    'Mineros',
    'Santa Ana de Yacuma',
    'Patacamaya',
    'Colchani',
    'Rurrenabaque',
    'Portachuelo',
    'Puerto Quijarro',
    'Uyuni',
    'Robore',
    'Pailon',
    'Cliza',
    'Achacachi',
    'Vallegrande',
    'Monteagudo',
    'Aiquile',
    'Tarata',
    'Challapata',
    'San Julian',
    'Reyes',
    'Concepcion',
    'San Matias',
    'La Belgica',
    'Santa Rosa del Sara',
    'Capinota',
    'Chimore',
    'San Pedro'
]
