cities = [
    'Sao Paulo',
    'Rio de Janeiro',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Brasilia',
    'Curitiba',
    'Manaus',
    'Recife',
    'Belem',
    'Porto Alegre',
    'Goiania',
    'Guarulhos',
    'Campinas',
    'Nova Iguacu',
    'Maceio',
    'Sao Luis',
    'Duque de Caxias',
    'Natal',
    'Teresina',
    'Sao Bernardo do Campo',
    'Campo Grande',
    'Jaboatao',
    'Osasco',
    'Santo Andre',
    'Joao Pessoa',
    'Jaboatao dos Guararapes',
    'Contagem',
    'Ribeirao Preto',
    'Sao Jose dos Campos',
    'Uberlandia',
    'Sorocaba',
    'Cuiaba',
    'Aparecida de Goiania',
    'Aracaju',
    'Feira de Santana',
    'Londrina',
    'Juiz de Fora',
    'Belford Roxo',
    'Joinville',
    'Niteroi',
    'Sao Joao de Meriti',
    'Ananindeua',
    'Florianopolis',
    'Santos',
    'Ribeirao das Neves',
    'Vila Velha',
    'Serra',
    'Diadema',
    'Campos dos Goytacazes',
    'Maua',
    'Betim',
    'Caxias do Sul',
    'Sao Jose do Rio Preto',
    'Olinda',
    'Carapicuiba',
    'Campina Grande',
    'Piracicaba',
    'Macapa',
    'Itaquaquecetuba',
    'Bauru',
    'Montes Claros',
    'Canoas',
    'Mogi das Cruzes',
    'Sao Vicente',
    'Jundiai',
    'Pelotas',
    'Anapolis',
    'Vitoria',
    'Maringa',
    'Guaruja',
    'Porto Velho',
    'Franca',
    'Blumenau',
    'Foz do Iguacu',
    'Ponta Grossa',
    'Paulista',
    'Limeira',
    'Viamao',
    'Suzano',
    'Caucaia',
    'Petropolis',
    'Uberaba',
    'Rio Branco',
    'Cascavel',
    'Novo Hamburgo',
    'Vitoria da Conquista',
    'Barueri',
    'Taubate',
    'Governador Valadares',
    'Praia Grande',
    'Varzea Grande',
    'Volta Redonda',
    'Santa Maria',
    'Santa Luzia',
    'Gravatai',
    'Caruaru',
    'Boa Vista',
    'Ipatinga',
    'Sumare',
    'Juazeiro do Norte',
    'Embu',
    'Imperatriz',
    'Colombo',
    'Taboao da Serra',
    'Jacarei',
    'Marilia',
    'Presidente Prudente',
    'Sao Leopoldo',
    'Itabuna',
    'Sao Carlos',
    'Hortolandia',
    'Mossoro',
    'Itapevi',
    'Sete Lagoas',
    'Sao Jose',
    'Palmas',
    'Americana',
    'Petrolina',
    'Divinopolis',
    'Maracanau',
    'Planaltina',
    'Santarem',
    'Camacari',
    "Santa Barbara d'Oeste",
    'Rio Grande',
    'Cachoeiro de Itapemirim',
    'Itaborai',
    'Rio Claro',
    'Indaiatuba',
    'Passo Fundo',
    'Cotia',
    'Francisco Morato',
    'Aracatuba',
    'Araraquara',
    'Ferraz de Vasconcelos',
    'Arapiraca',
    'Lages',
    'Barra Mansa',
    'Nossa Senhora do Socorro',
    'Dourados',
    'Criciuma',
    'Chapeco',
    'Barreiras',
    'Sobral',
    'Itajai',
    'Ilheus',
    'Angra dos Reis',
    'Nova Friburgo',
    'Rondonopolis',
    'Itapecerica da Serra',
    'Guarapuava',
    'Parnamirim',
    'Caxias',
    'Nilopolis',
    'Pocos de Caldas',
    'Maraba',
    'Luziania',
    'Cabo',
    'Macae',
    'Ibirite',
    'Lauro de Freitas',
    'Paranagua',
    'Parnaiba',
    'Itu',
    'Castanhal',
    'Sao Caetano do Sul',
    'Queimados',
    'Pindamonhangaba',
    'Sapucaia',
    'Jaragua do Sul',
    'Mogi Guacu',
    'Jequie',
    'Itapetininga',
    'Patos de Minas',
    'Braganca Paulista',
    'Timon',
    'Sao Jose dos Pinhais',
    'Teresopolis',
    'Uruguaiana',
    'Porto Seguro',
    'Alagoinhas',
    'Palhoca',
    'Barbacena',
    'Cachoeirinha',
    'Santa Rita',
    'Toledo',
    'Jau',
    'Cubatao',
    'Pinhais',
    'Simoes Filho',
    'Varginha',
    'Sinop',
    'Pouso Alegre',
    'Eunapolis',
    'Botucatu',
    'Jandira',
    'Ribeirao Pires',
    'Conselheiro Lafaiete',
    'Resende',
    'Araucaria',
    'Atibaia',
    'Varzea Paulista',
    'Garanhuns',
    'Araruama',
    'Catanduva',
    'Franco da Rocha',
    'Cabo Frio',
    'Ji Parana',
    'Araras',
    'Poa',
    'Vitoria de Santo Antao',
    'Umuarama',
    'Apucarana',
    'Santa Cruz do Sul',
    'Guaratingueta',
    'Linhares',
    'Araguaina',
    'Esmeraldas',
    'Birigui',
    'Assis',
    'Barretos',
    'Colatina',
    'Teofilo Otoni',
    'Guaiba',
    'Guarapari',
    'Coronel Fabriciano',
    'Itaguai',
    'Rio das Ostras',
    'Itabira',
    'Votorantim',
    'Sertaozinho',
    'Santana de Parnaiba',
    'Bage',
    'Passos',
    'Salto',
    'Uba',
    'Ourinhos',
    'Trindade',
    'Arapongas',
    'Araguari',
    'Corumba',
    'Erechim',
    'Japeri',
    'Vespasiano',
    'Campo Largo',
    'Tatui',
    'Patos',
    'Timoteo',
    'Muriae',
    'Cambe',
    'Bayeux',
    'Bento Goncalves',
    'Caraguatatuba',
    'Itanhaem',
    'Santana do Livramento',
    'Almirante Tamandare',
    'Planaltina',
    'Crato',
    'Valinhos',
    'Sao Lourenco da Mata',
    'Nova Lima',
    'Brusque',
    'Barra do Pirai',
    'Alegrete',
    'Caieiras',
    'Barra do Corda',
    'Igarassu',
    'Paulo Afonso',
    'Ituiutaba',
    'Esteio',
    'Sarandi',
    'Itaperuna',
    'Santana',
    'Jardim Paulista',
    'Codo',
    'Araxa',
    'Abreu e Lima',
    'Itajuba',
    'Lavras',
    'Avare',
    'Formosa',
    'Leme',
    'Cruzeiro do Sul',
    'Itumbiara',
    'Marica',
    'Ubatuba',
    'Tres Lagoas',
    'Sao Joao del Rei',
    'Mogi Mirim',
    'Abaetetuba',
    'Sao Bento do Sul',
    'Itauna',
    'Sao Mateus',
    'Jatai',
    'Sao Joao da Boa Vista',
    'Lorena',
    'Santa Cruz do Capibaribe',
    'Sao Sebastiao',
    'Tucurui',
    'Embu Guacu',
    'Sapiranga',
    'Para de Minas',
    'Campo Mourao',
    'Cachoeira do Sul',
    'Santo Antonio de Jesus',
    'Paranavai',
    'Joao Monlevade',
    'Matao',
    'Bacabal',
    'Cacapava',
    'Aruja',
    'Cruzeiro',
    'Patrocinio',
    'Tres Rios',
    'Bebedouro',
    'Sao Cristovao',
    'Alfenas',
    'Ijui',
    'Altamira',
    'Paracatu',
    'Carpina',
    'Iguatu',
    'Votuporanga',
    'Paragominas',
    'Lins',
    'Jaboticabal',
    'Vicosa',
    'Sao Sebastiao do Paraiso',
    'Balsas',
    'Itatiba',
    'Santa Ines',
    'Tubarao',
    'Pato Branco',
    'Paulinia',
    'Lajeado',
    'Cruz Alta',
    'Aquiraz',
    'Itacoatiara',
    'Gurupi',
    'Itaituba',
    'Santo Angelo',
    'Parintins',
    'Curvelo',
    'Itabaiana',
    'Cacador',
    'Ouro Preto',
    'Caldas Novas',
    'Irece',
    'Catalao',
    'Tres Coracoes',
    'Rio Largo',
    'Vilhena',
    'Valenca',
    'Peruibe',
    'Itapeva',
    'Cataguases',
    'Saquarema',
    'Tupa',
    'Fernandopolis',
    'Senador Canedo',
    'Itapira',
    'Gravata',
    'Valenca',
    'Pirassununga',
    'Unai',
    'Caratinga',
    'Itapetinga',
    'Mococa',
    'Sao Borja',
    'Carazinho',
    'Santa Rosa',
    'Telemaco Borba',
    'Guanambi',
    'Aracruz',
    'Ariquemes',
    'Farroupilha',
    'Francisco Beltrao',
    'Picos',
    'Lencois Paulista',
    'Arcoverde',
    'Braganca',
    'Vacaria',
    'Cajamar',
    'Janauba',
    'Vinhedo',
    'Formiga',
    'Cianorte',
    'Nova Vicosa',
    'Itapipoca',
    'Ponta Pora',
    'Estancia',
    'Cacoal',
    'Sao Gabriel',
    'Concordia',
    'Pacatuba',
    'Viana',
    'Sao Pedro da Aldeia',
    'Caico',
    'Seropedica'
]
