cities = [
    'Sofia',
    'Plovdiv',
    'Varna',
    'Burgas',
    'Ruse',
    'Stara Zagora',
    'Pleven',
    'Sliven',
    'Dobrich',
    'Shumen',
    'Pernik',
    'Yambol',
    'Haskovo',
    'Pazardzhik',
    'Blagoevgrad',
    'Veliko Turnovo',
    'Gabrovo',
    'Vratsa',
    'Kazanlak',
    'Vidin',
    'Asenovgrad',
    'Kardzhali',
    'Kyustendil',
    'Montana',
    'Dimitrovgrad',
    'Lovech',
    'Silistra',
    'Razgrad',
    'Targovishte',
    'Dupnitsa',
    'Gorna Oryahovitsa',
    'Svishtov',
    'Smolyan',
    'Petrich',
    'Samokov',
    'Lom',
    'Sandanski',
    'Sevlievo',
    'Nova Zagora',
    'Velingrad',
    'Cherven Bryag',
    'Troyan',
    'Aytos',
    'Botevgrad',
    'Gotse Delchev',
    'Karlovo',
    'Karnobat',
    'Panagyurishte',
    'Svilengrad',
    'Harmanli',
    'Peshtera',
    'Chirpan',
    'Parvomay',
    'Popovo',
    'Rakovski',
    'Berkovitsa',
    'Radomir',
    'Kozloduy',
    'Radnevo',
    'Ihtiman',
    'Tryavna',
    'Provadia',
    'Pomorie',
    'Byala Slatina',
    'Novi Pazar',
    'Balchik',
    'Razlog',
    'Pavlikeni',
    'Kostinbrod',
    'Stamboliyski',
    'Mezdra',
    'Levski',
    'Kavarna',
    'Elhovo',
    'Etropole',
    'Teteven',
    'Tutrakan',
    'Lukovit',
    'Belene',
    'Zlatni Pyasatsi',
    'Isperih',
    'Sredets',
    'Veliki Preslav',
    'Bansko',
    'Omurtag',
    'Kubrat',
    'Svoge',
    'Septemvri',
    'Krichim',
    'Lyaskovets',
    'Gulubovo',
    'Rakitovo',
    'Dryanovo',
    'Devnya',
    'Pirdop',
    'Lyubimets',
    'Beloslav',
    'Hisarya',
    'General Toshevo',
    'Slivnitsa',
    'Varshets',
    'Devin',
    'Simeonovgrad',
    'Elin Pelin',
    'Zlatograd',
    'Dolni Chiflik',
    'Aksakovo',
    'Knezha',
    'Tervel',
    'Dulovo',
    'Simitli',
    'Tvarditsa',
    'Topolovgrad',
    'Saedinenie',
    'Kotel',
    'Nesebar',
    'Bobov Dol',
    'Tsarevo',
    'Elena',
    'Yakoruda',
    'Straldzha',
    'Zlatitsa',
    'Strazhitsa',
    'Oryahovo',
    'Belogradchik',
    'Polski Trambesh',
    'Madan',
    'Chepelare',
    'Perushtitsa',
    'Dalgopol',
    'Krumovgrad',
    'Dolni Dabnik',
    'Valchedram',
    'Vetovo',
    'Godech',
    'Nedelino'
]
