cities = [
    'Santiago',
    'Puente Alto',
    'Antofagasta',
    'Vina del Mar',
    'Valparaiso',
    'Talcahuano',
    'San Bernardo',
    'Temuco',
    'Iquique',
    'Concepcion',
    'Rancagua',
    'La Pintana',
    'Talca',
    'Arica',
    'Coquimbo',
    'Puerto Montt',
    'La Serena',
    'Chillan',
    'Calama',
    'Osorno',
    'Valdivia',
    'Quilpue',
    'Copiapo',
    'Los Angeles',
    'Punta Arenas',
    'Lo Prado',
    'Curico',
    'Villa Alemana',
    'Coronel',
    'San Antonio',
    'Chiguayante',
    'Ovalle',
    'Linares',
    'Quillota',
    'Penaflor',
    'Melipilla',
    'San Felipe',
    'Los Andes',
    'Buin',
    'Talagante',
    'Lota',
    'Hacienda La Calera',
    'Tome',
    'Penco',
    'Coyhaique',
    'Vallenar',
    'Angol',
    'Rengo',
    'Constitucion',
    'Limache',
    'Santa Cruz',
    'Paine',
    'Villarrica',
    'San Carlos',
    'Cauquenes',
    'Curanilahue',
    'Las Animas',
    'Castro',
    'San Vicente de Tagua Tagua',
    'Lampa',
    'Molina',
    'Ancud',
    'Machali',
    'Pucon',
    'Parral',
    'La Union',
    'Puerto Varas',
    'La Ligua',
    'Arauco',
    'Victoria',
    'Tocopilla',
    'Graneros',
    'El Monte',
    'Illapel',
    'San Vicente',
    'San Javier',
    'Lebu',
    'Mulchen',
    'Quellon',
    'Lautaro',
    'Nacimiento',
    'Canete',
    'Puerto Natales',
    'Nueva Imperial',
    'Cabrero',
    'Diego de Almagro',
    'Chicureo Abajo',
    'Chimbarongo',
    'Puerto Aysen',
    'Cartagena',
    'Llaillay',
    'Laja',
    'Collipulli',
    'Panguipulli',
    'Loncoche',
    'Rio Bueno',
    'Traiguen',
    'Monte Patria',
    'Pitrufquen',
    'San Clemente',
    'Purranque',
    'Vicuna',
    'Salamanca',
    'Bulnes',
    'Chonchi',
    'Calbuco',
    'Carahue',
    'Yumbel',
    'Taltal',
    'Vilcun',
    'Rauco',
    'Quirihue',
    'Freire',
    'Coihueco',
    'Teno',
    'Longavi'
]
