cities = [
    'Zagreb',
    'Split',
    'Rijeka',
    'Osijek',
    'Zadar',
    'Slavonski Brod',
    'Pula',
    'Sesvete',
    'Karlovac',
    'Varazdin',
    'Stenjevec',
    'Sibenik',
    'Centar',
    'Sisak',
    'Velika Gorica',
    'Vinkovci',
    'Vukovar',
    'Dubrovnik',
    'Bjelovar',
    'Koprivnica',
    'Pozega',
    'Solin',
    'Zapresic',
    'GJakovo',
    'Cakovec',
    'Virovitica',
    'Samobor',
    'Kutina',
    'Metkovic',
    'Petrinja',
    'Zupanja',
    'Rovinj',
    'Makarska',
    'Nova Gradiska',
    'Krizevci',
    'Sinj',
    'Knin',
    'Slatina',
    'Trogir',
    'Brezovica',
    'Porec',
    'Daruvar',
    'Cepin',
    'Podstrana',
    'Ogulin',
    'Beli Manastir',
    'Nasice',
    'Labin',
    'Valpovo',
    'Opatija',
    'Umag',
    'Drenova',
    'Tenja',
    'Novska',
    'Belisce',
    'Crikvenica',
    'Kastel Stari',
    'Ivankovo',
    'Visnjevac',
    'Omis',
    'Kastel Novi',
    'GJurgevac',
    'Mursko Sredisce',
    'Vodice',
    'Gospic',
    'Buzet',
    'Ilok',
    'Otok',
    'Pitomaca',
    'Senj',
    'Ivanec',
    'Jastrebarsko',
    'Kastel Luksic',
    'Darda',
    'Biograd na Moru',
    'Novi Vinodolski',
    'Gunja',
    'Borovo',
    'Kastel Kambelovac',
    'Pazin',
    'Krapina'
]
