cities = [
    'Guayaquil',
    'Quito',
    'Cuenca',
    'Santo Domingo de los Colorados',
    'Machala',
    'Manta',
    'Portoviejo',
    'Eloy Alfaro',
    'Esmeraldas',
    'Ambato',
    'Tutamandahostel',
    'Milagro',
    'Ibarra',
    'Riobamba',
    'Quevedo',
    'Loja',
    'Tulcan',
    'Babahoyo',
    'La Libertad',
    'Latacunga',
    'Velasco Ibarra',
    'Puerto Francisco de Orellana',
    'Ventanas',
    'Pasaje',
    'Chone',
    'Salinas',
    'Santa Elena',
    'Rosa Zarate',
    'Santa Rosa',
    'Balzar',
    'Huaquillas',
    'Bahia de Caraquez',
    'La Troncal',
    'Jipijapa',
    'Azogues',
    'Naranjito',
    'Vinces',
    'Otavalo',
    'El Triunfo',
    'Naranjal',
    'Playas',
    'Yaguachi Nuevo',
    'Cayambe',
    'Machachi',
    'Puyo',
    'Nueva Loja',
    'Samborondon',
    'Macas',
    'Pedro Carbo',
    'Guaranda',
    'Boca Suno',
    'San Lorenzo de Esmeraldas',
    'Catamayo',
    'Montecristi',
    'Atuntaqui',
    'Calceta',
    'Tena',
    'Gualaceo',
    'Pinas',
    'Cariamanga',
    'Pelileo',
    'La Mana',
    'Pujili',
    'Montalvo',
    'Sucre',
    'Zamora',
    'San Gabriel',
    'Tosagua',
    'Alausi',
    'Muisne',
    'Macara',
    'Santa Ana',
    'Guano',
    'Alfredo Baquerizo Moreno',
    'San Miguel',
    'Santa Lucia',
    'Zaruma',
    'Balao',
    'Valdez',
    'Catacocha',
    'San Miguel de Salcedo',
    'Rocafuerte',
    'Yantzaza',
    'Canar',
    'Catarama',
    'Portovelo',
    'Banos',
    'Colimes',
    'Palestina',
    'Pajan',
    'Junin',
    'Palenque',
    'Puerto Ayora',
    'Puerto Bolivar',
    'Cotacachi',
    'Lomas de Sargentillo',
    'Pillaro',
    'Sucua',
    'Pimampiro',
    'Archidona',
    'Coronel Marcelino Mariduena',
    'Palora',
    'Pedernales',
    'Celica',
    'Sangolqui',
    'Puerto Baquerizo Moreno'
]
