cities = [
    'Athens',
    'Thessaloniki',
    'Patra',
    'Piraeus',
    'Larisa',
    'Peristeri',
    'Irakleion',
    'Kallithea',
    'Acharnes',
    'Kalamaria',
    'Nikaia',
    'Glyfada',
    'Volos',
    'Ilion',
    'Ilioupoli',
    'Keratsini',
    'Khalandrion',
    'Nea Smyrni',
    'Marousi',
    'Agios Dimitrios',
    'Zografos',
    'Aigaleo',
    'Nea Ionia',
    'Ioannina',
    'Palaio Faliro',
    'Korydallos',
    'Trikala',
    'Vyronas',
    'Agia Paraskevi',
    'Galatsi',
    'Chalkida',
    'Petroupolis',
    'Serres',
    'Rodos',
    'Kalamata',
    'Kavala',
    'Chania',
    'Katerini',
    'Alexandroupoli',
    'Lamia',
    'Irakleio',
    'Xanthi',
    'Kifisia',
    'Agrinio',
    'Chaidari',
    'Komotini',
    'Sykies',
    'Drama',
    'Veroia',
    'Alimos',
    'Polichni',
    'Kozani',
    'Agioi Anargyroi',
    'Argyroupoli',
    'Ano Liosia',
    'Karditsa',
    'Nea Ionia',
    'Rethymno',
    'Cholargos',
    'Vrilissia',
    'Aspropyrgos',
    'Korinthos',
    'Ptolemaida',
    'Gerakas',
    'Metamorfosi',
    'Voula',
    'Kamateron',
    'Mytilene',
    'Giannitsa',
    'Neapoli',
    'Corfu',
    'Tripoli',
    'Agia Varvara',
    'Kaisariani',
    'Nea Filadelfeia',
    'Moskhaton',
    'Perama',
    'Salamina',
    'Elefsina',
    'Chios',
    'Pylaia',
    'Megara',
    'Dhafni',
    'Melissia',
    'Pyrgos',
    'Argos',
    'Thivai',
    'Arta',
    'Livadeia',
    'Artemida',
    'Pefki',
    'Aigio',
    'Naousa',
    'Kilkis',
    'Kos',
    'Koropi',
    'Edessa',
    'Florina',
    'Nea Erythraia',
    'Preveza',
    'Elliniko',
    'Amaliada',
    'Panorama',
    'Sparti',
    'Orestiada',
    'Peraia',
    'Agios Ioannis Rentis',
    'Vari',
    'Menemeni',
    'Nea Makri',
    'Oraiokastro',
    'Tavros',
    'Pallini',
    'Paiania',
    'Nafplio',
    'Kalyvia Thorikou',
    'Thermi',
    'Drapetsona',
    'Papagou',
    'Alexandreia',
    'Nafpaktos',
    'Kastoria',
    'Mesolongi',
    'Gazi',
    'Ierapetra',
    'Kalymnos',
    'Rafina',
    'Nea Alikarnassos',
    'Loutraki',
    'Zakynthos',
    'Ialysos',
    'Agios Nikolaos',
    'Ermoupolis',
    'Mandra',
    'Triandria',
    'Ymittos',
    'Tyrnavos',
    'Grevena',
    'Farsala',
    'Diavata',
    'Neo Psychiko',
    'Polygyros',
    'Agios Stefanos',
    'Nea Chalkidona',
    'Argostolion',
    'Kiato',
    'Anatoli',
    'Limin Mesoyaias',
    'Lykovrysi',
    'Psychiko',
    'Markopoulo',
    'Igoumenitsa',
    'Nea Artaki',
    'Zefyri',
    'Nea Moudhania',
    'Spata',
    'Chrysoupolis',
    'Sitia',
    'Lefkada',
    'Didymoteicho',
    'Nea Peramos',
    'Koufalia',
    'Sindos',
    'Kalampaka',
    'Epanomi',
    'Gastouni',
    'Almyros',
    'Nea Michaniona',
    'Giannouli',
    'Keratea',
    'Argos Orestiko',
    'Chalastra',
    'Filothei',
    'Nea Kallikrateia',
    'Trilofos',
    'Agios Pavlos',
    'Lagkadas',
    'Nea Penteli',
    'Drosia',
    'Marathonas',
    'Lavrio',
    'Naxos',
    'Elassona',
    'Filiatra',
    'Polykastro',
    'Karpenisi',
    'Aegina',
    'Amfissa',
    'Krya Vrysi',
    'Messini',
    'Souda',
    'Litochoro',
    'Neon Karlovasion',
    'Vasilikon',
    'Aridaia',
    'Ayios Konstandinos',
    'Anoixi',
    'Asvestochori',
    'Moires',
    'Paralia',
    'Gargalianoi',
    'Anavyssos',
    'Thrakomakedones',
    'Faliraki',
    'Ampelona',
    'Leondarion',
    'Orchomenos',
    'Nea Anchialos',
    'Zacharo',
    'Ekali',
    'Ovria',
    'Psachna',
    'Kato Achaia',
    'Avlonas',
    'Palamas',
    'Dionysos',
    'Siatista',
    'Afantou',
    'Agria',
    'Xylokastro',
    'Myrina',
    'Feres',
    'Archangelos',
    'Plagiari',
    'Vrontados',
    'Mournies',
    'Paros',
    'Tympaki',
    'Megalopoli',
    'Skiathos',
    'Aliveri',
    'Sidirokastro',
    'Karystos',
    'Neoi Epivates',
    'Kryoneri',
    'Kyparissia',
    'Dhrosia',
    'Karyes'
]
