cities = [
    'Dublin',
    'Cork',
    'Dun Laoghaire',
    'Luimneach',
    'Gaillimh',
    'Tallaght',
    'Waterford',
    'Swords',
    'Drogheda',
    'Dundalk',
    'Navan',
    'Ennis',
    'Balbriggan',
    'Tralee',
    'Sandyford',
    'Kilkenny',
    'Naas',
    'Sligo',
    'Carlow',
    'Loch Garman',
    'Finglas',
    'Celbridge',
    'Droichead Nua',
    'Cluain Meala',
    'An Muileann gCearr',
    'Letterkenny',
    'Blanchardstown',
    'Athlone',
    'Malahide',
    'Leixlip',
    'Donaghmede',
    'Lucan',
    'Kilquade',
    'Carrigaline',
    'Knocklyon',
    'Clondalkin',
    'Wicklow',
    'Portlaoise',
    'Greystones',
    'Castlebar',
    'Foxrock',
    'Athy',
    'Maynooth',
    'Dundrum',
    'Arklow',
    'Tullamore',
    'Ashbourne',
    'Crumlin',
    'Rathmines',
    'Marino',
    'Laytown',
    'Jobstown',
    'Donnybrook',
    'Cobh',
    'Shankill',
    'Ballina',
    'Cabinteely',
    'Derry',
    'Oldbawn',
    'Enniscorthy',
    'Shannon',
    'Skerries',
    'Ballyboden',
    'Mallow',
    'Portmarnock',
    'An Ros',
    'Tra Mhor',
    'Balally',
    'Ratoath',
    'Sandymount',
    'Midleton',
    'Blackrock',
    'Beaumont',
    'Ballyfermot',
    'Ballinteer',
    'Rathgar',
    'Castleknock',
    'Ringsend',
    'Kildare',
    'Baldoyle',
    'Little Bray',
    'Cherry Orchard',
    'Mount Merrion',
    'Portarlington',
    'Longford',
    'Terenure',
    'Donnycarney',
    'Thurles',
    'Dungarvan',
    'Cill Airne',
    'Palmerstown',
    'Raheny',
    'Booterstown',
    'Templeogue',
    'Lusk',
    'Dunboyne',
    'Sallynoggin',
    'Greenhills',
    'Youghal',
    'Firhouse',
    'Newtown Trim',
    'Donabate',
    'Clane',
    'New Ross',
    'Nenagh Bridge',
    'Dalkey',
    'Bray',
    'Ballinasloe',
    'Cavan',
    'Cherryville',
    'Newcastle West',
    'Ballymun',
    'Westport',
    'Tuam',
    'Gorey',
    'Monaghan',
    'Hartstown',
    'Kinsealy-Drinan',
    'Carrick-on-Suir',
    'Roscommon',
    'Darndale',
    'Monkstown',
    'Buncrana',
    'Kilcock',
    'Nenagh',
    'Bandon',
    'Roscrea',
    'Confey',
    'Eadestown',
    'Artane',
    'Chapelizod',
    'Sallins',
    'Killester',
    'Dollymount',
    'Loughrea',
    'Blessington'
]
