cities = [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Palermo',
    'Genoa',
    'Bologna',
    'Florence',
    'Catania',
    'Bari',
    'Messina',
    'Verona',
    'Padova',
    'Trieste',
    'Brescia',
    'Prato',
    'Taranto',
    'Reggio Calabria',
    'Modena',
    'Livorno',
    'Cagliari',
    'Mestre',
    'Parma',
    'Foggia',
    "Reggio nell'Emilia",
    'Acilia-Castel Fusano-Ostia Antica',
    'Salerno',
    'Perugia',
    'Monza',
    'Rimini',
    'Pescara',
    'Bergamo',
    'Vicenza',
    'Bolzano',
    'Andria',
    'Udine',
    'Siracusa',
    'Terni',
    'Forli',
    'Novara',
    'Barletta',
    'Piacenza',
    'Ferrara',
    'Sassari',
    'Ancona',
    'La Spezia',
    'Torre del Greco',
    'Como',
    'Lucca',
    'Ravenna',
    'Lecce',
    'Trento',
    'Giugliano in Campania',
    'Busto Arsizio',
    'Lido di Ostia',
    'Cesena',
    'Catanzaro',
    'Brindisi',
    'Marsala',
    'Treviso',
    'Pesaro',
    'Pisa',
    'Varese',
    'Sesto San Giovanni',
    'Arezzo',
    'Latina',
    'Gela',
    'Pistoia',
    'Caserta',
    'Cinisello Balsamo',
    'Lamezia Terme',
    'Altamura',
    'Guidonia Montecelio',
    "Quartu Sant'Elena",
    'Pavia',
    'Castellammare di Stabia',
    'Massa',
    'Alessandria',
    'Cosenza',
    'Afragola',
    'Ragusa',
    'Asti',
    'Grosseto',
    'Cremona',
    'Molfetta',
    'Trapani',
    'Carrara',
    'Casoria',
    'Savona',
    'Vigevano',
    'Legnano',
    'Caltanissetta',
    'Potenza',
    'Portici',
    'Matera',
    'San Severo',
    'Cerignola',
    'Trani',
    'Bisceglie',
    'Acerra',
    'Ercolano',
    'Carpi Centro',
    'Imola',
    'Bagheria',
    'Manfredonia',
    'Aversa',
    'Bitonto',
    'Venice',
    'Vittoria',
    'Gallarate',
    'Marano di Napoli',
    'Pordenone',
    'Acireale',
    'Scafati',
    'Moncalieri',
    'Viareggio',
    'Benevento',
    'Crotone',
    'Velletri',
    'Cava De Tirreni',
    'Avellino',
    'Foligno',
    'Nichelino',
    'Civitavecchia',
    'Viterbo',
    'Battipaglia',
    'Rho',
    'San Remo',
    'Lecco',
    'Collegno',
    'Corato',
    'Cuneo',
    'Paderno Dugnano',
    'Rivoli',
    'Paterno',
    'Montesilvano Marina',
    'Mazara del Vallo',
    'San Benedetto del Tronto',
    'Casalnuovo di Napoli',
    'Cologno Monzese',
    'Sesto Fiorentino',
    'Vercelli',
    'Pozzuoli',
    'Misterbianco',
    'San Giorgio a Cremano',
    'Anzio',
    'Nocera Inferiore',
    'Scandicci',
    'Nettuno',
    'Frosinone',
    'Chieti',
    'Alcamo',
    'Settimo Torinese',
    'Torre Annunziata',
    'Biella',
    'Olbia',
    'Siena',
    'Seregno',
    'Gravina in Puglia',
    'Chioggia',
    'Ascoli Piceno',
    'Faenza',
    'Civitanova Marche',
    'Modica',
    'Capannori',
    'Aprilia',
    'Lodi',
    'Cascina',
    'Desio',
    'Marcianise',
    'Nicastro',
    'Rozzano',
    'Campobasso',
    'Rovigo',
    'Mantova',
    'Rieti',
    'Fano',
    "Pomigliano d'Arco",
    'Imperia',
    'Bassano del Grappa',
    'Saronno',
    'Marino',
    'Avezzano',
    'Monopoli',
    'Martina Franca',
    'Quarto',
    'Lissone',
    'Cantu',
    'Monterotondo',
    'Cesano Maderno',
    'Jesi',
    'Melito di Napoli',
    'Sassuolo',
    'Sciacca',
    'Licata',
    'Modugno',
    'Teramo',
    'Voghera',
    'Nuoro',
    'Caltagirone',
    'Bollate',
    'Ciampino',
    'Carini',
    'Arzano',
    'Gorizia',
    'Caivano',
    'Barcellona Pozzo di Gotto',
    'Fiumicino-Isola Sacra',
    'Maddaloni',
    'Adrano',
    'Empoli',
    'Alghero',
    'Mugnano di Napoli',
    'Ladispoli',
    'Pioltello',
    'Rovereto',
    'Casalecchio di Reno',
    'Schio',
    "L'Aquila",
    'Corsico',
    "Sant'Antimo",
    'Venaria Reale',
    'Merano',
    'Francavilla Fontana',
    'Grugliasco',
    'Brugherio',
    'Canicatti',
    'Mira Taglio',
    'Campi Bisenzio',
    'Pagani',
    'San Dona di Piave',
    'Riccione',
    'Casal Palocco',
    'Agrigento',
    'Somma Vesuviana',
    'Aosta',
    'Lucera',
    'Chieri',
    'Favara',
    'Limbiate',
    'Milazzo',
    'Santa Maria Capua Vetere',
    'Angri',
    'Crema',
    'Grottaglie',
    'Casale Monferrato',
    'Verbania',
    'San Giuliano Milanese',
    'Termoli',
    'Terracina',
    'Senigallia',
    'Massafra',
    'Pinerolo',
    'Macerata',
    'Conegliano',
    'Augusta',
    'Lanciano',
    'Abbiategrasso',
    'Vasto',
    'Piombino',
    'Canosa di Puglia',
    'Mascalucia',
    'Marigliano',
    'Frattamaggiore',
    'San Paolo',
    'Nardo',
    'Monterusciello',
    'Gragnano',
    'Cernusco sul Naviglio',
    'Pallanza-Intra-Suna',
    'Sarno',
    'Partinico',
    'Avola',
    'Formia',
    'San Donato Milanese',
    'Segrate',
    'Castelvetrano',
    'Manduria',
    'Cisterna di Latina',
    'Rapallo',
    'Niscemi',
    'San Giuseppe Vesuviano',
    'Boscoreale',
    'Triggiano',
    'Camaiore',
    'Monfalcone',
    'Albano Laziale',
    'Montebelluna',
    'Fondi',
    'Chiavari',
    'Gravina di Catania',
    'Mesagne',
    'San Miniato Basso',
    'Parabiago',
    'Formigine',
    'Comiso',
    'Eboli',
    'San Giovanni Rotondo',
    'Romano Banco',
    'Mondragone',
    'Garbagnate Milanese',
    'Novi Ligure',
    'Falconara Marittima',
    'Terlizzi',
    'Bresso',
    'Bacoli',
    'Castelfranco Veneto',
    'Assemini',
    'Villaricca',
    'Belluno',
    'Lainate',
    'Marina di Carrara',
    'Treviglio',
    'Alba',
    'Santeramo in Colle',
    'Vittorio Veneto',
    'Orta di Atella',
    'Mola di Bari',
    'Bagnoli',
    'Aci Catena',
    'Oristano',
    'Giussano',
    'Gioia del Colle',
    'Ostuni',
    'Giarre',
    'Lentini',
    'Nola',
    'Bra',
    'Ruvo di Puglia',
    'Pompei',
    'Casa Santa',
    'Rossano Stazione',
    'Sora',
    'Qualiano',
    'Lumezzane',
    'Spinea-Orgnano',
    'Putignano',
    'Seriate',
    'Copertino',
    'Nocera Superiore',
    'Ottaviano',
    'Cesano Boscone',
    'Selargius',
    'Ivrea',
    'Fabriano',
    'San Sebastiano',
    'Muggio',
    'Biancavilla',
    'Chivasso',
    'Carmagnola',
    'Enna',
    'Termini Imerese',
    'Volla',
    'Quattromiglia',
    'Dalmine',
    'Tortona',
    'Seveso',
    'Vimercate',
    'Desenzano del Garda',
    'Meda',
    'Conversano',
    'Iglesias',
    'Palma di Montechiaro',
    'Mariano Comense',
    'Fasano',
    'Magenta',
    'Valdagno',
    'Citta di Castello',
    'Vignola',
    'San Lazzaro',
    'Pomezia',
    'Nova Milanese',
    'Cardito',
    "Porto Sant'Elpidio",
    'Floridia',
    'San Cataldo',
    'San Giovanni la Punta',
    'Cecina',
    'Tivoli',
    'Mogliano Veneto',
    'Noicattaro',
    'Monreale',
    'Fidenza',
    'Castel Volturno',
    'Mondovi',
    'Orbassano',
    'Poggibonsi',
    'Carbonia',
    'Porto Torres',
    'Legnago',
    'Lugo',
    'Arzignano',
    'Cassano Magnago',
    'Follonica',
    'San Nicola la Strada',
    'Thiene',
    'Francavilla al Mare',
    'Sulmona',
    'Cassino',
    'Guidonia'
]
