cities = [
    'Mexico City',
    'Iztapalapa',
    'Ecatepec de Morelos',
    'Guadalajara',
    'Puebla',
    'Juarez',
    'Tijuana',
    'Leon de los Aldama',
    'Gustavo Adolfo Madero',
    'Zapopan',
    'Monterrey',
    'Ciudad Nezahualcoyotl',
    'Chihuahua',
    'Naucalpan de Juarez',
    'Merida',
    'Alvaro Obregon',
    'San Luis Potosi',
    'Aguascalientes',
    'Hermosillo',
    'Saltillo',
    'Mexicali',
    'Culiacan',
    'Guadalupe',
    'Acapulco de Juarez',
    'Tlalnepantla',
    'Cancun',
    'Santiago de Queretaro',
    'Coyoacan',
    'Santa Maria Chimalhuacan',
    'Torreon',
    'Morelia',
    'Reynosa',
    'Tlaquepaque',
    'Tlalpan',
    'Tuxtla',
    'Cuauhtemoc',
    'Victoria de Durango',
    'Toluca',
    'Ciudad Lopez Mateos',
    'Cuautitlan Izcalli',
    'Ciudad Apodaca',
    'Heroica Matamoros',
    'San Nicolas de los Garza',
    'Venustiano Carranza',
    'Veracruz',
    'Xalapa de Enriquez',
    'Azcapotzalco',
    'Tonala',
    'Xochimilco',
    'Benito Juarez',
    'Iztacalco',
    'Mazatlan',
    'Irapuato',
    'Nuevo Laredo',
    'Miguel Hidalgo',
    'Xico',
    'Benito Juarez',
    'Villahermosa',
    'Ciudad General Escobedo',
    'Celaya',
    'Cuernavaca',
    'Tepic',
    'Ixtapaluca',
    'Tampico',
    'Ciudad Victoria',
    'Tlahuac',
    'Ciudad Obregon',
    'Nicolas Romero',
    'Ensenada',
    'Coacalco',
    'Santa Catarina',
    'Uruapan',
    'Gomez Palacio',
    'Los Mochis',
    'Pachuca de Soto',
    'Oaxaca',
    'Soledad de Graciano Sanchez',
    'Colonia del Valle',
    'Tehuacan',
    'Ojo de Agua',
    'Magdalena Contreras',
    'Coatzacoalcos',
    'Campeche',
    'Monclova',
    'La Paz',
    'Nogales',
    'Buenavista',
    'Puerto Vallarta',
    'Tapachula',
    'Ciudad Madero',
    'Chilpancingo',
    'Poza Rica de Hidalgo',
    'Chicoloapan',
    'Ciudad del Carmen',
    'Chalco',
    'Jiutepec',
    'Delegacion Cuajimalpa de Morelos',
    'Salamanca',
    'San Luis Rio Colorado',
    'San Cristobal de las Casas',
    'San Pablo de las Salinas',
    'Cuautla',
    'Ciudad Benito Juarez',
    'Chetumal',
    'Piedras Negras',
    'Playa del Carmen',
    'Zamora',
    'Cordoba',
    'San Juan del Rio',
    'Colima',
    'Ciudad Acuna',
    'Manzanillo',
    'Zacatecas',
    'Huixquilucan',
    'Ciudad Valles',
    'Guadalupe',
    'San Pedro Garza Garcia',
    'San Pedro Garza Garcia',
    'Fresnillo',
    'Orizaba',
    'Miramar',
    'Iguala de la Independencia',
    'Ciudad Delicias',
    'Ciudad de Villa de Alvarez',
    'Cuauhtemoc',
    'Navojoa',
    'Heroica Guaymas',
    'Minatitlan',
    'Cuautitlan',
    'Texcoco de Mora',
    'Parral',
    'Tepexpan',
    'Tulancingo',
    'Tuxtepec',
    'Colonia Lindavista',
    'Apatzingan',
    'Lagos de Moreno',
    'Temixco',
    'Ciudad Guzman',
    'Comitan',
    'Ciudad Rio Bravo',
    'Garcia',
    'Tepatitlan de Morelos',
    'Cardenas',
    'Cholula',
    'Hacienda Santa Fe',
    'Atlixco',
    'Tecoman',
    'Los Reyes Acaquilpan',
    'Ciudad Mante',
    'Tuxpam de Rodriguez Cano',
    'Tlaxcala',
    'Heroica Zitacuaro',
    'Ocotlan',
    'La Piedad',
    'Ciudad Lerdo',
    'Ciudad Lazaro Cardenas',
    'Matehuala',
    'Agua Prieta',
    'Kanasin',
    'Cozumel',
    'Amozoc de Mota',
    'Salina Cruz',
    'San Martin Texmelucan de Labastida',
    'Juchitan de Zaragoza',
    'Silao',
    'Fuentes del Valle',
    'Guanajuato',
    'El Pueblito',
    'Guasave',
    'San Francisco del Rincon',
    'San Miguel de Allende',
    'San Jose del Cabo',
    'Frontera',
    'Cabo San Lucas',
    'Cadereyta Jimenez',
    'Valle de Santiago',
    'Cadereyta',
    'San Mateo Atenco',
    'Zihuatanejo',
    'Santa Cruz Xoxocotlan',
    'Ramos Arizpe',
    'Tultepec',
    'Rosarito',
    'Tecate',
    'Sahuayo de Morelos',
    'Guamuchil',
    'Linares',
    'Tesistan',
    'San Andres Tuxtla',
    'Cortazar',
    'San Salvador Tizatlalli',
    'Ciudad Hidalgo',
    'Martinez de la Torre',
    'Villa Vicente Guerrero',
    'Colonia Nativitas',
    'Heroica Caborca',
    'Altamira',
    'Dolores Hidalgo Cuna de la Independencia Nacional',
    'Teziutlan',
    'Acambaro',
    'Jacona de Plancarte',
    'Puerto Penasco',
    'Huauchinango',
    'Nuevo Casas Grandes',
    'Patzcuaro',
    'Sabinas',
    'San Bernardino Tlaxcalancingo',
    'Zinacantepec',
    'Jardines de la Silla',
    'Santiago Teyahualco',
    'Coatepec',
    'Papantla de Olarte',
    'Rioverde',
    'Ciudad de Huajuapan de Leon',
    'Zacapu',
    'Matamoros',
    'Taxco de Alarcon',
    'Arandas',
    'Huamantla',
    'Uriangato',
    'Teoloyucan',
    'Acayucan',
    'Zumpango',
    'Zacapu',
    'Polanco',
    'San Luis de la Paz',
    'Apizaco',
    'Emiliano Zapata',
    'Valladolid',
    'Valle Hermoso',
    'San Pedro',
    'San Juan de los Lagos',
    'Colonia del Sol',
    'Santa Ana Chiautempan',
    'Tierra Blanca',
    'Tlapa de Comonfort',
    'Tizimin',
    'Autlan de Navarro',
    'Mazatlan',
    'Chiapa de Corzo',
    'San Buenaventura',
    'Purisima de Bustos',
    'Tizayuca',
    'Moroleon',
    'Jerez de Garcia Salinas',
    'Jesus Maria',
    'Palenque',
    'Izucar de Matamoros',
    'Yautepec',
    'Las Choapas',
    'Empalme',
    'Cintalapa de Figueroa',
    'Juventino Rosas',
    'Santo Domingo Tehuantepec',
    'Ocosingo',
    'Comalcalco',
    'San Pedro',
    'Ciudad Constitucion',
    'Panuco',
    'Rio Blanco',
    'Camargo',
    'Penjamo',
    'Huejutla de Reyes',
    'San Andres Cholula',
    'Xicotepec de Juarez',
    'Uman',
    'Los Reyes de Salgado',
    'Ocozocoautla de Espinosa',
    'Esperanza',
    'Melchor Ocampo',
    'Zacatelco',
    'Nueva Rosita',
    'Tepotzotlan',
    'Guacamayas',
    'Perote',
    'Progreso',
    'Villaflores',
    'Salvatierra',
    'Santa Teresa',
    'Santiago',
    'San Jeronimo Cuatro Vientos',
    'Ameca',
    'Agua Dulce',
    'Xalisco',
    'Coyotepec',
    'Ciudad Mendoza',
    'Tala',
    'San Martin Azcatepec',
    'Tlapacoyan',
    'Tonala',
    'La Barca',
    'San Pablo Autopan',
    'Ciudad Melchor Muzquiz',
    'Ixmiquilpan',
    'Fraccionamiento Real Palmas',
    'San Miguel Topilejo',
    'Maravatio de Ocampo',
    'Jose Mariano Jimenez',
    'Porticos de San Antonio',
    'Tepeji del Rio de Ocampo',
    'Coatzintla',
    'Parras de la Fuente',
    'San Isidro',
    'Zacatlan',
    'Calpulalpan',
    'Ciudad Sabinas Hidalgo',
    'Rio Grande',
    'Ticul',
    'Jaltipan de Morelos',
    'Victor Rosales',
    'Tenosique',
    'Nueva Italia de Ruiz',
    'Zapotlanejo',
    'Macuspana',
    'Centro Familiar la Soledad',
    'Huixtla',
    'Ciudad Fernandez',
    'Amecameca',
    'Cananea',
    'Loma Bonita',
    'Huatusco',
    'San Jose Guadalupe Otzacatipan',
    'Chilapa de Alvarez',
    'Jimenez',
    'Champoton',
    'Miguel Aleman',
    'Escuinapa',
    'Tantoyuca',
    'Cosamaloapan',
    'Puruandiro',
    'Huatabampo',
    'Nicolas R Casillas',
    'Tlajomulco de Zuniga',
    'Tequisquiapan',
    'San Miguel Ajusco',
    'Coyula',
    'Pinotepa Nacional',
    'Escarcega',
    'Marfil',
    'Santa Isabel',
    'Actopan',
    'Tequila',
    'San Fernando',
    'Navolato',
    'Ixtapa',
    'Tecamachalco',
    'Pabellon de Arteaga',
    'Tula de Allende',
    'Ciudad Sahagun',
    'San Felipe',
    'Metepec',
    'San Sebastian el Grande',
    'Nuevo Mexico',
    'Berriozabal',
    'Ajalpan',
    'Tultitlan de Mariano Escobedo',
    'Apaseo el Alto',
    'Rincon de Romos',
    'San Francisco Acuautla',
    'Sanctorum',
    'Catemaco',
    'Contla',
    'Leyva Solano',
    'Tuxpan',
    'Tepeaca',
    'Abasolo',
    'Huimanguillo',
    'Moyotzingo',
    'Villagran',
    'Atotonilco el Alto',
    'Rancho La Gloria',
    'Misantla',
    'Sayula',
    'Apan',
    'Francisco I. Madero',
    'Magdalena de Kino',
    'Teapa',
    'Las Pintitas',
    'Rio de Teapa',
    'Magdalena Atlicpac',
    'Isla',
    'San Jeronimo Chicahualco',
    'Reforma',
    'Ixtaczoquitlan',
    'Apaseo el Grande',
    'Santiago Papasquiaro',
    'Ciudad de Allende',
    'Ocoyoacac',
    'Puerto Escondido',
    'Acatzingo',
    'Tecax',
    'Felipe Carrillo Puerto',
    'Valente Diaz',
    'Huejotzingo',
    'Tacambaro de Codallos',
    'Tejupilco de Hidalgo',
    'Valle de Bravo',
    'Mixquiahuala de Juarez',
    'Ixtepec'
]
