cities = [
    'Auckland',
    'Wellington',
    'Christchurch',
    'Manukau City',
    'Waitakere',
    'North Shore',
    'Hamilton',
    'Dunedin',
    'Tauranga',
    'Lower Hutt',
    'Palmerston North',
    'Rotorua',
    'Hastings',
    'Nelson',
    'Napier',
    'Mangere',
    'Porirua',
    'Whangarei',
    'New Plymouth',
    'Invercargill',
    'Wanganui',
    'Upper Hutt',
    'Gisborne',
    'Ashburton',
    'Papakura',
    'Timaru',
    'Blenheim',
    'Paraparaumu',
    'Taupo',
    'Pukekohe East',
    'Masterton',
    'Levin',
    'Whakatane',
    'Taradale',
    'Cambridge',
    'Tokoroa',
    'Richmond',
    'Oamaru',
    'Gore',
    'Hawera',
    'Takanini',
    'Queenstown',
    'Kaiapoi',
    'Greymouth',
    'Pakuranga',
    'Khandallah',
    'Waiuku',
    'Motueka',
    'Thames',
    'Kawerau',
    'Petone',
    'Papatowai',
    'Waitara',
    'Matamata',
    'Otaki',
    'Kerikeri',
    'Ngaruawahia',
    'Waitangi',
    'Linton Military Camp'
]
