cities = [
    'Lima',
    'Arequipa',
    'Callao',
    'Trujillo',
    'Chiclayo',
    'Iquitos',
    'Huancayo',
    'Piura',
    'Chimbote',
    'Cusco',
    'Pucallpa',
    'Tacna',
    'Santiago de Surco',
    'Ica',
    'Juliaca',
    'Sullana',
    'Chincha Alta',
    'Huanuco',
    'Ayacucho',
    'Cajamarca',
    'Puno',
    'Tumbes',
    'Talara',
    'Chosica',
    'Huaraz',
    'Cerro de Pasco',
    'Chulucanas',
    'San Isidro',
    'Huaral',
    'Pisco',
    'Catacaos',
    'Paita',
    'Abancay',
    'Huacho',
    'Moquegua',
    'Ilo',
    'Tingo Maria',
    'Jaen',
    'Tarma',
    'Barranca',
    'Moyobamba',
    'Lambayeque',
    'Picsi',
    'Chepen',
    'Yurimaguas',
    'Huancavelica',
    'Sana',
    'Tambopata',
    'Juanjui',
    'Puerto Maldonado',
    'La Union',
    'Ferrenafe',
    'Sicuani',
    'La Oroya',
    'Chocope',
    'Imperial',
    'Nuevo Imperial',
    'Tambo Grande',
    'La Rinconada',
    'Pacasmayo',
    'Tocache',
    'Mollendo',
    'Chaupimarca',
    'Paramonga',
    'La Peca',
    'Chancay',
    'Hualmay',
    'Monsefu',
    'Marcavelica',
    'San Vicente de Canete',
    'Querecotillo',
    'Guadalupe',
    'Santa Ana',
    'Rioja',
    'Laredo',
    'Nazca',
    'Yanacancha',
    'Sechura',
    'Moche',
    'Santiago de Cao',
    'Huamachuco',
    'Paijan',
    'Jauja',
    'Viru',
    'Huaura',
    'Bagua Grande',
    'Chachapoyas',
    'Ayaviri',
    'Huanta',
    'Uchiza',
    'La Breita',
    'Andahuaylas',
    'Mala',
    'Zarumilla',
    'Camana',
    'San Pedro de Lloc',
    'Huarmey',
    'Yunguyo',
    'Chongoyape',
    'Ilave',
    'San Clemente',
    'Pimentel',
    'Satipo',
    'Minas de Marcona',
    'Junin',
    'Bellavista',
    'Coishco',
    'Chicama',
    'Saposoa',
    'Santa Maria',
    'Tabalosos',
    'San Ramon',
    'Celendin',
    'Chota',
    'Salinera Colan',
    'Puerto Santa',
    'Ascope',
    'Contamana',
    'Supe',
    'Eten',
    'Lamas',
    'Motupe',
    'Pativilca',
    'Cajabamba',
    'Bambamarca',
    'Azangaro',
    'Vice',
    'Chilca',
    'Atuncolla',
    'Pueblo Nuevo',
    'Morropon',
    'Zorritos',
    'Oxapampa',
    'Puerto Supe',
    'Concepcion',
    'Villa Tupac Amaru',
    'Caras',
    'Soritor',
    'Santa Rosa',
    'Puquio',
    'Santiago',
    'Otuzco',
    'Salaverry',
    'Chupaca',
    'Reque',
    'Olmos',
    'Ilabaya',
    'Sisa',
    'Las Lomas',
    'El Alto',
    'Quiruvilca',
    'Lagunas',
    'Calca',
    'Carhuamayo',
    'Aguas Verdes',
    'Mancora',
    'Subtanjalla',
    'Yauya',
    'Campoverde',
    'San Luis',
    'Cocachacra',
    'San Jeronimo',
    'Pacanga',
    'Huancabamba',
    'La Huaca',
    'San Miguel',
    'Pilcomay',
    'Putina',
    'Chazuta',
    'Buenos Aires',
    'San Ignacio',
    'Morococha',
    'Los Aquijes',
    'Hacienda Huancane',
    'Pacocha',
    'Urubamba',
    'Mochumi',
    'Villa Rica',
    'San Jose',
    'Coracora',
    'Talavera',
    'Juli',
    'Cajaruro',
    'Jepelacio',
    'Torata',
    'Tucume',
    'San Juan Bautista',
    'Ambo',
    'Perene',
    'Sicaya',
    'Mazamari',
    'Acolla',
    'Santiago de Chuco',
    'Huicungo',
    'Picota',
    'Morrope',
    'Pangoa',
    'Quilmana',
    'Punta de Bombon',
    'Oyotun',
    'Bellavista',
    'Oyon',
    'Vegueta',
    'Sayan',
    'Jayanca',
    'Macusani',
    'Lluta',
    'San Agustin',
    'Yanahuanca',
    'Bernal',
    'Palpa',
    'Anta',
    'Huayucachi',
    'Asentamiento Humano Nicolas de Pierola',
    'Barranca',
    'Pueblo Nuevo',
    'San Pedro de Cajas',
    'San Bartolo',
    'Yura',
    'Orcopampa',
    'San Jeronimo',
    'Pampas',
    'Caleta de Carquin',
    'Ramon Castilla',
    'Papayal',
    'Urcos',
    'Salitral',
    'Desaguadero',
    'San Miguel de Cauri',
    'Ayabaca',
    'Yungay',
    'Huasahuasi',
    'Tinyahuarco',
    'Carhuaz',
    'Tambo'
]
