cities = [
    'Lisbon',
    'Porto',
    'Amadora',
    'Braga',
    'Setubal',
    'Coimbra',
    'Queluz',
    'Funchal',
    'Cacem',
    'Vila Nova de Gaia',
    'Algueirao',
    'Loures',
    'Felgueiras',
    'Evora',
    'Rio de Mouro',
    'Odivelas',
    'Aveiro',
    'Amora',
    'Corroios',
    'Barreiro',
    'Monsanto',
    'Rio Tinto',
    'Sao Domingos de Rana',
    'Figueira da Foz',
    'Leiria',
    'Ponte de Lima',
    'Faro',
    'Sesimbra',
    'Guimaraes',
    'Ermesinde',
    'Santo Antonio dos Olivais',
    'Portimao',
    'Benfica',
    'Cascais',
    'Maia',
    'Viana do Castelo',
    'Oeiras',
    'Beja',
    'Esposende',
    'Braganca',
    'Almada',
    'Olivais',
    'Castelo Branco',
    'Alcabideche',
    'Espinho',
    'Camara de Lobos',
    'Guarda',
    'Alvalade',
    'Arrentela',
    'Montijo',
    'Charneca de Caparica',
    'Santarem',
    'Olhao',
    'Povoa de Varzim',
    'Senhora da Hora',
    'Marinha Grande',
    'Povoa de Santa Iria',
    'Sequeira',
    'Massama',
    'Matosinhos',
    'Gondomar',
    'Aguas Santas',
    'Vila do Conde',
    'Caldas da Rainha',
    'Sao Martinho',
    'Canidelo',
    'Viseu',
    'Sintra',
    'Paco de Arcos',
    'Sao Mamede de Infesta',
    'Quinta Do Conde',
    'Torres Vedras',
    'Oliveira do Douro',
    'Fanzeres',
    'Estoril',
    'Carnaxide',
    'Pinhal Novo',
    'Monte Estoril',
    'Canico',
    'Pontinha',
    'Loule',
    'Arcos de Valdevez',
    'Moscavide e Portela',
    'Sao Joao da Madeira',
    'Lavradio',
    'Bougado',
    'Valongo',
    'Caparica',
    'Belas',
    'Laranjeira',
    'Linda-a-Velha',
    'Trofa',
    'Baiao',
    'Laranjeiro',
    'Carcavelos',
    'Camarate',
    'Ponta Delgada',
    'Entroncamento',
    'Paredes',
    'Moncao',
    'Piedade',
    'Custoias',
    'Alges',
    'Tomar',
    'Barcelos',
    'Pedroso',
    'Vilar de Andorinho',
    'Sao Joao da Talha',
    'Azeitao',
    'Lagos',
    'Quarteira',
    'Santa Iria da Azoia',
    'Ovar',
    'Vila Franca de Xira',
    'Leca da Palmeira',
    'Moita',
    'Sacavem',
    'Covilha',
    'Chaves',
    'Ramada',
    'Pombal',
    'Ilhavo',
    'Parede',
    'Condeixa-a-Nova',
    'Alfragide',
    'Sao Pedro da Cova',
    'Vila Real',
    'Palmela',
    'Fafe',
    'Cabeceiras de Basto',
    'Feira',
    'Leca do Bailio',
    'Vialonga',
    'Albufeira',
    'Baguim do Monte',
    'Alcobaca',
    'Peniche',
    'Portalegre',
    'Alfena',
    'Tavira',
    'Torres Novas',
    'Povoa de Santo Adriao',
    'Gafanha da Nazare',
    'Vilar do Paraiso',
    'Valbom',
    'Lagoa',
    'Arcozelo',
    'Canelas',
    'Costa de Caparica',
    'Valenza',
    'Samora Correia',
    'Santo Tirso',
    'Porto Salvo',
    'Abrantes',
    'Esgueira',
    'Alhos Vedros',
    'Moreira',
    'Montemor-o-Novo',
    'Sines',
    'Beato Antonio',
    'Ourem',
    'Machico',
    'Pedroucos',
    'Perafita',
    'Mirandela',
    'Azenha',
    'Mafra',
    'Aldeia de Paio Pires',
    'Tabua',
    'Rio Maior',
    'Angra do Heroismo',
    'Barcarena',
    'Alijo',
    'Agueda',
    'Fatima',
    'Oliveira de Azemeis',
    'Real',
    'Semelhe',
    'Sao Felix da Marinha',
    'Santa Comba Dao',
    'Avintes',
    'Vila Real de Santo Antonio',
    'Almeirim',
    'Rebordosa',
    'Lousa',
    'Esmoriz',
    'Calendario',
    'Moreira',
    'Vendas Novas',
    'Santo Andre',
    'Obidos',
    'Sao Bras de Alportel',
    'Sobreda',
    'Santo Antonio da Charneca',
    'Cucujaes',
    'Ponte de Sor',
    'Foz do Douro',
    'Canecas',
    'Anta',
    'Lamego',
    'Silves',
    'Grijo',
    'Vale da Amoreira',
    'Grandola',
    'Unhos',
    'Gulpilhares',
    'Margaride',
    'Santo Andre',
    'Charneca',
    'Cartaxo',
    'Aver-o-Mar',
    'Sao Joao das Lampas',
    'Carregado',
    'Melres',
    'Caldas de Vizela',
    'Selho',
    'Moimenta da Beira',
    'Lordelo',
    'Meadela',
    'Elvas',
    'Almancil',
    'Maceira',
    'Fundao',
    'Alcochete',
    'Santa Clara',
    'Lavra',
    'Alenquer',
    'Lourosa',
    'Madalena',
    'Sao Joao de Ver',
    'Rio de Loba',
    'Vila Nova de Famalicao',
    'Famoes',
    'Sao Roque',
    'Moura',
    'Estremoz',
    'Abraveses',
    'Valadares',
    'Guifoes',
    'Alcacer do Sal',
    'Lourinha',
    'Gondizalves',
    'Quinta do Anjo',
    'Vinhais',
    'Marco de Canavezes',
    'Caxias',
    'Mem Martins',
    'Nazare',
    'Benavente',
    'Campo',
    'Mangualde',
    'Queijas',
    'Santana',
    'Tondela',
    'Coruche',
    'Argoncilhe',
    'Ribeirao',
    'Fiaes',
    'Sao Romao do Coronado',
    'Estombar',
    'Tavarede',
    'Torre de Moncorvo',
    'Benedita',
    'Moncarapacho',
    'Aves',
    'Alpendurada',
    'Soure',
    'Bobadela',
    'Sao Bartolomeu de Messines',
    'Casteloes de Cepeda',
    'Vila Vicosa',
    'Atouguia da Baleia',
    'Murtosa',
    'Almargem',
    'Campo Maior',
    'Beduido',
    'Darque',
    'Penafiel',
    'Serzedo',
    'Camacha',
    'Freamunde',
    'Albergaria-a-Velha',
    'Alpiarca',
    'Batalha',
    'Colares',
    'Serzedo',
    'Rosto de Cao',
    'Sao Joao da Pesqueira',
    'Ferreiros',
    'Joane',
    'Buarcos',
    'Miranda do Corvo',
    'Santiago do Cacem',
    'Sande',
    'Pragal',
    'Mira',
    'Rabo de Peixe',
    'Castanheira do Ribatejo',
    'Vale de Cambra',
    'Ericeira',
    'Mondim de Basto',
    'Miranda do Douro',
    'Nisa',
    'Almodovar',
    'Nossa Senhora do Monte',
    'Cantanhede',
    'Vila Nova da Barquinha',
    'Vila Nova de Foz Coa',
    'Apulia e Fao',
    'Aradas',
    'Mertola',
    'Mozelos',
    'Alhandra',
    'Reguengos de Monsaraz',
    'Silvalde',
    'Apelacao',
    'Azambuja',
    'Oia',
    'Seia',
    'Jovim',
    'Ponte',
    'Valega',
    'Arrifes',
    'Silveira',
    'Arrifana',
    'Arcos',
    'Amarante',
    'Pacos de Ferreira',
    'Sao Joao',
    'Arcos',
    'Sobrado',
    'Aveleda',
    'Negrelos',
    'Fazendas de Almeirim',
    'A dos Cunhados',
    'Serpa',
    'Horta',
    'Macedo de Cavaleiros',
    'Avanca',
    'Prior Velho',
    'Sao Romao',
    'Cacilhas',
    'Sandim',
    'Carrazeda de Anciaes',
    'Sabrosa',
    'Tabuaco',
    'Foz do Sousa',
    'Lagoa',
    'Perozinho',
    'Oliveira do Bairro',
    'Santa Cruz do Bispo',
    'Oliveira',
    'Arruda dos Vinhos',
    'Aljubarrota',
    'Madalena',
    'Sao Vicente',
    'Praia da Vitoria',
    'Marinhas',
    'Lobao',
    'Gandra',
    'Porto de Mos',
    'Santa Cruz',
    'Fontanelas',
    'Eixo',
    'Olival do Basto',
    'Milharado',
    'Ribeira Brava',
    'Vidigueira',
    'Arazede',
    'Aljezur',
    'Bombarral',
    'Vila Nova da Telha',
    'Redondo',
    'Odemira',
    'Vieira de Leiria',
    'Marinhais',
    'Monte Real',
    'Boticas',
    'Caldelas',
    'Caldas das Taipas',
    'Oleiros',
    'Olival',
    'Sernancelhe',
    'Serta',
    'Branca',
    'Lamas',
    'Moreira de Conegos',
    'Trafaria',
    'Carregal do Sal',
    'Sao Roque',
    'Barrosas',
    'Vilela',
    'Poiares',
    'Pataias',
    'Aguiar da Beira',
    'Riachos',
    'Urgeses',
    'Monchique',
    'Sao Miguel do Couto',
    'Galegos'
]
