cities = [
    'Bucharest',
    'Sector 3',
    'Sector 6',
    'Sector 2',
    'Iasi',
    'Cluj-Napoca',
    'Timisoara',
    'Craiova',
    'Constanta',
    'Galati',
    'Sector 4',
    'Brasov',
    'Sector 5',
    'Ploiesti',
    'Sector 1',
    'Braila',
    'Oradea',
    'Bacau',
    'Arad',
    'Pitesti',
    'Sibiu',
    'Targu-Mures',
    'Baia Mare',
    'Buzau',
    'Botosani',
    'Satu Mare',
    'Ramnicu Valcea',
    'Suceava',
    'Piatra Neamt',
    'Drobeta-Turnu Severin',
    'Targu Jiu',
    'Tulcea',
    'Targoviste',
    'Bistrita',
    'Resita',
    'Slatina',
    'Focsani',
    'Vaslui',
    'Hunedoara',
    'Giurgiu',
    'Roman',
    'Barlad',
    'Deva',
    'Alba Iulia',
    'Zalau',
    'Sfantu Gheorghe',
    'Turda',
    'Medias',
    'Slobozia',
    'Alexandria',
    'Pascani',
    'Petrosani',
    'Medgidia',
    'Lugoj',
    'Campina',
    'Miercurea-Ciuc',
    'Tecuci',
    'Sighetu Marmatiei',
    'Mangalia',
    'Ramnicu Sarat',
    'Dej',
    'Odorheiu Secuiesc',
    'Reghin-Sat',
    'Sighisoara',
    'Caracal',
    'Navodari',
    'Fetesti',
    'Curtea de Arges',
    'Dorohoi',
    'Fagaras',
    'Lupeni',
    'Voluntari',
    'Sacele',
    'Falticeni',
    'Husi',
    'Mioveni',
    'Vulcan',
    'Turnu Magurele',
    'Tarnaveni',
    'Aiud',
    'Caransebes',
    'Rosiorii de Vede',
    'Sebes',
    'Borsa',
    'Campia Turzii',
    'Oltenita',
    'Petrila',
    'Zarnesti',
    'Cugir',
    'Codlea',
    'Moinesti',
    'Radauti',
    'Fetesti-Gara',
    'Gherla',
    'Comanesti',
    'Motru',
    'Carei',
    'Orastie',
    'Buftea',
    'Dragasani',
    'Bals',
    'Moreni',
    'Targu Neamt',
    'Blaj',
    'Targu Secuiesc',
    'Corabia',
    'Baicoi',
    'Gheorgheni',
    'Campulung Moldovenesc',
    'Bailesti',
    'Filiasi',
    'Calafat',
    'Cernavoda',
    'Buhusi',
    'Breaza',
    'Salonta',
    'Adjud',
    'Ludus',
    'Viseu de Sus',
    'Urziceni',
    'Baia Sprie',
    'Bocsa',
    'Pantelimon',
    'Vatra Dornei',
    'Brad',
    'Gura Humorului',
    'Simleu Silvaniei',
    'Mizil',
    'Ocna Mures',
    'Popesti-Leordeni',
    'Rasnov',
    'Zimnicea',
    'Cisnadie',
    'Gaesti',
    'Pucioasa',
    'Darmanesti',
    'Vicovu de Sus',
    'Avrig',
    'Marghita',
    'Simeria',
    'Targu Frumos',
    'Dabuleni',
    'Negresti-Oas',
    'Valenii de Munte',
    'Moldova Noua',
    'Ovidiu',
    'Comarnic',
    'Targu Ocna',
    'Sannicolau Mare',
    'Stefanesti',
    'Pecica',
    'Chitila',
    'Calan',
    'Santana',
    'Poiana Mare',
    'Scornicesti',
    'Orsova',
    'Oravita',
    'Rovinari',
    'Tandarei',
    'Draganesti-Olt',
    'Jilava',
    'Sinaia',
    'Darabani',
    'Tomesti',
    'Videle',
    'Storesti',
    'Urlati',
    'Holboca',
    'Bolintin Vale',
    'Matca',
    'Strehaia',
    'Otelu Rosu',
    'Sovata',
    'Boldesti-Scaeni',
    'Nehoiu',
    'Belcesti',
    'Harlau',
    'Pechea',
    'Ianca',
    'Jibou',
    'Lipova',
    'Topoloveni',
    'Dolhasca',
    'Covasna',
    'Liesti',
    'Beclean',
    'Murfatlar',
    'Breaza de Sus',
    'Hateg',
    'Jimbolia',
    'Dofteana',
    'Beius',
    'Costesti',
    'Agnita',
    'Deleni',
    'Vladimirescu',
    'Bumbesti-Jiu',
    'Calinesti',
    'Seini',
    'Nasaud',
    'Valea Calugareasca',
    'Otopeni',
    'Macin',
    'Bucov',
    'Alesd',
    'Cormaia',
    'Victoria',
    'Valea lui Mihai',
    'Sabaoani',
    'Filipestii de Padure',
    'Nicolae Balcescu',
    'Ciurea',
    'Babadag',
    'Titu',
    'Harsova',
    'Ineu',
    'Negresti',
    'Sascut',
    'Mihail Kogalniceanu',
    'Uricani',
    'Busteni',
    'Homocea',
    'Poienile de sub Munte',
    'Liteni',
    'Munteni',
    'Podu Iloaiei',
    'Cumpana',
    'Modelu',
    'Ivesti',
    'Curtici',
    'Budesti',
    'Oituz',
    'Cristuru Secuiesc',
    'Borcea',
    'Cernica',
    'Zorleni',
    'Eforie Sud',
    'Marginea',
    'Berca',
    'Tasnad',
    'Simian',
    'Baraolt',
    'Huedin',
    'Magurele',
    'Babeni',
    'Iernut',
    'Siret',
    'Barcanesti',
    'Branesti',
    'Preutesti',
    'Vadu Pasii',
    'Intorsura Buzaului',
    'Cobadin',
    'Borlesti',
    'Moisei',
    'Puchenii Mari',
    'Lovrin',
    'Marasesti',
    'Panciu',
    'Hotarele',
    'Aricestii-Rahtivani',
    'Bascov',
    'Valu lui Traian',
    'Vanatori-Neamt',
    'Anina',
    'Roznov',
    'Apahida',
    'Salcea',
    'Targu Carbunesti',
    'Branesti',
    'Dragalina',
    'Joita',
    'Vernesti',
    'Pipirig',
    'Milcovul',
    'Recas',
    'Calimanesti',
    'Targsoru Vechi',
    'Turceni',
    'Brazii de Sus',
    'Milisauti',
    'Zlatna',
    'Popesti',
    'Roata de Jos',
    'Bicaz',
    'Vidra',
    'Razvad',
    'Potlogi',
    'Tamaseni',
    'Sadova',
    'Bragadiru',
    'Corbii Mari',
    'Sangeorz-Bai',
    'Baleni Sarbi',
    'Raucesti',
    'Orbeasca de Sus',
    'Dragomiresti',
    'Chisineu-Cris',
    'Dumbraveni',
    'Miroslava',
    'Saveni',
    'Dumbraveni',
    'Prejmer',
    'Chiajna',
    'Buruenesti',
    'Nadlac',
    'Cudalbi',
    'Baciu',
    'Margineni-Munteni',
    'Odobesti',
    'Chirnogi',
    'Siria',
    'Gataia',
    'Vorona Teodoru',
    'Cotnari',
    'Balcani',
    'Segarcea',
    'Poduri',
    'Campeni',
    'Darmanesti',
    'Motatei',
    'Corod',
    'Piatra Soimului',
    'Vasilati',
    'Racaciuni',
    '1 Decembrie',
    'Castelu',
    'Peretu',
    'Vacaresti',
    'Filipestii de Targ',
    'Adancata',
    'Pogoanele',
    'Sangeorgiu de Mures',
    'Suraia',
    'Tismana',
    'Gilau',
    'Plopeni',
    'Comana',
    'Raducaneni',
    'Brahasestii de Sus',
    'Murgeni',
    'Tibanesti',
    'Blejoi',
    'Buzias',
    'Scobinti',
    'Cornesti',
    'Ulmi',
    'Band',
    'Brebu Manastirei',
    'Somcuta Mare',
    'Fieni',
    'Amara',
    'Scheia',
    'Floresti',
    'Mihailesti',
    'Tulucesti',
    'Sarichioi',
    'Sagna',
    'Asau',
    'Vidra',
    'Floresti',
    'Girov',
    'Sarmasu',
    'Bixad',
    'Doljesti',
    'Balesti',
    'Vadu Moldovei',
    'Insuratei',
    'Cornu Luncii',
    'Balan',
    'Maieru',
    'Armasesti',
    'Cajvana',
    'Peris',
    'Glina',
    'Tarlungeni',
    'Ciacova',
    'Cojasca',
    'Helegiu',
    'Manesti',
    'Halmeu',
    'Gruiu',
    'Udesti',
    'Lumina',
    'Blagesti',
    'Malini',
    'Merei',
    'Pancota',
    'Faget',
    'Cordun',
    'Mediesu Aurit',
    'Umbraresti',
    'Teius',
    'Daneti',
    'Dumbrava Rosie',
    'Tibana',
    'Maracineni',
    'Veresti',
    'Copalau'
]
