cities = [
    'Belgrade',
    'Nis',
    'Novi Sad',
    'Zemun',
    'Kragujevac',
    'Cacak',
    'Subotica',
    'Leskovac',
    'Novi Pazar',
    'Kraljevo',
    'Zrenjanin',
    'Pancevo',
    'Krusevac',
    'Uzice',
    'Smederevo',
    'Valjevo',
    'Vranje',
    'Sabac',
    'Zajecar',
    'Trstenik',
    'Sombor',
    'Kikinda',
    'Pozarevac',
    'Pirot',
    'Bor',
    'Sremska Mitrovica',
    'Vrsac',
    'Jagodina',
    'Ruma',
    'Backa Palanka',
    'Prokuplje',
    'Smederevska Palanka',
    'Ingija',
    'Vrbas',
    'Becej',
    'Knjazevac',
    'Arangelovac',
    'Gornji Milanovac',
    'Lazarevac',
    'Sremcica',
    'Cuprija',
    'Senta',
    'Apatin',
    'Negotin',
    'Obrenovac',
    'Stara Pazova',
    'Backa Topola',
    'Nova Pazova',
    'Kovin',
    'Petrovaradin',
    'Surcin',
    'Bela Crkva',
    'Veternik',
    'Vrnjacka Banja',
    'Kanjiza',
    'Majdanpek',
    'Curug',
    'Backo Petrovo Selo',
    'Sremski Karlovci',
    'Bajina Basta',
    'Zabalj',
    'Novi Knezevac',
    'Mol',
    'Novo Milosevo',
    'Melenci',
    'Dobanovci',
    'Lapovo',
    'Kovacica',
    'Backi Petrovac',
    'Bogatic',
    'Arilje',
    'Mokrin',
    'Debeljaca',
    'Beska',
    'Padina',
    'Banatski Karlovac',
    'Titel',
    'Paracin',
    'Sonta',
    'Badovinci',
    'Backo Gradiste',
    'Umka',
    'Stanisic',
    'Srpska Crnja',
    'Coka',
    'Crepaja',
    'Zvecka',
    'Ecka',
    'Kovilj',
    'Vladimirovac',
    'Baric',
    'Prigrevica',
    'Celarevo'
]
