cities = [
    'Bratislava',
    'Kosice',
    'Presov',
    'Nitra',
    'Zilina',
    'Banska Bystrica',
    'Trnava',
    'Martin',
    'Trencin',
    'Poprad',
    'Prievidza',
    'Zvolen',
    'Povazska Bystrica',
    'Nove Zamky',
    'Michalovce',
    'Spisska Nova Ves',
    'Levice',
    'Komarno',
    'Humenne',
    'Liptovsky Mikulas',
    'Bardejov',
    'Ruzomberok',
    'Piestany',
    'Lucenec',
    'Dubnica nad Vahom',
    'Rimavska Sobota',
    'Cadca',
    'Sala',
    'Partizanske',
    'Hlohovec',
    'Dunajska Streda',
    "Vranov nad Topl'ou",
    'Trebisov',
    'Snina',
    'Senica',
    'Nove Mesto nad Vahom',
    'Kezmarok',
    'Pezinok',
    'Brezno',
    'Ziar nad Hronom',
    'Roznava',
    'Dolny Kubin',
    'Banovce nad Bebravou',
    'Puchov',
    'Handlova',
    'Malacky',
    'Kysucke Nove Mesto',
    'Galanta',
    "Stara L'ubovna",
    'Zlate Moravce',
    'Detva',
    'Skalica',
    'Senec',
    'Levoca',
    'Revuca',
    'Myjava',
    'Velky Krtis',
    'Svidnik',
    'Nova Dubnica',
    'Sabinov',
    'Samorin',
    'Sturovo',
    'Holic',
    'Bytca',
    'Stropkov',
    'Kolarovo',
    'Surany',
    'Stara Tura',
    "Fil'akovo",
    'Banska Stiavnica',
    'Tvrdosin',
    'Moldava nad Bodvou',
    'Vrable',
    'Velky Meder',
    'Krompachy',
    'Modra',
    'Hrinova',
    'Hurbanovo',
    'Namestovo',
    'Stupava',
    'Sahy',
    'Chlmec',
    'Krupina',
    'Turzovka',
    'Secovce',
    'Liptovsky Hradok',
    'Zeliezovce',
    'Nova Bana',
    'Trstena',
    'Svit',
    'Vrutky',
    'Medzilaborce',
    'Zarnovica',
    'Gelnica',
    'Rajec',
    'Sobrance',
    'Vrbove',
    'Ivanka pri Dunaji',
    'Nemsova',
    'Spisska Bela',
    'Lipany',
    'Poltar',
    'Sladkovicovo',
    'Brezova pod Bradlom',
    'Bratislava - Vajnory',
    'Ilava',
    'Kremnica',
    'Gabcikovo',
    'Cierny Balog',
    'Gbely'
]
