cities = [
    'Ljubljana',
    'Maribor',
    'Celje',
    'Kranj',
    'Velenje',
    'Koper',
    'Novo Mesto',
    'Ptuj',
    'Trbovlje',
    'Kamnik',
    'Jesenice',
    'Nova Gorica',
    'Domzale',
    'Skofja Loka',
    'Murska Sobota',
    'Izola',
    'Postojna',
    'Logatec',
    'Kocevje',
    'Vrhnika',
    'Slovenj Gradec',
    'Slovenska Bistrica',
    'Grosuplje',
    'Krsko',
    'Ravne na Koroskem',
    'Ajdovscina',
    'Brezice',
    'Litija',
    'Zagorje ob Savi',
    'Menges',
    'Idrija',
    'Radovljica',
    'Lucija',
    'Crnomelj',
    'Hrastnik',
    'Sezana',
    'Bled',
    'Medvode',
    'Rogaska Slatina',
    'Zalec',
    'Slovenske Konjice',
    'Sentjur',
    'Sevnica',
    'Prevalje',
    'Ilirska Bistrica',
    'Ruse',
    'Piran',
    'Cerknica',
    'Trzic',
    'Miklavz na Dravskem Polju',
    'Trzin',
    'Sempeter pri Gorici',
    'Ribnica',
    'Ziri',
    'Tolmin',
    'Trebnje',
    'Ljutomer',
    'Lasko',
    'Dravograd',
    'Ankaran',
    'Metlika',
    'Mezica',
    'Gornja Radgona',
    'Sencur',
    'Lendava',
    'Zelezniki',
    'Lenart v Slov. Goricah',
    'Zrece',
    'Sostanj',
    'Brezovica pri Ljubljani',
    'Radlje ob Dravi',
    'Spodnje Hoce',
    'Race',
    'Crna na Koroskem',
    'Beltinci',
    'Polzela',
    'Muta',
    'Vojnik',
    'Ig',
    'Skofljica',
    'Radenci',
    'Ormoz',
    'Radece',
    'Borovnica',
    'Pivka',
    'Mozirje',
    'Semic',
    'Straza',
    'Ivancna Gorica',
    'Lovrenc na Pohorju',
    'Mislinja',
    'Store',
    'Sentilj v Slov. Goricah',
    'Bohinjska Bistrica',
    'Smarje pri Jelsah',
    'Vipava',
    'Naklo',
    'Prebold',
    'Odranci',
    'Log pri Brezovici',
    'Bovec',
    'Cerklje na Gorenjskem',
    'Cerkno',
    'Vodice',
    'Vuzenica',
    'Rogatec',
    'Turnisce',
    'Miren',
    'Smartno pri Litiji',
    'Kranjska Gora',
    'Spodnji Duplek',
    'Sentjernej',
    'Mirna',
    'Divaca',
    'Oplotnica',
    'Horjul',
    'Selnica ob Dravi',
    'Kanal',
    'Dornava',
    'Kidricevo',
    'Gorenja Vas',
    'Crensovci',
    'Poljcane',
    'Sredisce ob Dravi',
    'Kobarid',
    'Ljubno ob Savinji',
    'Zuzemberk',
    'Gornji Grad',
    'Mirna Pec',
    'Dobrovnik',
    'Benedikt',
    'Dobrova',
    'Velika Polana',
    'Pesnica pri Mariboru',
    'Moravce',
    'Verzej',
    'Komenda',
    'Nazarje',
    'Vitanje',
    'Preddvor',
    'Sodrazica',
    'Starse',
    'Dolenjske Toplice',
    'Gorisnica',
    'Vransko',
    'Volcja Draga',
    'Moravske Toplice',
    'Sv. Trojica v Slov. Goricah',
    'Velike Lasce',
    'Kostanjevica na Krki',
    'Grad',
    'Kozje',
    'Komen',
    'Smartno ob Paki',
    'Puconci',
    'Majsperk',
    'Mokronog',
    'Kobilje',
    'Zirovnica',
    'Videm',
    'Zgornje Jezersko',
    'Dobrna',
    'Kozina',
    'Leskova Dolina',
    'Zgornja Kungota',
    'Apace',
    'Podcetrtek',
    'Zgornje Gorje',
    'Krizevci pri Ljutomeru',
    'Recica ob Savinji',
    'Videm pri Ptuju',
    'Markovci',
    'Cankova',
    'Ribnica na Pohorju',
    'Cirkulane',
    'Salovci',
    'Gornji Petrovci',
    'Lukovica pri Domzalah',
    'Luce',
    'Tabor',
    'Tisina',
    'Zetale',
    'Podlehnik',
    'Jurovski Dol',
    'Braslovce',
    'Kuzma',
    'Hrib-Loski Potok',
    'Dobrovo',
    'Trnovska Vas',
    'Podvelka',
    'Sentrupert',
    'Vitomarci',
    'Smarjeta',
    'Jursinci',
    'Nova Vas',
    'Sveti Tomaz',
    'Bistrica ob Sotli',
    'Spodnja Hajdina',
    'Rogasovci',
    'Razkrizje',
    'Makole',
    'Skocjan',
    'Dol pri Ljubljani',
    'Hodos',
    'Solcava',
    'Sveti Jurij ob Scavnici',
    'Destrnik',
    'Sv. Ana v Slov. Goricah',
    'Cerkvenjak',
    'Dobje pri Planini',
    'Osilnica',
    'Zavrc',
    'Kostel'
]
