cities = [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Sevilla',
    'Zaragoza',
    'Malaga',
    'Murcia',
    'Palma',
    'Las Palmas de Gran Canaria',
    'Bilbao',
    'Alicante',
    'Cordoba',
    'Valladolid',
    'Vigo',
    'Gijon',
    'Eixample',
    "L'Hospitalet de Llobregat",
    'Latina',
    'Carabanchel',
    'A Coruna',
    'Puente de Vallecas',
    'Sant Marti',
    'Gasteiz / Vitoria',
    'Granada',
    'Elche',
    'Ciudad Lineal',
    'Oviedo',
    'Santa Cruz de Tenerife',
    'Fuencarral-El Pardo',
    'Badalona',
    'Cartagena',
    'Terrassa',
    'Jerez de la Frontera',
    'Sabadell',
    'Mostoles',
    'Alcala de Henares',
    'Pamplona',
    'Fuenlabrada',
    'Almeria',
    'Leganes',
    'San Sebastian',
    'Sants-Montjuic',
    'Santander',
    'Castello de la Plana',
    'Burgos',
    'Albacete',
    'Horta-Guinardo',
    'Alcorcon',
    'Getafe',
    'Nou Barris',
    'Hortaleza',
    'San Blas-Canillejas',
    'Salamanca',
    'Tetuan de las Victorias',
    'Logrono',
    'La Laguna',
    'City Center',
    'Huelva',
    'Arganzuela',
    'Badajoz',
    'Sarria-Sant Gervasi',
    'Sant Andreu',
    'Salamanca',
    'Chamberi',
    'Usera',
    'Tarragona',
    'Chamartin',
    'Lleida',
    'Marbella',
    'Leon',
    'Villaverde',
    'Cadiz',
    'Retiro',
    'Dos Hermanas',
    'Mataro',
    'Gracia',
    'Santa Coloma de Gramenet',
    'Torrejon de Ardoz',
    'Jaen',
    'Moncloa-Aravaca',
    'Algeciras',
    'Parla',
    'Delicias',
    'Ourense',
    'Alcobendas',
    'Reus',
    'Moratalaz',
    'Ciutat Vella',
    'Torrevieja',
    'Telde',
    'Barakaldo',
    'Lugo',
    'San Fernando',
    'Girona',
    'Santiago de Compostela',
    'Caceres',
    'Lorca',
    'Coslada',
    'Talavera de la Reina',
    'El Puerto de Santa Maria',
    'Cornella de Llobregat',
    'Las Rozas de Madrid',
    'Orihuela',
    'Aviles',
    'El Ejido',
    'Guadalajara',
    'Roquetas de Mar',
    'Palencia',
    'Algorta',
    'Pozuelo de Alarcon',
    'Sant Boi de Llobregat',
    'Toledo',
    'Les Corts',
    'Pontevedra',
    'Getxo',
    'Gandia',
    'Sant Cugat del Valles',
    'Ceuta',
    'Arona',
    'Torrent',
    'Chiclana de la Frontera',
    'Manresa',
    'San Sebastian de los Reyes',
    'Ferrol',
    'Velez-Malaga',
    'Ciudad Real',
    'Mijas',
    'Melilla',
    'Rubi',
    'Fuengirola',
    'Benidorm',
    'Alcala de Guadaira',
    'Ponferrada',
    'Rivas-Vaciamadrid',
    'Majadahonda',
    'Campina',
    'Vicalvaro',
    'Zamora',
    'Sagunto',
    'Vilanova i la Geltru',
    'Sanlucar de Barrameda',
    'Estepona',
    'Torremolinos',
    'Villa de Vallecas',
    'La Linea de la Concepcion',
    'Molina de Segura',
    'Paterna',
    'Santa Lucia',
    'Viladecans',
    'El Prat de Llobregat',
    'Valdemoro',
    'Grao de Murviedro',
    'Castelldefels',
    'Alcoy',
    'Linares',
    'Irun',
    'Granollers',
    'Motril',
    'Santutxu',
    'Arrecife',
    'Benalmadena',
    'Cerdanyola del Valles',
    "la Nova Esquerra de l'Eixample",
    'Avila',
    'Barri de Sant Andreu',
    'Segovia',
    'Merida',
    'Cuenca',
    'Torrelavega',
    'Elda',
    'Collado-Villalba',
    'Aranjuez',
    'San Vicent del Raspeig',
    'Mollet del Valles',
    'San Bartolome de Tirajana',
    'Huesca',
    'Puertollano',
    'Calvia',
    'Sagrada Familia',
    'Arganda',
    'Vila-real',
    'la Vila de Gracia',
    'Utrera',
    'Ibiza',
    'el Raval',
    'Portugalete',
    'Sant Gervasi - Galvany',
    'Santurtzi',
    'Esplugues de Llobregat',
    'Barri de les Corts',
    'Gava',
    'Sama',
    'Antequera',
    'Alzira',
    'Denia',
    'Mieres',
    "Dreta de l'Eixample",
    'Llefia',
    'Mislata',
    'Colmenar Viejo',
    'Pinto',
    'Barajas de Madrid',
    'Boadilla del Monte',
    'Figueres',
    'Adeje',
    'Sant Feliu de Llobregat',
    'Basauri',
    'Lucena',
    "l'Antiga Esquerra de l'Eixample",
    'Tres Cantos',
    'Sants',
    'La Orotava',
    'Plasencia',
    'Alcantarilla',
    'San Fernando de Henares',
    'Poble Sec',
    'Mairena del Aljarafe',
    'Manacor',
    'Ecija',
    'Puerto Real',
    'Blanes',
    'Granadilla de Abona',
    'Vic',
    'Soria',
    'Lloret de Mar',
    'Miranda de Ebro',
    'Andujar',
    'Igualada',
    'Errenteria',
    'Rincon de la Victoria',
    'Sant Antoni',
    'Burjassot',
    'Vilafranca del Penedes',
    "el Camp de l'Arpa del Clot",
    'Tomelloso',
    'Ontinyent',
    'Naron',
    'Vilagarcia de Arousa',
    'Los Realejos',
    'Ripollet',
    'Ronda',
    'Los Palacios y Villafranca',
    'Arucas',
    'Llucmajor',
    'el Guinardo',
    'Realejo Alto',
    'La Rinconada',
    'El Vendrell',
    'Don Benito',
    'Puerto del Rosario',
    'Ubeda',
    'Teruel',
    'Villena',
    'Mazarron',
    'Cieza',
    'Tortosa',
    'Alhaurin de la Torre',
    'Yecla',
    'San Pedro de Alcantara',
    'Tudela',
    'Burriana',
    'Aguilas',
    "el Camp d'en Grassot i Gracia Nova",
    'Villajoyosa',
    'Sant Adria de Besos',
    'el Poblenou',
    'Almendralejo',
    'Olot',
    'Montcada i Reixac',
    'Oleiros',
    'Marratxi',
    'Maspalomas',
    'Aranda de Duero',
    'Azuqueca de Henares',
    'Cambrils',
    'Puerto de la Cruz',
    'Sant Joan Despi',
    'Fort Pienc',
    'El Carmel',
    'Galapagar',
    'Santa Pola',
    'Castro-Urdiales',
    'Javea',
    'Torre-Pacheco',
    'San Javier',
    'Camargo',
    'Santa Eularia des Riu',
    'Arcos de la Frontera',
    'Leioa',
    'Valdepenas',
    'Barbera del Valles',
    'Carballo',
    'Hellin',
    'San Andres del Rabanedo',
    'Xirivella',
    'Alcazar de San Juan',
    'Manises',
    'la Marina de Port',
    'Alaquas',
    'Oliver-Valdefierro',
    'Puente-Genil',
    'Redondela',
    'Puerto del Carmen',
    'Pinar de Chamartin',
    'Atamaria',
    'Salt',
    'Aldaia',
    'Arteixo',
    'Calp',
    'Sestao',
    'Xativa',
    'Ingenio',
    'Inca',
    'el Putxet i el Farro',
    'San Roque',
    'Galdakao',
    'Totana',
    'Rota',
    'Ciutadella',
    'La Sagrera',
    'Mao',
    'la Verneda i la Pau',
    'Aguimes',
    'Sueca',
    'Crevillente',
    'Moron de la Frontera',
    'Oliva',
    'Sant Pere de Ribes',
    'Carmona',
    'Algemesi',
    'Vinaros',
    'Durango',
    'Culleredo',
    'Coria del Rio',
    'Sant Vicenc dels Horts',
    'Almunecar',
    'Sitges',
    'Ribeira',
    'Eibar',
    'Premia de Mar',
    'el Clot',
    'Santa Uxia de Ribeira',
    'Novelda',
    'Catarroja',
    'Ames',
    'Martorell',
    'Horta',
    'Benicarlo',
    'Salou',
    'Villarrobledo',
    'Nijar',
    'El Campello',
    'Villaviciosa de Odon',
    'Lebrija',
    'Caravaca',
    'Sant Andreu de la Barca',
    'la Prosperitat',
    'Pineda de Mar',
    'Sant Marti de Provencals',
    'Camas',
    'Marin',
    'Lepe',
    'Villanueva de la Serena',
    'Almozara',
    'el Baix Guinardo',
    'Cangas do Morrazo',
    'Almansa',
    'Onda',
    'Jumilla',
    'Vilapicina i la Torre Llobeta',
    'La Bonanova',
    'Quart de Poblet',
    'Valls',
    'Santa Perpetua de Mogoda',
    'Almassora',
    'Iturrama',
    'Sarria',
    'Calahorra',
    'Martos',
    'Porta',
    'Galdar',
    'Adra',
    'Sants - Badal',
    'Candelaria',
    'Calafell',
    'Erandio',
    'Cullera',
    'Ibi',
    'Molins de Rei',
    'la Maternitat i Sant Ramon',
    'Icod de los Vinos',
    'Montilla',
    'Altea',
    'San Pedro del Pinatar',
    'Tacoronte',
    'Paiporta',
    'Priego de Cordoba',
    'Baza',
    'Alhaurin el Grande',
    'Olesa de Montserrat'
]
