cities = [
    'Taipei',
    'Kaohsiung',
    'Taichung',
    'Tainan',
    'Banqiao',
    'Hsinchu',
    'Taoyuan City',
    'Keelung',
    'Hualien City',
    'Yuanlin',
    'Taitung City',
    'Nantou',
    'Douliu',
    'Yilan',
    'Puli',
    'Daxi',
    'Magong',
    'Donggang',
    'Jincheng',
    'Hengchun',
    'Zhongxing New Village',
    'Lugu',
    'Yujing'
]
