cities = [
    'Bangkok',
    'Samut Prakan',
    'Mueang Nonthaburi',
    'Udon Thani',
    'Chon Buri',
    'Nakhon Ratchasima',
    'Chiang Mai',
    'Hat Yai',
    'Pak Kret',
    'Si Racha',
    'Phra Pradaeng',
    'Lampang',
    'Khon Kaen',
    'Surat Thani',
    'Ubon Ratchathani',
    'Nakhon Si Thammarat',
    'Khlong Luang',
    'Nakhon Pathom',
    'Rayong',
    'Phitsanulok',
    'Chanthaburi',
    'Pattaya',
    'Yala',
    'Ratchaburi',
    'Nakhon Sawan',
    'Phuket',
    'Ban Mai',
    'Songkhla',
    'Phra Nakhon Si Ayutthaya',
    'Chiang Rai',
    'Bang Kruai',
    'Sakon Nakhon',
    'Krathum Baen',
    'Saraburi',
    'Trang',
    'Sattahip',
    'Kanchanaburi',
    'Nong Khai',
    'Samut Sakhon',
    'Ban Lam Luk Ka',
    'Kamphaeng Phet',
    'Chaiyaphum',
    'Uttaradit',
    'Lop Buri',
    'Ban Pong',
    'Phra Phutthabat',
    'Chumphon',
    'Klaeng',
    'Kalasin',
    'Suphan Buri',
    'Tha Maka',
    'Ban Talat Yai',
    'Maha Sarakham',
    'Phetchabun',
    'Hua Hin',
    'Ko Samui',
    'Chachoengsao',
    'Cha-am',
    'Pak Chong',
    'Narathiwat',
    'Pran Buri',
    'Surin',
    'Phetchaburi',
    'Chum Phae',
    'Sadao',
    'Si Sa Ket',
    'Mae Sot',
    'Pattani',
    'Phatthalung',
    'Lamphun',
    'Warin Chamrap',
    'Su-ngai Kolok',
    'Tha Yang',
    'Ban Phaeo',
    'Bang Bua Thong',
    'Nong Khae',
    'Mukdahan',
    'Ban Na',
    'Bang Lamung',
    'Roi Et',
    'Wichian Buri',
    'Wichit',
    'Phrae',
    'Mae Chan',
    'Sam Phran',
    'Sukhothai',
    'Kantharalak',
    'Photharam',
    'Phichit',
    'Det Udom',
    'Ban Phai',
    'Tha Bo',
    'Loei',
    'Samut Songkhram',
    'Kathu',
    'Amnat Charoen',
    'Nakhon Phanom',
    'Satun',
    'Nong Bua Lamphu',
    'Ban Ratsada',
    'Prachuap Khiri Khan',
    'San Kamphaeng',
    'Prachin Buri',
    'Krabi',
    'Ban Khlong Bang Sao Thong',
    'Yaring',
    'Na Klang',
    'Kaeng Khoi',
    'Betong',
    'Bang Phae',
    'Ban Phan Don',
    'Kaeng Khro',
    'Amphoe Sikhiu',
    'Sa Kaeo',
    'Bang Bo District',
    'Buri Ram',
    'Thung Song',
    'Ban Chang',
    'Ban Bang Kadi Pathum Thani',
    'Nong Phai',
    'Mae Sai',
    'Tha Muang',
    'Ron Phibun',
    'Ban Talat Bueng',
    'Si Satchanalai',
    'Tha Kham',
    'Bang Pakong',
    'Chai Badan',
    'Pak Phanang',
    'Kut Chap',
    'Nan',
    'Ranong',
    'Pathum Thani',
    'Tak',
    'Dok Kham Tai',
    'Ban Bueng',
    'Kamalasai',
    'Ban Talat Nua',
    'Chok Chai',
    'Damnoen Saduak',
    'Tha Mai',
    'Uthai Thani',
    'Nang Rong',
    'Phanat Nikhom',
    'Ban Na San',
    'Taphan Hin',
    'Khanu Woralaksaburi',
    'Ban Nong Wua So',
    'Yasothon',
    'Trat',
    'Nakhon Nayok',
    'Phayao',
    'Kuchinarai',
    'Bang Pa-in',
    'Aranyaprathet',
    'Kabin Buri',
    'Sing Buri',
    'Phibun Mangsahan',
    'Sawankhalok',
    'Ranot',
    'Sam Roi Yot',
    'Ban Dung',
    'Phak Hai',
    'Nam Som',
    'Wiset Chaichan',
    'Tha Ruea',
    'Kui Buri',
    'Bang Krathum',
    'Phan Thong',
    'Khon Buri',
    'Kaset Wisai',
    'Khao Yoi',
    'Thoen',
    'Non Sung',
    'Ban Tak',
    'Ban Chalong',
    'Hang Dong',
    'Bang Len',
    'San Pa Tong',
    'Chon Daen',
    'Lat Yao',
    'Ban Phe',
    'Ban Selaphum',
    'Mae Ramat',
    'Lom Sak',
    'Tak Bai',
    'Phu Khiao',
    'Den Chai',
    'Nong Kung Si',
    'Kaset Sombun',
    'Ra-ngae',
    'Bang Rakam',
    'Bua Yai',
    'Sawang Daen Din',
    'Bo Phloi',
    'Thap Than',
    'Bang Ban',
    'Huai Yot',
    'Seka',
    'Wang Nam Yen',
    'Lang Suan',
    'Phu Kradueng',
    'Laem Sing',
    'Phanom Sarakham',
    'Ban Mo',
    'Wang Noi',
    'Wang Saphung',
    'Bang Mun Nak',
    'Pa Sang',
    'Dan Khun Thot',
    'Prakhon Chai',
    'Thap Khlo',
    'Chai Nat',
    'Ban Huai Thalaeng',
    'Bang Racham',
    'Phon Charoen',
    'Khao Wong',
    'Chom Bueng',
    'Bang Saphan',
    'Nakhon Luang',
    'Bamnet Narong',
    'Patong',
    'Doembang Nangbuat',
    'Phon',
    'Chiang Khong',
    'Ban Thai Tan',
    'That Phanom',
    'Pong',
    'Sung Noen',
    'Sai Buri',
    'Ban Su-ngai Pa Di',
    'Nong Bua',
    'Kantang',
    'Soeng Sang',
    'Chiang Kham',
    'Si Chiang Mai',
    'Bang Yai',
    'Lan Sak',
    'Ang Thong',
    'Pho Chai',
    'Pa Daet',
    'Rawai',
    'Bo Rai',
    'Nong Ki',
    'Bang Khla',
    'Kranuan',
    'Ban Sam Chuk',
    'Yang Talat',
    'Waeng',
    'Khlung',
    'Chaiyo',
    'Chiang Klang',
    'Phai Sali',
    'Phimai',
    'Na Wa',
    'Si Bun Rueang',
    'Chom Thong',
    'Phanom Thuan',
    'Don Sak',
    'Huai Mek',
    'Nakhon Thai',
    'Ban Nam Yuen',
    'Phayuha Khiri',
    'Chaiya',
    'Suwannaphum',
    'Nuea Khlong',
    'Pho Thong',
    'Rong Kwang',
    'Non Thai',
    'Wiang Sa',
    'Ko Pha Ngan',
    'Non Sang',
    'Long',
    'Phrai Bueng',
    'Satuek',
    'Nong Chik',
    'Khiri Mat',
    'Kham Sakae Saeng',
    'Chawang',
    'Chiang Saen',
    'Kosum Phisai',
    'Phayakkhaphum Phisai',
    'Wapi Pathum',
    'Ban Ko Kaeo',
    'Mae Tha',
    'Sangkhla Buri',
    'Bueng Kan',
    'Phang Nga',
    'Ao Luek',
    'Mae Hong Son',
    'Wang Sai Phun',
    'Pong Nam Ron',
    'Bang Nam Priao',
    'Ban Ao Nang',
    'Saladan',
    'Sawang Wirawong',
    'Fang',
    'Lan Krabue',
    'Na Mom',
    'Nong Wua So',
    'Tha Khanon',
    'Tham Phannara',
    'Ban Karon',
    'Chai Buri',
    'Ko Lanta',
    'Huai Khot',
    'Ban Dan Lan Hoi',
    'Ban Phru Nai',
    'Moeiwadi',
    'Mae Chai'
]
