cities = [
    'Tunis',
    'Sfax',
    'Sousse',
    'Kairouan',
    'Bizerte',
    'Gabes',
    'Ariana',
    'Kasserine',
    'Gafsa',
    'La Goulette',
    'Zarzis',
    'Ben Arous',
    'Monastir',
    'La Mohammedia',
    'Al Marsa',
    'Msaken',
    'Skanes',
    'Houmt El Souk',
    'Tataouine',
    'El Hamma',
    'Medenine',
    'Douane',
    'Beja',
    'Nabeul',
    'Hammamet',
    'Jendouba',
    'El Kef',
    'Hammam-Lif',
    'Oued Lill',
    'Menzel Bourguiba',
    'Mahdia',
    'Zouila',
    'Rades',
    'Kelibia',
    'Sidi Bouzid',
    'Metlaoui',
    'Djemmal',
    'Ksar Hellal',
    'Tozeur',
    'Dar Chabanne',
    'Hammam Sousse',
    'Gremda',
    'Korba',
    'La Sebala du Mornag',
    'Midoun',
    'Mateur',
    'Ar Rudayyif',
    'Douz',
    'Ksour Essaf',
    'Siliana',
    'Manouba',
    'Nefta',
    'Chebba',
    'Menzel Jemil',
    'Takelsa',
    'Medjez el Bab',
    'El Jem',
    'Akouda',
    'Kebili',
    'Tajerouine',
    'Douar Tindja',
    'Ouardenine',
    'El Fahs',
    'Beni Khiar',
    'Zaghouan',
    'Mennzel Bou Zelfa',
    'El Alia',
    'Thala',
    'Bekalta',
    'Carthage',
    'Menzel Abderhaman',
    'Galaat el Andeless',
    'Maktar',
    'Erriadh',
    'Sahline',
    'Seiada',
    'Tabarka',
    'Testour',
    'Ben Gardane',
    'Tabursuq',
    'Banbalah',
    'Bou Arada',
    'Ksibet el Mediouni',
    'Beni Khalled',
    'As Sars',
    'Gafour',
    'Bou Arkoub',
    'El Haouaria',
    'Rafraf',
    'Skhira',
    'Sidi Bou Ali',
    'Menzel Kamel',
    'Beni Hassane',
    'Degache',
    'As Sanad',
    'Haffouz',
    'Le Krib',
    'Al Matlin',
    'Djebeniana',
    'El Golaa',
    'Sbikha',
    'Sidi Alouane',
    'El Maamoura',
    'Harqalah',
    'Er Regueb',
    'Zaouiat Djedidi',
    'Sakiet Sidi Youssef',
    'Mellouleche',
    'Chorbane',
    'Sbiba',
    'Jemna',
    'Touza',
    'El Battan',
    'Port el Kantaoui',
    'Jilma',
    'Mezzouna',
    'Lemta',
    'El Ksour',
    'Rhar el Melah',
    'Bir el Hafey',
    'Sejenane'
]
