cities = [
    'Ho Chi Minh City',
    'Hanoi',
    'Da Nang',
    'Haiphong',
    'Bien Hoa',
    'Hue',
    'Nha Trang',
    'Can Tho',
    'Rach Gia',
    'Qui Nhon',
    'Vung Tau',
    'Da Lat',
    'Nam Dinh',
    'Vinh',
    'GJuc Trong',
    'La Gi',
    'Phan Thiet',
    'Long Xuyen',
    'Can Giuoc',
    'Bao Loc',
    'Ha Long',
    'Buon Ma Thuot',
    'Cam Ranh',
    'Sa Pa',
    'Cam Pha Mines',
    'Thai Nguyen',
    'My Tho',
    'Soc Trang',
    'Pleiku',
    'Thanh Hoa',
    'Ca Mau',
    'Bac Lieu',
    'Yen Vinh',
    'Hoa Binh',
    'Vinh Long',
    'Yen Bai',
    'Song Cau',
    'Viet Tri',
    'Phan Rang-Thap Cham',
    'Thu Dau Mot',
    'Cung Kiem',
    'Cu Chi',
    'Mong Cai',
    'Cho Dok',
    'Tuy Hoa',
    'Tan An',
    'Thanh Pho Uong Bi',
    'Cao Lanh',
    'Sa Dec',
    'Ben Tre',
    'Tam Ky',
    'Hai Duong',
    'Tra Vinh',
    'Lang Son',
    'Can Gio',
    'Bim Son',
    'Bac Giang',
    'Thai Binh',
    'Ha Dong',
    'Phu Khuong',
    'Kon Tum',
    'Bac Ninh',
    'Cao Bang',
    'Son Tay',
    'Dien Bien Phu',
    'Hung Yen',
    'Ha Tien',
    'Ninh Binh',
    'Lao Cai',
    'Tay Ninh',
    'Tuyen Quang',
    'Quang Ngai',
    'Hoi An',
    'Ha Giang',
    'Phu Ly',
    'Kwang Binh',
    'Cat Ba',
    'Ha Tinh',
    'Vi Thanh',
    'Don Luan',
    'Son La',
    'Vinh Yen',
    'Bac Kan',
    'Dong Ha',
    'GJinh Van',
    'Binh Long',
    'Duong GJong',
    'Ap Tan Ngai',
    'Thanh Pho Ba Ria',
    'Lai Chau',
    'Gia Nghia'
]
