cities = [
    'Adak',
    'Akiachak',
    'Akiak',
    'Akutan',
    'Alakanuk',
    'Aleknagik',
    'Allakaket',
    'Ambler',
    'Anaktuvuk Pass',
    'Anchor Point',
    'Anchorage',
    'Anderson',
    'Angoon',
    'Aniak',
    'Anvik',
    'Arctic Village',
    'Atka',
    'Atqasuk',
    'Auke Bay',
    'Barrow',
    'Beaver',
    'Bethel',
    'Bettles Field',
    'Big Lake',
    'Brevig Mission',
    'Buckland',
    'Cantwell',
    'Central',
    'Chalkyitsik',
    'Chefornak',
    'Chevak',
    'Chicken',
    'Chignik',
    'Chignik Lagoon',
    'Chignik Lake',
    'Chitina',
    'Chugiak',
    'Circle',
    'Clam Gulch',
    'Clarks Point',
    'Clear',
    'Coffman Cove',
    'Cold Bay',
    'College',
    'Cooper Landing',
    'Copper Center',
    'Cordova',
    'Craig',
    'Crooked Creek',
    'Deering',
    'Delta Junction',
    'Denali National Park',
    'Dillingham',
    'Douglas',
    'Dutch Harbor',
    'Eagle',
    'Eagle River',
    'Eek',
    'Egegik',
    'Eielson AFB',
    'Ekwok',
    'Elfin Cove',
    'Elim',
    'Elmendorf AFB',
    'Emmonak',
    'Ester',
    'Fairbanks',
    'False Pass',
    'Flat',
    'Fort Richardson',
    'Fort Wainwright',
    'Fort Yukon',
    'Funny River',
    'Gakona',
    'Galena',
    'Gambell',
    'Girdwood',
    'Glennallen',
    'Goodnews Bay',
    'Grayling',
    'Gustavus',
    'Haines',
    'Healy',
    'Holy Cross',
    'Homer',
    'Hoonah',
    'Hooper Bay',
    'Hope',
    'Houston',
    'Hughes',
    'Huslia',
    'Hydaburg',
    'Hyder',
    'Iliamna',
    'Indian',
    'Juneau',
    'Kake',
    'Kaktovik',
    'Kalskag',
    'Kaltag',
    'Karluk',
    'Kasigluk',
    'Kasilof',
    'Kenai',
    'Ketchikan',
    'Kiana',
    'King Cove',
    'King Salmon',
    'Kipnuk',
    'Kivalina',
    'Klawock',
    'Knik',
    'Kobuk',
    'Kodiak',
    'Kotlik',
    'Kotzebue',
    'Koyuk',
    'Koyukuk',
    'Kwethluk',
    'Kwigillingok',
    'Lake Minchumina',
    'Larsen Bay',
    'Levelock',
    'Lower Kalskag',
    'Manley Hot Springs',
    'Manokotak',
    'Marshall',
    'McGrath',
    'Mekoryuk',
    'Metlakatla',
    'Meyers Chuck',
    'Minto',
    'Moose Pass',
    'Mountain Village',
    'Naknek',
    'Napakiak',
    'Nenana',
    'New Stuyahok',
    'Nightmute',
    'Nikiski',
    'Nikolai',
    'Nikolski',
    'Ninilchik',
    'Noatak',
    'Nome',
    'Nondalton',
    'Noorvik',
    'North Pole',
    'Northway',
    'Nuiqsut',
    'Nulato',
    'Nunapitchuk',
    'Old Harbor',
    'Ouzinkie',
    'Palmer',
    'Pedro Bay',
    'Pelican',
    'Perryville',
    'Petersburg',
    'Pilot Point',
    'Pilot Station',
    'Platinum',
    'Point Baker',
    'Point Hope',
    'Point Lay',
    'Port Alexander',
    'Port Alsworth',
    'Port Heiden',
    'Port Lions',
    'Prudhoe Bay',
    'Quinhagak',
    'Rampart',
    'Red Devil',
    'Ruby',
    'Russian Mission',
    'Saint George Island',
    'Saint Marys',
    'Saint Michael',
    'Saint Paul Island',
    'Salcha',
    'Sand Point',
    'Savoonga',
    'Scammon Bay',
    'Selawik',
    'Seldovia',
    'Seward',
    'Shageluk',
    'Shaktoolik',
    'Sheldon Point',
    'Shishmaref',
    'Shungnak',
    'Sitka',
    'Skagway',
    'Skwentna',
    'Sleetmute',
    'Soldotna',
    'South Naknek',
    'Stebbins',
    'Sterling',
    'Stevens Village',
    'Sutton',
    'Takotna',
    'Talkeetna',
    'Tanacross',
    'Tanana',
    'Tatitlek',
    'Teller',
    'Tenakee Springs',
    'Tetlin',
    'Thorne Bay',
    'Togiak',
    'Tok',
    'Toksook Bay',
    'Trapper Creek',
    'Tuluksak',
    'Tuntutuliak',
    'Tununak',
    'Two Rivers',
    'Tyonek',
    'Unalakleet',
    'Unalaska',
    'Valdez',
    'Venetie',
    'Wainwright',
    'Wales',
    'Ward Cove',
    'Wasilla',
    'White Mountain',
    'Whittier',
    'Willow',
    'Wrangell',
    'Yakutat'
]
