cities = [
    'Abbeville',
    'Acworth',
    'Adairsville',
    'Adel',
    'Adrian',
    'Ailey',
    'Alamo',
    'Alapaha',
    'Albany',
    'Allenhurst',
    'Allentown',
    'Alma',
    'Alpharetta',
    'Alston',
    'Alto',
    'Ambrose',
    'Americus',
    'Andersonville',
    'Appling',
    'Arabi',
    'Aragon',
    'Argyle',
    'Arlington',
    'Armuchee',
    'Arnoldsville',
    'Ashburn',
    'Athens',
    'Atlanta',
    'Attapulgus',
    'Auburn',
    'Augusta',
    'Austell',
    'Avera',
    'Avondale Estates',
    'Axson',
    'Baconton',
    'Bainbridge',
    'Baldwin',
    'Ball Ground',
    'Barnesville',
    'Barney',
    'Bartow',
    'Barwick',
    'Baxley',
    'Bellville',
    'Berlin',
    'Bethlehem',
    'Bishop',
    'Blackshear',
    'Blairsville',
    'Blakely',
    'Bloomingdale',
    'Blue Ridge',
    'Bluffton',
    'Blythe',
    'Bogart',
    'Bolingbroke',
    'Bonaire',
    'Boneville',
    'Boston',
    'Bostwick',
    'Bowdon',
    'Bowdon Junction',
    'Bowersville',
    'Bowman',
    'Box Springs',
    'Braselton',
    'Bremen',
    'Brinson',
    'Bristol',
    'Bronwood',
    'Brookfield',
    'Brooklet',
    'Brooks',
    'Broxton',
    'Brunswick',
    'Buchanan',
    'Buckhead',
    'Buena Vista',
    'Buford',
    'Butler',
    'Byromville',
    'Byron',
    'Cadwell',
    'Cairo',
    'Calhoun',
    'Calvary',
    'Camak',
    'Camilla',
    'Canon',
    'Canton',
    'Carlton',
    'Carnesville',
    'Carrollton',
    'Cartersville',
    'Cassville',
    'Cataula',
    'Cave Spring',
    'Cecil',
    'Cedar Springs',
    'Cedartown',
    'Centerville',
    'Chatsworth',
    'Chauncey',
    'Cherrylog',
    'Chester',
    'Chestnut Mountain',
    'Chickamauga',
    'Chula',
    'Cisco',
    'Clarkdale',
    'Clarkesville',
    'Clarkston',
    'Claxton',
    'Clayton',
    'Clermont',
    'Cleveland',
    'Climax',
    'Clinchfield',
    'Clyo',
    'Cobb',
    'Cobbtown',
    'Cochran',
    'Cohutta',
    'Colbert',
    'Coleman',
    'Collins',
    'Colquitt',
    'Columbus',
    'Comer',
    'Commerce',
    'Concord',
    'Conley',
    'Conyers',
    'Coolidge',
    'Coosa',
    'Cordele',
    'Cornelia',
    'Cotton',
    'Covington',
    'Crandall',
    'Crawford',
    'Crawfordville',
    'Crescent',
    'Culloden',
    'Cumming',
    'Cusseta',
    'Cuthbert',
    'Dacula',
    'Dahlonega',
    'Daisy',
    'Dallas',
    'Dalton',
    'Damascus',
    'Danielsville',
    'Danville',
    'Darien',
    'Davisboro',
    'Dawson',
    'Dawsonville',
    'De Soto',
    'Dearing',
    'Decatur',
    'Demorest',
    'Denton',
    'Dewy Rose',
    'Dexter',
    'Dillard',
    'Dixie',
    'Doerun',
    'Donalsonville',
    'Douglas',
    'Douglasville',
    'Dover',
    'Dry Branch',
    'Du Pont',
    'Dublin',
    'Dudley',
    'Duluth',
    'East Ellijay',
    'East Point',
    'Eastanollee',
    'Eastman',
    'Eatonton',
    'Eden',
    'Edison',
    'Elberton',
    'Elko',
    'Ellabell',
    'Ellaville',
    'Ellenton',
    'Ellenwood',
    'Ellerslie',
    'Ellijay',
    'Emerson',
    'Enigma',
    'Epworth',
    'Esom Hill',
    'Eton',
    'Evans',
    'Experiment',
    'Fairburn',
    'Fairmount',
    'Fargo',
    'Farmington',
    'Fayetteville',
    'Felton',
    'Fitzgerald',
    'Fleming',
    'Flintstone',
    'Flovilla',
    'Flowery Branch',
    'Folkston',
    'Forest Park',
    'Forsyth',
    'Fort Benning',
    'Fort Gaines',
    'Fort Oglethorpe',
    'Fort Stewart',
    'Fort Valley',
    'Fortson',
    'Fowlstown',
    'Franklin',
    'Franklin Springs',
    'Funston',
    'Gainesville',
    'Garfield',
    'Gay',
    'Geneva',
    'Georgetown',
    'Gibson',
    'Gillsville',
    'Girard',
    'Glenn',
    'Glennville',
    'Glenwood',
    'Good Hope',
    'Gordon',
    'Gough',
    'Gracewood',
    'Grantville',
    'Gray',
    'Grayson',
    'Graysville',
    'Greensboro',
    'Greenville',
    'Griffin',
    'Grovetown',
    'Guyton',
    'Haddock',
    'Hagan',
    'Hahira',
    'Hamilton',
    'Hampton',
    'Haralson',
    'Hardwick',
    'Harlem',
    'Harrison',
    'Hartsfield',
    'Hartwell',
    'Hawkinsville',
    'Hazlehurst',
    'Helen',
    'Helena',
    'Hephzibah',
    'Hiawassee',
    'High Shoals',
    'Hillsboro',
    'Hinesville',
    'Hiram',
    'Hoboken',
    'Hogansville',
    'Holly Springs',
    'Homer',
    'Homerville',
    'Hortense',
    'Hoschton',
    'Howard',
    'Hull',
    'Ideal',
    'Ila',
    'Inman',
    'Iron City',
    'Irwinton',
    'Irwinville',
    'Jackson',
    'Jacksonville',
    'Jakin',
    'Jasper',
    'Jefferson',
    'Jeffersonville',
    'Jekyll Island',
    'Jenkinsburg',
    'Jersey',
    'Jesup',
    'Jewell',
    'Jonesboro',
    'Juliette',
    'Junction City',
    'Kathleen',
    'Kennesaw',
    'Keysville',
    'Kings Bay',
    'Kingsland',
    'Kingston',
    'Kite',
    'Knoxville',
    'La Fayette',
    'Lagrange',
    'Lake Park',
    'Lakeland',
    'Lakemont',
    'Lavonia',
    'Lawrenceville',
    'Leary',
    'Lebanon',
    'Leesburg',
    'Lenox',
    'Leslie',
    'Lexington',
    'Lilburn',
    'Lilly',
    'Lincolnton',
    'Lindale',
    'Lithia Springs',
    'Lithonia',
    'Lizella',
    'Locust Grove',
    'Loganville',
    'Lookout Mountain',
    'Louisville',
    'Louvale',
    'Lovejoy',
    'Ludowici',
    'Lula',
    'Lumber City',
    'Lumpkin',
    'Luthersville',
    'Lyerly',
    'Lyons',
    'Mableton',
    'Macon',
    'Madison',
    'Manassas',
    'Manchester',
    'Manor',
    'Mansfield',
    'Marble Hill',
    'Marietta',
    'Marshallville',
    'Martin',
    'Matthews',
    'Mauk',
    'Maxeys',
    'Maysville',
    'McCaysville',
    'Mcdonough',
    'McIntyre',
    'McRae',
    'Meansville',
    'Meigs',
    'Meldrim',
    'Menlo',
    'Meridian',
    'Mershon',
    'Mesena',
    'Metter',
    'Midland',
    'Midville',
    'Midway',
    'Milan',
    'Milledgeville',
    'Millen',
    'Millwood',
    'Milner',
    'Mineral Bluff',
    'Mitchell',
    'Molena',
    'Monroe',
    'Montezuma',
    'Monticello',
    'Montrose',
    'Moreland',
    'Morgan',
    'Morganton',
    'Morris',
    'Morrow',
    'Morven',
    'Moultrie',
    'Mount Airy',
    'Mount Berry',
    'Mount Vernon',
    'Mount Zion',
    'Mountain City',
    'Murrayville',
    'Musella',
    'Mystic',
    'Nahunta',
    'Nashville',
    'Naylor',
    'Nelson',
    'Newborn',
    'Newington',
    'Newnan',
    'Newton',
    'Nicholls',
    'Nicholson',
    'Norcross',
    'Norman Park',
    'Norristown',
    'Norwood',
    'Nunez',
    'Oakfield',
    'Oakman',
    'Oakwood',
    'Ochlocknee',
    'Ocilla',
    'Oconee',
    'Odum',
    'Offerman',
    'Oglethorpe',
    'Oliver',
    'Omaha',
    'Omega',
    'Orchard Hill',
    'Oxford',
    'Palmetto',
    'Parrott',
    'Patterson',
    'Pavo',
    'Peachtree City',
    'Pearson',
    'Pelham',
    'Pembroke',
    'Pendergrass',
    'Perkins',
    'Perry',
    'Pine Lake',
    'Pine Mountain',
    'Pine Mountain Valley',
    'Pinehurst',
    'Pineview',
    'Pitts',
    'Plainfield',
    'Plains',
    'Plainville',
    'Pooler',
    'Portal',
    'Porterdale',
    'Poulan',
    'Powder Springs',
    'Preston',
    'Pulaski',
    'Putney',
    'Quitman',
    'Rabun Gap',
    'Ranger',
    'Ray City',
    'Rayle',
    'Rebecca',
    'Red Oak',
    'Redan',
    'Register',
    'Reidsville',
    'Rentz',
    'Resaca',
    'Rex',
    'Reynolds',
    'Rhine',
    'Riceboro',
    'Richland',
    'Richmond Hill',
    'Rincon',
    'Ringgold',
    'Rising Fawn',
    'Riverdale',
    'Roberta',
    'Rochelle',
    'Rock Spring',
    'Rockledge',
    'Rockmart',
    'Rocky Face',
    'Rocky Ford',
    'Rome',
    'Roopville',
    'Rossville',
    'Roswell',
    'Royston',
    'Rupert',
    'Rutledge',
    'Rydal',
    'Saint George',
    'Saint Marys',
    'Saint Simons Island',
    'Sale City',
    'Sandersville',
    'Sapelo Island',
    'Sardis',
    'Sargent',
    'Sasser',
    'Sautee Nacoochee',
    'Savannah',
    'Scotland',
    'Scottdale',
    'Screven',
    'Sea Island',
    'Senoia',
    'Seville',
    'Shady Dale',
    'Shannon',
    'Sharon',
    'Sharpsburg',
    'Shellman',
    'Shiloh',
    'Siloam',
    'Silver Creek',
    'Smarr',
    'Smithville',
    'Smyrna',
    'Snellville',
    'Social Circle',
    'Soperton',
    'Sparks',
    'Sparta',
    'Springfield',
    'Stapleton',
    'Statenville',
    'Statesboro',
    'Statham',
    'Stephens',
    'Stillmore',
    'Stockbridge',
    'Stockton',
    'Stone Mountain',
    'Suches',
    'Sugar Valley',
    'Summertown',
    'Summerville',
    'Sumner',
    'Sunny Side',
    'Surrency',
    'Suwanee',
    'Swainsboro',
    'Sycamore',
    'Sylvania',
    'Sylvester',
    'Talbotton',
    'Talking Rock',
    'Tallapoosa',
    'Tallulah Falls',
    'Talmo',
    'Tarrytown',
    'Tate',
    'Taylorsville',
    'Temple',
    'Tennga',
    'Tennille',
    'The Rock',
    'Thomaston',
    'Thomasville',
    'Thomson',
    'Tifton',
    'Tiger',
    'Tignall',
    'Toccoa',
    'Toomsboro',
    'Townsend',
    'Trenton',
    'Trion',
    'Tucker',
    'Tunnel Hill',
    'Turin',
    'Turnerville',
    'Twin City',
    'Ty Ty',
    'Tybee Island',
    'Tyrone',
    'Unadilla',
    'Union City',
    'Union Point',
    'Upatoi',
    'Uvalda',
    'Valdosta',
    'Valona',
    'Varnell',
    'Vidalia',
    'Vienna',
    'Villa Rica',
    'Waco',
    'Wadley',
    'Waleska',
    'Walthourville',
    'Waresboro',
    'Warm Springs',
    'Warner Robins',
    'Warrenton',
    'Warthen',
    'Warwick',
    'Washington',
    'Watkinsville',
    'Waverly',
    'Waverly Hall',
    'Waycross',
    'Waynesboro',
    'Waynesville',
    'West Green',
    'West Point',
    'Weston',
    'Whigham',
    'White',
    'White Oak',
    'White Plains',
    'Whitesburg',
    'Wildwood',
    'Wiley',
    'Willacoochee',
    'Williamson',
    'Winder',
    'Winston',
    'Winterville',
    'Woodbine',
    'Woodbury',
    'Woodland',
    'Woodstock',
    'Wray',
    'Wrens',
    'Wrightsville',
    'Yatesville',
    'Young Harris',
    'Zebulon'
]
