cities = [
    'Abingdon',
    'Adair',
    'Addieville',
    'Addison',
    'Adrian',
    'Akin',
    'Albany',
    'Albers',
    'Albion',
    'Alden',
    'Aledo',
    'Alexander',
    'Alexis',
    'Algonquin',
    'Alhambra',
    'Allendale',
    'Allerton',
    'Alma',
    'Alpha',
    'Alsey',
    'Alsip',
    'Altamont',
    'Alto Pass',
    'Alton',
    'Altona',
    'Alvin',
    'Amboy',
    'Amf Ohare',
    'Anchor',
    'Ancona',
    'Andalusia',
    'Andover',
    'Anna',
    'Annapolis',
    'Annawan',
    'Antioch',
    'Apple River',
    'Arcola',
    'Arenzville',
    'Argenta',
    'Arlington',
    'Arlington Heights',
    'Armington',
    'Armstrong',
    'Aroma Park',
    'Arrowsmith',
    'Arthur',
    'Ashkum',
    'Ashland',
    'Ashley',
    'Ashmore',
    'Ashton',
    'Assumption',
    'Astoria',
    'Athens',
    'Atkinson',
    'Atlanta',
    'Atwater',
    'Atwood',
    'Auburn',
    'Augusta',
    'Aurora',
    'Ava',
    'Aviston',
    'Avon',
    'Baileyville',
    'Baldwin',
    'Bardolph',
    'Barnhill',
    'Barrington',
    'Barry',
    'Barstow',
    'Bartelso',
    'Bartlett',
    'Basco',
    'Batavia',
    'Batchtown',
    'Bath',
    'Baylis',
    'Beardstown',
    'Beason',
    'Beaverville',
    'Beckemeyer',
    'Bedford Park',
    'Beecher',
    'Beecher City',
    'Belknap',
    'Belle Rive',
    'Belleville',
    'Bellflower',
    'Bellmont',
    'Bellwood',
    'Belvidere',
    'Bement',
    'Benld',
    'Bensenville',
    'Benson',
    'Benton',
    'Berkeley',
    'Berwick',
    'Berwyn',
    'Bethalto',
    'Bethany',
    'Big Rock',
    'Biggsville',
    'Bingham',
    'Birds',
    'Bishop Hill',
    'Bismarck',
    'Blackstone',
    'Blandinsville',
    'Bloomingdale',
    'Bloomington',
    'Blue Island',
    'Blue Mound',
    'Bluff Springs',
    'Bluffs',
    'Bluford',
    'Boles',
    'Bolingbrook',
    'Bondville',
    'Bone Gap',
    'Bonfield',
    'Bonnie',
    'Boody',
    'Bourbonnais',
    'Bowen',
    'Braceville',
    'Bradford',
    'Bradley',
    'Braidwood',
    'Breese',
    'Bridgeport',
    'Bridgeview',
    'Brighton',
    'Brimfield',
    'Bristol',
    'Broadlands',
    'Broadview',
    'Brocton',
    'Brookfield',
    'Brookport',
    'Broughton',
    'Browning',
    'Browns',
    'Brownstown',
    'Brushy Mound',
    'Brussels',
    'Bryant',
    'Buckingham',
    'Buckley',
    'Buckner',
    'Buda',
    'Buffalo',
    'Buffalo Grove',
    'Buffalo Prairie',
    'Bulpitt',
    'Buncombe',
    'Bunker Hill',
    'Burbank',
    'Bureau',
    'Burlington',
    'Burnside',
    'Burnt Prairie',
    'Bushnell',
    'Butler',
    'Byron',
    'Cabery',
    'Cache',
    'Cairo',
    'Caledonia',
    'Calhoun',
    'Calumet City',
    'Camargo',
    'Cambria',
    'Cambridge',
    'Camden',
    'Cameron',
    'Camp Grove',
    'Camp Point',
    'Campbell Hill',
    'Campus',
    'Canton',
    'Cantrall',
    'Capron',
    'Carbon Cliff',
    'Carbondale',
    'Carlinville',
    'Carlock',
    'Carlyle',
    'Carman',
    'Carmi',
    'Carol Stream',
    'Carpentersville',
    'Carrier Mills',
    'Carrollton',
    'Carterville',
    'Carthage',
    'Cary',
    'Casey',
    'Caseyville',
    'Castleton',
    'Catlin',
    'Cave In Rock',
    'Cedar Point',
    'Cedarville',
    'Centralia',
    'Cerro Gordo',
    'Chadwick',
    'Chambersburg',
    'Champaign',
    'Chana',
    'Chandlerville',
    'Channahon',
    'Chapin',
    'Charleston',
    'Chatham',
    'Chatsworth',
    'Chebanse',
    'Chenoa',
    'Cherry',
    'Cherry Valley',
    'Chester',
    'Chesterfield',
    'Chestnut',
    'Chicago',
    'Chicago Heights',
    'Chicago Ridge',
    'Chillicothe',
    'Chrisman',
    'Christopher',
    'Cicero',
    'Cisco',
    'Cisne',
    'Cissna Park',
    'Clare',
    'Claremont',
    'Clarendon Hills',
    'Clay City',
    'Clayton',
    'Claytonville',
    'Clifton',
    'Clinton',
    'Coal City',
    'Coal Valley',
    'Coatsburg',
    'Cobden',
    'Coello',
    'Coffeen',
    'Colchester',
    'Coleta',
    'Colfax',
    'Collinsville',
    'Collison',
    'Colona',
    'Colp',
    'Columbia',
    'Colusa',
    'Compton',
    'Concord',
    'Congerville',
    'Cooksville',
    'Cordova',
    'Cornell',
    'Cornland',
    'Cortland',
    'Cottage Hills',
    'Coulterville',
    'Country Club Hills',
    'Cowden',
    'Creal Springs',
    'Crescent City',
    'Creston',
    'Crete',
    'Creve Coeur',
    'Cropsey',
    'Crossville',
    'Crystal Lake',
    'Cuba',
    'Cullom',
    'Cutler',
    'Cypress',
    'Dahinda',
    'Dahlgren',
    'Dakota',
    'Dale',
    'Dallas City',
    'Dalton City',
    'Dalzell',
    'Dana',
    'Danforth',
    'Danvers',
    'Danville',
    'Darien',
    'Davis',
    'Davis Junction',
    'Dawson',
    'De Land',
    'De Soto',
    'Decatur',
    'Deer Creek',
    'Deer Grove',
    'Deerfield',
    'Dekalb',
    'Delavan',
    'Dement',
    'Dennison',
    'Depue',
    'Des Plaines',
    'Dewey',
    'Dewitt',
    'Dieterich',
    'Divernon',
    'Dix',
    'Dixon',
    'Dolton',
    'Dongola',
    'Donnellson',
    'Donovan',
    'Dorsey',
    'Dover',
    'Dow',
    'Dowell',
    'Downers Grove',
    'Downs',
    'Du Bois',
    'Du Quoin',
    'Dundas',
    'Dundee',
    'Dunfermline',
    'Dunlap',
    'Dupo',
    'Durand',
    'Dwight',
    'Eagarville',
    'Earlville',
    'East Alton',
    'East Carondelet',
    'East Dubuque',
    'East Galesburg',
    'East Lynn',
    'East Moline',
    'East Peoria',
    'East Saint Louis',
    'Easton',
    'Eddyville',
    'Edelstein',
    'Edgewood',
    'Edinburg',
    'Edwards',
    'Edwardsville',
    'Effingham',
    'El Paso',
    'Elburn',
    'Eldena',
    'Eldorado',
    'Eldred',
    'Eleroy',
    'Elgin',
    'Elizabeth',
    'Elizabethtown',
    'Elk Grove Village',
    'Elkhart',
    'Elkville',
    'Ellery',
    'Elliott',
    'Ellis Grove',
    'Ellisville',
    'Ellsworth',
    'Elmhurst',
    'Elmwood',
    'Elmwood Park',
    'Elsah',
    'Elvaston',
    'Elwin',
    'Elwood',
    'Emden',
    'Emington',
    'Emma',
    'Energy',
    'Enfield',
    'Eola',
    'Equality',
    'Erie',
    'Esmond',
    'Essex',
    'Eureka',
    'Evanston',
    'Evansville',
    'Evergreen Park',
    'Ewing',
    'Fairbury',
    'Fairfield',
    'Fairmount',
    'Fairview',
    'Fairview Heights',
    'Farina',
    'Farmer City',
    'Farmersville',
    'Farmington',
    'Fenton',
    'Ferris',
    'Fiatt',
    'Fidelity',
    'Fieldon',
    'Fillmore',
    'Findlay',
    'Fisher',
    'Fithian',
    'Flanagan',
    'Flat Rock',
    'Flora',
    'Flossmoor',
    'Foosland',
    'Forest City',
    'Forest Park',
    'Forrest',
    'Forreston',
    'Forsyth',
    'Fort Sheridan',
    'Fowler',
    'Fox Lake',
    'Fox River Grove',
    'Fox Valley',
    'Frankfort',
    'Frankfort Heights',
    'Franklin',
    'Franklin Grove',
    'Franklin Park',
    'Frederick',
    'Freeburg',
    'Freeman Spur',
    'Freeport',
    'Fulton',
    'Fults',
    'Galatia',
    'Galena',
    'Galesburg',
    'Galt',
    'Galva',
    'Garden Prairie',
    'Gardner',
    'Garrett',
    'Gays',
    'Geff',
    'Geneseo',
    'Geneva',
    'Genoa',
    'Georgetown',
    'Gerlaw',
    'German Valley',
    'Germantown',
    'Gibson City',
    'Gifford',
    'Gilberts',
    'Gillespie',
    'Gilman',
    'Gilson',
    'Girard',
    'Gladstone',
    'Glasford',
    'Glen Carbon',
    'Glen Ellyn',
    'Glenarm',
    'Glencoe',
    'Glendale Heights',
    'Glenview',
    'Glenview Nas',
    'Glenwood',
    'Godfrey',
    'Golconda',
    'Golden',
    'Golden Eagle',
    'Golden Gate',
    'Golf',
    'Good Hope',
    'Goodfield',
    'Goodwine',
    'Goreville',
    'Gorham',
    'Grafton',
    'Grand Chain',
    'Grand Ridge',
    'Grand Tower',
    'Granite City',
    'Grant Park',
    'Grantsburg',
    'Granville',
    'Graymont',
    'Grayslake',
    'Grayville',
    'Great Lakes',
    'Green Valley',
    'Greenfield',
    'Greenup',
    'Greenview',
    'Greenville',
    'Gridley',
    'Griggsville',
    'Groveland',
    'Gurnee',
    'Hagarstown',
    'Hamburg',
    'Hamel',
    'Hamilton',
    'Hamletsburg',
    'Hammond',
    'Hampshire',
    'Hampton',
    'Hanna City',
    'Hanover',
    'Hanover Park',
    'Hardin',
    'Harmon',
    'Harrisburg',
    'Harristown',
    'Hartford',
    'Hartsburg',
    'Harvard',
    'Harvel',
    'Harvey',
    'Harwood Heights',
    'Havana',
    'Hazel Crest',
    'Hebron',
    'Hecker',
    'Henderson',
    'Hennepin',
    'Henning',
    'Henry',
    'Herald',
    'Herod',
    'Herrick',
    'Herrin',
    'Herscher',
    'Hettick',
    'Heyworth',
    'Hickory Hills',
    'Hidalgo',
    'Highland',
    'Highland Park',
    'Highwood',
    'Hillsboro',
    'Hillsdale',
    'Hillside',
    'Hillview',
    'Hillyard',
    'Hinckley',
    'Hindsboro',
    'Hines',
    'Hinsdale',
    'Hoffman',
    'Hoffman Estates',
    'Holcomb',
    'Homer',
    'Hometown',
    'Homewood',
    'Hoopeston',
    'Hooppole',
    'Hopedale',
    'Hopkins Park',
    'Hoyleton',
    'Hudson',
    'Huey',
    'Hull',
    'Humboldt',
    'Hume',
    'Huntley',
    'Huntsville',
    'Hurst',
    'Hutsonville',
    'Illinois City',
    'Illiopolis',
    'Ina',
    'Indianola',
    'Industry',
    'Ingleside',
    'Ingraham',
    'Iola',
    'Ipava',
    'Iroquois',
    'Irving',
    'Irvington',
    'Island Lake',
    'Itasca',
    'Iuka',
    'Ivesdale',
    'Jacksonville',
    'Jacob',
    'Janesville',
    'Jerseyville',
    'Jewett',
    'Johnsonville',
    'Johnston City',
    'Joliet',
    'Jonesboro',
    'Joppa',
    'Joy',
    'Junction',
    'Justice',
    'Kampsville',
    'Kane',
    'Kaneville',
    'Kankakee',
    'Kansas',
    'Karbers Ridge',
    'Karnak',
    'Kasbeer',
    'Keenes',
    'Keensburg',
    'Keithsburg',
    'Kell',
    'Kempton',
    'Kenilworth',
    'Kenney',
    'Kent',
    'Kewanee',
    'Keyesport',
    'Kilbourne',
    'Kincaid',
    'Kinderhook',
    'Kingston',
    'Kingston Mines',
    'Kinmundy',
    'Kinsman',
    'Kirkland',
    'Kirkwood',
    'Knoxville',
    'La Fayette',
    'La Grange',
    'La Grange Park',
    'La Harpe',
    'La Moille',
    'La Place',
    'La Prairie',
    'La Rose',
    'La Salle',
    'Lacon',
    'Ladd',
    'Lafox',
    'Lake Bluff',
    'Lake Forest',
    'Lake Fork',
    'Lake in the Hills',
    'Lake Villa',
    'Lake Zurich',
    'Lakewood',
    'Lanark',
    'Lancaster',
    'Lane',
    'Lansing',
    'Latham',
    'Laura',
    'Lawndale',
    'Lawrenceville',
    'Le Roy',
    'Leaf River',
    'Lebanon',
    'Lee',
    'Lee Center',
    'Leland',
    'Lemont',
    'Lena',
    'Lenzburg',
    'Leonore',
    'Lerna',
    'Lewistown',
    'Lexington',
    'Liberty',
    'Libertyville',
    'Lima',
    'Lincoln',
    'Lincoln S New Salem',
    'Lincolnshire',
    'Lincolnwood',
    'Lindenwood',
    'Lisle',
    'Litchfield',
    'Literberry',
    'Little York',
    'Littleton',
    'Liverpool',
    'Livingston',
    'Loami',
    'Lockport',
    'Loda',
    'Logan',
    'Lomax',
    'Lombard',
    'London Mills',
    'Long Grove',
    'Long Point',
    'Longview',
    'Loogootee',
    'Loraine',
    'Lostant',
    'Louisville',
    'Lovejoy',
    'Loves Park',
    'Lovington',
    'Lowder',
    'Lowpoint',
    'Ludlow',
    'Lyndon',
    'Lynn Center',
    'Lyons',
    'Macedonia',
    'Machesney Park',
    'Mackinaw',
    'Macomb',
    'Macon',
    'Madison',
    'Maeystown',
    'Magnolia',
    'Mahomet',
    'Makanda',
    'Malden',
    'Malta',
    'Manchester',
    'Manhattan',
    'Manito',
    'Manlius',
    'Mansfield',
    'Manteno',
    'Maple Park',
    'Mapleton',
    'Maquon',
    'Marengo',
    'Marietta',
    'Marine',
    'Marion',
    'Marissa',
    'Mark',
    'Maroa',
    'Marseilles',
    'Marshall',
    'Martinsville',
    'Martinton',
    'Maryville',
    'Mascoutah',
    'Mason',
    'Mason City',
    'Matherville',
    'Matteson',
    'Mattoon',
    'Maunie',
    'Maywood',
    'Mazon',
    'McClure',
    'McConnell',
    'Mchenry',
    'McLean',
    'McLeansboro',
    'McNabb',
    'Mechanicsburg',
    'Media',
    'Medinah',
    'Medora',
    'Melrose Park',
    'Melvin',
    'Menard',
    'Mendon',
    'Mendota',
    'Meredosia',
    'Merna',
    'Metamora',
    'Metcalf',
    'Metropolis',
    'Michael',
    'Middletown',
    'Midlothian',
    'Milan',
    'Milford',
    'Mill Shoals',
    'Millbrook',
    'Millcreek',
    'Milledgeville',
    'Miller City',
    'Millington',
    'Millstadt',
    'Milmine',
    'Milton',
    'Mineral',
    'Minier',
    'Minonk',
    'Minooka',
    'Mode',
    'Modesto',
    'Modoc',
    'Mokena',
    'Moline',
    'Momence',
    'Monee',
    'Monmouth',
    'Monroe Center',
    'Montgomery',
    'Monticello',
    'Montrose',
    'Mooseheart',
    'Moro',
    'Morris',
    'Morrison',
    'Morrisonville',
    'Morton',
    'Morton Grove',
    'Mossville',
    'Mound City',
    'Mounds',
    'Mount Auburn',
    'Mount Carmel',
    'Mount Carroll',
    'Mount Erie',
    'Mount Morris',
    'Mount Olive',
    'Mount Prospect',
    'Mount Pulaski',
    'Mount Sterling',
    'Mount Vernon',
    'Moweaqua',
    'Mozier',
    'Mt Zion',
    'Muddy',
    'Mulberry Grove',
    'Mulkeytown',
    'Muncie',
    'Mundelein',
    'Murdock',
    'Murphysboro',
    'Murrayville',
    'Muscatine',
    'Nachusa',
    'Naperville',
    'Nashville',
    'Nason',
    'National Stock Yards',
    'Nauvoo',
    'Nebo',
    'Nelson',
    'Neoga',
    'Neponset',
    'New Athens',
    'New Baden',
    'New Bedford',
    'New Berlin',
    'New Boston',
    'New Burnside',
    'New Canton',
    'New Douglas',
    'New Haven',
    'New Holland',
    'New Lenox',
    'New Memphis',
    'New Salem',
    'New Windsor',
    'Newark',
    'Newman',
    'Newton',
    'Niantic',
    'Niles',
    'Nilwood',
    'Niota',
    'Noble',
    'Nokomis',
    'Nora',
    'Normal',
    'Norris',
    'Norris City',
    'North Aurora',
    'North Chicago',
    'North Henderson',
    'Northbrook',
    'O Fallon',
    'Oak Brook',
    'Oak Forest',
    'Oak Lawn',
    'Oak Park',
    'Oakdale',
    'Oakford',
    'Oakland',
    'Oakley',
    'Oakwood',
    'Oblong',
    'Oconee',
    'Odell',
    'Odin',
    'Ogden',
    'Oglesby',
    'Ohio',
    'Ohlman',
    'Okawville',
    'Olive Branch',
    'Olmsted',
    'Olney',
    'Olympia Fields',
    'Omaha',
    'Onarga',
    'Oneida',
    'Opdyke',
    'Opheim',
    'Oquawka',
    'Orangeville',
    'Oraville',
    'Oreana',
    'Oregon',
    'Orient',
    'Orion',
    'Orland Park',
    'Osco',
    'Oswego',
    'Ottawa',
    'Owaneco',
    'Ozark',
    'Palatine',
    'Palestine',
    'Palmer',
    'Palmyra',
    'Paloma',
    'Palos Heights',
    'Palos Hills',
    'Palos Park',
    'Pana',
    'Panama',
    'Papineau',
    'Paris',
    'Park Forest',
    'Park Ridge',
    'Parkersburg',
    'Patoka',
    'Patterson',
    'Paw Paw',
    'Pawnee',
    'Paxton',
    'Payson',
    'Pearl',
    'Pearl City',
    'Pecatonica',
    'Pekin',
    'Penfield',
    'Peoria',
    'Peotone',
    'Percy',
    'Perks',
    'Perry',
    'Peru',
    'Pesotum',
    'Petersburg',
    'Philadelphia',
    'Philo',
    'Piasa',
    'Pierron',
    'Pinckneyville',
    'Piper City',
    'Pittsburg',
    'Pittsfield',
    'Plainfield',
    'Plainville',
    'Plano',
    'Plato Center',
    'Pleasant Hill',
    'Pleasant Plains',
    'Plymouth',
    'Pocahontas',
    'Polo',
    'Pomona',
    'Pontiac',
    'Poplar Grove',
    'Port Byron',
    'Posen',
    'Potomac',
    'Prairie City',
    'Prairie Du Rocher',
    'Preemption',
    'Princeton',
    'Princeville',
    'Prophetstown',
    'Prospect Heights',
    'Pulaski',
    'Putnam',
    'Quincy',
    'Radom',
    'Raleigh',
    'Ramsey',
    'Rankin',
    'Ransom',
    'Rantoul',
    'Rapids City',
    'Raritan',
    'Raymond',
    'Red Bud',
    'Reddick',
    'Redmon',
    'Renault',
    'Reynolds',
    'Richland',
    'Richmond',
    'Richton Park',
    'Richview',
    'Ridge Farm',
    'Ridgway',
    'Ridott',
    'Rinard',
    'Ringwood',
    'Rio',
    'River Forest',
    'River Grove',
    'Riverdale',
    'Riverside',
    'Riverton',
    'Roanoke',
    'Robbins',
    'Roberts',
    'Robinson',
    'Rochelle',
    'Rochester',
    'Rock City',
    'Rock Falls',
    'Rock Island',
    'Rockbridge',
    'Rockford',
    'Rockport',
    'Rockton',
    'Rockwood',
    'Rolling Meadows',
    'Rome',
    'Romeoville',
    'Roodhouse',
    'Rosamond',
    'Roscoe',
    'Roselle',
    'Roseville',
    'Rosiclare',
    'Rossville',
    'Round Lake',
    'Roxana',
    'Royal',
    'Royalton',
    'Rushville',
    'Russell',
    'Rutland',
    'Sadorus',
    'Sailor Springs',
    'Saint Anne',
    'Saint Augustine',
    'Saint Charles',
    'Saint David',
    'Saint Elmo',
    'Saint Francisville',
    'Saint Jacob',
    'Saint Joseph',
    'Saint Libory',
    'Saint Peter',
    'Sainte Marie',
    'Salem',
    'San Jose',
    'Sandoval',
    'Sandwich',
    'Saunemin',
    'Savanna',
    'Savoy',
    'Sawyerville',
    'Saybrook',
    'Scales Mound',
    'Schaumburg',
    'Scheller',
    'Schiller Park',
    'Sciota',
    'Scioto Mills',
    'Scott Air Force Base',
    'Scottville',
    'Seaton',
    'Seatonville',
    'Secor',
    'Seneca',
    'Serena',
    'Sesser',
    'Seward',
    'Seymour',
    'Shabbona',
    'Shannon',
    'Shattuc',
    'Shawneetown',
    'Sheffield',
    'Shelbyville',
    'Sheldon',
    'Sheridan',
    'Sherman',
    'Sherrard',
    'Shipman',
    'Shirland',
    'Shirley',
    'Shobonier',
    'Shumway',
    'Sibley',
    'Sidell',
    'Sidney',
    'Sigel',
    'Silvis',
    'Simpson',
    'Sims',
    'Skokie',
    'Smithboro',
    'Smithfield',
    'Smithshire',
    'Smithton',
    'Solon Mills',
    'Somonauk',
    'Sorento',
    'South Beloit',
    'South Elgin',
    'South Holland',
    'South Pekin',
    'South Roxana',
    'South Wilmington',
    'Sparland',
    'Sparta',
    'Speer',
    'Spring Grove',
    'Spring Valley',
    'Springerton',
    'Springfield',
    'Standard',
    'Standard City',
    'Stanford',
    'Staunton',
    'Steeleville',
    'Steger',
    'Sterling',
    'Steward',
    'Stewardson',
    'Stillman Valley',
    'Stockland',
    'Stockton',
    'Stone Park',
    'Stonefort',
    'Stonington',
    'Stoy',
    'Strasburg',
    'Strawn',
    'Streamwood',
    'Streator',
    'Stronghurst',
    'Sublette',
    'Sugar Grove',
    'Sullivan',
    'Summerfield',
    'Summit',
    'Summit Argo',
    'Sumner',
    'Sutter',
    'Sycamore',
    'Table Grove',
    'Tallula',
    'Tamaroa',
    'Tamms',
    'Tampico',
    'Taylor Ridge',
    'Taylor Springs',
    'Taylorville',
    'Techny',
    'Tennessee',
    'Teutopolis',
    'Texico',
    'Thawville',
    'Thayer',
    'Thebes',
    'Thomasboro',
    'Thompsonville',
    'Thomson',
    'Thornton',
    'Tilden',
    'Tilton',
    'Timewell',
    'Tinley Park',
    'Tiskilwa',
    'Toledo',
    'Tolono',
    'Toluca',
    'Tonica',
    'Topeka',
    'Toulon',
    'Tovey',
    'Towanda',
    'Tower Hill',
    'Tremont',
    'Trenton',
    'Trilla',
    'Triumph',
    'Trivoli',
    'Troy',
    'Troy Grove',
    'Tunnel Hill',
    'Tuscola',
    'Ullin',
    'Union',
    'Union Hill',
    'Unity',
    'Urbana',
    'Ursa',
    'Utica',
    'Valier',
    'Valmeyer',
    'Van Orin',
    'Vandalia',
    'Varna',
    'Venice',
    'Vergennes',
    'Vermilion',
    'Vermont',
    'Vernon',
    'Vernon Hills',
    'Verona',
    'Versailles',
    'Victoria',
    'Vienna',
    'Villa Grove',
    'Villa Park',
    'Villa Ridge',
    'Viola',
    'Virden',
    'Virgil',
    'Virginia',
    'Wadsworth',
    'Waggoner',
    'Walnut',
    'Walnut Hill',
    'Walsh',
    'Walshville',
    'Waltonville',
    'Wapella',
    'Warren',
    'Warrensburg',
    'Warrenville',
    'Warsaw',
    'Wasco',
    'Washburn',
    'Washington',
    'Wataga',
    'Waterloo',
    'Waterman',
    'Watseka',
    'Watson',
    'Wauconda',
    'Waukegan',
    'Waverly',
    'Wayne',
    'Wayne City',
    'Waynesville',
    'Wedron',
    'Weldon',
    'Wellington',
    'Wenona',
    'West Brooklyn',
    'West Chicago',
    'West Frankfort',
    'West Liberty',
    'West Point',
    'West Salem',
    'West Union',
    'West York',
    'Westchester',
    'Western Springs',
    'Westfield',
    'Westmont',
    'Westville',
    'Wheaton',
    'Wheeler',
    'Wheeling',
    'White Hall',
    'White Heath',
    'Whittington',
    'Williamsfield',
    'Williamsville',
    'Willisville',
    'Willow Hill',
    'Willow Springs',
    'Wilmette',
    'Wilmington',
    'Wilsonville',
    'Winchester',
    'Windsor',
    'Winfield',
    'Winnebago',
    'Winnetka',
    'Winslow',
    'Winthrop Harbor',
    'Witt',
    'Wolf Lake',
    'Wonder Lake',
    'Wood Dale',
    'Wood River',
    'Woodhull',
    'Woodland',
    'Woodlawn',
    'Woodridge',
    'Woodson',
    'Woodstock',
    'Woosung',
    'Worden',
    'Worth',
    'Wrights',
    'Wyanet',
    'Wyoming',
    'Xenia',
    'Yale',
    'Yates City',
    'Yorkville',
    'Zeigler',
    'Zion'
]
