cities = [
    'Advance',
    'Akron',
    'Alamo',
    'Albany',
    'Albion',
    'Alexandria',
    'Ambia',
    'Amboy',
    'Amo',
    'Anderson',
    'Andrews',
    'Angola',
    'Arcadia',
    'Arcola',
    'Argos',
    'Arlington',
    'Ashley',
    'Athens',
    'Atlanta',
    'Attica',
    'Atwood',
    'Auburn',
    'Aurora',
    'Austin',
    'Avilla',
    'Avoca',
    'Avon',
    'Bainbridge',
    'Bargersville',
    'Batesville',
    'Bath',
    'Battle Ground',
    'Bedford',
    'Beech Grove',
    'Bellmore',
    'Bennington',
    'Bentonville',
    'Berne',
    'Bethlehem',
    'Beverly Shores',
    'Bicknell',
    'Bippus',
    'Birdseye',
    'Blanford',
    'Bloomfield',
    'Bloomingdale',
    'Bloomington',
    'Bluffton',
    'Boggstown',
    'Boone Grove',
    'Boonville',
    'Borden',
    'Boston',
    'Boswell',
    'Bourbon',
    'Bowling Green',
    'Bradford',
    'Branchville',
    'Brazil',
    'Bremen',
    'Bridgeton',
    'Brimfield',
    'Bringhurst',
    'Bristol',
    'Bristow',
    'Brook',
    'Brooklyn',
    'Brookston',
    'Brookville',
    'Brownsburg',
    'Brownstown',
    'Brownsville',
    'Bruceville',
    'Bryant',
    'Buck Creek',
    'Buckskin',
    'Buffalo',
    'Bunker Hill',
    'Burket',
    'Burlington',
    'Burnettsville',
    'Burrows',
    'Butler',
    'Butlerville',
    'Cambridge City',
    'Camby',
    'Camden',
    'Campbellsburg',
    'Canaan',
    'Cannelburg',
    'Cannelton',
    'Carbon',
    'Carlisle',
    'Carmel',
    'Cartersburg',
    'Carthage',
    'Cayuga',
    'Cedar Grove',
    'Cedar Lake',
    'Celestine',
    'Centerpoint',
    'Centerville',
    'Central',
    'Chalmers',
    'Chandler',
    'Charlestown',
    'Charlottesville',
    'Chesterton',
    'Chrisney',
    'Churubusco',
    'Cicero',
    'Clarks Hill',
    'Clarksburg',
    'Clarksville',
    'Clay City',
    'Claypool',
    'Clayton',
    'Clear Creek',
    'Clifford',
    'Clinton',
    'Cloverdale',
    'Coal City',
    'Coalmont',
    'Coatesville',
    'Colfax',
    'Columbia City',
    'Columbus',
    'Commiskey',
    'Connersville',
    'Converse',
    'Cortland',
    'Corunna',
    'Cory',
    'Corydon',
    'Covington',
    'Craigville',
    'Crandall',
    'Crane',
    'Crawfordsville',
    'Cromwell',
    'Cross Plains',
    'Crothersville',
    'Crown Point',
    'Culver',
    'Cutler',
    'Cynthiana',
    'Dale',
    'Daleville',
    'Dana',
    'Danville',
    'Darlington',
    'Dayton',
    'Decatur',
    'Decker',
    'Deedsville',
    'Delong',
    'Delphi',
    'Demotte',
    'Denver',
    'Depauw',
    'Deputy',
    'Derby',
    'Dillsboro',
    'Donaldson',
    'Dublin',
    'Dubois',
    'Dugger',
    'Dunkirk',
    'Dunreith',
    'Dupont',
    'Dyer',
    'Earl Park',
    'East Chicago',
    'East Enterprise',
    'Eaton',
    'Eckerty',
    'Economy',
    'Edinburgh',
    'Edwardsport',
    'Elberfeld',
    'Elizabeth',
    'Elizabethtown',
    'Elkhart',
    'Ellettsville',
    'Elnora',
    'Elwood',
    'Eminence',
    'English',
    'Etna Green',
    'Evanston',
    'Evansville',
    'Fair Oaks',
    'Fairbanks',
    'Fairland',
    'Fairmount',
    'Falmouth',
    'Farmersburg',
    'Farmland',
    'Ferdinand',
    'Fillmore',
    'Finly',
    'Fishers',
    'Flat Rock',
    'Flora',
    'Florence',
    'Floyds Knobs',
    'Folsomville',
    'Fontanet',
    'Forest',
    'Fort Branch',
    'Fort Ritner',
    'Fort Wayne',
    'Fortville',
    'Fountain City',
    'Fountaintown',
    'Fowler',
    'Fowlerton',
    'Francesville',
    'Francisco',
    'Frankfort',
    'Franklin',
    'Frankton',
    'Fredericksburg',
    'Freedom',
    'Freelandville',
    'Freetown',
    'Fremont',
    'French Lick',
    'Friendship',
    'Fulda',
    'Fulton',
    'Galveston',
    'Garrett',
    'Gary',
    'Gas City',
    'Gaston',
    'Geneva',
    'Gentryville',
    'Georgetown',
    'Glenwood',
    'Goldsmith',
    'Goodland',
    'Goshen',
    'Gosport',
    'Grabill',
    'Grammer',
    'Grandview',
    'Granger',
    'Grantsburg',
    'Grass Creek',
    'Graysville',
    'Greencastle',
    'Greenfield',
    'Greens Fork',
    'Greensboro',
    'Greensburg',
    'Greentown',
    'Greenville',
    'Greenwood',
    'Griffin',
    'Griffith',
    'Grissom AFB',
    'Grovertown',
    'Guilford',
    'Gwynneville',
    'Hagerstown',
    'Hamblen',
    'Hamilton',
    'Hamlet',
    'Hammond',
    'Hanna',
    'Hanover',
    'Hardinsburg',
    'Harlan',
    'Harmony',
    'Harrison',
    'Harrodsburg',
    'Hartford City',
    'Hartsville',
    'Hatfield',
    'Haubstadt',
    'Hayden',
    'Hazleton',
    'Hebron',
    'Helmsburg',
    'Helt',
    'Heltonville',
    'Hemlock',
    'Henryville',
    'Highland',
    'Hillisburg',
    'Hillsboro',
    'Hillsdale',
    'Hoagland',
    'Hobart',
    'Hobbs',
    'Holland',
    'Holton',
    'Homer',
    'Hope',
    'Howe',
    'Hudson',
    'Huntertown',
    'Huntingburg',
    'Huntington',
    'Huron',
    'Hymera',
    'Idaville',
    'Indianapolis',
    'Ingalls',
    'Inglefield',
    'Ireland',
    'Jackson',
    'Jamestown',
    'Jasonville',
    'Jasper',
    'Jefferson',
    'Jeffersonville',
    'Jonesboro',
    'Jonesville',
    'Judson',
    'Kempton',
    'Kendallville',
    'Kennard',
    'Kentland',
    'Kewanna',
    'Keystone',
    'Kimmell',
    'Kingman',
    'Kingsbury',
    'Kingsford Heights',
    'Kirklin',
    'Knightstown',
    'Knightsville',
    'Knox',
    'Kokomo',
    'Koleen',
    'Kouts',
    'Kurtz',
    'La Crosse',
    'La Fontaine',
    'La Porte',
    'Laconia',
    'Ladoga',
    'Lafayette',
    'Lagrange',
    'Lagro',
    'Lake Cicott',
    'Lake Station',
    'Lake Village',
    'Laketon',
    'Lakeville',
    'Lamar',
    'Lanesville',
    'Laotto',
    'Lapaz',
    'Lapel',
    'Larwill',
    'Laurel',
    'Lawrenceburg',
    'Leavenworth',
    'Lebanon',
    'Leesburg',
    'Leiters Ford',
    'Leo',
    'Leopold',
    'Leroy',
    'Lewis',
    'Lewisville',
    'Lexington',
    'Liberty',
    'Liberty Center',
    'Liberty Mills',
    'Ligonier',
    'Lincoln City',
    'Linden',
    'Linn Grove',
    'Linton',
    'Little York',
    'Lizton',
    'Logansport',
    'Loogootee',
    'Losantville',
    'Lovett',
    'Lowell',
    'Lucerne',
    'Lynn',
    'Lynnville',
    'Lyons',
    'Mackey',
    'Macy',
    'Madison',
    'Manilla',
    'Marengo',
    'Mariah Hill',
    'Marion',
    'Markle',
    'Markleville',
    'Marshall',
    'Martinsville',
    'Marysville',
    'Matthews',
    'Mauckport',
    'Maxwell',
    'Mays',
    'McCordsville',
    'Mecca',
    'Medaryville',
    'Medora',
    'Mellott',
    'Memphis',
    'Mentone',
    'Merom',
    'Merrillville',
    'Metamora',
    'Mexico',
    'Miami',
    'Michigan City',
    'Michigantown',
    'Middlebury',
    'Middletown',
    'Midland',
    'Milan',
    'Milford',
    'Mill Creek',
    'Millersburg',
    'Millhousen',
    'Milltown',
    'Milroy',
    'Milton',
    'Mishawaka',
    'Mitchell',
    'Modoc',
    'Mongo',
    'Monon',
    'Monroe',
    'Monroe City',
    'Monroeville',
    'Monrovia',
    'Monterey',
    'Montezuma',
    'Montgomery',
    'Monticello',
    'Montmorenci',
    'Montpelier',
    'Mooreland',
    'Moores Hill',
    'Mooresville',
    'Morgantown',
    'Morocco',
    'Morris',
    'Morristown',
    'Mount Ayr',
    'Mount Saint Francis',
    'Mount Summit',
    'Mount Vernon',
    'Mulberry',
    'Muncie',
    'Munster',
    'Nabb',
    'Napoleon',
    'Nappanee',
    'Nashville',
    'Nebraska',
    'Needham',
    'New Albany',
    'New Carlisle',
    'New Castle',
    'New Goshen',
    'New Harmony',
    'New Haven',
    'New Lebanon',
    'New Lisbon',
    'New Market',
    'New Middletown',
    'New Palestine',
    'New Paris',
    'New Point',
    'New Richmond',
    'New Ross',
    'New Salisbury',
    'New Trenton',
    'New Washington',
    'New Waverly',
    'Newberry',
    'Newburgh',
    'Newport',
    'Newtown',
    'Nineveh',
    'Noble',
    'Noblesville',
    'Norman',
    'North Judson',
    'North Liberty',
    'North Manchester',
    'North Salem',
    'North Vernon',
    'North Webster',
    'Notre Dame',
    'Oakford',
    'Oakland City',
    'Oaktown',
    'Oakville',
    'Odon',
    'Oldenburg',
    'Onward',
    'Oolitic',
    'Ora',
    'Orestes',
    'Orland',
    'Orleans',
    'Osceola',
    'Osgood',
    'Ossian',
    'Otisco',
    'Otterbein',
    'Otwell',
    'Owensburg',
    'Owensville',
    'Oxford',
    'Palmyra',
    'Paoli',
    'Paragon',
    'Paris Crossing',
    'Parker City',
    'Patoka',
    'Patricksburg',
    'Patriot',
    'Paxton',
    'Pekin',
    'Pendleton',
    'Pennville',
    'Perrysville',
    'Pershing',
    'Peru',
    'Petersburg',
    'Petroleum',
    'Pierceton',
    'Pierceville',
    'Pimento',
    'Pine Village',
    'Pittsboro',
    'Plainfield',
    'Plainville',
    'Pleasant Lake',
    'Pleasant Mills',
    'Plymouth',
    'Poland',
    'Poneto',
    'Portage',
    'Porter',
    'Portland',
    'Poseyville',
    'Prairie Creek',
    'Prairieton',
    'Preble',
    'Princeton',
    'Putnamville',
    'Quincy',
    'Ragsdale',
    'Ramsey',
    'Redkey',
    'Reelsville',
    'Remington',
    'Rensselaer',
    'Reynolds',
    'Richland',
    'Richmond',
    'Ridgeville',
    'Riley',
    'Rising Sun',
    'Roachdale',
    'Roann',
    'Roanoke',
    'Rochester',
    'Rockfield',
    'Rockport',
    'Rockville',
    'Rolling Prairie',
    'Rome',
    'Rome City',
    'Romney',
    'Rosedale',
    'Roselawn',
    'Rossville',
    'Royal Center',
    'Rushville',
    'Russellville',
    'Russiaville',
    'Saint Anthony',
    'Saint Bernice',
    'Saint Croix',
    'Saint Joe',
    'Saint John',
    'Saint Mary Of The Woods',
    'Saint Meinrad',
    'Saint Paul',
    'Salamonia',
    'Salem',
    'San Pierre',
    'Sandborn',
    'Santa Claus',
    'Saratoga',
    'Schererville',
    'Schneider',
    'Schnellville',
    'Scipio',
    'Scotland',
    'Scott',
    'Scottsburg',
    'Sedalia',
    'Seelyville',
    'Sellersburg',
    'Selma',
    'Servia',
    'Seymour',
    'Sharpsville',
    'Shelburn',
    'Shelby',
    'Shelbyville',
    'Shepardsville',
    'Sheridan',
    'Shipshewana',
    'Shirley',
    'Shoals',
    'Sidney',
    'Silver Lake',
    'Smithville',
    'Solsberry',
    'Somerset',
    'Somerville',
    'South Bend',
    'South Milford',
    'South Whitley',
    'Spencer',
    'Spencerville',
    'Spiceland',
    'Springport',
    'Springville',
    'Spurgeon',
    'Stanford',
    'Star City',
    'State Line',
    'Staunton',
    'Stendal',
    'Stilesville',
    'Stinesville',
    'Stockwell',
    'Straughn',
    'Stroh',
    'Sullivan',
    'Sulphur',
    'Sulphur Springs',
    'Sumava Resorts',
    'Summitville',
    'Sunman',
    'Swayzee',
    'Sweetser',
    'Switz City',
    'Syracuse',
    'Talbot',
    'Taswell',
    'Taylorsville',
    'Tefft',
    'Tell City',
    'Templeton',
    'Tennyson',
    'Terre Haute',
    'Thayer',
    'Thorntown',
    'Tippecanoe',
    'Tipton',
    'Topeka',
    'Trafalgar',
    'Troy',
    'Tunnelton',
    'Twelve Mile',
    'Tyner',
    'Underwood',
    'Union City',
    'Union Mills',
    'Uniondale',
    'Unionville',
    'Universal',
    'Upland',
    'Urbana',
    'Vallonia',
    'Valparaiso',
    'Van Buren',
    'Veedersburg',
    'Velpen',
    'Vernon',
    'Versailles',
    'Vevay',
    'Vincennes',
    'Wabash',
    'Wadesville',
    'Wakarusa',
    'Waldron',
    'Walkerton',
    'Wallace',
    'Walton',
    'Wanatah',
    'Warren',
    'Warsaw',
    'Washington',
    'Waterloo',
    'Waveland',
    'Wawaka',
    'Waynetown',
    'Webster',
    'West Baden Springs',
    'West College Corner',
    'West Harrison',
    'West Lafayette',
    'West Lebanon',
    'West Middleton',
    'West Newton',
    'West Terre Haute',
    'Westfield',
    'Westphalia',
    'Westpoint',
    'Westport',
    'Westville',
    'Wheatfield',
    'Wheatland',
    'Wheeler',
    'Whiteland',
    'Whitestown',
    'Whiting',
    'Wilkinson',
    'Williams',
    'Williamsburg',
    'Williamsport',
    'Winamac',
    'Winchester',
    'Windfall',
    'Wingate',
    'Winona Lake',
    'Winslow',
    'Wolcott',
    'Wolcottville',
    'Wolflake',
    'Woodburn',
    'Worthington',
    'Wyatt',
    'Yeoman',
    'Yoder',
    'Yorktown',
    'Young America',
    'Zanesville',
    'Zionsville'
]
