cities = [
    'Aberdeen',
    'Adairville',
    'Adams',
    'Adolphus',
    'Ages Brookside',
    'Albany',
    'Alexandria',
    'Allegre',
    'Allen',
    'Allensville',
    'Almo',
    'Alpha',
    'Alvaton',
    'Annville',
    'Argillite',
    'Arjay',
    'Arlington',
    'Artemus',
    'Ary',
    'Ashcamp',
    'Asher',
    'Ashland',
    'Athol',
    'Auburn',
    'Augusta',
    'Austin',
    'Auxier',
    'Avawam',
    'Bagdad',
    'Bakerton',
    'Bandana',
    'Banner',
    'Barbourville',
    'Bardstown',
    'Bardwell',
    'Barlow',
    'Baskett',
    'Battletown',
    'Baxter',
    'Bays',
    'Bear Branch',
    'Beattyville',
    'Beaumont',
    'Beauty',
    'Beaver',
    'Beaver Dam',
    'Bedford',
    'Bee Spring',
    'Beech Creek',
    'Beech Grove',
    'Beechmont',
    'Belcher',
    'Belfry',
    'Bellevue',
    'Belton',
    'Benham',
    'Benton',
    'Berea',
    'Berry',
    'Bethany',
    'Bethelridge',
    'Bethlehem',
    'Betsy Layne',
    'Beverly',
    'Bevinsville',
    'Big Clifty',
    'Big Creek',
    'Big Laurel',
    'Big Spring',
    'Bighill',
    'Bimble',
    'Blackey',
    'Blackford',
    'Blaine',
    'Bledsoe',
    'Bloomfield',
    'Blue River',
    'Boaz',
    'Bonnieville',
    'Bonnyman',
    'Booneville',
    'Boons Camp',
    'Boston',
    'Bowling Green',
    'Bradfordsville',
    'Brandenburg',
    'Breeding',
    'Bremen',
    'Brodhead',
    'Bronston',
    'Brooklyn',
    'Brooks',
    'Brooksville',
    'Browder',
    'Brownsville',
    'Bryants Store',
    'Bryantsville',
    'Buckhorn',
    'Buckner',
    'Buffalo',
    'Bulan',
    'Burdine',
    'Burgin',
    'Burkesville',
    'Burlington',
    'Burna',
    'Burnside',
    'Bush',
    'Busy',
    'Butler',
    'Bypro',
    'Cadiz',
    'Calhoun',
    'California',
    'Calvert City',
    'Calvin',
    'Camp Dix',
    'Campbellsburg',
    'Campbellsville',
    'Campton',
    'Canada',
    'Cane Valley',
    'Caneyville',
    'Canmer',
    'Cannel City',
    'Cannon',
    'Carlisle',
    'Carrie',
    'Carrollton',
    'Carter',
    'Catlettsburg',
    'Cave City',
    'Cawood',
    'Cecilia',
    'Center',
    'Centertown',
    'Central City',
    'Cerulean',
    'Chaplin',
    'Chappell',
    'Chavies',
    'Cisco',
    'Clarkson',
    'Clay',
    'Clay City',
    'Clayhole',
    'Clearfield',
    'Cleaton',
    'Clermont',
    'Clifty',
    'Clinton',
    'Closplint',
    'Cloverport',
    'Coalgood',
    'Coldiron',
    'Columbia',
    'Columbus',
    'Combs',
    'Confluence',
    'Corbin',
    'Corinth',
    'Cornettsville',
    'Corydon',
    'Covington',
    'Coxs Creek',
    'Crab Orchard',
    'Cranks',
    'Crayne',
    'Crestwood',
    'Crittenden',
    'Crockett',
    'Crofton',
    'Cromona',
    'Cromwell',
    'Cub Run',
    'Cumberland',
    'Cunningham',
    'Curdsville',
    'Custer',
    'Cynthiana',
    'Dabolt',
    'Dana',
    'Danville',
    'David',
    'Dawson Springs',
    'Dayhoit',
    'Dayton',
    'De Mossville',
    'Deane',
    'Debord',
    'Delphia',
    'Dema',
    'Denniston',
    'Denton',
    'Denver',
    'Dewitt',
    'Dexter',
    'Dice',
    'Dixon',
    'Dorton',
    'Dover',
    'Drake',
    'Drakesboro',
    'Drift',
    'Dry Ridge',
    'Dubre',
    'Dunbar',
    'Dundee',
    'Dunmor',
    'Dunnville',
    'Dwale',
    'Dwarf',
    'Dycusburg',
    'Earlington',
    'East Bernstadt',
    'East Point',
    'Eastern',
    'Eastview',
    'Eastwood',
    'Eddyville',
    'Edmonton',
    'Edna',
    'Eighty Eight',
    'Ekron',
    'Elizabethtown',
    'Elizaville',
    'Elk Horn',
    'Elkfork',
    'Elkhorn City',
    'Elkton',
    'Elliottville',
    'Elsie',
    'Emerson',
    'Eminence',
    'Emlyn',
    'Emmalena',
    'Eolia',
    'Eriline',
    'Erlanger',
    'Ermine',
    'Essie',
    'Etoile',
    'Eubank',
    'Evarts',
    'Ewing',
    'Ezel',
    'Fairdale',
    'Fairfield',
    'Fairplay',
    'Fairview',
    'Falcon',
    'Fall Rock',
    'Falls Of Rough',
    'Falmouth',
    'Fancy Farm',
    'Farmers',
    'Farmington',
    'Fedscreek',
    'Ferguson',
    'Finchville',
    'Firebrick',
    'Fisherville',
    'Fisty',
    'Flat Lick',
    'Flatgap',
    'Flatwoods',
    'Flemingsburg',
    'Florence',
    'Ford',
    'Fords Branch',
    'Fordsville',
    'Forest Hills',
    'Fort Campbell',
    'Fort Knox',
    'Fort Mitchell',
    'Fort Thomas',
    'Foster',
    'Fountain Run',
    'Fourmile',
    'Frakes',
    'Frankfort',
    'Franklin',
    'Fredonia',
    'Freeburn',
    'Frenchburg',
    'Ft Mitchell',
    'Fulton',
    'Gamaliel',
    'Gapville',
    'Garfield',
    'Garner',
    'Garrard',
    'Garrett',
    'Garrison',
    'Gays Creek',
    'Georgetown',
    'Germantown',
    'Ghent',
    'Gilbertsville',
    'Girdler',
    'Glasgow',
    'Glencoe',
    'Glendale',
    'Glens Fork',
    'Glenview',
    'Goose Rock',
    'Gordon',
    'Goshen',
    'Gracey',
    'Gradyville',
    'Graham',
    'Grahn',
    'Grand Rivers',
    'Gravel Switch',
    'Gray',
    'Gray Hawk',
    'Grays Knob',
    'Grayson',
    'Green Road',
    'Greensburg',
    'Greenup',
    'Greenville',
    'Grethel',
    'Gulston',
    'Gunlock',
    'Guston',
    'Guthrie',
    'Hadley',
    'Hagerhill',
    'Haldeman',
    'Halfway',
    'Hallie',
    'Hamlin',
    'Hampton',
    'Hanson',
    'Happy',
    'Hardburly',
    'Hardin',
    'Hardinsburg',
    'Hardy',
    'Hardyville',
    'Harlan',
    'Harned',
    'Harold',
    'Harrods Creek',
    'Harrodsburg',
    'Hartford',
    'Hawesville',
    'Hazard',
    'Hazel',
    'Hazel Green',
    'Hebron',
    'Heidelberg',
    'Heidrick',
    'Hellier',
    'Helton',
    'Henderson',
    'Herndon',
    'Hestand',
    'Hi Hat',
    'Hickman',
    'Hickory',
    'Hillsboro',
    'Hima',
    'Hindman',
    'Hinkle',
    'Hiseville',
    'Hitchins',
    'Hodgenville',
    'Holland',
    'Holmes Mill',
    'Hope',
    'Hopkinsville',
    'Horse Branch',
    'Horse Cave',
    'Hoskinston',
    'Huddy',
    'Hudson',
    'Hueysville',
    'Hulen',
    'Huntsville',
    'Hustonville',
    'Hyden',
    'Independence',
    'Inez',
    'Ingram',
    'Irvine',
    'Irvington',
    'Island',
    'Island City',
    'Isom',
    'Isonville',
    'Ivel',
    'Ivyton',
    'Jackhorn',
    'Jackson',
    'Jacobs',
    'Jamestown',
    'Jeff',
    'Jeffersonville',
    'Jenkins',
    'Jeremiah',
    'Jetson',
    'Jonancy',
    'Jonesville',
    'Junction City',
    'Keaton',
    'Keavy',
    'Keene',
    'Kenton',
    'Kenvir',
    'Kettle Island',
    'Kevil',
    'Kimper',
    'Kings Mountain',
    'Kirksey',
    'Kite',
    'Knifley',
    'Knob Lick',
    'Krypton',
    'Kuttawa',
    'La Center',
    'La Fayette',
    'La Grange',
    'Lackey',
    'Lancaster',
    'Langley',
    'Latonia',
    'Lawrenceburg',
    'Leander',
    'Lebanon',
    'Lebanon Junction',
    'Leburn',
    'Ledbetter',
    'Lee City',
    'Leitchfield',
    'Lejunior',
    'Lerose',
    'Letcher',
    'Lewisburg',
    'Lewisport',
    'Lexington',
    'Liberty',
    'Lick Creek',
    'Lily',
    'Lindseyville',
    'Linefork',
    'Littcarr',
    'Livermore',
    'Livingston',
    'Lloyd',
    'Lockport',
    'London',
    'Lone',
    'Lookout',
    'Loretto',
    'Lost Creek',
    'Louisa',
    'Louisville',
    'Lovelaceville',
    'Lovely',
    'Lowes',
    'Lowmansville',
    'Loyall',
    'Lucas',
    'Lynch',
    'Lynnville',
    'Maceo',
    'Mackville',
    'Madisonville',
    'Magnolia',
    'Majestic',
    'Mallie',
    'Malone',
    'Mammoth Cave',
    'Manchester',
    'Manitou',
    'Mannsville',
    'Maple Mount',
    'Marion',
    'Marrowbone',
    'Marshes Siding',
    'Martha',
    'Martin',
    'Mary Alice',
    'Marydell',
    'Mason',
    'Masonic Home',
    'Mayfield',
    'Mayking',
    'Mayslick',
    'Maysville',
    'Mazie',
    'McAndrews',
    'McCarr',
    'McDaniels',
    'McDowell',
    'McHenry',
    'McKee',
    'McKinney',
    'McQuady',
    'McRoberts',
    'McVeigh',
    'Meally',
    'Means',
    'Melber',
    'Melbourne',
    'Melvin',
    'Middleburg',
    'Middlesboro',
    'Middlesborough',
    'Midway',
    'Milburn',
    'Milford',
    'Mill Springs',
    'Millersburg',
    'Millstone',
    'Milltown',
    'Millwood',
    'Milton',
    'Minerva',
    'Minnie',
    'Miracle',
    'Mistletoe',
    'Mitchellsburg',
    'Mize',
    'Monticello',
    'Moorefield',
    'Morehead',
    'Morganfield',
    'Morgantown',
    'Morning View',
    'Mortons Gap',
    'Mount Eden',
    'Mount Hermon',
    'Mount Olivet',
    'Mount Sherman',
    'Mount Sterling',
    'Mount Vernon',
    'Mount Washington',
    'Mousie',
    'Mouthcard',
    'Mozelle',
    'Muldraugh',
    'Munfordville',
    'Murray',
    'Muses Mills',
    'Myra',
    'Nancy',
    'Nazareth',
    'Nebo',
    'Neon',
    'Nerinx',
    'Nevisdale',
    'New Castle',
    'New Concord',
    'New Haven',
    'New Hope',
    'New Liberty',
    'Newport',
    'Nicholasville',
    'North Middletown',
    'Nortonville',
    'Oak Grove',
    'Oakland',
    'Oil Springs',
    'Olaton',
    'Olive Hill',
    'Olmstead',
    'Olympia',
    'Oneida',
    'Ophir',
    'Orlando',
    'Owensboro',
    'Owenton',
    'Owingsville',
    'Paducah',
    'Paint Lick',
    'Paintsville',
    'Paris',
    'Park City',
    'Parkers Lake',
    'Parksville',
    'Partridge',
    'Pathfork',
    'Payneville',
    'Pellville',
    'Pembroke',
    'Pendleton',
    'Penrod',
    'Peoples',
    'Perry Park',
    'Perryville',
    'Petersburg',
    'Pewee Valley',
    'Phelps',
    'Philpot',
    'Phyllis',
    'Pikeville',
    'Pilgrim',
    'Pine Knot',
    'Pine Ridge',
    'Pine Top',
    'Pineville',
    'Pinsonfork',
    'Pippa Passes',
    'Pittsburg',
    'Pleasureville',
    'Plummers Landing',
    'Poole',
    'Port Royal',
    'Powderly',
    'Premium',
    'Preston',
    'Prestonsburg',
    'Primrose',
    'Princeton',
    'Printer',
    'Prospect',
    'Providence',
    'Provo',
    'Putney',
    'Quincy',
    'Raccoon',
    'Radcliff',
    'Ransom',
    'Raven',
    'Ravenna',
    'Raywick',
    'Redfox',
    'Reed',
    'Regina',
    'Renfro Valley',
    'Revelo',
    'Reynolds Station',
    'Rhodelia',
    'Ricetown',
    'Richardsville',
    'Richmond',
    'Rineyville',
    'River',
    'Roark',
    'Robards',
    'Robinson Creek',
    'Rochester',
    'Rockfield',
    'Rockholds',
    'Rockhouse',
    'Rockport',
    'Rocky Hill',
    'Rogers',
    'Rosine',
    'Roundhill',
    'Rousseau',
    'Rowdy',
    'Roxana',
    'Royalton',
    'Rumsey',
    'Rush',
    'Russell',
    'Russell Springs',
    'Russellville',
    'Sacramento',
    'Sadieville',
    'Saint Catharine',
    'Saint Charles',
    'Saint Francis',
    'Saint Helens',
    'Saint Mary',
    'Saint Paul',
    'Salem',
    'Salt Lick',
    'Salvisa',
    'Salyersville',
    'Sanders',
    'Sandgap',
    'Sandy Hook',
    'Sassafras',
    'Saul',
    'Scalf',
    'Science Hill',
    'Scottsville',
    'Scuddy',
    'Se Ree',
    'Sebree',
    'Seco',
    'Sedalia',
    'Sextons Creek',
    'Sharon Grove',
    'Sharpsburg',
    'Shelbiana',
    'Shelby Gap',
    'Shelbyville',
    'Shepherdsville',
    'Sidney',
    'Siler',
    'Silver Grove',
    'Simpsonville',
    'Sitka',
    'Sizerock',
    'Slade',
    'Slaughters',
    'Slemp',
    'Smilax',
    'Smith',
    'Smith Mills',
    'Smithfield',
    'Smithland',
    'Smiths Grove',
    'Soldier',
    'Somerset',
    'Sonora',
    'South Carrollton',
    'South Portsmouth',
    'South Shore',
    'South Union',
    'South Williamson',
    'Sparta',
    'Spottsville',
    'Springfield',
    'Staffordsville',
    'Stambaugh',
    'Stamping Ground',
    'Stanford',
    'Stanley',
    'Stanton',
    'Stanville',
    'Stearns',
    'Steele',
    'Stephensport',
    'Stinnett',
    'Stone',
    'Stoney Fork',
    'Stopover',
    'Strunk',
    'Sturgis',
    'Sullivan',
    'Sulphur',
    'Summer Shade',
    'Summersville',
    'Summit',
    'Sweeden',
    'Symsonia',
    'Talbert',
    'Tateville',
    'Taylorsville',
    'Teaberry',
    'Thelma',
    'Thornton',
    'Thousandsticks',
    'Tiline',
    'Tiptonville',
    'Toler',
    'Tollesboro',
    'Tolu',
    'Tomahawk',
    'Tompkinsville',
    'Topmost',
    'Totz',
    'Tram',
    'Trenton',
    'Trosper',
    'Turners Station',
    'Tutor Key',
    'Tyner',
    'Ulysses',
    'Union',
    'Union Star',
    'Uniontown',
    'Upton',
    'Utica',
    'Van Lear',
    'Vanceburg',
    'Vancleve',
    'Varney',
    'Verona',
    'Versailles',
    'Vest',
    'Vicco',
    'Vincent',
    'Vine Grove',
    'Viper',
    'Virgie',
    'Waco',
    'Waddy',
    'Walker',
    'Wallingford',
    'Wallins Creek',
    'Walton',
    'Waneta',
    'Warbranch',
    'Warfield',
    'Warsaw',
    'Washington',
    'Water Valley',
    'Waterview',
    'Waverly',
    'Wayland',
    'Waynesburg',
    'Webbville',
    'Webster',
    'Weeksbury',
    'Welchs Creek',
    'Wellington',
    'Wendover',
    'West Liberty',
    'West Louisville',
    'West Paducah',
    'West Point',
    'West Prestonsburg',
    'West Somerset',
    'West Van Lear',
    'Westport',
    'Westview',
    'Wheatcroft',
    'Wheelwright',
    'Whick',
    'White Mills',
    'White Plains',
    'Whitesburg',
    'Whitesville',
    'Whitley City',
    'Wickliffe',
    'Wildie',
    'Willard',
    'Williamsburg',
    'Williamsport',
    'Williamstown',
    'Willisburg',
    'Wilmore',
    'Winchester',
    'Windsor',
    'Wingo',
    'Winston',
    'Wittensville',
    'Woodbine',
    'Woodburn',
    'Woodbury',
    'Woollum',
    'Wooton',
    'Worthington',
    'Worthville',
    'Wrigley',
    'Yeaddiss',
    'Yerkes',
    'Yosemite',
    'Zoe'
]
