cities = [
    'Abell',
    'Aberdeen',
    'Aberdeen Proving Ground',
    'Abingdon',
    'Accident',
    'Accokeek',
    'Adamstown',
    'Allen',
    'Andrews Air Force Base',
    'Annapolis',
    'Annapolis Junction',
    'Aquasco',
    'Arnold',
    'Ashton',
    'Avenue',
    'Baldwin',
    'Baltimore',
    'Barclay',
    'Barnesville',
    'Barstow',
    'Barton',
    'Beallsville',
    'Bel Air',
    'Bel Air South',
    'Bel Alton',
    'Belcamp',
    'Beltsville',
    'Benedict',
    'Benson',
    'Berlin',
    'Bethesda',
    'Bethlehem',
    'Betterton',
    'Big Pool',
    'Bishopville',
    'Bittinger',
    'Bivalve',
    'Bladensburg',
    'Bloomington',
    'Boonsboro',
    'Boring',
    'Bowie',
    'Boyds',
    'Bozman',
    'Braddock Heights',
    'Brandywine',
    'Brentwood',
    'Brinklow',
    'Brookeville',
    'Brooklandville',
    'Brooklyn',
    'Broomes Island',
    'Brownsville',
    'Brunswick',
    'Bryans Road',
    'Bryantown',
    'Buckeystown',
    'Burkittsville',
    'Burtonsville',
    'Bushwood',
    'Butler',
    'Cabin John',
    'California',
    'Callaway',
    'Cambridge',
    'Capitol Heights',
    'Cascade',
    'Catonsville',
    'Cavetown',
    'Cecilton',
    'Centreville',
    'Chaptico',
    'Charlestown',
    'Charlotte Hall',
    'Chase',
    'Cheltenham',
    'Chesapeake Beach',
    'Chesapeake City',
    'Chester',
    'Chestertown',
    'Chevy Chase',
    'Chewsville',
    'Childs',
    'Church Creek',
    'Church Hill',
    'Churchton',
    'Churchville',
    'Claiborne',
    'Clarksburg',
    'Clarksville',
    'Clear Spring',
    'Clements',
    'Clinton',
    'Cobb Island',
    'Cockeysville',
    'College Park',
    'Colora',
    'Coltons Point',
    'Columbia',
    'Compton',
    'Conowingo',
    'Cooksville',
    'Cordova',
    'Corriganville',
    'Crapo',
    'Crisfield',
    'Crocheron',
    'Crofton',
    'Crownsville',
    'Crumpton',
    'Cumberland',
    'Curtis Bay',
    'Damascus',
    'Dameron',
    'Darlington',
    'Davidsonville',
    'Dayton',
    'Deal Island',
    'Deale',
    'Delmar',
    'Denton',
    'Derwood',
    'Dickerson',
    'District Heights',
    'Dowell',
    'Drayden',
    'Dundalk',
    'Dunkirk',
    'Earleville',
    'East New Market',
    'Easton',
    'Eckhart Mines',
    'Eden',
    'Edgewater',
    'Edgewood',
    'Elk Mills',
    'Elkridge',
    'Elkton',
    'Ellerslie',
    'Ellicott City',
    'Emmitsburg',
    'Essex',
    'Ewell',
    'Fairmount',
    'Fairplay',
    'Fallston',
    'Faulkner',
    'Federalsburg',
    'Finksburg',
    'Fishing Creek',
    'Flintstone',
    'Forest Hill',
    'Fork',
    'Fort George G Meade',
    'Fort Howard',
    'Fort Washington',
    'Frederick',
    'Freeland',
    'Friendship',
    'Friendsville',
    'Frostburg',
    'Fruitland',
    'Fulton',
    'Funkstown',
    'Gaithersburg',
    'Galena',
    'Galesville',
    'Gambrills',
    'Gapland',
    'Garrett Park',
    'Garrison',
    'Georgetown',
    'Germantown',
    'Gibson Island',
    'Girdletree',
    'Glen Arm',
    'Glen Burnie',
    'Glen Echo',
    'Glenelg',
    'Glenn Dale',
    'Glenwood',
    'Glyndon',
    'Goldsboro',
    'Grantsville',
    'Grasonville',
    'Great Mills',
    'Greenbelt',
    'Greensboro',
    'Gunpowder',
    'Gwynn Oak',
    'Hagerstown',
    'Halethorpe',
    'Hampstead',
    'Hancock',
    'Hanover',
    'Harmans',
    'Harwood',
    'Havre De Grace',
    'Hebron',
    'Helen',
    'Henderson',
    'Henryton',
    'Highland',
    'Hillsboro',
    'Hollywood',
    'Hughesville',
    'Hunt Valley',
    'Huntingtown',
    'Hurlock',
    'Hyattsville',
    'Hydes',
    'Ijamsville',
    'Indian Head',
    'Ingleside',
    'Ironsides',
    'Issue',
    'Jarrettsville',
    'Jefferson',
    'Jessup',
    'Joppa',
    'Keedysville',
    'Kennedyville',
    'Kensington',
    'Keymar',
    'Kingsville',
    'Kitzmiller',
    'Knoxville',
    'La Plata',
    'Ladiesburg',
    'Lanham',
    'Laurel',
    'Leonardtown',
    'Lexington Park',
    'Libertytown',
    'Lineboro',
    'Linkwood',
    'Linthicum Heights',
    'Linwood',
    'Lisbon',
    'Little Orleans',
    'Lonaconing',
    'Long Green',
    'Lothian',
    'Loveville',
    'Luke',
    'Lusby',
    'Lutherville Timonium',
    'Madison',
    'Manchester',
    'Manokin',
    'Marbury',
    'Mardela Springs',
    'Marion Station',
    'Marriottsville',
    'Marydel',
    'Maryland Line',
    'Massey',
    'Maugansville',
    'Mayo',
    'Mcdaniel',
    'McHenry',
    'Mechanicsville',
    'Middle River',
    'Middletown',
    'Midland',
    'Midlothian',
    'Millersville',
    'Millington',
    'Monkton',
    'Monrovia',
    'Montgomery Village',
    'Morganza',
    'Mount Airy',
    'Mount Rainier',
    'Mount Savage',
    'Mount Victoria',
    'Myersville',
    'Nanjemoy',
    'Nanticoke',
    'Neavitt',
    'New Market',
    'New Midway',
    'New Windsor',
    'Newark',
    'Newburg',
    'Newcomb',
    'North Beach',
    'North East',
    'Nottingham',
    'Oakland',
    'Ocean City',
    'Odenton',
    'Oldtown',
    'Olney',
    'Owings',
    'Owings Mills',
    'Oxford',
    'Oxon Hill',
    'Park Hall',
    'Parkton',
    'Parkville',
    'Parsonsburg',
    'Pasadena',
    'Patuxent River',
    'Perry Hall',
    'Perry Point',
    'Perryman',
    'Perryville',
    'Phoenix',
    'Pikesville',
    'Piney Point',
    'Pinto',
    'Pittsville',
    'Pocomoke City',
    'Point Of Rocks',
    'Pomfret',
    'Poolesville',
    'Port Deposit',
    'Port Republic',
    'Port Tobacco',
    'Potomac',
    'Powellville',
    'Preston',
    'Price',
    'Prince Frederick',
    'Princess Anne',
    'Pylesville',
    'Quantico',
    'Queen Anne',
    'Queenstown',
    'Randallstown',
    'Rawlings',
    'Rehobeth',
    'Reisterstown',
    'Rhodesdale',
    'Riderwood',
    'Ridge',
    'Ridgely',
    'Rising Sun',
    'Riva',
    'Riverdale',
    'Rock Hall',
    'Rock Point',
    'Rockville',
    'Rocky Ridge',
    'Rohrersville',
    'Rosedale',
    'Royal Oak',
    'Sabillasville',
    'Saint Inigoes',
    'Saint James',
    'Saint Leonard',
    'Saint Marys City',
    'Saint Michaels',
    'Salisbury',
    'Sandy Spring',
    'Savage',
    'Scotland',
    'Secretary',
    'Severn',
    'Severna Park',
    'Shady Side',
    'Sharpsburg',
    'Sharptown',
    'Sherwood',
    'Showell',
    'Silver Spring',
    'Simpsonville',
    'Smithsburg',
    'Snow Hill',
    'Solomons',
    'Southern Md Facility',
    'Sparks Glencoe',
    'Sparrows Point',
    'Spencerville',
    'Spring Gap',
    'Stevenson',
    'Stevensville',
    'Still Pond',
    'Stockton',
    'Street',
    'Suburb Maryland Fac',
    'Sudlersville',
    'Suitland',
    'Sunderland',
    'Swanton',
    'Sykesville',
    'Takoma Park',
    'Tall Timbers',
    'Taneytown',
    'Taylors Island',
    'Temple Hills',
    'Templeville',
    'Thurmont',
    'Tilghman',
    'Toddville',
    'Towson',
    'Tracys Landing',
    'Trappe',
    'Tuscarora',
    'Tyaskin',
    'Tylerton',
    'Union Bridge',
    'Unionville',
    'Upper Fairmount',
    'Upper Falls',
    'Upper Marlboro',
    'Upperco',
    'Valley Lee',
    'Vienna',
    'Waldorf',
    'Walkersville',
    'Warwick',
    'Washington Grove',
    'Welcome',
    'Wenona',
    'West Friendship',
    'West River',
    'Westernport',
    'Westminster',
    'Westover',
    'Whaleyville',
    'White Hall',
    'White Marsh',
    'White Plains',
    'Whiteford',
    'Willards',
    'Williamsport',
    'Windsor Mill',
    'Wingate',
    'Wittman',
    'Woodbine',
    'Woodsboro',
    'Woodstock',
    'Woolford',
    'Worton',
    'Wye Mills'
]
