cities = [
    'Abington',
    'Accord',
    'Acton',
    'Acushnet',
    'Adams',
    'Agawam',
    'Allston',
    'Amesbury',
    'Amherst',
    'Andover',
    'Arlington',
    'Arlington Heights',
    'Ashburnham',
    'Ashby',
    'Ashfield',
    'Ashland',
    'Ashley Falls',
    'Assonet',
    'Athol',
    'Attleboro',
    'Attleboro Falls',
    'Auburn',
    'Auburndale',
    'Avon',
    'Ayer',
    'Babson Park',
    'Baldwinville',
    'Barnstable',
    'Barnstable Town',
    'Barre',
    'Becket',
    'Bedford',
    'Belchertown',
    'Bellingham',
    'Belmont',
    'Berkley',
    'Berkshire',
    'Berlin',
    'Bernardston',
    'Beverly',
    'Billerica',
    'Blackstone',
    'Blandford',
    'Bolton',
    'Bondsville',
    'Boston',
    'Boxborough',
    'Boxford',
    'Boylston',
    'Braintree',
    'Brant Rock',
    'Brewster',
    'Bridgewater',
    'Brighton',
    'Brimfield',
    'Brockton',
    'Brookfield',
    'Brookline',
    'Brookline Village',
    'Bryantville',
    'Buckland',
    'Burlington',
    'Buzzards Bay',
    'Byfield',
    'Cambridge',
    'Canton',
    'Carlisle',
    'Carver',
    'Cataumet',
    'Centerville',
    'Charlemont',
    'Charlestown',
    'Charlton',
    'Charlton City',
    'Charlton Depot',
    'Chartley',
    'Chatham',
    'Chelmsford',
    'Chelsea',
    'Cherry Valley',
    'Cheshire',
    'Chester',
    'Chesterfield',
    'Chestnut Hill',
    'Chicopee',
    'Chilmark',
    'Clinton',
    'Cohasset',
    'Colrain',
    'Concord',
    'Conway',
    'Cotuit',
    'Cummaquid',
    'Cummington',
    'Cuttyhunk',
    'Dalton',
    'Danvers',
    'Dartmouth',
    'Dedham',
    'Deerfield',
    'Dennis',
    'Dennis Port',
    'Dighton',
    'Douglas',
    'Dover',
    'Dracut',
    'Drury',
    'Dudley',
    'Dunstable',
    'Duxbury',
    'East Bridgewater',
    'East Brookfield',
    'East Dennis',
    'East Falmouth',
    'East Freetown',
    'East Longmeadow',
    'East Mansfield',
    'East Orleans',
    'East Otis',
    'East Princeton',
    'East Sandwich',
    'East Taunton',
    'East Templeton',
    'East Walpole',
    'East Wareham',
    'Eastham',
    'Easthampton',
    'Easton',
    'Edgartown',
    'Elmwood',
    'Erving',
    'Essex',
    'Everett',
    'Fairhaven',
    'Fall River',
    'Falmouth',
    'Fayville',
    'Feeding Hills',
    'Fiskdale',
    'Fitchburg',
    'Florence',
    'Forestdale',
    'Foxboro',
    'Foxborough',
    'Framingham',
    'Franklin',
    'Gardner',
    'Georgetown',
    'Gilbertville',
    'Glendale',
    'Gloucester',
    'Goshen',
    'Grafton',
    'Granby',
    'Granville',
    'Great Barrington',
    'Green Harbor',
    'Greenbush',
    'Greenfield',
    'Groton',
    'Groveland',
    'Hadley',
    'Halifax',
    'Hamilton',
    'Hampden',
    'Hanover',
    'Hanscom AFB',
    'Hanson',
    'Hardwick',
    'Harvard',
    'Harwich',
    'Harwich Port',
    'Hatfield',
    'Hathorne',
    'Haverhill',
    'Haydenville',
    'Heath',
    'Hingham',
    'Hinsdale',
    'Holbrook',
    'Holden',
    'Holland',
    'Holliston',
    'Holyoke',
    'Hopedale',
    'Hopkinton',
    'Housatonic',
    'Hubbardston',
    'Hudson',
    'Hull',
    'Humarock',
    'Huntington',
    'Hyannis',
    'Hyannis Port',
    'Hyde Park',
    'Indian Orchard',
    'Ipswich',
    'Jamaica Plain',
    'Jefferson',
    'Kingston',
    'Lake Pleasant',
    'Lakeville',
    'Lancaster',
    'Lanesboro',
    'Lawrence',
    'Lee',
    'Leeds',
    'Leicester',
    'Lenox',
    'Lenox Dale',
    'Leominster',
    'Leverett',
    'Lexington',
    'Lincoln',
    'Linwood',
    'Littleton',
    'Longmeadow',
    'Lowell',
    'Ludlow',
    'Lunenburg',
    'Lynn',
    'Lynnfield',
    'Malden',
    'Manchaug',
    'Manchester',
    'Manomet',
    'Mansfield',
    'Marblehead',
    'Marion',
    'Marlborough',
    'Marshfield',
    'Marshfield Hills',
    'Marstons Mills',
    'Mashpee',
    'Mattapan',
    'Mattapoisett',
    'Maynard',
    'Medfield',
    'Medford',
    'Medway',
    'Melrose',
    'Mendon',
    'Menemsha',
    'Merrimac',
    'Methuen',
    'Middleboro',
    'Middlefield',
    'Middleton',
    'Milford',
    'Mill River',
    'Millbury',
    'Millis',
    'Millville',
    'Milton',
    'Milton Village',
    'Minot',
    'Monponsett',
    'Monroe Bridge',
    'Monson',
    'Montague',
    'Monterey',
    'Monument Beach',
    'Nahant',
    'Nantucket',
    'Natick',
    'Needham',
    'New Bedford',
    'New Braintree',
    'New Salem',
    'New Town',
    'Newbury',
    'Newburyport',
    'Newton',
    'Newton Center',
    'Newton Highlands',
    'Newton Lower Falls',
    'Newton Upper Falls',
    'Newtonville',
    'Nonantum',
    'Norfolk',
    'North Adams',
    'North Amherst',
    'North Andover',
    'North Attleboro',
    'North Billerica',
    'North Brookfield',
    'North Carver',
    'North Chatham',
    'North Chelmsford',
    'North Dartmouth',
    'North Dighton',
    'North Eastham',
    'North Easton',
    'North Egremont',
    'North Falmouth',
    'North Grafton',
    'North Hatfield',
    'North Marshfield',
    'North Oxford',
    'North Pembroke',
    'North Reading',
    'North Scituate',
    'North Truro',
    'North Uxbridge',
    'Northampton',
    'Northborough',
    'Northbridge',
    'Northfield',
    'Norton',
    'Norwell',
    'Norwood',
    'Nutting Lake',
    'Oak Bluffs',
    'Oakham',
    'Ocean Bluff',
    'Onset',
    'Orange',
    'Orleans',
    'Osterville',
    'Otis',
    'Oxford',
    'Palmer',
    'Paxton',
    'Peabody',
    'Pembroke',
    'Pepperell',
    'Petersham',
    'Pinehurst',
    'Pittsfield',
    'Plainfield',
    'Plainville',
    'Plymouth',
    'Plympton',
    'Pocasset',
    'Prides Crossing',
    'Princeton',
    'Provincetown',
    'Quincy',
    'Randolph',
    'Raynham',
    'Raynham Center',
    'Reading',
    'Readville',
    'Rehoboth',
    'Revere',
    'Richmond',
    'Rochdale',
    'Rochester',
    'Rockland',
    'Rockport',
    'Roslindale',
    'Rowe',
    'Rowley',
    'Royalston',
    'Russell',
    'Rutland',
    'Sagamore',
    'Sagamore Beach',
    'Salem',
    'Salisbury',
    'Sandisfield',
    'Sandwich',
    'Saugus',
    'Savoy',
    'Scituate',
    'Seekonk',
    'Sharon',
    'Shattuckville',
    'Sheffield',
    'Shelburne Falls',
    'Sheldonville',
    'Sherborn',
    'Shirley',
    'Shrewsbury',
    'Shutesbury',
    'Siasconset',
    'Silver Beach',
    'Somerset',
    'Somerville',
    'South Barre',
    'South Carver',
    'South Chatham',
    'South Dartmouth',
    'South Deerfield',
    'South Dennis',
    'South Easton',
    'South Egremont',
    'South Grafton',
    'South Hadley',
    'South Hamilton',
    'South Harwich',
    'South Lancaster',
    'South Lee',
    'South Orleans',
    'South Walpole',
    'South Wellfleet',
    'South Yarmouth',
    'Southampton',
    'Southborough',
    'Southbridge',
    'Southfield',
    'Southwick',
    'Spencer',
    'Springfield',
    'Sterling',
    'Still River',
    'Stockbridge',
    'Stoneham',
    'Stoughton',
    'Stow',
    'Sturbridge',
    'Sudbury',
    'Sunderland',
    'Sutton',
    'Swampscott',
    'Swansea',
    'Taunton',
    'Templeton',
    'Tewksbury',
    'Thorndike',
    'Three Rivers',
    'Tolland',
    'Topsfield',
    'Townsend',
    'Truro',
    'Turners Falls',
    'Tyngsboro',
    'Tyringham',
    'Upton',
    'Uxbridge',
    'Village Of Nagog Woods',
    'Vineyard Haven',
    'Waban',
    'Wakefield',
    'Wales',
    'Walpole',
    'Waltham',
    'Ware',
    'Wareham',
    'Warren',
    'Warwick',
    'Watertown',
    'Waverley',
    'Wayland',
    'Webster',
    'Wellesley',
    'Wellesley Hills',
    'Wellfleet',
    'Wendell',
    'Wendell Depot',
    'Wenham',
    'West Barnstable',
    'West Boxford',
    'West Boylston',
    'West Bridgewater',
    'West Brookfield',
    'West Chatham',
    'West Chesterfield',
    'West Dennis',
    'West Falmouth',
    'West Groton',
    'West Harwich',
    'West Hatfield',
    'West Hyannisport',
    'West Medford',
    'West Millbury',
    'West Newbury',
    'West Newton',
    'West Roxbury',
    'West Springfield',
    'West Stockbridge',
    'West Tisbury',
    'West Townsend',
    'West Wareham',
    'West Warren',
    'West Yarmouth',
    'Westborough',
    'Westfield',
    'Westford',
    'Westminster',
    'Weston',
    'Westport',
    'Westport Point',
    'Westwood',
    'Weymouth',
    'Whately',
    'Wheelwright',
    'White Horse Beach',
    'Whitinsville',
    'Whitman',
    'Wilbraham',
    'Williamsburg',
    'Williamstown',
    'Wilmington',
    'Winchendon',
    'Winchendon Springs',
    'Winchester',
    'Windsor',
    'Winthrop',
    'Woburn',
    'Woods Hole',
    'Woodville',
    'Worcester',
    'Woronoco',
    'Worthington',
    'Wrentham',
    'Yarmouth Port'
]
