cities = [
    'Acton',
    'Ada',
    'Adams',
    'Adolph',
    'Adrian',
    'Afton',
    'Ah Gwah Ching',
    'Aitkin',
    'Akeley',
    'Albany',
    'Albert Lea',
    'Alberta',
    'Albertville',
    'Alborn',
    'Alden',
    'Aldrich',
    'Alexandria',
    'Almelund',
    'Alpha',
    'Altura',
    'Alvarado',
    'Amboy',
    'Andover',
    'Angle Inlet',
    'Angora',
    'Angus',
    'Annandale',
    'Anoka',
    'Appleton',
    'Arco',
    'Argyle',
    'Arlington',
    'Ashby',
    'Askov',
    'Atwater',
    'Audubon',
    'Aurora',
    'Austin',
    'Avoca',
    'Avon',
    'Babbitt',
    'Backus',
    'Badger',
    'Bagley',
    'Baker',
    'Balaton',
    'Barnesville',
    'Barnum',
    'Barrett',
    'Barry',
    'Battle Lake',
    'Baudette',
    'Baxter',
    'Bayport',
    'Beardsley',
    'Beaver Bay',
    'Beaver Creek',
    'Becker',
    'Bejou',
    'Belgrade',
    'Belle Plaine',
    'Bellingham',
    'Beltrami',
    'Belview',
    'Bemidji',
    'Bena',
    'Benedict',
    'Benson',
    'Bertha',
    'Bethel',
    'Big Falls',
    'Big Lake',
    'Bigelow',
    'Bigfork',
    'Bingham Lake',
    'Birchdale',
    'Bird Island',
    'Biwabik',
    'Blackduck',
    'Blomkest',
    'Blooming Prairie',
    'Blue Earth',
    'Bluffton',
    'Bock',
    'Borup',
    'Bovey',
    'Bowlus',
    'Bowstring',
    'Boyd',
    'Braham',
    'Brainerd',
    'Brandon',
    'Breckenridge',
    'Brewster',
    'Bricelyn',
    'Brimson',
    'Britt',
    'Brook Park',
    'Brooks',
    'Brookston',
    'Brooten',
    'Browerville',
    'Browns Valley',
    'Brownsdale',
    'Brownsville',
    'Brownton',
    'Bruno',
    'Buckman',
    'Buffalo',
    'Buffalo Lake',
    'Buhl',
    'Burnsville',
    'Burtrum',
    'Butterfield',
    'Byron',
    'Caledonia',
    'Callaway',
    'Calumet',
    'Cambridge',
    'Campbell',
    'Canby',
    'Cannon Falls',
    'Canton',
    'Canyon',
    'Carlos',
    'Carlton',
    'Carver',
    'Cass Lake',
    'Castle Rock',
    'Cedar',
    'Center City',
    'Ceylon',
    'Champlin',
    'Chandler',
    'Chanhassen',
    'Chaska',
    'Chatfield',
    'Chisago City',
    'Chisholm',
    'Chokio',
    'Circle Pines',
    'Clara City',
    'Claremont',
    'Clarissa',
    'Clark',
    'Clarkfield',
    'Clarks Grove',
    'Clear Lake',
    'Clearbrook',
    'Clearwater',
    'Clements',
    'Cleveland',
    'Climax',
    'Clinton',
    'Clitherall',
    'Clontarf',
    'Cloquet',
    'Cohasset',
    'Cokato',
    'Cold Spring',
    'Coleraine',
    'Collegeville',
    'Cologne',
    'Comfrey',
    'Comstock',
    'Conger',
    'Cook',
    'Correll',
    'Cosmos',
    'Cottage Grove',
    'Cotton',
    'Cottonwood',
    'Courtland',
    'Crane Lake',
    'Cromwell',
    'Crookston',
    'Crosby',
    'Crosslake',
    'Crystal Bay',
    'Currie',
    'Cushing',
    'Cyrus',
    'Dakota',
    'Dalbo',
    'Dalton',
    'Danube',
    'Danvers',
    'Darfur',
    'Darwin',
    'Dassel',
    'Dawson',
    'Dayton',
    'Deer Creek',
    'Deer River',
    'Deerwood',
    'Delano',
    'Delavan',
    'Dennison',
    'Dent',
    'Detroit Lakes',
    'Dexter',
    'Dilworth',
    'Dodge Center',
    'Donaldson',
    'Donnelly',
    'Dover',
    'Dovray',
    'Duluth',
    'Dumont',
    'Dundas',
    'Dunnell',
    'Eagle Bend',
    'Eagle Lake',
    'East Grand Forks',
    'Easton',
    'Echo',
    'Eden Prairie',
    'Eden Valley',
    'Edgerton',
    'Effie',
    'Eitzen',
    'Elbow Lake',
    'Elgin',
    'Elizabeth',
    'Elk River',
    'Elko',
    'Elkton',
    'Ellendale',
    'Elrosa',
    'Ely',
    'Elysian',
    'Embarrass',
    'Emily',
    'Emmons',
    'Erhard',
    'Erskine',
    'Esko',
    'Essig',
    'Euclid',
    'Evansville',
    'Eveleth',
    'Excelsior',
    'Eyota',
    'Fairfax',
    'Fairmont',
    'Faribault',
    'Farmington',
    'Farwell',
    'Federal Dam',
    'Felton',
    'Fergus Falls',
    'Fertile',
    'Fifty Lakes',
    'Finland',
    'Finlayson',
    'Fisher',
    'Fleming',
    'Flensburg',
    'Flom',
    'Floodwood',
    'Florence',
    'Foley',
    'Forbes',
    'Forest Lake',
    'Foreston',
    'Fort Ripley',
    'Fosston',
    'Fountain',
    'Foxhome',
    'Franklin',
    'Frazee',
    'Freeborn',
    'Freeport',
    'Frontenac',
    'Frost',
    'Fulda',
    'Garden City',
    'Garfield',
    'Garrison',
    'Garvin',
    'Gary',
    'Gatzke',
    'Gaylord',
    'Geneva',
    'Georgetown',
    'Ghent',
    'Gibbon',
    'Gilbert',
    'Gilman',
    'Glencoe',
    'Glenville',
    'Glenwood',
    'Glyndon',
    'Gonvick',
    'Good Thunder',
    'Goodhue',
    'Goodland',
    'Goodridge',
    'Graceville',
    'Graham Lakes',
    'Granada',
    'Grand Marais',
    'Grand Meadow',
    'Grand Portage',
    'Grand Rapids',
    'Grandy',
    'Granite Falls',
    'Grasston',
    'Green Isle',
    'Greenbush',
    'Greenwald',
    'Grey Eagle',
    'Grove City',
    'Grygla',
    'Gully',
    'Hackensack',
    'Hallock',
    'Halma',
    'Halstad',
    'Hamburg',
    'Hamel',
    'Hampton',
    'Hancock',
    'Hanley Falls',
    'Hanover',
    'Hanska',
    'Hardwick',
    'Harmony',
    'Harris',
    'Hartland',
    'Hastings',
    'Hawick',
    'Hawley',
    'Hayfield',
    'Hayward',
    'Hector',
    'Henderson',
    'Hendricks',
    'Hendrum',
    'Henning',
    'Henriette',
    'Herman',
    'Heron Lake',
    'Hewitt',
    'Hibbing',
    'Hill City',
    'Hillman',
    'Hills',
    'Hinckley',
    'Hines',
    'Hitterdal',
    'Hoffman',
    'Hokah',
    'Holdingford',
    'Holland',
    'Hollandale',
    'Holloway',
    'Holmes City',
    'Holyoke',
    'Homer',
    'Hope',
    'Hopkins',
    'Houston',
    'Hovland',
    'Howard Lake',
    'Hoyt Lakes',
    'Hugo',
    'Humboldt',
    'Huntley',
    'Hutchinson',
    'Ihlen',
    'International Falls',
    'Inver Grove Heights',
    'Iona',
    'Iron',
    'Ironton',
    'Isabella',
    'Isanti',
    'Isle',
    'Itasca',
    'Ivanhoe',
    'Jackson',
    'Jacobson',
    'Janesville',
    'Jasper',
    'Jeffers',
    'Jenkins',
    'Jordan',
    'Kanaranzi',
    'Kandiyohi',
    'Karlstad',
    'Kasota',
    'Kasson',
    'Keewatin',
    'Kelliher',
    'Kellogg',
    'Kennedy',
    'Kenneth',
    'Kensington',
    'Kent',
    'Kenyon',
    'Kerkhoven',
    'Kerrick',
    'Kettle River',
    'Kiester',
    'Kilkenny',
    'Kimball',
    'Kinney',
    'Knife River',
    'Kroschel',
    'La Crescent',
    'La Salle',
    'Lafayette',
    'Lake Benton',
    'Lake Bronson',
    'Lake City',
    'Lake Crystal',
    'Lake Elmo',
    'Lake Eunice',
    'Lake George',
    'Lake Hubert',
    'Lake Lillian',
    'Lake Park',
    'Lake Wilson',
    'Lakefield',
    'Lakeland',
    'Lakeville',
    'Lamberton',
    'Lancaster',
    'Lanesboro',
    'Lansing',
    'Laporte',
    'Lastrup',
    'Le Center',
    'Le Roy',
    'Le Sueur',
    'Lengby',
    'Leonard',
    'Leota',
    'Lester Prairie',
    'Lewiston',
    'Lewisville',
    'Lindstrom',
    'Lismore',
    'Litchfield',
    'Little Falls',
    'Littlefork',
    'Loman',
    'Long Lake',
    'Long Prairie',
    'Longville',
    'Lonsdale',
    'Loretto',
    'Lowry',
    'Lucan',
    'Lutsen',
    'Luverne',
    'Lyle',
    'Lynd',
    'Madelia',
    'Madison',
    'Madison Lake',
    'Magnolia',
    'Mahnomen',
    'Makinen',
    'Manchester',
    'Mankato',
    'Mantorville',
    'Maple Lake',
    'Maple Plain',
    'Mapleton',
    'Marble',
    'Marcell',
    'Margie',
    'Marietta',
    'Marine On Saint Croix',
    'Marshall',
    'Max',
    'Mayer',
    'Maynard',
    'Mazeppa',
    'McGrath',
    'Mcgregor',
    'Mcintosh',
    'McKinley',
    'Meadowlands',
    'Medford',
    'Melrose',
    'Melrude',
    'Menahga',
    'Mendota',
    'Mentor',
    'Merrifield',
    'Middle River',
    'Milaca',
    'Milan',
    'Millville',
    'Milroy',
    'Miltona',
    'Minneapolis',
    'Minneota',
    'Minnesota City',
    'Minnesota Lake',
    'Minnetonka',
    'Minnetonka Beach',
    'Mizpah',
    'Montevideo',
    'Montgomery',
    'Monticello',
    'Montrose',
    'Moorhead',
    'Moose Lake',
    'Mora',
    'Morgan',
    'Morris',
    'Morristown',
    'Morton',
    'Motley',
    'Mound',
    'Mount Morris',
    'Mountain Iron',
    'Mountain Lake',
    'Murdock',
    'Nashua',
    'Nashwauk',
    'Navarre',
    'Naytahwaush',
    'Nelson',
    'Nerstrand',
    'Nett Lake',
    'Nevis',
    'New Auburn',
    'New Germany',
    'New London',
    'New Market',
    'New Munich',
    'New Prague',
    'New Richland',
    'New Ulm',
    'New York Mills',
    'Newfolden',
    'Newport',
    'Nicollet',
    'Nielsville',
    'Nimrod',
    'Nisswa',
    'Norcross',
    'North Branch',
    'Northfield',
    'Northome',
    'Northrop',
    'Norwood',
    'Noyes',
    'Oak Island',
    'Oak Park',
    'Oakland',
    'Odessa',
    'Odin',
    'Ogema',
    'Ogilvie',
    'Okabena',
    'Oklee',
    'Olivia',
    'Onamia',
    'Ormsby',
    'Oronoco',
    'Orr',
    'Ortonville',
    'Osage',
    'Osakis',
    'Oslo',
    'Osseo',
    'Ostrander',
    'Ottertail',
    'Outing',
    'Owatonna',
    'Palisade',
    'Park Rapids',
    'Parkers Prairie',
    'Paynesville',
    'Pease',
    'Pelican Rapids',
    'Pemberton',
    'Pengilly',
    'Pennington',
    'Pennock',
    'Pequot Lakes',
    'Perham',
    'Perley',
    'Peterson',
    'Pierz',
    'Pillager',
    'Pine City',
    'Pine Island',
    'Pine River',
    'Pipestone',
    'Plainview',
    'Plato',
    'Plummer',
    'Ponemah',
    'Ponsford',
    'Porter',
    'Powers',
    'Preston',
    'Princeton',
    'Prinsburg',
    'Prior Lake',
    'Puposky',
    'Racine',
    'Randall',
    'Randolph',
    'Ranier',
    'Ray',
    'Raymond',
    'Reading',
    'Reads Landing',
    'Red Lake Falls',
    'Red Wing',
    'Redby',
    'Redlake',
    'Redwood Falls',
    'Remer',
    'Renville',
    'Revere',
    'Rice',
    'Richmond',
    'Richville',
    'Richwood',
    'Rochert',
    'Rochester',
    'Rock Creek',
    'Rockford',
    'Rockville',
    'Rogers',
    'Rollingstone',
    'Roosevelt',
    'Roscoe',
    'Rose Creek',
    'Roseau',
    'Rosemount',
    'Rothsay',
    'Round Lake',
    'Royalton',
    'Rush City',
    'Rushford',
    'Rushmore',
    'Russell',
    'Ruthton',
    'Sabin',
    'Sacred Heart',
    'Saginaw',
    'Saint Bonifacius',
    'Saint Charles',
    'Saint Clair',
    'Saint Cloud',
    'Saint Francis',
    'Saint Hilaire',
    'Saint James',
    'Saint Joseph',
    'Saint Martin',
    'Saint Michael',
    'Saint Paul',
    'Saint Paul Park',
    'Saint Peter',
    'Saint Stephen',
    'Saint Vincent',
    'Salol',
    'Sanborn',
    'Sandstone',
    'Santiago',
    'Sargeant',
    'Sartell',
    'Sauk Centre',
    'Sauk Rapids',
    'Savage',
    'Sawyer',
    'Scandia',
    'Schroeder',
    'Seaforth',
    'Searles',
    'Sebeka',
    'Shafer',
    'Shakopee',
    'Shelly',
    'Sherburn',
    'Shevlin',
    'Side Lake',
    'Silver Bay',
    'Silver Creek',
    'Silver Lake',
    'Slayton',
    'Sleepy Eye',
    'Solway',
    'Soudan',
    'South Haven',
    'South International Falls',
    'South Saint Paul',
    'Spicer',
    'Spring Grove',
    'Spring Lake',
    'Spring Park',
    'Spring Valley',
    'Springfield',
    'Squaw Lake',
    'St. Leo',
    'Stacy',
    'Stanchfield',
    'Staples',
    'Starbuck',
    'Steen',
    'Stephen',
    'Stewart',
    'Stewartville',
    'Stillwater',
    'Stockton',
    'Storden',
    'Strandquist',
    'Strathcona',
    'Sturgeon Lake',
    'Sunburg',
    'Swan River',
    'Swanville',
    'Swatara',
    'Swift',
    'Taconite',
    'Talmoon',
    'Tamarack',
    'Taopi',
    'Taunton',
    'Taylors Falls',
    'Tenstrike',
    'Thief River Falls',
    'Tintah',
    'Tofte',
    'Tower',
    'Tracy',
    'Trail',
    'Trimont',
    'Trosky',
    'Truman',
    'Twig',
    'Twin Lakes',
    'Twin Valley',
    'Two Harbors',
    'Tyler',
    'Ulen',
    'Underwood',
    'Upsala',
    'Utica',
    'Vergas',
    'Vermillion',
    'Verndale',
    'Vernon Center',
    'Vesta',
    'Victoria',
    'Viking',
    'Villard',
    'Vining',
    'Virginia',
    'Wabasha',
    'Wabasso',
    'Waconia',
    'Wadena',
    'Wahkon',
    'Waite Park',
    'Waldorf',
    'Walker',
    'Walnut Grove',
    'Waltham',
    'Wanamingo',
    'Wanda',
    'Wannaska',
    'Warba',
    'Warren',
    'Warroad',
    'Warsaw',
    'Waseca',
    'Waskish',
    'Watertown',
    'Waterville',
    'Watkins',
    'Watson',
    'Waubun',
    'Waverly',
    'Wayzata',
    'Webster',
    'Welch',
    'Welcome',
    'Wells',
    'Wendell',
    'West Albany',
    'West Concord',
    'West Union',
    'Westbrook',
    'Wheaton',
    'White Earth',
    'Willernie',
    'Williams',
    'Willmar',
    'Willow River',
    'Wilmont',
    'Wilton',
    'Windom',
    'Winger',
    'Winnebago',
    'Winona',
    'Winsted',
    'Winthrop',
    'Winton',
    'Wirt',
    'Wolf Lake',
    'Wolverton',
    'Wood Lake',
    'Woodstock',
    'Worthington',
    'Wrenshall',
    'Wright',
    'Wykoff',
    'Wyoming',
    'Young America',
    'Zimmerman',
    'Zumbro Falls',
    'Zumbrota'
]
