cities = [
    'Absarokee',
    'Acton',
    'Alberton',
    'Alder',
    'Alzada',
    'Anaconda',
    'Angela',
    'Antelope',
    'Arlee',
    'Ashland',
    'Augusta',
    'Avon',
    'Babb',
    'Bainville',
    'Baker',
    'Ballantine',
    'Basin',
    'Bearcreek',
    'Belfry',
    'Belgrade',
    'Belt',
    'Biddle',
    'Big Arm',
    'Big Sandy',
    'Big Sky',
    'Big Timber',
    'Bigfork',
    'Bighorn',
    'Billings',
    'Birney',
    'Black Eagle',
    'Bloomfield',
    'Bonner',
    'Boulder',
    'Box Elder',
    'Boyd',
    'Boyes',
    'Bozeman',
    'Brady',
    'Bridger',
    'Broadus',
    'Broadview',
    'Brockton',
    'Brockway',
    'Browning',
    'Brusett',
    'Buffalo',
    'Busby',
    'Butte',
    'Bynum',
    'Cameron',
    'Canyon Creek',
    'Capitol',
    'Cardwell',
    'Carter',
    'Cascade',
    'Charlo',
    'Chester',
    'Chinook',
    'Choteau',
    'Circle',
    'Clancy',
    'Clinton',
    'Clyde Park',
    'Coffee Creek',
    'Cohagen',
    'Colstrip',
    'Columbia Falls',
    'Columbus',
    'Condon',
    'Conner',
    'Conrad',
    'Cooke City',
    'Coram',
    'Corvallis',
    'Crane',
    'Crow Agency',
    'Culbertson',
    'Custer',
    'Cut Bank',
    'Dagmar',
    'Darby',
    'Dayton',
    'De Borgia',
    'Decker',
    'Deer Lodge',
    'Dell',
    'Denton',
    'Dillon',
    'Divide',
    'Dixon',
    'Dodson',
    'Drummond',
    'Dupuyer',
    'Dutton',
    'East Glacier Park',
    'East Helena',
    'Edgar',
    'Ekalaka',
    'Elliston',
    'Elmo',
    'Emigrant',
    'Ennis',
    'Essex',
    'Ethridge',
    'Eureka',
    'Fairfield',
    'Fairview',
    'Fallon',
    'Fishtail',
    'Flaxville',
    'Florence',
    'Floweree',
    'Forestgrove',
    'Forsyth',
    'Fort Benton',
    'Fort Harrison',
    'Fort Peck',
    'Fort Shaw',
    'Fortine',
    'Four Corners',
    'Frazer',
    'Frenchtown',
    'Froid',
    'Fromberg',
    'Galata',
    'Gallatin Gateway',
    'Gardiner',
    'Garneill',
    'Garrison',
    'Garryowen',
    'Geraldine',
    'Geyser',
    'Gildford',
    'Glasgow',
    'Glen',
    'Glendive',
    'Glentana',
    'Gold Creek',
    'Grantsdale',
    'Grass Range',
    'Great Falls',
    'Greenough',
    'Greycliff',
    'Hall',
    'Hamilton',
    'Hammond',
    'Hardin',
    'Harlem',
    'Harlowton',
    'Harrison',
    'Hathaway',
    'Haugan',
    'Havre',
    'Hays',
    'Heart Butte',
    'Helena',
    'Helmville',
    'Heron',
    'Highwood',
    'Hilger',
    'Hingham',
    'Hinsdale',
    'Hobson',
    'Hogeland',
    'Homestead',
    'Hot Springs',
    'Hungry Horse',
    'Huntley',
    'Huson',
    'Hysham',
    'Ingomar',
    'Inverness',
    'Ismay',
    'Jackson',
    'Jefferson City',
    'Joliet',
    'Joplin',
    'Jordan',
    'Judith Gap',
    'Kalispell',
    'Kevin',
    'Kila',
    'Kinsey',
    'Kremlin',
    'Lake McDonald',
    'Lakeside',
    'Lambert',
    'Lame Deer',
    'Larslan',
    'Laurel',
    'Lavina',
    'Ledger',
    'Lewistown',
    'Libby',
    'Lima',
    'Lincoln',
    'Lindsay',
    'Livingston',
    'Lloyd',
    'Lodge Grass',
    'Lolo',
    'Loma',
    'Lonepine',
    'Loring',
    'Lothair',
    'Malmstrom A F B',
    'Malta',
    'Manhattan',
    'Marion',
    'Martin City',
    'Martinsdale',
    'Marysville',
    'McAllister',
    'McCabe',
    'McLeod',
    'Medicine Lake',
    'Melrose',
    'Melstone',
    'Melville',
    'Mildred',
    'Miles City',
    'Milltown',
    'Missoula',
    'Moccasin',
    'Molt',
    'Monarch',
    'Moore',
    'Mosby',
    'Musselshell',
    'Nashua',
    'Neihart',
    'Norris',
    'Noxon',
    'Nye',
    'Oilmont',
    'Olive',
    'Olney',
    'Opheim',
    'Otter',
    'Outlook',
    'Ovando',
    'Pablo',
    'Paradise',
    'Park City',
    'Peerless',
    'Pendroy',
    'Philipsburg',
    'Pinesdale',
    'Plains',
    'Plentywood',
    'Plevna',
    'Polaris',
    'Polebridge',
    'Polson',
    'Pompeys Pillar',
    'Pony',
    'Poplar',
    'Powderville',
    'Power',
    'Pray',
    'Proctor',
    'Pryor',
    'Radersburg',
    'Ramsay',
    'Rapelje',
    'Ravalli',
    'Raymond',
    'Raynesford',
    'Red Lodge',
    'Redstone',
    'Reed Point',
    'Reserve',
    'Rexford',
    'Richey',
    'Richland',
    'Ringling',
    'Roberts',
    'Rollins',
    'Ronan',
    'Roscoe',
    'Rosebud',
    'Roundup',
    'Roy',
    'Rudyard',
    'Ryegate',
    'Saco',
    'Saint Ignatius',
    'Saint Marie',
    'Saint Regis',
    'Saint Xavier',
    'Saltese',
    'Sand Coulee',
    'Sand Springs',
    'Sanders',
    'Santa Rita',
    'Savage',
    'Scobey',
    'Seeley Lake',
    'Shawmut',
    'Shelby',
    'Shepherd',
    'Sheridan',
    'Sidney',
    'Silver Gate',
    'Silver Star',
    'Simms',
    'Somers',
    'Sonnette',
    'Springdale',
    'Stanford',
    'Stevensville',
    'Stockett',
    'Stryker',
    'Sula',
    'Sumatra',
    'Sun River',
    'Sunburst',
    'Superior',
    'Sweet Grass',
    'Teigen',
    'Terry',
    'Thompson Falls',
    'Three Forks',
    'Toston',
    'Townsend',
    'Trego',
    'Trout Creek',
    'Troy',
    'Turner',
    'Twin Bridges',
    'Two Dot',
    'Ulm',
    'Valier',
    'Vandalia',
    'Vaughn',
    'Victor',
    'Vida',
    'Virginia City',
    'Volborg',
    'Warm Springs',
    'West Glacier',
    'West Yellowstone',
    'Westby',
    'White Sulphur Springs',
    'Whitefish',
    'Whitehall',
    'Whitetail',
    'Whitewater',
    'Whitlash',
    'Wibaux',
    'Willard',
    'Willow Creek',
    'Wilsall',
    'Winifred',
    'Winnett',
    'Winston',
    'Wisdom',
    'Wise River',
    'Wolf Creek',
    'Wolf Point',
    'Worden',
    'Wyola',
    'Yellowtail',
    'Zortman',
    'Zurich'
]
