cities = [
    'Abie',
    'Adams',
    'Ainsworth',
    'Albion',
    'Alda',
    'Alexandria',
    'Allen',
    'Alliance',
    'Alma',
    'Alvo',
    'Amelia',
    'Ames',
    'Amherst',
    'Angora',
    'Anselmo',
    'Ansley',
    'Arapahoe',
    'Arcadia',
    'Archer',
    'Arlington',
    'Arnold',
    'Arthur',
    'Ashby',
    'Ashland',
    'Ashton',
    'Atkinson',
    'Atlanta',
    'Auburn',
    'Aurora',
    'Avoca',
    'Axtell',
    'Ayr',
    'Bancroft',
    'Barneston',
    'Bartlett',
    'Bartley',
    'Bassett',
    'Battle Creek',
    'Bayard',
    'Beatrice',
    'Beaver City',
    'Beaver Crossing',
    'Bee',
    'Beemer',
    'Belden',
    'Belgrade',
    'Bellevue',
    'Bellwood',
    'Belvidere',
    'Benedict',
    'Benkelman',
    'Bennet',
    'Bennington',
    'Bertrand',
    'Berwyn',
    'Big Springs',
    'Bingham',
    'Bladen',
    'Blair',
    'Bloomfield',
    'Bloomington',
    'Blue Hill',
    'Blue Springs',
    'Boelus',
    'Boys Town',
    'Bradshaw',
    'Brady',
    'Brainard',
    'Brewster',
    'Bridgeport',
    'Bristow',
    'Broadwater',
    'Brock',
    'Broken Bow',
    'Brownville',
    'Brule',
    'Bruning',
    'Bruno',
    'Brunswick',
    'Burchard',
    'Burr',
    'Burwell',
    'Bushnell',
    'Butte',
    'Byron',
    'Cairo',
    'Callaway',
    'Cambridge',
    'Campbell',
    'Carleton',
    'Carroll',
    'Cedar Bluffs',
    'Cedar Creek',
    'Cedar Rapids',
    'Center',
    'Central City',
    'Ceresco',
    'Chadron',
    'Chambers',
    'Champion',
    'Chapman',
    'Chappell',
    'Chester',
    'Clarks',
    'Clarkson',
    'Clatonia',
    'Clay Center',
    'Clearwater',
    'Cody',
    'Coleridge',
    'Colon',
    'Columbus',
    'Comstock',
    'Concord',
    'Cook',
    'Cordova',
    'Cortland',
    'Cozad',
    'Crab Orchard',
    'Craig',
    'Crawford',
    'Creighton',
    'Creston',
    'Crete',
    'Crofton',
    'Crookston',
    'Culbertson',
    'Curtis',
    'Dakota City',
    'Dalton',
    'Danbury',
    'Dannebrog',
    'Davenport',
    'Davey',
    'David City',
    'Dawson',
    'Daykin',
    'De Witt',
    'Decatur',
    'Denton',
    'Deshler',
    'Deweese',
    'Dickens',
    'Diller',
    'Dix',
    'Dixon',
    'Dodge',
    'Doniphan',
    'Dorchester',
    'Douglas',
    'Du Bois',
    'Dunbar',
    'Duncan',
    'Dunning',
    'Dwight',
    'Eagle',
    'Eddyville',
    'Edgar',
    'Edison',
    'Elba',
    'Elgin',
    'Elk Creek',
    'Elkhorn',
    'Ellsworth',
    'Elm Creek',
    'Elmwood',
    'Elsie',
    'Elsmere',
    'Elwood',
    'Elyria',
    'Emerson',
    'Emmet',
    'Enders',
    'Endicott',
    'Ericson',
    'Eustis',
    'Ewing',
    'Exeter',
    'Fairbury',
    'Fairfield',
    'Fairmont',
    'Falls City',
    'Farnam',
    'Farwell',
    'Filley',
    'Firth',
    'Fordyce',
    'Fort Calhoun',
    'Foster',
    'Franklin',
    'Fremont',
    'Friend',
    'Fullerton',
    'Funk',
    'Garland',
    'Geneva',
    'Genoa',
    'Gering',
    'Gibbon',
    'Gilead',
    'Giltner',
    'Glenvil',
    'Goehner',
    'Gordon',
    'Gothenburg',
    'Grafton',
    'Grand Island',
    'Grant',
    'Greeley',
    'Greenwood',
    'Gresham',
    'Gretna',
    'Guide Rock',
    'Gurley',
    'Hadar',
    'Haigler',
    'Hallam',
    'Halsey',
    'Hamlet',
    'Hampton',
    'Hardy',
    'Harrisburg',
    'Harrison',
    'Hartington',
    'Harvard',
    'Hastings',
    'Hay Springs',
    'Hayes Center',
    'Hazard',
    'Heartwell',
    'Hebron',
    'Hemingford',
    'Henderson',
    'Hendley',
    'Henry',
    'Herman',
    'Hershey',
    'Hickman',
    'Hildreth',
    'Holbrook',
    'Holdrege',
    'Holmesville',
    'Holstein',
    'Homer',
    'Hooper',
    'Hordville',
    'Hoskins',
    'Howells',
    'Hubbard',
    'Hubbell',
    'Humboldt',
    'Humphrey',
    'Hyannis',
    'Imperial',
    'Inavale',
    'Indianola',
    'Inland',
    'Inman',
    'Ithaca',
    'Jackson',
    'Jansen',
    'Johnson',
    'Johnstown',
    'Juniata',
    'Kearney',
    'Kenesaw',
    'Kennard',
    'Keystone',
    'Kilgore',
    'Kimball',
    'La Vista',
    'Lakeside',
    'Laurel',
    'Lawrence',
    'Lebanon',
    'Leigh',
    'Lemoyne',
    'Leshara',
    'Lewellen',
    'Lewiston',
    'Lexington',
    'Liberty',
    'Lincoln',
    'Lindsay',
    'Linwood',
    'Lisco',
    'Litchfield',
    'Lodgepole',
    'Long Pine',
    'Loomis',
    'Lorton',
    'Louisville',
    'Loup City',
    'Lyman',
    'Lynch',
    'Lyons',
    'Macy',
    'Madison',
    'Madrid',
    'Magnet',
    'Malcolm',
    'Malmo',
    'Manley',
    'Marquette',
    'Marsland',
    'Martell',
    'Martin',
    'Maskell',
    'Mason City',
    'Max',
    'Maxwell',
    'Maywood',
    'McCook',
    'McCool Junction',
    'Mcgrew',
    'Mclean',
    'Mead',
    'Meadow Grove',
    'Melbeta',
    'Memphis',
    'Merna',
    'Merriman',
    'Milford',
    'Miller',
    'Milligan',
    'Mills',
    'Minatare',
    'Minden',
    'Mitchell',
    'Monroe',
    'Moorefield',
    'Morrill',
    'Morse Bluff',
    'Mullen',
    'Murdock',
    'Murray',
    'Naper',
    'Naponee',
    'Nebraska City',
    'Nehawka',
    'Neligh',
    'Nelson',
    'Nemaha',
    'Nenzel',
    'Newcastle',
    'Newman Grove',
    'Newport',
    'Nickerson',
    'Niobrara',
    'Norfolk',
    'Norman',
    'North Bend',
    'North Loup',
    'North Platte',
    'Oak',
    'Oakdale',
    'Oakland',
    'Oconto',
    'Odell',
    'Odessa',
    'Offutt A F B',
    'Ogallala',
    'Ohiowa',
    'Omaha',
    'Oneill',
    'Ong',
    'Orchard',
    'Ord',
    'Orleans',
    'Osceola',
    'Oshkosh',
    'Osmond',
    'Otoe',
    'Overton',
    'Oxford',
    'Page',
    'Palisade',
    'Palmer',
    'Palmyra',
    'Panama',
    'Papillion',
    'Parks',
    'Pawnee City',
    'Paxton',
    'Pender',
    'Peru',
    'Petersburg',
    'Phillips',
    'Pickrell',
    'Pierce',
    'Pilger',
    'Pine Bluffs',
    'Plainview',
    'Platte Center',
    'Plattsmouth',
    'Pleasant Dale',
    'Pleasanton',
    'Plymouth',
    'Polk',
    'Ponca',
    'Potter',
    'Prague',
    'Primrose',
    'Purdum',
    'Ragan',
    'Randolph',
    'Ravenna',
    'Raymond',
    'Red Cloud',
    'Republican City',
    'Reynolds',
    'Richfield',
    'Rising City',
    'Riverdale',
    'Riverton',
    'Roca',
    'Rockville',
    'Rogers',
    'Rosalie',
    'Rose',
    'Roseland',
    'Royal',
    'Rulo',
    'Rushville',
    'Ruskin',
    'Saint Edward',
    'Saint Helena',
    'Saint Libory',
    'Saint Paul',
    'Salem',
    'Sargent',
    'Saronville',
    'Schuyler',
    'Scotia',
    'Scottsbluff',
    'Scribner',
    'Seneca',
    'Seward',
    'Shelby',
    'Shelton',
    'Shickley',
    'Shubert',
    'Sidney',
    'Silver Creek',
    'Smithfield',
    'Snyder',
    'South Bend',
    'South Sioux City',
    'Spalding',
    'Sparks',
    'Spencer',
    'Sprague',
    'Springfield',
    'Springview',
    'St Columbans',
    'Stamford',
    'Stanton',
    'Staplehurst',
    'Stapleton',
    'Steele City',
    'Steinauer',
    'Stella',
    'Sterling',
    'Stockville',
    'Strang',
    'Stratton',
    'Stromsburg',
    'Stuart',
    'Sumner',
    'Superior',
    'Surprise',
    'Sutherland',
    'Sutton',
    'Swanton',
    'Syracuse',
    'Table Rock',
    'Talmage',
    'Taylor',
    'Tecumseh',
    'Tekamah',
    'Thedford',
    'Thurston',
    'Tilden',
    'Tobias',
    'Trenton',
    'Trumbull',
    'Tryon',
    'Uehling',
    'Ulysses',
    'Unadilla',
    'Union',
    'Upland',
    'Utica',
    'Valentine',
    'Valley',
    'Valparaiso',
    'Venango',
    'Verdel',
    'Verdigre',
    'Verdon',
    'Virginia',
    'Waco',
    'Wahoo',
    'Wakefield',
    'Wallace',
    'Walthill',
    'Walton',
    'Washington',
    'Waterbury',
    'Waterloo',
    'Wauneta',
    'Wausa',
    'Waverly',
    'Wayne',
    'Weeping Water',
    'Weissert',
    'Wellfleet',
    'West Point',
    'Western',
    'Westerville',
    'Weston',
    'Whiteclay',
    'Whitman',
    'Whitney',
    'Wilber',
    'Wilcox',
    'Willow Island',
    'Wilsonville',
    'Winnebago',
    'Winnetoon',
    'Winside',
    'Winslow',
    'Wisner',
    'Wolbach',
    'Wood Lake',
    'Wood River',
    'Wymore',
    'Wynot',
    'York',
    'Yutan'
]
