cities = [
    'Acworth',
    'Alstead',
    'Alton',
    'Alton Bay',
    'Amherst',
    'Andover',
    'Antrim',
    'Ashland',
    'Ashuelot',
    'Atkinson',
    'Auburn',
    'Barnstead',
    'Barrington',
    'Bartlett',
    'Bath',
    'Bedford',
    'Belmont',
    'Bennington',
    'Berlin',
    'Bethlehem',
    'Bow',
    'Bradford',
    'Bretton Woods',
    'Bristol',
    'Brookline',
    'Campton',
    'Canaan',
    'Candia',
    'Canterbury',
    'Center Barnstead',
    'Center Conway',
    'Center Harbor',
    'Center Ossipee',
    'Center Sandwich',
    'Center Strafford',
    'Center Tuftonboro',
    'Charlestown',
    'Chester',
    'Chesterfield',
    'Chichester',
    'Chocorua',
    'Claremont',
    'Colebrook',
    'Concord',
    'Contoocook',
    'Conway',
    'Cornish',
    'Cornish Flat',
    'Danbury',
    'Danville',
    'Deerfield',
    'Derry',
    'Dover',
    'Drewsville',
    'Dublin',
    'Dunbarton',
    'Durham',
    'East Andover',
    'East Candia',
    'East Derry',
    'East Hampstead',
    'East Hebron',
    'East Kingston',
    'East Wakefield',
    'Eaton Center',
    'Elkins',
    'Enfield',
    'Enfield Center',
    'Epping',
    'Epsom',
    'Errol',
    'Etna',
    'Exeter',
    'Farmington',
    'Fitzwilliam',
    'Francestown',
    'Franconia',
    'Franklin',
    'Freedom',
    'Fremont',
    'Georges Mills',
    'Gilmanton',
    'Gilmanton Iron Works',
    'Gilsum',
    'Glen',
    'Glencliff',
    'Goffstown',
    'Gorham',
    'Goshen',
    'Grafton',
    'Grantham',
    'Greenfield',
    'Greenland',
    'Greenville',
    'Groveton',
    'Guild',
    'Hampstead',
    'Hampton',
    'Hampton Falls',
    'Hancock',
    'Hanover',
    'Harrisville',
    'Haverhill',
    'Hebron',
    'Henniker',
    'Hill',
    'Hillsboro',
    'Hinsdale',
    'Holderness',
    'Hollis',
    'Hooksett',
    'Hudson',
    'Intervale',
    'Jackson',
    'Jaffrey',
    'Jefferson',
    'Kearsarge',
    'Keene',
    'Kingston',
    'Laconia',
    'Lancaster',
    'Landaff',
    'Lebanon',
    'Lempster',
    'Lincoln',
    'Lisbon',
    'Litchfield',
    'Littleton',
    'Lochmere',
    'Londonderry',
    'Loudon',
    'Lyme',
    'Lyme Center',
    'Lyndeborough',
    'Madison',
    'Manchester',
    'Marlborough',
    'Marlow',
    'Meadows',
    'Melvin Village',
    'Meredith',
    'Meriden',
    'Merrimack',
    'Milan',
    'Milford',
    'Milton',
    'Milton Mills',
    'Mirror Lake',
    'Monroe',
    'Mont Vernon',
    'Moultonborough',
    'Mount Washington',
    'Munsonville',
    'Nashua',
    'New Boston',
    'New Castle',
    'New Durham',
    'New Hampton',
    'New Ipswich',
    'New London',
    'Newbury',
    'Newfields',
    'Newmarket',
    'Newport',
    'Newton',
    'Newton Junction',
    'North Conway',
    'North Hampton',
    'North Haverhill',
    'North Salem',
    'North Sandwich',
    'North Stratford',
    'North Sutton',
    'North Walpole',
    'North Woodstock',
    'Northwood',
    'Nottingham',
    'Orford',
    'Ossipee',
    'Pelham',
    'Peterborough',
    'Piermont',
    'Pike',
    'Pittsburg',
    'Pittsfield',
    'Plainfield',
    'Plaistow',
    'Plymouth',
    'Portsmouth',
    'Raymond',
    'Rindge',
    'Rochester',
    'Rollinsford',
    'Rumney',
    'Rye',
    'Rye Beach',
    'Salem',
    'Salisbury',
    'Sanbornton',
    'Sanbornville',
    'Sandown',
    'Seabrook',
    'Sharon',
    'Silver Lake',
    'Somersworth',
    'South Acworth',
    'South Effingham',
    'South Newbury',
    'South Sutton',
    'South Tamworth',
    'Spofford',
    'Springfield',
    'Stinson Lake',
    'Stoddard',
    'Strafford',
    'Stratham',
    'Sullivan',
    'Sunapee',
    'Suncook',
    'Swanzey',
    'Tamworth',
    'Temple',
    'Tilton',
    'Troy',
    'Twin Mountain',
    'Union',
    'Walpole',
    'Warner',
    'Warren',
    'Washington',
    'Waterville Valley',
    'Weare',
    'Wentworth',
    'West Chesterfield',
    'West Lebanon',
    'West Nottingham',
    'West Ossipee',
    'West Peterborough',
    'West Stewartstown',
    'West Swanzey',
    'Westmoreland',
    'Whitefield',
    'Wilmot',
    'Wilton',
    'Winchester',
    'Windham',
    'Winnisquam',
    'Wolfeboro',
    'Wolfeboro Falls',
    'Wonalancet',
    'Woodstock',
    'Woodsville'
]
