cities = [
    'Abiquiu',
    'Alamogordo',
    'Albuquerque',
    'Alcalde',
    'Algodones',
    'Alto',
    'Amalia',
    'Amistad',
    'Angel Fire',
    'Animas',
    'Anthony',
    'Anton Chico',
    'Aragon',
    'Arenas Valley',
    'Arrey',
    'Arroyo Hondo',
    'Arroyo Seco',
    'Artesia',
    'Aztec',
    'Bard',
    'Bayard',
    'Belen',
    'Bell Ranch',
    'Bent',
    'Berino',
    'Bernalillo',
    'Blanco',
    'Bloomfield',
    'Bluewater',
    'Boles Acres',
    'Bosque',
    'Bosque Farms',
    'Brimhall',
    'Broadview',
    'Buckhorn',
    'Buena Vista',
    'Caballo',
    'Canjilon',
    'Cannon AFB',
    'Canones',
    'Capitan',
    'Caprock',
    'Capulin',
    'Carlsbad',
    'Carrizozo',
    'Carson',
    'Casa Blanca',
    'Causey',
    'Cebolla',
    'Cedar Crest',
    'Cedarvale',
    'Cerrillos',
    'Cerro',
    'Chacon',
    'Chama',
    'Chamberino',
    'Chamisal',
    'Chaparral',
    'Chimayo',
    'Church Rock',
    'Cimarron',
    'Claunch',
    'Clayton',
    'Cleveland',
    'Cliff',
    'Clines Corners',
    'Cloudcroft',
    'Clovis',
    'Cochiti Lake',
    'Cochiti Pueblo',
    'Columbus',
    'Conchas Dam',
    'Continental Divide',
    'Cordova',
    'Corona',
    'Corrales',
    'Costilla',
    'Counselor',
    'Coyote',
    'Crossroads',
    'Crownpoint',
    'Cuba',
    'Cubero',
    'Cuervo',
    'Datil',
    'Deming',
    'Derry',
    'Des Moines',
    'Dexter',
    'Dixon',
    'Dona Ana',
    'Dora',
    'Dulce',
    'Eagle Nest',
    'Edgewood',
    'El Paso',
    'El Prado',
    'El Rito',
    'Elephant Butte',
    'Elida',
    'Embudo',
    'Encino',
    'Espanola',
    'Estancia',
    'Eunice',
    'Fairacres',
    'Farmington',
    'Faywood',
    'Fence Lake',
    'Flora Vista',
    'Floyd',
    'Folsom',
    'Fort Bayard',
    'Fort Stanton',
    'Fort Sumner',
    'Fort Wingate',
    'Fruitland',
    'Gallina',
    'Gallup',
    'Gamerco',
    'Garfield',
    'Garita',
    'Gila',
    'Gladstone',
    'Glencoe',
    'Glenwood',
    'Glorieta',
    'Grady',
    'Grants',
    'Grenville',
    'Guadalupita',
    'Hachita',
    'Hagerman',
    'Hanover',
    'Hatch',
    'Hernandez',
    'High Rolls Mountain Park',
    'Hillsboro',
    'Hobbs',
    'Holloman Air Force Base',
    'Holman',
    'Hondo',
    'Hope',
    'House',
    'Hurley',
    'Ilfeld',
    'Isleta',
    'Jal',
    'Jamestown',
    'Jarales',
    'Jemez Pueblo',
    'Jemez Springs',
    'Kenna',
    'Kirtland',
    'Kirtland AFB',
    'La Jara',
    'La Joya',
    'La Loma',
    'La Luz',
    'La Madera',
    'La Mesa',
    'La Plata',
    'Laguna',
    'Lake Arthur',
    'Lakewood',
    'Lamy',
    'Las Cruces',
    'Las Vegas',
    'Lemitar',
    'Lincoln',
    'Lindrith',
    'Lingo',
    'Llano',
    'Loco Hills',
    'Logan',
    'Lordsburg',
    'Los Alamos',
    'Los Lunas',
    'Los Ojos',
    'Loving',
    'Lovington',
    'Luna',
    'Magdalena',
    'Malaga',
    'Maljamar',
    'Maxwell',
    'Mayhill',
    'McAlister',
    'McDonald',
    'McIntosh',
    'Medanales',
    'Melrose',
    'Mentmore',
    'Mescalero',
    'Mesilla',
    'Mesilla Park',
    'Mesquite',
    'Mexican Springs',
    'Miami',
    'Milan',
    'Mills',
    'Milnesand',
    'Mimbres',
    'Montezuma',
    'Monticello',
    'Monument',
    'Mora',
    'Moriarty',
    'Mosquero',
    'Mount Dora',
    'Mountainair',
    'Mule Creek',
    'Nageezi',
    'Nara Visa',
    'Navajo',
    'Navajo Dam',
    'New Laguna',
    'Newcomb',
    'Newkirk',
    'Nogal',
    'Ocate',
    'Ojo Caliente',
    'Ojo Feliz',
    'Organ',
    'Orogrande',
    'Paguate',
    'Pecos',
    'Pena Blanca',
    'Penasco',
    'Pep',
    'Peralta',
    'Petaca',
    'Picacho',
    'Pie Town',
    'Pinehill',
    'Pinon',
    'Pinos Altos',
    'Placitas',
    'Playas',
    'Polvadera',
    'Ponderosa',
    'Portales',
    'Prewitt',
    'Pueblo Of Acoma',
    'Quay',
    'Quemado',
    'Questa',
    'Radium Springs',
    'Rainsville',
    'Ramah',
    'Ranchos De Taos',
    'Raton',
    'Red River',
    'Redrock',
    'Regina',
    'Rehoboth',
    'Reserve',
    'Ribera',
    'Rincon',
    'Rio Rancho',
    'Rociada',
    'Rodeo',
    'Rogers',
    'Roswell',
    'Rowe',
    'Roy',
    'Ruidoso',
    'Ruidoso Downs',
    'Sacramento',
    'Saint Vrain',
    'Salem',
    'San Acacia',
    'San Antonio',
    'San Cristobal',
    'San Fidel',
    'San Jon',
    'San Jose',
    'San Juan Pueblo',
    'San Miguel',
    'San Patricio',
    'San Rafael',
    'San Ysidro',
    'Sandia Park',
    'Sanostee',
    'Santa Clara',
    'Santa Cruz',
    'Santa Fe',
    'Santa Rosa',
    'Santa Teresa',
    'Santo Domingo Pueblo',
    'Sapello',
    'Sedan',
    'Seneca',
    'Serafina',
    'Sheep Springs',
    'Shiprock',
    'Silver City',
    'Smith Lake',
    'Socorro',
    'Solano',
    'Springer',
    'Stanley',
    'Sunland Park',
    'Sunspot',
    'Taiban',
    'Tajique',
    'Taos',
    'Taos Ski Valley',
    'Tatum',
    'Tererro',
    'Tesuque',
    'Texico',
    'Thoreau',
    'Tierra Amarilla',
    'Tijeras',
    'Timberon',
    'Tinnie',
    'Tohatchi',
    'Tome',
    'Torreon',
    'Trampas',
    'Trementina',
    'Tres Piedras',
    'Truchas',
    'Truth Or Consequences',
    'Tucumcari',
    'Tularosa',
    'Tyrone',
    'Ute Park',
    'Vadito',
    'Vado',
    'Valdez',
    'Vallecitos',
    'Valmora',
    'Vanderwagen',
    'Vaughn',
    'Veguita',
    'Velarde',
    'Villanueva',
    'Wagon Mound',
    'Waterflow',
    'Watrous',
    'Weed',
    'White Sands Missile Range',
    'Whites City',
    'Willard',
    'Williamsburg',
    'Winston',
    'Yatahey',
    'Yeso',
    'Youngsville',
    'Zuni'
]
