cities = [
    'Accord',
    'Acra',
    'Adams',
    'Adams Basin',
    'Adams Center',
    'Addison',
    'Adirondack',
    'Afton',
    'Akron',
    'Alabama',
    'Albany',
    'Albertson',
    'Albion',
    'Alcove',
    'Alden',
    'Alder Creek',
    'Alexander',
    'Alexandria Bay',
    'Alfred',
    'Alfred Station',
    'Allegany',
    'Allentown',
    'Alma',
    'Almond',
    'Alpine',
    'Alplaus',
    'Altamont',
    'Altmar',
    'Alton',
    'Altona',
    'Amagansett',
    'Amawalk',
    'Amenia',
    'Amityville',
    'Amsterdam',
    'Ancram',
    'Ancramdale',
    'Andes',
    'Andover',
    'Angelica',
    'Angola',
    'Annandale On Hudson',
    'Antwerp',
    'Apalachin',
    'Appleton',
    'Apulia Station',
    'Aquebogue',
    'Arcade',
    'Arden',
    'Ardsley',
    'Ardsley On Hudson',
    'Argyle',
    'Arkport',
    'Arkville',
    'Armonk',
    'Arverne',
    'Ashland',
    'Ashville',
    'Astoria',
    'Athens',
    'Athol',
    'Athol Springs',
    'Atlanta',
    'Atlantic Beach',
    'Attica',
    'Au Sable Forks',
    'Auburn',
    'Auriesville',
    'Aurora',
    'Austerlitz',
    'Ava',
    'Averill Park',
    'Avoca',
    'Avon',
    'Babylon',
    'Bainbridge',
    'Bakers Mills',
    'Baldwin',
    'Baldwin Place',
    'Baldwinsville',
    'Ballston Lake',
    'Ballston Spa',
    'Bangall',
    'Barker',
    'Barneveld',
    'Barrytown',
    'Barryville',
    'Barton',
    'Basom',
    'Batavia',
    'Bath',
    'Bay Shore',
    'Bayport',
    'Bayside',
    'Bayville',
    'Beacon',
    'Bear Mountain',
    'Bearsville',
    'Beaver Dams',
    'Beaver Falls',
    'Bedford',
    'Bedford Hills',
    'Belfast',
    'Bellerose',
    'Belleville',
    'Bellmore',
    'Bellona',
    'Bellport',
    'Bellvale',
    'Belmont',
    'Bemus Point',
    'Bergen',
    'Berkshire',
    'Berlin',
    'Berne',
    'Bernhards Bay',
    'Bethel',
    'Bethpage',
    'Bible School Park',
    'Big Flats',
    'Big Indian',
    'Billings',
    'Binghamton',
    'Black Creek',
    'Black River',
    'Blauvelt',
    'Bliss',
    'Blodgett Mills',
    'Bloomfield',
    'Blooming Grove',
    'Bloomingburg',
    'Bloomingdale',
    'Bloomington',
    'Bloomville',
    'Blossvale',
    'Blue Mountain Lake',
    'Blue Point',
    'Bohemia',
    'Boiceville',
    'Bolivar',
    'Bolton Landing',
    'Bombay',
    'Boonville',
    'Boston',
    'Bouckville',
    'Bovina Center',
    'Bowmansville',
    'Bradford',
    'Brainard',
    'Brainardsville',
    'Branchport',
    'Brant',
    'Brant Lake',
    'Brantingham',
    'Brasher Falls',
    'Breesport',
    'Breezy Point',
    'Brentwood',
    'Brewerton',
    'Brewster',
    'Briarcliff Manor',
    'Bridgehampton',
    'Bridgeport',
    'Bridgewater',
    'Brier Hill',
    'Brightwaters',
    'Broadalbin',
    'Brockport',
    'Brocton',
    'Bronx',
    'Bronxville',
    'Brookfield',
    'Brookhaven',
    'Brooklyn',
    'Brooktondale',
    'Brownville',
    'Brushton',
    'Buchanan',
    'Buffalo',
    'Bullville',
    'Burdett',
    'Burke',
    'Burlingham',
    'Burlington Flats',
    'Burnt Hills',
    'Burt',
    'Buskirk',
    'Byron',
    'Cadyville',
    'Cairo',
    'Calcium',
    'Caledonia',
    'Callicoon',
    'Callicoon Center',
    'Calverton',
    'Cambria Heights',
    'Cambridge',
    'Camden',
    'Cameron',
    'Cameron Mills',
    'Camillus',
    'Campbell',
    'Campbell Hall',
    'Canaan',
    'Canadice',
    'Canajoharie',
    'Canandaigua',
    'Canaseraga',
    'Canastota',
    'Candor',
    'Caneadea',
    'Canisteo',
    'Canton',
    'Cape Vincent',
    'Carle Place',
    'Carlisle',
    'Carmel',
    'Caroga Lake',
    'Carthage',
    'Cassadaga',
    'Cassville',
    'Castile',
    'Castle Creek',
    'Castle Point',
    'Castleton On Hudson',
    'Castorland',
    'Cato',
    'Catskill',
    'Cattaraugus',
    'Cayuga',
    'Cayuta',
    'Cazenovia',
    'Cedarhurst',
    'Celoron',
    'Center Moriches',
    'Centereach',
    'Centerport',
    'Centerville',
    'Central Bridge',
    'Central Islip',
    'Central Square',
    'Central Valley',
    'Ceres',
    'Chadwicks',
    'Chaffee',
    'Champlain',
    'Chappaqua',
    'Charlotteville',
    'Chase Mills',
    'Chateaugay',
    'Chatham',
    'Chaumont',
    'Chautauqua',
    'Chazy',
    'Chelsea',
    'Chemung',
    'Chenango Bridge',
    'Chenango Forks',
    'Cherry Creek',
    'Cherry Plain',
    'Cherry Valley',
    'Chester',
    'Chestertown',
    'Chichester',
    'Childwold',
    'Chippewa Bay',
    'Chittenango',
    'Churchville',
    'Churubusco',
    'Cicero',
    'Cincinnatus',
    'Circleville',
    'Clarence',
    'Clarence Center',
    'Clarendon',
    'Clark Mills',
    'Clarkson',
    'Clarksville',
    'Claryville',
    'Claverack',
    'Clay',
    'Clayton',
    'Clayville',
    'Clemons',
    'Cleveland',
    'Cleverdale',
    'Clifton Park',
    'Clifton Springs',
    'Climax',
    'Clinton',
    'Clinton Corners',
    'Clintondale',
    'Clockville',
    'Clyde',
    'Clymer',
    'Cobleskill',
    'Cochecton',
    'Cochecton Center',
    'Coeymans',
    'Coeymans Hollow',
    'Cohocton',
    'Cohoes',
    'Cold Brook',
    'Cold Spring',
    'Cold Spring Harbor',
    'Colden',
    'Colesville',
    'College Point',
    'Colliersville',
    'Collins',
    'Collins Center',
    'Colton',
    'Columbiaville',
    'Commack',
    'Comstock',
    'Conesus',
    'Conewango Valley',
    'Congers',
    'Conklin',
    'Connelly',
    'Constable',
    'Constableville',
    'Constantia',
    'Coopers Plains',
    'Cooperstown',
    'Copake',
    'Copake Falls',
    'Copenhagen',
    'Copiague',
    'Coram',
    'Corbettsville',
    'Corfu',
    'Corinth',
    'Corning',
    'Cornwall',
    'Cornwall On Hudson',
    'Cornwallville',
    'Corona',
    'Cortland',
    'Cortlandt Manor',
    'Cossayuna',
    'Cottekill',
    'Cowlesville',
    'Coxsackie',
    'Cragsmoor',
    'Cranberry Lake',
    'Craryville',
    'Crittenden',
    'Croghan',
    'Crompond',
    'Cropseyville',
    'Cross River',
    'Croton Falls',
    'Croton On Hudson',
    'Crown Point',
    'Cuba',
    'Cuddebackville',
    'Cutchogue',
    'Dale',
    'Dalton',
    'Dannemora',
    'Dansville',
    'Darien Center',
    'Davenport',
    'Davenport Center',
    'Dayton',
    'De Kalb Junction',
    'De Lancey',
    'De Peyster',
    'De Ruyter',
    'Deansboro',
    'Deer Park',
    'Deer River',
    'Deferiet',
    'Delanson',
    'Delevan',
    'Delhi',
    'Delmar',
    'Delphi Falls',
    'Denmark',
    'Denver',
    'Depauville',
    'Depew',
    'Deposit',
    'Derby',
    'Dewittville',
    'Dexter',
    'Diamond Point',
    'Dickinson Center',
    'Dobbs Ferry',
    'Dolgeville',
    'Dormansville',
    'Dover Plains',
    'Downsville',
    'Dresden',
    'Dryden',
    'Duanesburg',
    'Dundee',
    'Dunkirk',
    'Durham',
    'Durhamville',
    'Eagle Bay',
    'Eagle Bridge',
    'Earlton',
    'Earlville',
    'East Amherst',
    'East Aurora',
    'East Berne',
    'East Bethany',
    'East Bloomfield',
    'East Branch',
    'East Chatham',
    'East Concord',
    'East Durham',
    'East Elmhurst',
    'East Greenbush',
    'East Hampton',
    'East Homer',
    'East Islip',
    'East Jewett',
    'East Marion',
    'East Meadow',
    'East Meredith',
    'East Moriches',
    'East Nassau',
    'East Northport',
    'East Norwich',
    'East Otto',
    'East Pembroke',
    'East Pharsalia',
    'East Quogue',
    'East Randolph',
    'East Rochester',
    'East Rockaway',
    'East Schodack',
    'East Setauket',
    'East Springfield',
    'East Syracuse',
    'East Williamson',
    'East Worcester',
    'Eastchester',
    'Eastport',
    'Eaton',
    'Eden',
    'Edmeston',
    'Edwards',
    'Elba',
    'Elbridge',
    'Eldred',
    'Elizabethtown',
    'Elizaville',
    'Elka Park',
    'Ellenburg',
    'Ellenburg Center',
    'Ellenburg Depot',
    'Ellenville',
    'Ellicottville',
    'Ellington',
    'Ellisburg',
    'Elma',
    'Elmhurst',
    'Elmira',
    'Elmont',
    'Elmsford',
    'Endicott',
    'Endwell',
    'Erieville',
    'Erin',
    'Esopus',
    'Esperance',
    'Essex',
    'Etna',
    'Evans Mills',
    'Fabius',
    'Fair Haven',
    'Fairport',
    'Falconer',
    'Fallsburg',
    'Fancher',
    'Far Rockaway',
    'Farmersville Station',
    'Farmingdale',
    'Farmington',
    'Farmingville',
    'Farnham',
    'Fayette',
    'Fayetteville',
    'Felts Mills',
    'Ferndale',
    'Feura Bush',
    'Fillmore',
    'Findley Lake',
    'Fine',
    'Fishers',
    'Fishers Island',
    'Fishers Landing',
    'Fishkill',
    'Fishs Eddy',
    'Fleischmanns',
    'Floral Park',
    'Florida',
    'Flushing',
    'Fly Creek',
    'Fonda',
    'Forest Hills',
    'Forestburgh',
    'Forestport',
    'Forestville',
    'Fort Ann',
    'Fort Covington',
    'Fort Drum',
    'Fort Edward',
    'Fort Hunter',
    'Fort Johnson',
    'Fort Montgomery',
    'Fort Plain',
    'Frankfort',
    'Franklin',
    'Franklin Springs',
    'Franklin Square',
    'Franklinville',
    'Fredonia',
    'Freedom',
    'Freehold',
    'Freeport',
    'Freeville',
    'Fremont Center',
    'Fresh Meadows',
    'Frewsburg',
    'Friendship',
    'Fulton',
    'Fultonham',
    'Fultonville',
    'Gabriels',
    'Gainesville',
    'Gallupville',
    'Galway',
    'Gansevoort',
    'Garden City',
    'Gardiner',
    'Garnerville',
    'Garrattsville',
    'Garrison',
    'Gasport',
    'Geneseo',
    'Geneva',
    'Genoa',
    'Georgetown',
    'Germantown',
    'Gerry',
    'Getzville',
    'Ghent',
    'Gilbertsville',
    'Gilboa',
    'Glasco',
    'Glen Aubrey',
    'Glen Cove',
    'Glen Head',
    'Glen Oaks',
    'Glen Spey',
    'Glen Wild',
    'Glenfield',
    'Glenford',
    'Glenham',
    'Glenmont',
    'Glens Falls',
    'Glenwood',
    'Glenwood Landing',
    'Gloversville',
    'Godeffroy',
    'Goldens Bridge',
    'Gorham',
    'Goshen',
    'Gouverneur',
    'Gowanda',
    'Grafton',
    'Grahamsville',
    'Grand Gorge',
    'Grand Island',
    'Granite Springs',
    'Granville',
    'Great Bend',
    'Great Neck',
    'Great River',
    'Great Valley',
    'Greene',
    'Greenfield Center',
    'Greenfield Park',
    'Greenhurst',
    'Greenlawn',
    'Greenport',
    'Greenvale',
    'Greenville',
    'Greenwich',
    'Greenwood',
    'Greenwood Lake',
    'Greig',
    'Groton',
    'Groveland',
    'Guilderland',
    'Guilderland Center',
    'Guilford',
    'Hadley',
    'Hagaman',
    'Hague',
    'Hailesboro',
    'Haines Falls',
    'Halcottsville',
    'Hall',
    'Hamburg',
    'Hamden',
    'Hamilton',
    'Hamlin',
    'Hammond',
    'Hammondsport',
    'Hampton',
    'Hampton Bays',
    'Hancock',
    'Hankins',
    'Hannacroix',
    'Hannawa Falls',
    'Hannibal',
    'Harford',
    'Harpersfield',
    'Harpursville',
    'Harriman',
    'Harris',
    'Harrison',
    'Harrisville',
    'Hartford',
    'Hartsdale',
    'Hartwick',
    'Hastings',
    'Hastings On Hudson',
    'Hauppauge',
    'Haverstraw',
    'Hawthorne',
    'Hector',
    'Helena',
    'Hemlock',
    'Hempstead',
    'Henderson',
    'Henderson Harbor',
    'Henrietta',
    'Hensonville',
    'Herkimer',
    'Hermon',
    'Heuvelton',
    'Hewlett',
    'Hicksville',
    'High Falls',
    'Highland',
    'Highland Falls',
    'Highland Lake',
    'Highland Mills',
    'Highmount',
    'Hillburn',
    'Hillsdale',
    'Hilton',
    'Himrod',
    'Hinckley',
    'Hinsdale',
    'Hobart',
    'Hoffmeister',
    'Hogansburg',
    'Holbrook',
    'Holland',
    'Holland Patent',
    'Holley',
    'Hollis',
    'Hollowville',
    'Holmes',
    'Holtsville',
    'Homer',
    'Honeoye',
    'Honeoye Falls',
    'Hoosick',
    'Hoosick Falls',
    'Hopewell Junction',
    'Hornell',
    'Horseheads',
    'Hortonville',
    'Houghton',
    'Howard Beach',
    'Howells',
    'Howes Cave',
    'Hubbardsville',
    'Hudson',
    'Hudson Falls',
    'Hughsonville',
    'Huguenot',
    'Huletts Landing',
    'Hume',
    'Hunt',
    'Hunter',
    'Huntington',
    'Huntington Station',
    'Hurley',
    'Hurleyville',
    'Hyde Park',
    'Ilion',
    'Indian Lake',
    'Inlet',
    'Interlaken',
    'Inwood',
    'Ionia',
    'Irving',
    'Irvington',
    'Island Park',
    'Islandia',
    'Islip',
    'Islip Terrace',
    'Ithaca',
    'Jackson Heights',
    'Jacksonville',
    'Jamaica',
    'Jamesport',
    'Jamestown',
    'Jamesville',
    'Jasper',
    'Java Center',
    'Java Village',
    'Jay',
    'Jefferson',
    'Jefferson Valley',
    'Jeffersonville',
    'Jericho',
    'Jewett',
    'Johnsburg',
    'Johnson',
    'Johnson City',
    'Johnsonville',
    'Johnstown',
    'Jordan',
    'Jordanville',
    'Kanona',
    'Katonah',
    'Kattskill Bay',
    'Kauneonga Lake',
    'Keene',
    'Keene Valley',
    'Keeseville',
    'Kendall',
    'Kennedy',
    'Kenoza Lake',
    'Kent',
    'Kerhonkson',
    'Keuka Park',
    'Kew Gardens',
    'Kiamesha Lake',
    'Kill Buck',
    'Killawog',
    'Kinderhook',
    'King Ferry',
    'Kings Park',
    'Kingston',
    'Kirkville',
    'Kirkwood',
    'Knowlesville',
    'Knox',
    'Knoxboro',
    'La Fargeville',
    'La Fayette',
    'La Grange',
    'Lacona',
    'Lagrangeville',
    'Lake Clear',
    'Lake George',
    'Lake Grove',
    'Lake Hill',
    'Lake Huntington',
    'Lake Katrine',
    'Lake Luzerne',
    'Lake Peekskill',
    'Lake Placid',
    'Lake Pleasant',
    'Lake View',
    'Lakemont',
    'Lakeville',
    'Lakewood',
    'Lancaster',
    'Lanesville',
    'Lansing',
    'Larchmont',
    'Latham',
    'Laurel',
    'Laurens',
    'Lawrence',
    'Lawrenceville',
    'Lawtons',
    'Le Roy',
    'Lee Center',
    'Leeds',
    'Leicester',
    'Leon',
    'Leonardsville',
    'Levittown',
    'Lewis',
    'Lewisboro',
    'Lewiston',
    'Lexington',
    'Liberty',
    'Lily Dale',
    'Lima',
    'Limerick',
    'Limestone',
    'Lincolndale',
    'Lindenhurst',
    'Lindley',
    'Linwood',
    'Lisbon',
    'Lisle',
    'Little Falls',
    'Little Genesee',
    'Little Neck',
    'Little Valley',
    'Little York',
    'Liverpool',
    'Livingston',
    'Livingston Manor',
    'Livonia',
    'Livonia Center',
    'Loch Sheldrake',
    'Locke',
    'Lockport',
    'Lockwood',
    'Locust Valley',
    'Lodi',
    'Long Beach',
    'Long Eddy',
    'Long Island City',
    'Long Lake',
    'Lorraine',
    'Lowman',
    'Lowville',
    'Lycoming',
    'Lynbrook',
    'Lyndonville',
    'Lyon Mountain',
    'Lyons',
    'Lyons Falls',
    'Macedon',
    'Machias',
    'Madison',
    'Madrid',
    'Mahopac',
    'Mahopac Falls',
    'Maine',
    'Malden Bridge',
    'Malden On Hudson',
    'Mallory',
    'Malone',
    'Malverne',
    'Mamaroneck',
    'Manchester',
    'Manhasset',
    'Manlius',
    'Mannsville',
    'Manorville',
    'Maple Springs',
    'Maple View',
    'Maplecrest',
    'Marathon',
    'Marcellus',
    'Marcy',
    'Margaretville',
    'Marietta',
    'Marilla',
    'Marion',
    'Marlboro',
    'Martinsburg',
    'Martville',
    'Maryknoll',
    'Maryland',
    'Masonville',
    'Maspeth',
    'Massapequa',
    'Massapequa Park',
    'Massena',
    'Mastic',
    'Mastic Beach',
    'Mattituck',
    'Maybrook',
    'Mayfield',
    'Mayville',
    'McConnellsville',
    'McDonough',
    'McGraw',
    'McLean',
    'Mechanicville',
    'Mecklenburg',
    'Medford',
    'Medina',
    'Medusa',
    'Mellenville',
    'Melrose',
    'Melville',
    'Memphis',
    'Mendon',
    'Meridale',
    'Meridian',
    'Merrick',
    'Mexico',
    'Mid Hudson',
    'Mid Island',
    'Middle Falls',
    'Middle Granville',
    'Middle Grove',
    'Middle Island',
    'Middle Village',
    'Middleburgh',
    'Middleport',
    'Middlesex',
    'Middletown',
    'Middleville',
    'Milford',
    'Mill Neck',
    'Millbrook',
    'Miller Place',
    'Millerton',
    'Millport',
    'Millwood',
    'Milton',
    'Mineola',
    'Minerva',
    'Minetto',
    'Mineville',
    'Minoa',
    'Model City',
    'Modena',
    'Mohawk',
    'Mohegan Lake',
    'Moira',
    'Mongaup Valley',
    'Monroe',
    'Monsey',
    'Montauk',
    'Montezuma',
    'Montgomery',
    'Monticello',
    'Montour Falls',
    'Montrose',
    'Mooers',
    'Mooers Forks',
    'Moravia',
    'Moriah',
    'Moriah Center',
    'Moriches',
    'Morris',
    'Morrisonville',
    'Morristown',
    'Morrisville',
    'Morton',
    'Mottville',
    'Mount Kisco',
    'Mount Marion',
    'Mount Morris',
    'Mount Sinai',
    'Mount Tremper',
    'Mount Upton',
    'Mount Vernon',
    'Mount Vision',
    'Mountain Dale',
    'Mountainville',
    'Mumford',
    'Munnsville',
    'Nanuet',
    'Napanoch',
    'Naples',
    'Narrowsburg',
    'Nassau',
    'Natural Bridge',
    'Nedrow',
    'Nelliston',
    'Nesconset',
    'Neversink',
    'New Baltimore',
    'New Berlin',
    'New City',
    'New Hampton',
    'New Hartford',
    'New Haven',
    'New Hyde Park',
    'New Kingston',
    'New Lebanon',
    'New Lisbon',
    'New Milford',
    'New Paltz',
    'New Rochelle',
    'New Russia',
    'New Suffolk',
    'New Windsor',
    'New Woodstock',
    'New York',
    'New York Mills',
    'Newark',
    'Newark Valley',
    'Newburgh',
    'Newcomb',
    'Newfane',
    'Newfield',
    'Newport',
    'Newton Falls',
    'Newtonville',
    'Niagara Falls',
    'Niagara University',
    'Nichols',
    'Nicholville',
    'Nineveh',
    'Niobe',
    'Niverville',
    'Norfolk',
    'North Babylon',
    'North Bangor',
    'North Bay',
    'North Blenheim',
    'North Boston',
    'North Branch',
    'North Brookfield',
    'North Chatham',
    'North Chili',
    'North Collins',
    'North Creek',
    'North Evans',
    'North Granville',
    'North Greece',
    'North Hoosick',
    'North Hudson',
    'North Java',
    'North Lawrence',
    'North Norwich',
    'North Pitcher',
    'North River',
    'North Rose',
    'North Salem',
    'North Tonawanda',
    'Northport',
    'Northville',
    'Norwich',
    'Norwood',
    'Nunda',
    'Nyack',
    'Oak Hill',
    'Oakdale',
    'Oakfield',
    'Oakland Gardens',
    'Oaks Corners',
    'Obernburg',
    'Ocean Beach',
    'Oceanside',
    'Odessa',
    'Ogdensburg',
    'Olcott',
    'Old Bethpage',
    'Old Chatham',
    'Old Forge',
    'Old Westbury',
    'Olean',
    'Olivebridge',
    'Olmstedville',
    'Oneida',
    'Oneonta',
    'Ontario',
    'Ontario Center',
    'Orangeburg',
    'Orchard Park',
    'Orient',
    'Oriskany',
    'Oriskany Falls',
    'Orwell',
    'Ossining',
    'Oswegatchie',
    'Oswego',
    'Otego',
    'Otisville',
    'Otto',
    'Ouaquaga',
    'Ovid',
    'Owego',
    'Owls Head',
    'Oxbow',
    'Oxford',
    'Oyster Bay',
    'Ozone Park',
    'Painted Post',
    'Palatine Bridge',
    'Palenville',
    'Palisades',
    'Palmyra',
    'Panama',
    'Paradox',
    'Parish',
    'Parishville',
    'Parksville',
    'Patchogue',
    'Patterson',
    'Pattersonville',
    'Paul Smiths',
    'Pavilion',
    'Pawling',
    'Pearl River',
    'Peconic',
    'Peekskill',
    'Pelham',
    'Penfield',
    'Penn Yan',
    'Pennellville',
    'Perkinsville',
    'Perry',
    'Perrysburg',
    'Peru',
    'Peterboro',
    'Petersburg',
    'Pharsalia',
    'Phelps',
    'Philadelphia',
    'Phillipsport',
    'Philmont',
    'Phoenicia',
    'Phoenix',
    'Piercefield',
    'Piermont',
    'Pierrepont Manor',
    'Piffard',
    'Pike',
    'Pine Bush',
    'Pine City',
    'Pine Hill',
    'Pine Island',
    'Pine Plains',
    'Pine Valley',
    'Piseco',
    'Pitcher',
    'Pittsford',
    'Plainview',
    'Plainville',
    'Plattekill',
    'Plattsburgh',
    'Pleasant Valley',
    'Pleasantville',
    'Plessis',
    'Plymouth',
    'Poestenkill',
    'Point Lookout',
    'Poland',
    'Pomona',
    'Pompey',
    'Pond Eddy',
    'Poplar Ridge',
    'Port Byron',
    'Port Chester',
    'Port Crane',
    'Port Ewen',
    'Port Gibson',
    'Port Henry',
    'Port Jefferson',
    'Port Jefferson Station',
    'Port Jervis',
    'Port Kent',
    'Port Leyden',
    'Port Washington',
    'Portage',
    'Portageville',
    'Porter Corners',
    'Portland',
    'Portlandville',
    'Portville',
    'Potsdam',
    'Pottersville',
    'Poughkeepsie',
    'Poughquag',
    'Pound Ridge',
    'Prattsburgh',
    'Prattsville',
    'Preble',
    'Preston Hollow',
    'Prospect',
    'Pulaski',
    'Pulteney',
    'Pultneyville',
    'Purchase',
    'Purdys',
    'Purling',
    'Putnam Station',
    'Putnam Valley',
    'Pyrites',
    'Quaker Street',
    'Queens Village',
    'Queensbury',
    'Quogue',
    'Rainbow Lake',
    'Randolph',
    'Ransomville',
    'Raquette Lake',
    'Ravena',
    'Ray Brook',
    'Raymondville',
    'Reading Center',
    'Red Creek',
    'Red Hook',
    'Redfield',
    'Redford',
    'Redwood',
    'Rego Park',
    'Remsen',
    'Remsenburg',
    'Rensselaer',
    'Rensselaer Falls',
    'Rensselaerville',
    'Retsof',
    'Rexford',
    'Rexville',
    'Rhinebeck',
    'Rhinecliff',
    'Richburg',
    'Richfield Springs',
    'Richford',
    'Richland',
    'Richmond Hill',
    'Richmondville',
    'Richville',
    'Ridge',
    'Ridgewood',
    'Rifton',
    'Riparius',
    'Ripley',
    'Riverhead',
    'Rochester',
    'Rock City Falls',
    'Rock Hill',
    'Rock Stream',
    'Rock Tavern',
    'Rockaway Park',
    'Rockville Centre',
    'Rocky Point',
    'Rodman',
    'Rome',
    'Romulus',
    'Ronkonkoma',
    'Roosevelt',
    'Rooseveltown',
    'Roscoe',
    'Rose',
    'Roseboom',
    'Rosedale',
    'Rosendale',
    'Roslyn',
    'Roslyn Heights',
    'Rossburg',
    'Rotterdam Junction',
    'Round Lake',
    'Round Top',
    'Rouses Point',
    'Roxbury',
    'Ruby',
    'Rush',
    'Rushford',
    'Rushville',
    'Russell',
    'Rye',
    'Sabael',
    'Sackets Harbor',
    'Sag Harbor',
    'Sagaponack',
    'Saint Albans',
    'Saint Bonaventure',
    'Saint James',
    'Saint Johnsville',
    'Saint Regis Falls',
    'Salamanca',
    'Salem',
    'Salisbury Center',
    'Salisbury Mills',
    'Salt Point',
    'Sanborn',
    'Sand Lake',
    'Sandusky',
    'Sandy Creek',
    'Sangerfield',
    'Saranac',
    'Saranac Lake',
    'Saratoga Springs',
    'Sardinia',
    'Saugerties',
    'Sauquoit',
    'Savannah',
    'Savona',
    'Sayville',
    'Scarsdale',
    'Schaghticoke',
    'Schenectady',
    'Schenevus',
    'Schodack Landing',
    'Schoharie',
    'Schroon Lake',
    'Schuyler Falls',
    'Schuyler Lake',
    'Schuylerville',
    'Scio',
    'Scipio Center',
    'Scottsburg',
    'Scottsville',
    'Sea Cliff',
    'Seaford',
    'Selden',
    'Selkirk',
    'Seneca Castle',
    'Seneca Falls',
    'Severance',
    'Shandaken',
    'Sharon Springs',
    'Shelter Island',
    'Shelter Island Heights',
    'Shenorock',
    'Sherburne',
    'Sheridan',
    'Sherman',
    'Sherrill',
    'Shinhopple',
    'Shirley',
    'Shokan',
    'Shoreham',
    'Shortsville',
    'Shrub Oak',
    'Shushan',
    'Sidney',
    'Sidney Center',
    'Silver Bay',
    'Silver Creek',
    'Silver Lake',
    'Silver Springs',
    'Sinclairville',
    'Skaneateles',
    'Skaneateles Falls',
    'Slate Hill',
    'Slaterville Springs',
    'Slingerlands',
    'Sloansville',
    'Sloatsburg',
    'Smallwood',
    'Smithboro',
    'Smithtown',
    'Smithville Flats',
    'Smyrna',
    'Sodus',
    'Sodus Point',
    'Solsville',
    'Somers',
    'Sonyea',
    'Sound Beach',
    'South Bethlehem',
    'South Butler',
    'South Byron',
    'South Cairo',
    'South Colton',
    'South Dayton',
    'South Fallsburg',
    'South Glens Falls',
    'South Jamesport',
    'South Kortright',
    'South Lima',
    'South New Berlin',
    'South Otselic',
    'South Ozone Park',
    'South Plymouth',
    'South Richmond Hill',
    'South Rutland',
    'South Salem',
    'South Schodack',
    'South Wales',
    'Southampton',
    'Southfields',
    'Southold',
    'Sparkill',
    'Sparrow Bush',
    'Speculator',
    'Spencer',
    'Spencerport',
    'Spencertown',
    'Speonk',
    'Sprakers',
    'Spring Brook',
    'Spring Glen',
    'Spring Valley',
    'Springfield Center',
    'Springfield Gardens',
    'Springville',
    'Springwater',
    'Staatsburg',
    'Stafford',
    'Stamford',
    'Stanfordville',
    'Stanley',
    'Star Lake',
    'Staten Island',
    'Steamburg',
    'Stella Niagara',
    'Stephentown',
    'Sterling',
    'Sterling Forest',
    'Stillwater',
    'Stittville',
    'Stockton',
    'Stone Ridge',
    'Stony Brook',
    'Stony Creek',
    'Stony Point',
    'Stormville',
    'Stottville',
    'Stow',
    'Stratford',
    'Strykersville',
    'Stuyvesant',
    'Stuyvesant Falls',
    'Suffern',
    'Sugar Loaf',
    'Summit',
    'Summitville',
    'Sundown',
    'Sunnyside',
    'Surprise',
    'Swain',
    'Swan Lake',
    'Sylvan Beach',
    'Syosset',
    'Syracuse',
    'Taberg',
    'Tallman',
    'Tannersville',
    'Tappan',
    'Tarrytown',
    'Thendara',
    'Theresa',
    'Thiells',
    'Thompson Ridge',
    'Thompsonville',
    'Thornwood',
    'Thousand Island Park',
    'Three Mile Bay',
    'Ticonderoga',
    'Tillson',
    'Tioga Center',
    'Tivoli',
    'Tomkins Cove',
    'Tonawanda',
    'Treadwell',
    'Tribes Hill',
    'Troupsburg',
    'Trout Creek',
    'Troy',
    'Trumansburg',
    'Truxton',
    'Tuckahoe',
    'Tully',
    'Tunnel',
    'Tupper Lake',
    'Turin',
    'Tuxedo Park',
    'Tyrone',
    'Ulster Park',
    'Unadilla',
    'Union Hill',
    'Union Springs',
    'Uniondale',
    'Unionville',
    'Upper Jay',
    'Upton',
    'Utica',
    'Vails Gate',
    'Valatie',
    'Valhalla',
    'Valley Cottage',
    'Valley Falls',
    'Valley Stream',
    'Van Buren Point',
    'Van Etten',
    'Van Hornesville',
    'Varysburg',
    'Verbank',
    'Vermontville',
    'Vernon',
    'Vernon Center',
    'Verona',
    'Verona Beach',
    'Verplanck',
    'Versailles',
    'Vestal',
    'Victor',
    'Victory Mills',
    'Voorheesville',
    'Waccabuc',
    'Waddington',
    'Wading River',
    'Wainscott',
    'Walden',
    'Wales Center',
    'Walker Valley',
    'Wallkill',
    'Walton',
    'Walworth',
    'Wampsville',
    'Wanakena',
    'Wantagh',
    'Wappingers Falls',
    'Warners',
    'Warnerville',
    'Warrensburg',
    'Warsaw',
    'Warwick',
    'Washington Mills',
    'Washingtonville',
    'Wassaic',
    'Water Mill',
    'Waterford',
    'Waterloo',
    'Waterport',
    'Watertown',
    'Waterville',
    'Watervliet',
    'Watkins Glen',
    'Waverly',
    'Wawarsing',
    'Wayland',
    'Wayne',
    'Webb',
    'Webster',
    'Weedsport',
    'Wellesley Island',
    'Wells',
    'Wells Bridge',
    'Wellsburg',
    'Wellsville',
    'West Babylon',
    'West Bloomfield',
    'West Burlington',
    'West Camp',
    'West Chazy',
    'West Clarksville',
    'West Copake',
    'West Coxsackie',
    'West Davenport',
    'West Eaton',
    'West Edmeston',
    'West Falls',
    'West Fulton',
    'West Harrison',
    'West Haverstraw',
    'West Hempstead',
    'West Henrietta',
    'West Hurley',
    'West Islip',
    'West Kill',
    'West Lebanon',
    'West Leyden',
    'West Monroe',
    'West Nyack',
    'West Oneonta',
    'West Park',
    'West Point',
    'West Sand Lake',
    'West Sayville',
    'West Shokan',
    'West Stockholm',
    'West Valley',
    'West Winfield',
    'Westbrookville',
    'Westbury',
    'Westdale',
    'Westerlo',
    'Westernville',
    'Westfield',
    'Westford',
    'Westhampton',
    'Westhampton Beach',
    'Westmoreland',
    'Westons Mills',
    'Westport',
    'Westtown',
    'Wevertown',
    'Whippleville',
    'White Lake',
    'White Plains',
    'White Sulphur Springs',
    'Whitehall',
    'Whitesboro',
    'Whitestone',
    'Whitestown',
    'Whitesville',
    'Whitney Point',
    'Willard',
    'Willet',
    'Williamson',
    'Williamstown',
    'Williston Park',
    'Willow',
    'Willsboro',
    'Willseyville',
    'Wilmington',
    'Wilson',
    'Wilton',
    'Windham',
    'Windsor',
    'Wingdale',
    'Winthrop',
    'Witherbee',
    'Wolcott',
    'Woodbourne',
    'Woodbury',
    'Woodgate',
    'Woodhaven',
    'Woodhull',
    'Woodmere',
    'Woodridge',
    'Woodside',
    'Woodstock',
    'Worcester',
    'Wurtsboro',
    'Wyandanch',
    'Wykagyl',
    'Wynantskill',
    'Wyoming',
    'Yaphank',
    'Yonkers',
    'York',
    'Yorkshire',
    'Yorktown Heights',
    'Yorkville',
    'Youngstown',
    'Youngsville',
    'Yulan'
]
