cities = [
    'Aberdeen',
    'Advance',
    'Ahoskie',
    'Alamance',
    'Albemarle',
    'Albertson',
    'Alexander',
    'Alexis',
    'Alliance',
    'Almond',
    'Altamahaw',
    'Andrews',
    'Angier',
    'Ansonville',
    'Apex',
    'Arapahoe',
    'Ararat',
    'Arden',
    'Ash',
    'Asheboro',
    'Asheville',
    'Atkinson',
    'Atlantic',
    'Atlantic Beach',
    'Aulander',
    'Aurora',
    'Autryville',
    'Avon',
    'Ayden',
    'Aydlett',
    'Badin',
    'Bahama',
    'Bailey',
    'Bakersville',
    'Balsam',
    'Balsam Grove',
    'Banner Elk',
    'Barco',
    'Barium Springs',
    'Barnardsville',
    'Barnesville',
    'Bat Cave',
    'Bath',
    'Battleboro',
    'Bayboro',
    'Bear Creek',
    'Beaufort',
    'Belews Creek',
    'Belhaven',
    'Bellarthur',
    'Belmont',
    'Belvidere',
    'Bennett',
    'Benson',
    'Bessemer City',
    'Bethania',
    'Bethel',
    'Beulaville',
    'Biscoe',
    'Black Creek',
    'Black Mountain',
    'Bladenboro',
    'Blanch',
    'Blounts Creek',
    'Blowing Rock',
    'Boiling Springs',
    'Bolivia',
    'Bolton',
    'Bonlee',
    'Boomer',
    'Boone',
    'Boonville',
    'Bostic',
    'Brasstown',
    'Brevard',
    'Bridgeton',
    'Broadway',
    'Browns Summit',
    'Brunswick',
    'Bryson City',
    'Buies Creek',
    'Bullock',
    'Bunn',
    'Bunnlevel',
    'Burgaw',
    'Burlington',
    'Burnsville',
    'Butner',
    'Buxton',
    'Bynum',
    'Calabash',
    'Calypso',
    'Camden',
    'Cameron',
    'Camp Lejeune',
    'Candler',
    'Candor',
    'Canton',
    'Caroleen',
    'Carolina Beach',
    'Carrboro',
    'Carthage',
    'Cary',
    'Casar',
    'Cashiers',
    'Castalia',
    'Castle Hayne',
    'Catawba',
    'Cedar Falls',
    'Cedar Grove',
    'Cedar Island',
    'Cedar Mountain',
    'Cerro Gordo',
    'Chadbourn',
    'Chapel Hill',
    'Charlotte',
    'Cherokee',
    'Cherry Point',
    'Cherryville',
    'Chimney Rock',
    'China Grove',
    'Chinquapin',
    'Chocowinity',
    'Claremont',
    'Clarendon',
    'Clarkton',
    'Clayton',
    'Clemmons',
    'Cleveland',
    'Cliffside',
    'Climax',
    'Clinton',
    'Clyde',
    'Coats',
    'Cofield',
    'Coinjock',
    'Colerain',
    'Colfax',
    'Collettsville',
    'Columbia',
    'Columbus',
    'Comfort',
    'Como',
    'Concord',
    'Conetoe',
    'Connellys Springs',
    'Conover',
    'Conway',
    'Cooleemee',
    'Corapeake',
    'Cordova',
    'Cornelius',
    'Corolla',
    'Council',
    'Cove City',
    'Cramerton',
    'Creedmoor',
    'Creston',
    'Creswell',
    'Crossnore',
    'Crouse',
    'Crumpler',
    'Culberson',
    'Cullowhee',
    'Cumberland',
    'Cumnock',
    'Currie',
    'Currituck',
    'Dallas',
    'Dana',
    'Danbury',
    'Davidson',
    'Davis',
    'Deep Gap',
    'Deep Run',
    'Delco',
    'Denton',
    'Denver',
    'Dillsboro',
    'Dobson',
    'Dover',
    'Drexel',
    'Dublin',
    'Dudley',
    'Dunn',
    'Durants Neck',
    'Durham',
    'Eagle Rock',
    'Eagle Springs',
    'Earl',
    'East Bend',
    'East Flat Rock',
    'East Spencer',
    'Eden',
    'Edenton',
    'Edneyville',
    'Edward',
    'Efland',
    'Elizabeth City',
    'Elizabethtown',
    'Elk Park',
    'Elkin',
    'Ellenboro',
    'Ellerbe',
    'Elm City',
    'Elon College',
    'Emerald Isle',
    'Enfield',
    'Engelhard',
    'Enka',
    'Ennice',
    'Ernul',
    'Erwin',
    'Ether',
    'Etowah',
    'Eure',
    'Everetts',
    'Evergreen',
    'Fair Bluff',
    'Fairfield',
    'Fairmont',
    'Fairplains',
    'Fairview',
    'Faison',
    'Faith',
    'Falcon',
    'Falkland',
    'Fallston',
    'Farmville',
    'Fayetteville',
    'Ferguson',
    'Flat Rock',
    'Fleetwood',
    'Fletcher',
    'Fontana Dam',
    'Forest City',
    'Fort Bragg',
    'Fountain',
    'Four Oaks',
    'Franklin',
    'Franklinton',
    'Franklinville',
    'Fremont',
    'Frisco',
    'Fuquay Varina',
    'Garland',
    'Garner',
    'Garysburg',
    'Gaston',
    'Gastonia',
    'Gates',
    'Gatesville',
    'Germanton',
    'Gerton',
    'Gibson',
    'Gibsonville',
    'Glade Valley',
    'Glen Alpine',
    'Glendale Springs',
    'Glenville',
    'Glenwood',
    'Gloucester',
    'Godwin',
    'Gold Hill',
    'Goldsboro',
    'Goldston',
    'Graham',
    'Grandy',
    'Granite Falls',
    'Granite Quarry',
    'Grantsboro',
    'Grassy Creek',
    'Greenmountain',
    'Greensboro',
    'Greenville',
    'Grifton',
    'Grimesland',
    'Grover',
    'Gulf',
    'Gumberry',
    'Halifax',
    'Hallsboro',
    'Hamilton',
    'Hamlet',
    'Hampstead',
    'Hamptonville',
    'Harbinger',
    'Harkers Island',
    'Harmony',
    'Harrells',
    'Harrellsville',
    'Harris',
    'Harrisburg',
    'Hassell',
    'Hatteras',
    'Havelock',
    'Haw River',
    'Hayesville',
    'Hays',
    'Hazelwood',
    'Henderson',
    'Hendersonville',
    'Henrico',
    'Henrietta',
    'Hertford',
    'Hickory',
    'Hiddenite',
    'High Point',
    'High Shoals',
    'Highfalls',
    'Highlands',
    'Hildebran',
    'Hillsborough',
    'Hobbsville',
    'Hobgood',
    'Hobucken',
    'Hoffman',
    'Hollister',
    'Holly Ridge',
    'Holly Springs',
    'Hookerton',
    'Hope Mills',
    'Horse Shoe',
    'Hot Springs',
    'Hubert',
    'Hudson',
    'Huntersville',
    'Hurdle Mills',
    'Icard',
    'Indian Trail',
    'Ingold',
    'Iron Station',
    'Ivanhoe',
    'Jackson',
    'Jackson Springs',
    'Jacksonville',
    'Jamestown',
    'Jamesville',
    'Jarvisburg',
    'Jefferson',
    'Jonas Ridge',
    'Jonesville',
    'Julian',
    'Kannapolis',
    'Kelford',
    'Kelly',
    'Kenansville',
    'Kenly',
    'Kernersville',
    'Kill Devil Hills',
    'King',
    'Kings Mountain',
    'Kinston',
    'Kipling',
    'Kittrell',
    'Kitty Hawk',
    'Knightdale',
    'Knotts Island',
    'Kure Beach',
    'La Grange',
    'Lake Junaluska',
    'Lake Lure',
    'Lake Toxaway',
    'Lake Waccamaw',
    'Lakeview',
    'Landis',
    'Lansing',
    'Lattimore',
    'Laurel Hill',
    'Laurel Springs',
    'Laurinburg',
    'Lawndale',
    'Lawsonville',
    'Leasburg',
    'Leicester',
    'Leland',
    'Lemon Springs',
    'Lenoir',
    'Lewiston Woodville',
    'Lewisville',
    'Lexington',
    'Liberty',
    'Lilesville',
    'Lillington',
    'Lincolnton',
    'Linden',
    'Linville',
    'Linville Falls',
    'Linwood',
    'Little Switzerland',
    'Littleton',
    'Locust',
    'Longwood',
    'Louisburg',
    'Lowell',
    'Lowgap',
    'Lowland',
    'Lucama',
    'Lumber Bridge',
    'Lumberton',
    'Lynn',
    'Macclesfield',
    'Macon',
    'Madison',
    'Maggie Valley',
    'Magnolia',
    'Maiden',
    'Mamers',
    'Manns Harbor',
    'Manson',
    'Manteo',
    'Maple',
    'Maple Hill',
    'Marble',
    'Margarettsville',
    'Marietta',
    'Marion',
    'Mars Hill',
    'Marshall',
    'Marshallberg',
    'Marshville',
    'Marston',
    'Matthews',
    'Maury',
    'Maxton',
    'Mayodan',
    'Maysville',
    'McAdenville',
    'Mccain',
    'Mccutcheon Field',
    'McFarlan',
    'McGrady',
    'McLeansville',
    'Mebane',
    'Merritt',
    'Merry Hill',
    'Micaville',
    'Micro',
    'Middleburg',
    'Middlesex',
    'Midland',
    'Midway Park',
    'Mill Spring',
    'Millers Creek',
    'Milton',
    'Milwaukee',
    'Mineral Springs',
    'Minneapolis',
    'Misenheimer',
    'Mocksville',
    'Moncure',
    'Monroe',
    'Montezuma',
    'Montreat',
    'Mooresboro',
    'Mooresville',
    'Moravian Falls',
    'Morehead City',
    'Morganton',
    'Morrisville',
    'Morven',
    'Mount Airy',
    'Mount Gilead',
    'Mount Holly',
    'Mount Mourne',
    'Mount Olive',
    'Mount Pleasant',
    'Mount Ulla',
    'Mountain Home',
    'Moyock',
    'Murfreesboro',
    'Murphy',
    'Nags Head',
    'Nakina',
    'Naples',
    'Nashville',
    'Nebo',
    'New Bern',
    'New Hill',
    'New London',
    'Newell',
    'Newland',
    'Newport',
    'Newton',
    'Newton Grove',
    'Norlina',
    'Norman',
    'North Wilkesboro',
    'Norwood',
    'Oak City',
    'Oak Island',
    'Oak Ridge',
    'Oakboro',
    'Ocean Isle Beach',
    'Ocracoke',
    'Old Fort',
    'Olin',
    'Olivia',
    'Oriental',
    'Orrum',
    'Otto',
    'Oxford',
    'Palmyra',
    'Pantego',
    'Parkton',
    'Parmele',
    'Patterson',
    'Paw Creek',
    'Peachland',
    'Pelham',
    'Pembroke',
    'Pendleton',
    'Penland',
    'Penrose',
    'Pfafftown',
    'Pikeville',
    'Pilot Mountain',
    'Pine Hall',
    'Pine Level',
    'Pinebluff',
    'Pinehurst',
    'Pineola',
    'Pinetops',
    'Pinetown',
    'Pineville',
    'Piney Creek',
    'Pink Hill',
    'Pinnacle',
    'Pisgah Forest',
    'Pittsboro',
    'Pleasant Garden',
    'Pleasant Hill',
    'Plumtree',
    'Plymouth',
    'Point Harbor',
    'Polkton',
    'Polkville',
    'Pollocksville',
    'Pope A F B',
    'Poplar Branch',
    'Potecasi',
    'Powells Point',
    'Powellsville',
    'Princeton',
    'Proctorville',
    'Prospect Hill',
    'Providence',
    'Purlear',
    'Raeford',
    'Raleigh',
    'Ramseur',
    'Randleman',
    'Red Oak',
    'Red Springs',
    'Reidsville',
    'Rex',
    'Rhodhiss',
    'Rich Square',
    'Richfield',
    'Richlands',
    'Ridgecrest',
    'Ridgeway',
    'Riegelwood',
    'Roanoke Rapids',
    'Roaring Gap',
    'Roaring River',
    'Robbins',
    'Robbinsville',
    'Robersonville',
    'Rockingham',
    'Rockwell',
    'Rocky Mount',
    'Rocky Point',
    'Rodanthe',
    'Roduco',
    'Rolesville',
    'Ronda',
    'Roper',
    'Rose Hill',
    'Roseboro',
    'Rosman',
    'Rougemont',
    'Rowland',
    'Roxboro',
    'Roxobel',
    'Ruffin',
    'Rural Hall',
    'Rutherford College',
    'Rutherfordton',
    'Saint Pauls',
    'Salemburg',
    'Salisbury',
    'Salter Path',
    'Saluda',
    'Salvo',
    'Sandy Ridge',
    'Sanford',
    'Sapphire',
    'Saratoga',
    'Saxapahaw',
    'Scaly Mountain',
    'Scotland Neck',
    'Scotts',
    'Scottville',
    'Scranton',
    'Seaboard',
    'Seagrove',
    'Sealevel',
    'Sedalia',
    'Selma',
    'Semora',
    'Seven Springs',
    'Severn',
    'Shallotte',
    'Shannon',
    'Sharpsburg',
    'Shawboro',
    'Shelby',
    'Sherrills Ford',
    'Shiloh',
    'Siler City',
    'Siloam',
    'Simpson',
    'Sims',
    'Skyland',
    'Smithfield',
    'Smyrna',
    'Sneads Ferry',
    'Snow Camp',
    'Snow Hill',
    'Sophia',
    'South Brunswick',
    'South Mills',
    'Southern Pines',
    'Southmont',
    'Southport',
    'Sparta',
    'Speed',
    'Spencer',
    'Spindale',
    'Spring Hope',
    'Spring Lake',
    'Spruce Pine',
    'Stacy',
    'Staley',
    'Stanfield',
    'Stanley',
    'Stantonsburg',
    'Star',
    'State Road',
    'Statesville',
    'Stedman',
    'Stella',
    'Stem',
    'Stokes',
    'Stokesdale',
    'Stoneville',
    'Stonewall',
    'Stony Point',
    'Stovall',
    'Stumpy Point',
    'Sugar Grove',
    'Summerfield',
    'Sunbury',
    'Sunset Beach',
    'Supply',
    'Swannanoa',
    'Swanquarter',
    'Swansboro',
    'Swepsonville',
    'Sylva',
    'Tabor City',
    'Tar Heel',
    'Tarawa Terrace',
    'Tarboro',
    'Taylorsville',
    'Teachey',
    'Terrell',
    'Thomasville',
    'Thurmond',
    'Tillery',
    'Timberlake',
    'Toast',
    'Tobaccoville',
    'Todd',
    'Topton',
    'Townsville',
    'Traphill',
    'Trenton',
    'Trinity',
    'Troutman',
    'Troy',
    'Tryon',
    'Tuckasegee',
    'Turkey',
    'Turnersburg',
    'Tuxedo',
    'Tyner',
    'Union Grove',
    'Union Mills',
    'Valdese',
    'Vale',
    'Valle Crucis',
    'Vanceboro',
    'Vandemere',
    'Vass',
    'Vaughan',
    'Vilas',
    'Waco',
    'Wade',
    'Wadesboro',
    'Wagram',
    'Wake Forest',
    'Walkertown',
    'Wallace',
    'Wallburg',
    'Walnut Cove',
    'Walstonburg',
    'Wanchese',
    'Warne',
    'Warrensville',
    'Warrenton',
    'Warsaw',
    'Washington',
    'Watha',
    'Waves',
    'Waxhaw',
    'Waynesville',
    'Weaverville',
    'Webster',
    'Welcome',
    'Weldon',
    'Wendell',
    'Wentworth',
    'West End',
    'West Jefferson',
    'Westfield',
    'Whitakers',
    'White Oak',
    'White Plains',
    'Whiteville',
    'Whitsett',
    'Whittier',
    'Wilkesboro',
    'Willard',
    'Williamston',
    'Williston',
    'Willow Spring',
    'Wilmington',
    'Wilson',
    'Wilsons Mills',
    'Windsor',
    'Winfall',
    'Wingate',
    'Winnabow',
    'Winston Salem',
    'Winterville',
    'Winton',
    'Wise',
    'Woodland',
    'Woodleaf',
    'Wrightsboro',
    'Wrightsville Beach',
    'Yadkinville',
    'Yanceyville',
    'Youngsville',
    'Zebulon',
    'Zionville',
    'Zirconia'
]
