cities = [
    'Adams',
    'Adel',
    'Adrian',
    'Agness',
    'Albany',
    'Allegany',
    'Alsea',
    'Alvadore',
    'Amity',
    'Antelope',
    'Arch Cape',
    'Arlington',
    'Arock',
    'Ashland',
    'Ashwood',
    'Astoria',
    'Athena',
    'Aumsville',
    'Aurora',
    'Azalea',
    'Baker City',
    'Bandon',
    'Banks',
    'Bates',
    'Bay City',
    'Beatty',
    'Beaver',
    'Beavercreek',
    'Beaverton',
    'Bend',
    'Blachly',
    'Blodgett',
    'Blue River',
    'Bly',
    'Boardman',
    'Bonanza',
    'Boring',
    'Bridal Veil',
    'Bridgeport',
    'Brightwood',
    'Broadbent',
    'Brogan',
    'Brookings',
    'Brothers',
    'Brownsville',
    'Burns',
    'Butte Falls',
    'Buxton',
    'Camas Valley',
    'Camp Sherman',
    'Canby',
    'Cannon Beach',
    'Canyon City',
    'Canyonville',
    'Carlton',
    'Cascade Locks',
    'Cascadia',
    'Cave Junction',
    'Cayuse',
    'Central Point',
    'Chemult',
    'Cheshire',
    'Chiloquin',
    'Christmas Valley',
    'Clackamas',
    'Clatskanie',
    'Cloverdale',
    'Colton',
    'Columbia City',
    'Condon',
    'Coos Bay',
    'Coquille',
    'Corbett',
    'Cornelius',
    'Corvallis',
    'Cottage Grove',
    'Cove',
    'Crabtree',
    'Crane',
    'Crater Lake',
    'Crawfordsville',
    'Crescent',
    'Crescent Lake',
    'Creswell',
    'Culp Creek',
    'Culver',
    'Curtin',
    'Dairy',
    'Dallas',
    'Days Creek',
    'Dayton',
    'Dayville',
    'Deadwood',
    'Deer Island',
    'Depoe Bay',
    'Detroit',
    'Dexter',
    'Diamond',
    'Dillard',
    'Donald',
    'Dorena',
    'Drain',
    'Drewsey',
    'Dufur',
    'Dundee',
    'Durkee',
    'Eagle Creek',
    'Eagle Point',
    'Echo',
    'Eddyville',
    'Elgin',
    'Elkton',
    'Elmira',
    'Enterprise',
    'Estacada',
    'Eugene',
    'Fairview',
    'Fall Creek',
    'Falls City',
    'Fields',
    'Florence',
    'Forest Grove',
    'Fort Klamath',
    'Fort Rock',
    'Fossil',
    'Foster',
    'Fox',
    'Frenchglen',
    'Gales Creek',
    'Gardiner',
    'Garibaldi',
    'Gaston',
    'Gates',
    'Gervais',
    'Gilchrist',
    'Gladstone',
    'Glendale',
    'Gleneden Beach',
    'Glide',
    'Gold Beach',
    'Gold Hill',
    'Government Camp',
    'Grand Ronde',
    'Grants Pass',
    'Grass Valley',
    'Gresham',
    'Haines',
    'Halfway',
    'Halsey',
    'Hammond',
    'Harper',
    'Harrisburg',
    'Hebo',
    'Helix',
    'Heppner',
    'Hereford',
    'Hermiston',
    'Hillsboro',
    'Hines',
    'Hood River',
    'Hubbard',
    'Huntington',
    'Idanha',
    'Idleyld Park',
    'Imbler',
    'Imnaha',
    'Independence',
    'Ione',
    'Ironside',
    'Irrigon',
    'Jacksonville',
    'Jamieson',
    'Jefferson',
    'John Day',
    'Joseph',
    'Junction City',
    'Juntura',
    'Keizer',
    'Keno',
    'Kent',
    'Kerby',
    'Kimberly',
    'Klamath Falls',
    'La Grande',
    'La Pine',
    'Lafayette',
    'Lake Oswego',
    'Lakeside',
    'Lakeview',
    'Langlois',
    'Lawen',
    'Lebanon',
    'Lexington',
    'Lincoln City',
    'Logsden',
    'Long Creek',
    'Lorane',
    'Lostine',
    'Lowell',
    'Lyons',
    'Madras',
    'Malin',
    'Manning',
    'Manzanita',
    'Mapleton',
    'Marcola',
    'Marion',
    'Marylhurst',
    'Maupin',
    'Mcminnville',
    'Meacham',
    'Medford',
    'Mehama',
    'Merlin',
    'Merrill',
    'Midland',
    'Mikkalo',
    'Mill City',
    'Milton Freewater',
    'Mitchell',
    'Molalla',
    'Monmouth',
    'Monroe',
    'Monument',
    'Moro',
    'Mosier',
    'Mount Angel',
    'Mount Hood Parkdale',
    'Mount Vernon',
    'Mulino',
    'Murphy',
    'Myrtle Creek',
    'Myrtle Point',
    'Nehalem',
    'Neotsu',
    'Neskowin',
    'Netarts',
    'Newberg',
    'Newport',
    'North Bend',
    'North Plains',
    'North Powder',
    'Norway',
    'Noti',
    'O Brien',
    'Oakland',
    'Oakridge',
    'Oceanside',
    'Odell',
    'Ontario',
    'Ophir',
    'Oregon City',
    'Otis',
    'Otter Rock',
    'Oxbow',
    'Pacific City',
    'Paisley',
    'Paulina',
    'Pendleton',
    'Philomath',
    'Phoenix',
    'Pilot Rock',
    'Pleasant Hill',
    'Plush',
    'Port Orford',
    'Portland',
    'Post',
    'Powell Butte',
    'Powers',
    'Prairie City',
    'Princeton',
    'Prineville',
    'Prospect',
    'Rainier',
    'Raleigh Hills',
    'Redmond',
    'Reedsport',
    'Remote',
    'Rhododendron',
    'Richland',
    'Rickreall',
    'Riddle',
    'Riley',
    'Ritter',
    'Riverside',
    'Rockaway Beach',
    'Rogue River',
    'Rose Lodge',
    'Roseburg',
    'Roseburg North',
    'Rufus',
    'Saginaw',
    'Saint Benedict',
    'Saint Helens',
    'Saint Paul',
    'Salem',
    'Sandy',
    'Scappoose',
    'Scio',
    'Scotts Mills',
    'Scottsburg',
    'Seal Rock',
    'Seaside',
    'Selma',
    'Seneca',
    'Shady Cove',
    'Shaniko',
    'Shedd',
    'Sheridan',
    'Sherwood',
    'Siletz',
    'Silver Lake',
    'Silverton',
    'Sisters',
    'Sixes',
    'South Beach',
    'Sprague River',
    'Spray',
    'Springfield',
    'Stanfield',
    'Stayton',
    'Sublimity',
    'Summer Lake',
    'Summerville',
    'Sumpter',
    'Sutherlin',
    'Sweet Home',
    'Swisshome',
    'Talent',
    'Tangent',
    'Tenmile',
    'Terrebonne',
    'The Dalles',
    'Thurston',
    'Tidewater',
    'Tillamook',
    'Tiller',
    'Timber',
    'Toledo',
    'Tolovana Park',
    'Trail',
    'Troutdale',
    'Tualatin',
    'Turner',
    'Tygh Valley',
    'Ukiah',
    'Umatilla',
    'Umpqua',
    'Union',
    'Unity',
    'Vale',
    'Veneta',
    'Vernonia',
    'Vida',
    'Waldport',
    'Wallowa',
    'Walterville',
    'Walton',
    'Warm Springs',
    'Warren',
    'Warrenton',
    'Wasco',
    'Wedderburn',
    'Welches',
    'West Linn',
    'Westfall',
    'Westfir',
    'Westlake',
    'Weston',
    'Wheeler',
    'White City',
    'Wilbur',
    'Wilderville',
    'Willamina',
    'Williams',
    'Wilsonville',
    'Winchester',
    'Winston',
    'Wolf Creek',
    'Woodburn',
    'Yachats',
    'Yamhill',
    'Yoncalla'
]
