cities = [
    'Aaronsburg',
    'Abbottstown',
    'Abington',
    'Ackermanville',
    'Acme',
    'Acosta',
    'Adah',
    'Adamsburg',
    'Adamstown',
    'Adamsville',
    'Addison',
    'Adrian',
    'Airville',
    'Akron',
    'Alba',
    'Albion',
    'Albrightsville',
    'Alburtis',
    'Aldenville',
    'Aleppo',
    'Alexandria',
    'Aliquippa',
    'Allenport',
    'Allensville',
    'Allentown',
    'Allenwood',
    'Allison',
    'Allison Park',
    'Allport',
    'Almedia',
    'Alsace',
    'Altoona',
    'Alum Bank',
    'Alverda',
    'Alverton',
    'Amberson',
    'Ambler',
    'Ambridge',
    'Amity',
    'Analomink',
    'Andreas',
    'Anita',
    'Annville',
    'Antes Fort',
    'Apollo',
    'Aquashicola',
    'Arcadia',
    'Archbald',
    'Arcola',
    'Ardara',
    'Ardmore',
    'Arendtsville',
    'Aristes',
    'Armagh',
    'Armbrust',
    'Arnot',
    'Arona',
    'Artemas',
    'Ashfield',
    'Ashland',
    'Ashville',
    'Aspers',
    'Aston',
    'Atglen',
    'Athens',
    'Atlantic',
    'Atlasburg',
    'Auburn',
    'Audubon',
    'Aultman',
    'Austin',
    'Avella',
    'Avis',
    'Avondale',
    'Avonmore',
    'Baden',
    'Bainbridge',
    'Bairdford',
    'Bakers Summit',
    'Bakerstown',
    'Bala Cynwyd',
    'Bally',
    'Bangor',
    'Barnesboro',
    'Barnesville',
    'Bart',
    'Barto',
    'Bartonsville',
    'Bath',
    'Bausman',
    'Beach Haven',
    'Beach Lake',
    'Beallsville',
    'Bear Creek',
    'Bear Lake',
    'Beaver',
    'Beaver Falls',
    'Beaver Meadows',
    'Beaver Springs',
    'Beaverdale',
    'Beavertown',
    'Beccaria',
    'Bechtelsville',
    'Bedford',
    'Bedminster',
    'Beech Creek',
    'Belle Vernon',
    'Bellefonte',
    'Belleville',
    'Bellwood',
    'Belsano',
    'Bendersville',
    'Benezett',
    'Bensalem',
    'Bentleyville',
    'Benton',
    'Berlin',
    'Bernville',
    'Berrysburg',
    'Berwick',
    'Berwyn',
    'Bessemer',
    'Bethel',
    'Bethel Park',
    'Bethlehem',
    'Beyer',
    'Big Cove Tannery',
    'Big Run',
    'Bigler',
    'Biglerville',
    'Birchrunville',
    'Bird In Hand',
    'Birdsboro',
    'Black Lick',
    'Blain',
    'Blairs Mills',
    'Blairsville',
    'Blakeslee',
    'Blanchard',
    'Blandburg',
    'Blandon',
    'Bloomfield',
    'Blooming Glen',
    'Bloomsburg',
    'Blossburg',
    'Blue Ball',
    'Blue Bell',
    'Blue Ridge Summit',
    'Boalsburg',
    'Bobtown',
    'Bodines',
    'Boiling Springs',
    'Bolivar',
    'Boswell',
    'Bovard',
    'Bowers',
    'Bowmansdale',
    'Bowmanstown',
    'Bowmansville',
    'Boyers',
    'Boyertown',
    'Boynton',
    'Brackenridge',
    'Brackney',
    'Braddock',
    'Bradenville',
    'Bradford',
    'Bradfordwoods',
    'Branchdale',
    'Branchton',
    'Brandamore',
    'Brandy Camp',
    'Brave',
    'Breezewood',
    'Breinigsville',
    'Bridgeport',
    'Bridgeton',
    'Bridgeville',
    'Brier Hill',
    'Brisbin',
    'Bristol',
    'Broad Top',
    'Brockport',
    'Brockton',
    'Brockway',
    'Brodheadsville',
    'Brogue',
    'Brookhaven',
    'Brooklyn',
    'Brookville',
    'Broomall',
    'Brownfield',
    'Brownstown',
    'Brownsville',
    'Bruin',
    'Brush Creek',
    'Brush Valley',
    'Bryn Athyn',
    'Bryn Mawr',
    'Buck Hill Falls',
    'Buckingham',
    'Buena Vista',
    'Buffalo Mills',
    'Bulger',
    'Bunola',
    'Burgettstown',
    'Burlington',
    'Burnham',
    'Burnside',
    'Burnt Cabins',
    'Bushkill',
    'Butler',
    'Byrnedale',
    'Cabot',
    'Cadogan',
    'Cairnbrook',
    'California',
    'Callensburg',
    'Callery',
    'Calumet',
    'Calvin',
    'Cambra',
    'Cambridge Springs',
    'Camp Hill',
    'Campbelltown',
    'Camptown',
    'Canadensis',
    'Canonsburg',
    'Canton',
    'Carbondale',
    'Cardale',
    'Carlisle',
    'Carlton',
    'Carmichaels',
    'Carnegie',
    'Carrolltown',
    'Carversville',
    'Cashtown',
    'Cassandra',
    'Cassville',
    'Castanea',
    'Catasauqua',
    'Catawissa',
    'Cecil',
    'Cedar Run',
    'Cedars',
    'Center Valley',
    'Centerport',
    'Centerville',
    'Central City',
    'Centralia',
    'Centre Hall',
    'Chadds Ford',
    'Chalfont',
    'Chalk Hill',
    'Chambersburg',
    'Chambersville',
    'Champion',
    'Chandlers Valley',
    'Charleroi',
    'Chatham',
    'Cheltenham',
    'Cherry Tree',
    'Cherryville',
    'Chest Springs',
    'Chester',
    'Chester Heights',
    'Chester Springs',
    'Chestnut Ridge',
    'Cheswick',
    'Cheyney',
    'Chicora',
    'Chinchilla',
    'Christiana',
    'Clairton',
    'Clarence',
    'Clarendon',
    'Claridge',
    'Clarington',
    'Clarion',
    'Clark',
    'Clarks Mills',
    'Clarks Summit',
    'Clarksburg',
    'Clarksville',
    'Claysburg',
    'Claysville',
    'Clearfield',
    'Clearville',
    'Clifford',
    'Climax',
    'Clinton',
    'Clintonville',
    'Clune',
    'Clymer',
    'Coal Center',
    'Coal Township',
    'Coaldale',
    'Coalport',
    'Coatesville',
    'Coburn',
    'Cochranton',
    'Cochranville',
    'Cocolamus',
    'Codorus',
    'Cogan Station',
    'Cokeburg',
    'Collegeville',
    'Colmar',
    'Columbia',
    'Columbia Cross Roads',
    'Columbus',
    'Colver',
    'Commodore',
    'Concord',
    'Concordville',
    'Conestoga',
    'Confluence',
    'Conneaut Lake',
    'Conneautville',
    'Connellsville',
    'Connoquenessing',
    'Conshohocken',
    'Conway',
    'Conyngham',
    'Cooksburg',
    'Coolspring',
    'Coopersburg',
    'Cooperstown',
    'Coplay',
    'Coral',
    'Coraopolis',
    'Cornwall',
    'Corry',
    'Corsica',
    'Coudersport',
    'Coulters',
    'Coupon',
    'Covington',
    'Cowanesque',
    'Cowansville',
    'Crabtree',
    'Craley',
    'Cranberry',
    'Cranberry Twp',
    'Cranesville',
    'Creamery',
    'Creekside',
    'Creighton',
    'Crescent',
    'Cresco',
    'Cresson',
    'Cressona',
    'Crosby',
    'Cross Fork',
    'Crown',
    'Croydon',
    'Crucible',
    'Crum Lynne',
    'Crystal Spring',
    'Cuddy',
    'Cumbola',
    'Cumru',
    'Curllsville',
    'Curryville',
    'Curtisville',
    'Curwensville',
    'Custer City',
    'Cyclone',
    'Dagus Mines',
    'Daisytown',
    'Dallas',
    'Dallastown',
    'Dalmatia',
    'Dalton',
    'Damascus',
    'Danboro',
    'Danielsville',
    'Danville',
    'Darby',
    'Darlington',
    'Darragh',
    'Dauberville',
    'Dauphin',
    'Davidsville',
    'Dawson',
    'Dayton',
    'De Lancey',
    'De Young',
    'Defiance',
    'Delano',
    'Delaware Water Gap',
    'Delmont',
    'Delta',
    'Denbo',
    'Denver',
    'Derrick City',
    'Derry',
    'Devault',
    'Devon',
    'Dewart',
    'Dickerson Run',
    'Dickson City',
    'Dilliner',
    'Dillsburg',
    'Dilltown',
    'Dimock',
    'Dingman',
    'Dingmans Ferry',
    'Distant',
    'Dixonville',
    'Donegal',
    'Donora',
    'Dornsife',
    'Douglassville',
    'Dover',
    'Downingtown',
    'Doylesburg',
    'Doylestown',
    'Dravosburg',
    'Dresher',
    'Drexel Hill',
    'Drifting',
    'Drifton',
    'Driftwood',
    'Drumore',
    'Drums',
    'Dry Run',
    'Du Bois',
    'Dublin',
    'Dudley',
    'Duke Center',
    'Dunbar',
    'Duncannon',
    'Duncansville',
    'Dunlevy',
    'Dunlo',
    'Duquesne',
    'Durham',
    'Duryea',
    'Dushore',
    'Dysart',
    'Eagles Mere',
    'Eagleville',
    'Earlington',
    'Earlville',
    'East Berlin',
    'East Brady',
    'East Butler',
    'East Earl',
    'East Fairfield',
    'East Freedom',
    'East Greenville',
    'East Hickory',
    'East McKeesport',
    'East Millsboro',
    'East Petersburg',
    'East Pittsburgh',
    'East Prospect',
    'East Smethport',
    'East Smithfield',
    'East Springfield',
    'East Stroudsburg',
    'East Texas',
    'East Vandergrift',
    'East Waterford',
    'Easton',
    'Eau Claire',
    'Ebensburg',
    'Ebervale',
    'Edgemont',
    'Edinboro',
    'Edinburg',
    'Edmon',
    'Effort',
    'Eighty Four',
    'Elco',
    'Eldersville',
    'Elderton',
    'Eldred',
    'Elgin',
    'Elizabeth',
    'Elizabethtown',
    'Elizabethville',
    'Elkins Park',
    'Elkland',
    'Elliottsburg',
    'Ellsworth',
    'Ellwood City',
    'Elm',
    'Elmhurst',
    'Elmora',
    'Elrama',
    'Elton',
    'Elverson',
    'Elysburg',
    'Emeigh',
    'Emigsville',
    'Emlenton',
    'Emmaus',
    'Emporium',
    'Endeavor',
    'Enola',
    'Enon Valley',
    'Entriken',
    'Ephrata',
    'Equinunk',
    'Erie',
    'Ernest',
    'Erwinna',
    'Essington',
    'Etters',
    'Evans City',
    'Everett',
    'Everson',
    'Excelsior',
    'Export',
    'Exton',
    'Factoryville',
    'Fairbank',
    'Fairchance',
    'Fairfield',
    'Fairhope',
    'Fairless Hills',
    'Fairmount City',
    'Fairview',
    'Fairview Village',
    'Fallentimber',
    'Falls',
    'Falls Creek',
    'Fannettsburg',
    'Farmington',
    'Farrell',
    'Fawn Grove',
    'Fayette City',
    'Fayetteville',
    'Feasterville Trevose',
    'Felton',
    'Fenelton',
    'Ferndale',
    'Finleyville',
    'Fisher',
    'Fishertown',
    'Fleetville',
    'Fleetwood',
    'Fleming',
    'Flicksville',
    'Flinton',
    'Flourtown',
    'Fogelsville',
    'Folcroft',
    'Folsom',
    'Fombell',
    'Forbes Road',
    'Force',
    'Ford City',
    'Ford Cliff',
    'Forest City',
    'Forest Grove',
    'Forestville',
    'Forksville',
    'Fort Hill',
    'Fort Littleton',
    'Fort Loudon',
    'Fort Washington',
    'Fountainville',
    'Foxburg',
    'Frackville',
    'Franconia',
    'Franklin',
    'Franklintown',
    'Frederick',
    'Fredericksburg',
    'Fredericktown',
    'Fredonia',
    'Freeburg',
    'Freedom',
    'Freeland',
    'Freeport',
    'Frenchville',
    'Friedens',
    'Friedensburg',
    'Friendsville',
    'Frostburg',
    'Fryburg',
    'Furlong',
    'Gaines',
    'Galeton',
    'Gallitzin',
    'Gans',
    'Gap',
    'Garards Fort',
    'Gardenville',
    'Gardners',
    'Garland',
    'Garrett',
    'Gastonville',
    'Geigertown',
    'Genesee',
    'Georgetown',
    'German',
    'Germansville',
    'Gettysburg',
    'Gibbon Glade',
    'Gibson',
    'Gibsonia',
    'Gifford',
    'Gilbert',
    'Gilberton',
    'Gilbertsville',
    'Gillett',
    'Gipsy',
    'Girard',
    'Girardville',
    'Gladwyne',
    'Glasgow',
    'Glassport',
    'Glen Campbell',
    'Glen Hope',
    'Glen Lyon',
    'Glen Mills',
    'Glen Richey',
    'Glen Riddle Lima',
    'Glen Rock',
    'Glenmoore',
    'Glenolden',
    'Glenshaw',
    'Glenside',
    'Glenville',
    'Goodville',
    'Gordon',
    'Gordonville',
    'Gouldsboro',
    'Gowen City',
    'Gradyville',
    'Grampian',
    'Grand Valley',
    'Grantham',
    'Grantville',
    'Granville',
    'Granville Summit',
    'Grapeville',
    'Grassflat',
    'Gratz',
    'Gray',
    'Graysville',
    'Great Bend',
    'Greeley',
    'Green Lane',
    'Green Park',
    'Greencastle',
    'Greenock',
    'Greensboro',
    'Greensburg',
    'Greentown',
    'Greenville',
    'Grindstone',
    'Grove City',
    'Grover',
    'Guys Mills',
    'Gwynedd',
    'Gwynedd Valley',
    'Hadley',
    'Halifax',
    'Hallstead',
    'Hamburg',
    'Hamilton',
    'Hamlin',
    'Hannastown',
    'Hanover',
    'Harborcreek',
    'Harford',
    'Harleigh',
    'Harleysville',
    'Harmonsburg',
    'Harmony',
    'Harrisburg',
    'Harrison City',
    'Harrison Valley',
    'Harrisonville',
    'Harrisville',
    'Hartleton',
    'Hartstown',
    'Harveys Lake',
    'Harwick',
    'Hastings',
    'Hatboro',
    'Hatfield',
    'Haverford',
    'Havertown',
    'Hawk Run',
    'Hawley',
    'Hawthorn',
    'Hazel Hurst',
    'Hazleton',
    'Hegins',
    'Heilwood',
    'Hellertown',
    'Hempfield',
    'Hendersonville',
    'Henryville',
    'Hereford',
    'Herman',
    'Herminie',
    'Hermitage',
    'Herndon',
    'Herrick Center',
    'Hershey',
    'Hesston',
    'Hibbs',
    'Hickory',
    'Hidden Valley',
    'Highspire',
    'Hiller',
    'Hilliards',
    'Hillsdale',
    'Hillsgrove',
    'Hillsville',
    'Hilltown',
    'Holbrook',
    'Holicong',
    'Hollidaysburg',
    'Hollsopple',
    'Holmes',
    'Holtwood',
    'Home',
    'Homer City',
    'Homestead',
    'Honesdale',
    'Honey Brook',
    'Honey Grove',
    'Hookstown',
    'Hooversville',
    'Hop Bottom',
    'Hopeland',
    'Hopewell',
    'Hopwood',
    'Horsham',
    'Hostetter',
    'Houston',
    'Houtzdale',
    'Howard',
    'Hughesville',
    'Hummels Wharf',
    'Hummelstown',
    'Hunker',
    'Hunlock Creek',
    'Huntingdon',
    'Huntingdon Valley',
    'Huntington Mills',
    'Hustontown',
    'Hutchinson',
    'Hyde',
    'Hyde Park',
    'Hydetown',
    'Hyndman',
    'Hyner',
    'Ickesburg',
    'Idaville',
    'Imler',
    'Immaculata',
    'Imperial',
    'Indian Head',
    'Indiana',
    'Indianola',
    'Industry',
    'Ingomar',
    'Intercourse',
    'Irvine',
    'Irvona',
    'Irwin',
    'Isabella',
    'Jackson',
    'Jackson Center',
    'Jacobs Creek',
    'James City',
    'James Creek',
    'Jamestown',
    'Jamison',
    'Jeannette',
    'Jefferson',
    'Jenkintown',
    'Jenners',
    'Jennerstown',
    'Jermyn',
    'Jerome',
    'Jersey Mills',
    'Jersey Shore',
    'Jessup',
    'Jim Thorpe',
    'Joffre',
    'Johnsonburg',
    'Johnstown',
    'Jones Mills',
    'Jonestown',
    'Josephine',
    'Julian',
    'Juneau',
    'Junedale',
    'Kane',
    'Kantner',
    'Karns City',
    'Karthaus',
    'Keisterville',
    'Kelayres',
    'Kelton',
    'Kemblesville',
    'Kempton',
    'Kennerdell',
    'Kennett Square',
    'Kent',
    'Kersey',
    'Kimberton',
    'King Of Prussia',
    'Kingsley',
    'Kingston',
    'Kintnersville',
    'Kinzers',
    'Kirkwood',
    'Kittanning',
    'Kleinfeltersville',
    'Klingerstown',
    'Knox',
    'Knox Dale',
    'Knoxville',
    'Koppel',
    'Kossuth',
    'Kreamer',
    'Kresgeville',
    'Kulpmont',
    'Kulpsville',
    'Kunkletown',
    'Kutztown',
    'Kylertown',
    'La Belle',
    'La Jose',
    'La Plume',
    'Laceyville',
    'Lackawaxen',
    'Lafayette Hill',
    'Lahaska',
    'Lairdsville',
    'Lake Ariel',
    'Lake City',
    'Lake Como',
    'Lake Harmony',
    'Lake Lynn',
    'Lake Winola',
    'Lakeville',
    'Lakewood',
    'Lamar',
    'Lamartine',
    'Lampeter',
    'Lancaster',
    'Landenberg',
    'Landingville',
    'Landisburg',
    'Landisville',
    'Lanesboro',
    'Langeloth',
    'Langhorne',
    'Lansdale',
    'Lansdowne',
    'Lanse',
    'Lansford',
    'Laporte',
    'Larimer',
    'Latrobe',
    'Lattimer Mines',
    'Laughlintown',
    'Laurelton',
    'Laurys Station',
    'Lavelle',
    'Lawn',
    'Lawrence',
    'Lawrenceville',
    'Lawton',
    'Le Raysville',
    'Lebanon',
    'Leck Kill',
    'Leckrone',
    'Lecontes Mills',
    'Lederach',
    'Leechburg',
    'Leeper',
    'Leesport',
    'Leetsdale',
    'Lehigh Valley',
    'Lehighton',
    'Lehman',
    'Leisenring',
    'Lemasters',
    'Lemont',
    'Lemont Furnace',
    'Lemoyne',
    'Lenhartsville',
    'Lenni',
    'Lenoxville',
    'Leola',
    'Leroy',
    'Levittown',
    'Lewis Run',
    'Lewisberry',
    'Lewisburg',
    'Lewistown',
    'Lewisville',
    'Liberty',
    'Library',
    'Lickingville',
    'Light Street',
    'Ligonier',
    'Lilly',
    'Limekiln',
    'Limeport',
    'Limestone',
    'Lincoln University',
    'Linden',
    'Line Lexington',
    'Linesville',
    'Lionville',
    'Listie',
    'Lititz',
    'Little Meadows',
    'Littlestown',
    'Liverpool',
    'Llewellyn',
    'Lock Haven',
    'Locust Gap',
    'Locustdale',
    'Loganton',
    'Loganville',
    'Long Pond',
    'Lopez',
    'Loretto',
    'Lost Creek',
    'Lowber',
    'Loyalhanna',
    'Loysburg',
    'Loysville',
    'Lucernemines',
    'Lucinda',
    'Ludlow',
    'Lumberville',
    'Lurgan',
    'Luthersburg',
    'Luxor',
    'Luzerne',
    'Lykens',
    'Lyndell',
    'Lyndora',
    'Lyon Station',
    'Mackeyville',
    'Macungie',
    'Madera',
    'Madison',
    'Madisonburg',
    'Mahaffey',
    'Mahanoy City',
    'Mahanoy Plane',
    'Mainesburg',
    'Mainland',
    'Malvern',
    'Mammoth',
    'Manchester',
    'Manheim',
    'Manns Choice',
    'Manor',
    'Manorville',
    'Mansfield',
    'Mapleton Depot',
    'Mar Lin',
    'Marble',
    'Marchand',
    'Marcus Hook',
    'Marianna',
    'Marienville',
    'Marietta',
    'Marion',
    'Marion Center',
    'Marion Heights',
    'Markleton',
    'Markleysburg',
    'Mars',
    'Marshalls Creek',
    'Marsteller',
    'Martin',
    'Martindale',
    'Martins Creek',
    'Martinsburg',
    'Mary D',
    'Marysville',
    'Masontown',
    'Matamoras',
    'Mather',
    'Mattawana',
    'Maxatawny',
    'Mayport',
    'Maytown',
    'Mcadoo',
    'McAlisterville',
    'McClellandtown',
    'McClure',
    'McConnellsburg',
    'McConnellstown',
    'McDonald',
    'McElhattan',
    'McEwensville',
    'McGrann',
    'McIntyre',
    'McKean',
    'McKees Rocks',
    'McKeesport',
    'McKnightstown',
    'McSherrystown',
    'McVeytown',
    'Meadow Lands',
    'Meadville',
    'Mechanicsburg',
    'Mechanicsville',
    'Media',
    'Mehoopany',
    'Melcroft',
    'Mendenhall',
    'Menges Mills',
    'Mentcle',
    'Mercer',
    'Mercersburg',
    'Merion Station',
    'Merrittstown',
    'Mertztown',
    'Meshoppen',
    'Mexico',
    'Meyersdale',
    'Middleburg',
    'Middlebury Center',
    'Middleport',
    'Middletown',
    'Midland',
    'Midway',
    'Mifflin',
    'Mifflinburg',
    'Mifflintown',
    'Mifflinville',
    'Milan',
    'Milanville',
    'Mildred',
    'Milesburg',
    'Milford',
    'Milford Square',
    'Mill Creek',
    'Mill Hall',
    'Mill Run',
    'Mill Village',
    'Millersburg',
    'Millerstown',
    'Millersville',
    'Millerton',
    'Millheim',
    'Millmont',
    'Millrift',
    'Mills',
    'Millsboro',
    'Millville',
    'Milnesville',
    'Milroy',
    'Milton',
    'Mineral Point',
    'Mineral Springs',
    'Minersville',
    'Mingoville',
    'Minisink Hills',
    'Miquon',
    'Modena',
    'Mohnton',
    'Mohrsville',
    'Monaca',
    'Monessen',
    'Monocacy Station',
    'Monongahela',
    'Monroeton',
    'Monroeville',
    'Mont Alto',
    'Mont Clare',
    'Montandon',
    'Montgomery',
    'Montgomeryville',
    'Montoursville',
    'Montrose',
    'Moosic',
    'Morann',
    'Morgan',
    'Morgantown',
    'Morris',
    'Morris Run',
    'Morrisdale',
    'Morrisville',
    'Morton',
    'Moscow',
    'Moshannon',
    'Mount Aetna',
    'Mount Bethel',
    'Mount Braddock',
    'Mount Carmel',
    'Mount Gretna',
    'Mount Holly Springs',
    'Mount Jewett',
    'Mount Joy',
    'Mount Morris',
    'Mount Pleasant',
    'Mount Pleasant Mills',
    'Mount Pocono',
    'Mount Union',
    'Mount Wolf',
    'Mountain Top',
    'Mountainhome',
    'Mountville',
    'Muhlenberg',
    'Muir',
    'Muncy',
    'Muncy Valley',
    'Munson',
    'Murrysville',
    'Muse',
    'Myerstown',
    'Nanticoke',
    'Nanty Glo',
    'Narberth',
    'Narvon',
    'Natrona Heights',
    'Nazareth',
    'Needmore',
    'Neelyton',
    'Neffs',
    'Nelson',
    'Nemacolin',
    'Nescopeck',
    'Nesquehoning',
    'New Albany',
    'New Alexandria',
    'New Baltimore',
    'New Bedford',
    'New Berlin',
    'New Berlinville',
    'New Bethlehem',
    'New Bloomfield',
    'New Brighton',
    'New Buffalo',
    'New Castle',
    'New Columbia',
    'New Cumberland',
    'New Derry',
    'New Eagle',
    'New Enterprise',
    'New Florence',
    'New Freedom',
    'New Freeport',
    'New Galilee',
    'New Geneva',
    'New Germantown',
    'New Holland',
    'New Hope',
    'New Kensington',
    'New Kingstown',
    'New London',
    'New Milford',
    'New Millport',
    'New Oxford',
    'New Paris',
    'New Park',
    'New Philadelphia',
    'New Providence',
    'New Ringgold',
    'New Salem',
    'New Stanton',
    'New Tripoli',
    'New Wilmington',
    'Newburg',
    'Newell',
    'Newfoundland',
    'Newmanstown',
    'Newport',
    'Newry',
    'Newton Hamilton',
    'Newtown',
    'Newtown Square',
    'Newville',
    'Nicholson',
    'Nicktown',
    'Nineveh',
    'Nisbet',
    'Normalville',
    'Norristown',
    'North Apollo',
    'North Bend',
    'North East',
    'North Springfield',
    'North Versailles',
    'North Wales',
    'North Washington',
    'Northampton',
    'Northpoint',
    'Northumberland',
    'Norvelt',
    'Norwood',
    'Nottingham',
    'Noxen',
    'Nu Mine',
    'Numidia',
    'Nuremberg',
    'Oak Ridge',
    'Oakdale',
    'Oakland Mills',
    'Oakmont',
    'Oaks',
    'Ohiopyle',
    'Oil City',
    'Olanta',
    'Old Forge',
    'Old Zionsville',
    'Oley',
    'Oliveburg',
    'Oliver',
    'Olyphant',
    'Oneida',
    'Ono',
    'Orangeville',
    'Orbisonia',
    'Orefield',
    'Oreland',
    'Orrstown',
    'Orrtanna',
    'Orson',
    'Orviston',
    'Orwigsburg',
    'Osceola',
    'Osceola Mills',
    'Osterburg',
    'Ottsville',
    'Oxford',
    'Palm',
    'Palmerton',
    'Palmyra',
    'Paoli',
    'Paradise',
    'Pardeesville',
    'Parker',
    'Parker Ford',
    'Parkesburg',
    'Parkhill',
    'Parryville',
    'Patton',
    'Paupack',
    'Paxinos',
    'Paxtonville',
    'Peach Bottom',
    'Peach Glen',
    'Peckville',
    'Pen Argyl',
    'Penfield',
    'Penn',
    'Penn Run',
    'Penns Creek',
    'Penns Park',
    'Pennsburg',
    'Pennsylvania Furnace',
    'Penryn',
    'Pequea',
    'Perkasie',
    'Perkiomenville',
    'Perry',
    'Perryopolis',
    'Petersburg',
    'Petrolia',
    'Philadelphia',
    'Philipsburg',
    'Phoenixville',
    'Picture Rocks',
    'Pillow',
    'Pine Bank',
    'Pine Forge',
    'Pine Grove',
    'Pine Grove Mills',
    'Pineville',
    'Pipersville',
    'Pitcairn',
    'Pitman',
    'Pittsburgh',
    'Pittsfield',
    'Pittston',
    'Plainfield',
    'Pleasant Hall',
    'Pleasant Mount',
    'Pleasant Unity',
    'Pleasantville',
    'Plumstead',
    'Plumsteadville',
    'Plumville',
    'Plymouth',
    'Plymouth Meeting',
    'Pocono Lake',
    'Pocono Lake Preserve',
    'Pocono Manor',
    'Pocono Pines',
    'Pocono Summit',
    'Pocopson',
    'Point Marion',
    'Point Pleasant',
    'Polk',
    'Pomeroy',
    'Port Allegany',
    'Port Carbon',
    'Port Clinton',
    'Port Matilda',
    'Port Royal',
    'Port Trevorton',
    'Portage',
    'Porters Sideling',
    'Portersville',
    'Portland',
    'Potter',
    'Pottersdale',
    'Potts Grove',
    'Pottstown',
    'Pottsville',
    'Poyntelle',
    'Presto',
    'Preston Park',
    'Pricedale',
    'Primos',
    'Prompton',
    'Prospect',
    'Prospect Park',
    'Prosperity',
    'Pulaski',
    'Punxsutawney',
    'Quakake',
    'Quakertown',
    'Quarryville',
    'Quecreek',
    'Queen',
    'Quentin',
    'Quincy',
    'Railroad',
    'Ralston',
    'Ramey',
    'Ransom',
    'Ravine',
    'Reading',
    'Reamstown',
    'Rebersburg',
    'Rebuck',
    'Rector',
    'Red Hill',
    'Red Lion',
    'Reeders',
    'Reedsville',
    'Refton',
    'Rehrersburg',
    'Reinholds',
    'Renfrew',
    'Reno',
    'Renovo',
    'Republic',
    'Revere',
    'Revloc',
    'Rew',
    'Rexmont',
    'Reynoldsville',
    'Rheems',
    'Rices Landing',
    'Riceville',
    'Richboro',
    'Richeyville',
    'Richfield',
    'Richland',
    'Richlandtown',
    'Riddlesburg',
    'Ridgway',
    'Ridley Park',
    'Riegelsville',
    'Rillton',
    'Rimersburg',
    'Ringgold',
    'Ringtown',
    'Riverside',
    'Rixford',
    'Roaring Branch',
    'Roaring Spring',
    'Robertsdale',
    'Robeson',
    'Robesonia',
    'Robinson',
    'Rochester',
    'Rochester Mills',
    'Rock Glen',
    'Rockhill Furnace',
    'Rockton',
    'Rockwood',
    'Rogersville',
    'Rome',
    'Ronco',
    'Ronks',
    'Roscoe',
    'Rossiter',
    'Rossville',
    'Roulette',
    'Rouseville',
    'Rouzerville',
    'Rowland',
    'Roxbury',
    'Royersford',
    'Ruffs Dale',
    'Rural Ridge',
    'Rural Valley',
    'Rushland',
    'Rushville',
    'Russell',
    'Russellton',
    'Sabinsville',
    'Sacramento',
    'Sadsburyville',
    'Saegertown',
    'Sagamore',
    'Saint Benedict',
    'Saint Boniface',
    'Saint Clair',
    'Saint Johns',
    'Saint Marys',
    'Saint Michael',
    'Saint Peters',
    'Saint Petersburg',
    'Saint Thomas',
    'Salford',
    'Salfordville',
    'Salina',
    'Salisbury',
    'Salix',
    'Salona',
    'Saltillo',
    'Saltsburg',
    'Sandy Lake',
    'Sandy Ridge',
    'Sarver',
    'Sassamansville',
    'Saxonburg',
    'Saxton',
    'Saylorsburg',
    'Sayre',
    'Scenery Hill',
    'Schaefferstown',
    'Schellsburg',
    'Schenley',
    'Schnecksville',
    'Schuylkill',
    'Schuylkill Haven',
    'Schwenksville',
    'Sciota',
    'Scotland',
    'Scotrun',
    'Scottdale',
    'Scranton',
    'Seanor',
    'Selinsgrove',
    'Sellersville',
    'Seltzer',
    'Seminole',
    'Seneca',
    'Seven Valleys',
    'Seward',
    'Sewickley',
    'Shade Gap',
    'Shady Grove',
    'Shamokin',
    'Shamokin Dam',
    'Shanksville',
    'Sharon',
    'Sharon Hill',
    'Sharpsville',
    'Shartlesville',
    'Shavertown',
    'Shawanese',
    'Shawnee On Delaware',
    'Shawville',
    'Sheakleyville',
    'Sheffield',
    'Shelocta',
    'Shenandoah',
    'Sheppton',
    'Shermans Dale',
    'Shickshinny',
    'Shinglehouse',
    'Shippensburg',
    'Shippenville',
    'Shippingport',
    'Shirleysburg',
    'Shoemakersville',
    'Shohola',
    'Shrewsbury',
    'Shunk',
    'Sidman',
    'Sigel',
    'Silver Spring',
    'Silverdale',
    'Sinnamahoning',
    'Sipesville',
    'Six Mile Run',
    'Skippack',
    'Skytop',
    'Slate Run',
    'Slatedale',
    'Slatington',
    'Slickville',
    'Sligo',
    'Slippery Rock',
    'Slovan',
    'Smethport',
    'Smicksburg',
    'Smithfield',
    'Smithmill',
    'Smithton',
    'Smock',
    'Smokerun',
    'Smoketown',
    'Snow Shoe',
    'Snydersburg',
    'Snydertown',
    'Solebury',
    'Somerset',
    'Soudersburg',
    'Souderton',
    'South Buffalo',
    'South Canaan',
    'South Fayette',
    'South Fork',
    'South Gibson',
    'South Heights',
    'South Londonderry',
    'South Montrose',
    'South Mountain',
    'South Sterling',
    'South Whitehall',
    'Southampton',
    'Southeastern',
    'Southview',
    'Southwest',
    'Spangler',
    'Spartansburg',
    'Spinnerstown',
    'Spraggs',
    'Sprankle Mills',
    'Spring Church',
    'Spring City',
    'Spring Creek',
    'Spring Glen',
    'Spring Grove',
    'Spring House',
    'Spring Mills',
    'Spring Mount',
    'Spring Run',
    'Springboro',
    'Springdale',
    'Springfield',
    'Springs',
    'Springtown',
    'Springville',
    'Sproul',
    'Spruce Creek',
    'Stahlstown',
    'Star Junction',
    'Starford',
    'Starlight',
    'Starrucca',
    'State College',
    'State Line',
    'Steelville',
    'Sterling',
    'Stevens',
    'Stevensville',
    'Stewartstown',
    'Stillwater',
    'Stockdale',
    'Stockertown',
    'Stoneboro',
    'Stony Run',
    'Stoystown',
    'Strabane',
    'Strasburg',
    'Strattanville',
    'Strausstown',
    'Strongstown',
    'Stroudsburg',
    'Stump Creek',
    'Sturgeon',
    'Sugar Grove',
    'Sugar Run',
    'Sugarloaf',
    'Summerdale',
    'Summerhill',
    'Summerville',
    'Summit Hill',
    'Summit Station',
    'Sumneytown',
    'Sunbury',
    'Suplee',
    'Susquehanna',
    'Sutersville',
    'Swarthmore',
    'Sweet Valley',
    'Swengel',
    'Swiftwater',
    'Sybertsville',
    'Sycamore',
    'Sykesville',
    'Sylvania',
    'Tafton',
    'Talmage',
    'Tamaqua',
    'Tamiment',
    'Tannersville',
    'Tarentum',
    'Tarrs',
    'Tatamy',
    'Taylor',
    'Taylorstown',
    'Telford',
    'Temple',
    'Templeton',
    'Terre Hill',
    'Thomasville',
    'Thompson',
    'Thompsontown',
    'Thorndale',
    'Thornton',
    'Three Springs',
    'Tidioute',
    'Timblin',
    'Tioga',
    'Tiona',
    'Tionesta',
    'Tipton',
    'Tire Hill',
    'Titusville',
    'Tobyhanna',
    'Todd',
    'Topton',
    'Torrance',
    'Toughkenamon',
    'Towanda',
    'Tower City',
    'Townville',
    'Trafford',
    'Transfer',
    'Treichlers',
    'Tremont',
    'Tresckow',
    'Trevorton',
    'Trexlertown',
    'Trout Run',
    'Troutville',
    'Troxelville',
    'Troy',
    'Trumbauersville',
    'Tunkhannock',
    'Turbotville',
    'Turkey City',
    'Turtle Creek',
    'Turtlepoint',
    'Tuscarora',
    'Twin Rocks',
    'Tyler Hill',
    'Tylersburg',
    'Tylersport',
    'Tylersville',
    'Tyrone',
    'Uledi',
    'Ulster',
    'Ulysses',
    'Union City',
    'Union Dale',
    'Uniontown',
    'Unionville',
    'United',
    'Unity House',
    'Unityville',
    'University Park',
    'Upper Black Eddy',
    'Upper Darby',
    'Upper Uwchlan',
    'Upperstrasburg',
    'Ursina',
    'Utica',
    'Uwchland',
    'Valencia',
    'Valier',
    'Valley Forge',
    'Valley View',
    'Van Voorhis',
    'Vanderbilt',
    'Vandergrift',
    'Venango',
    'Venetia',
    'Venus',
    'Verona',
    'Vestaburg',
    'Vicksburg',
    'Villa Maria',
    'Villanova',
    'Vintondale',
    'Virginville',
    'Volant',
    'Vowinckel',
    'Wagontown',
    'Wallaceton',
    'Wallingford',
    'Walnut Bottom',
    'Walnutport',
    'Walston',
    'Waltersburg',
    'Wampum',
    'Wapwallopen',
    'Warfordsburg',
    'Warminster',
    'Warren',
    'Warren Center',
    'Warrendale',
    'Warrington',
    'Warriors Mark',
    'Washington',
    'Washington Boro',
    'Washington Crossing',
    'Washingtonville',
    'Waterfall',
    'Waterford',
    'Waterville',
    'Watson',
    'Watsontown',
    'Wattsburg',
    'Waverly',
    'Waymart',
    'Wayne',
    'Waynesboro',
    'Waynesburg',
    'Weatherly',
    'Webster',
    'Weedville',
    'Weikert',
    'Wellersburg',
    'Wells Tannery',
    'Wellsboro',
    'Wellsville',
    'Wendel',
    'Wernersville',
    'West Alexander',
    'West Chester',
    'West Decatur',
    'West Elizabeth',
    'West Finley',
    'West Grove',
    'West Hickory',
    'West Lebanon',
    'West Leisenring',
    'West Middlesex',
    'West Middletown',
    'West Mifflin',
    'West Milton',
    'West Newton',
    'West Pittsburg',
    'West Point',
    'West Salisbury',
    'West Springfield',
    'West Sunbury',
    'West Willow',
    'Westfield',
    'Westland',
    'Westline',
    'Westmoreland City',
    'Weston',
    'Westover',
    'Westport',
    'Westtown',
    'Wexford',
    'Wheatland',
    'White',
    'White Deer',
    'White Haven',
    'White Mills',
    'Whitehall',
    'Whitney',
    'Wickhaven',
    'Wiconisco',
    'Widnoon',
    'Wilburton',
    'Wilcox',
    'Wildwood',
    'Wilkes Barre',
    'Williamsburg',
    'Williamson',
    'Williamsport',
    'Williamstown',
    'Willow Grove',
    'Willow Hill',
    'Willow Street',
    'Wilmerding',
    'Wilmore',
    'Winburne',
    'Wind Gap',
    'Wind Ridge',
    'Windber',
    'Windsor',
    'Winfield',
    'Witmer',
    'Wolf',
    'Womelsdorf',
    'Wood',
    'Woodbury',
    'Woodland',
    'Woodlyn',
    'Woodward',
    'Woolrich',
    'Worcester',
    'Worthington',
    'Worthville',
    'Woxall',
    'Wrightsville',
    'Wyalusing',
    'Wyano',
    'Wycombe',
    'Wyncote',
    'Wynnewood',
    'Wyoming',
    'Wysox',
    'Yatesboro',
    'Yeagertown',
    'York',
    'York Haven',
    'York New Salem',
    'York Springs',
    'Youngstown',
    'Youngsville',
    'Youngwood',
    'Yukon',
    'Zelienople',
    'Zieglerville',
    'Zion Grove',
    'Zionhill',
    'Zionsville',
    'Zullinger'
]
