cities = [
    'Aberdeen',
    'Agar',
    'Akaska',
    'Alcester',
    'Alexandria',
    'Allen',
    'Alpena',
    'Amherst',
    'Andover',
    'Arlington',
    'Armour',
    'Artesian',
    'Ashton',
    'Astoria',
    'Aurora',
    'Avon',
    'Badger',
    'Baltic',
    'Barnard',
    'Batesland',
    'Bath',
    'Belle Fourche',
    'Belvidere',
    'Benton',
    'Beresford',
    'Bethlehem',
    'Big Sioux',
    'Big Stone City',
    'Bison',
    'Black Hawk',
    'Blunt',
    'Bonesteel',
    'Bowdle',
    'Box Elder',
    'Bradley',
    'Brandon',
    'Brandt',
    'Brantford',
    'Brentford',
    'Bridgewater',
    'Bristol',
    'Britton',
    'Brookings',
    'Bruce',
    'Bryant',
    'Buffalo',
    'Buffalo Gap',
    'Buffalo Ridge',
    'Bullhead',
    'Burbank',
    'Burke',
    'Cambria',
    'Camp Crook',
    'Canistota',
    'Canova',
    'Canton',
    'Caputa',
    'Carlisle',
    'Carpenter',
    'Carter',
    'Carthage',
    'Castlewood',
    'Cavour',
    'Centerville',
    'Chamberlain',
    'Chancellor',
    'Cherry Creek',
    'Chester',
    'Claire City',
    'Claremont',
    'Clark',
    'Clear Lake',
    'Cleveland',
    'Colman',
    'Colome',
    'Colton',
    'Columbia',
    'Conde',
    'Corona',
    'Corsica',
    'Creighton',
    'Cresbard',
    'Crooks',
    'Custer',
    'Dallas',
    'Dante',
    'Davis',
    'De Smet',
    'Deadwood',
    'Dell Rapids',
    'Delmont',
    'Dimock',
    'Doland',
    'Draper',
    'Dupree',
    'Eagle Butte',
    'Eden',
    'Edgemont',
    'Egan',
    'Elk Point',
    'Elkton',
    'Ellsworth AFB',
    'Elm Springs',
    'Emery',
    'Enning',
    'Erwin',
    'Estelline',
    'Ethan',
    'Eureka',
    'Fairburn',
    'Fairfax',
    'Fairview',
    'Faith',
    'Faulkton',
    'Fedora',
    'Ferney',
    'Firesteel',
    'Flandreau',
    'Florence',
    'Fort Meade',
    'Fort Pierre',
    'Fort Thompson',
    'Frankfort',
    'Frederick',
    'Freeman',
    'Fruitdale',
    'Fulton',
    'Gann Valley',
    'Garden City',
    'Garretson',
    'Gary',
    'Gayville',
    'Geddes',
    'Gettysburg',
    'Glad Valley',
    'Glencross',
    'Glenham',
    'Goodwin',
    'Gregory',
    'Grenville',
    'Groton',
    'Hamill',
    'Harrisburg',
    'Harrison',
    'Harrold',
    'Hartford',
    'Hayes',
    'Hayti',
    'Hazel',
    'Hecla',
    'Henry',
    'Hermosa',
    'Herreid',
    'Herrick',
    'Hetland',
    'Highmore',
    'Hill City',
    'Hitchcock',
    'Holabird',
    'Hosmer',
    'Hot Springs',
    'Houghton',
    'Hoven',
    'Howard',
    'Howes',
    'Hudson',
    'Humboldt',
    'Hurley',
    'Huron',
    'Ideal',
    'Interior',
    'Iona',
    'Ipswich',
    'Irene',
    'Iroquois',
    'Isabel',
    'Java',
    'Jefferson',
    'Kadoka',
    'Kaylor',
    'Keldron',
    'Kennebec',
    'Keystone',
    'Kimball',
    'Kranzburg',
    'Kyle',
    'Labolt',
    'Lake Andes',
    'Lake City',
    'Lake Norden',
    'Lake Preston',
    'Lane',
    'Langford',
    'Lantry',
    'Lead',
    'Lebanon',
    'Lennox',
    'Leola',
    'Lesterville',
    'Letcher',
    'Little Eagle',
    'Lodgepole',
    'Long Valley',
    'Longlake',
    'Lower Brule',
    'Ludlow',
    'Lyons',
    'Madison',
    'Mahto',
    'Manderson',
    'Mansfield',
    'Marion',
    'Martin',
    'Marty',
    'Marvin',
    'McIntosh',
    'McLaughlin',
    'Meadow',
    'Meckling',
    'Mellette',
    'Menno',
    'Midland',
    'Milbank',
    'Milesville',
    'Miller',
    'Mina',
    'Mission',
    'Mission Hill',
    'Mission Ridge',
    'Mitchell',
    'Mobridge',
    'Monroe',
    'Montrose',
    'Morristown',
    'Mound City',
    'Mount Vernon',
    'Mud Butte',
    'Murdo',
    'Nemo',
    'New Effington',
    'New Holland',
    'New Underwood',
    'Newell',
    'Nisland',
    'Norris',
    'North Sioux City',
    'Northville',
    'Nunda',
    'Oacoma',
    'Oelrichs',
    'Oglala',
    'Okaton',
    'Okreek',
    'Oldham',
    'Olivet',
    'Onaka',
    'Onida',
    'Opal',
    'Oral',
    'Orient',
    'Ortley',
    'Owanka',
    'Parade',
    'Parker',
    'Parkston',
    'Parmelee',
    'Peever',
    'Perry',
    'Philip',
    'Pickstown',
    'Piedmont',
    'Pierpont',
    'Pierre',
    'Pine Ridge',
    'Plankinton',
    'Platte',
    'Pollock',
    'Porcupine',
    'Prairie City',
    'Presho',
    'Pringle',
    'Provo',
    'Pukwana',
    'Quinn',
    'Ralph',
    'Ramona',
    'Rapid City',
    'Ravinia',
    'Raymond',
    'Red Owl',
    'Redfield',
    'Redig',
    'Ree Heights',
    'Reliance',
    'Renner',
    'Reva',
    'Revillo',
    'Ridgeview',
    'Rochford',
    'Rockham',
    'Roscoe',
    'Rosebud',
    'Rosholt',
    'Roslyn',
    'Rowena',
    'Rutland',
    'Saint Charles',
    'Saint Francis',
    'Saint Lawrence',
    'Saint Onge',
    'Salem',
    'Scenic',
    'Scotland',
    'Selby',
    'Seneca',
    'Shadehill',
    'Sinai',
    'Sioux Falls',
    'Sisseton',
    'Smithwick',
    'South Shore',
    'Spearfish',
    'Spencer',
    'Springfield',
    'Stephan',
    'Stickney',
    'Stockholm',
    'Strandburg',
    'Stratford',
    'Sturgis',
    'Summit',
    'Tabor',
    'Tea',
    'Timber Lake',
    'Tolstoy',
    'Toronto',
    'Trail City',
    'Trent',
    'Tripp',
    'Tulare',
    'Turton',
    'Tuthill',
    'Twin Brooks',
    'Tyndall',
    'Union Center',
    'Utica',
    'Vale',
    'Valley Springs',
    'Veblen',
    'Vermillion',
    'Viborg',
    'Vienna',
    'Virgil',
    'Vivian',
    'Volga',
    'Volin',
    'Wagner',
    'Wakonda',
    'Wakpala',
    'Walker',
    'Wall',
    'Wallace',
    'Wanblee',
    'Ward',
    'Warner',
    'Wasta',
    'Watauga',
    'Watertown',
    'Waubay',
    'Waverly',
    'Webster',
    'Wentworth',
    'Wessington',
    'Wessington Springs',
    'Westport',
    'Wewela',
    'White',
    'White Lake',
    'White Owl',
    'White River',
    'Whitehorse',
    'Whitewood',
    'Willow Lake',
    'Wilmot',
    'Winfred',
    'Winner',
    'Witten',
    'Wolsey',
    'Wood',
    'Woonsocket',
    'Worthing',
    'Wounded Knee',
    'Yale',
    'Yankton',
    'York'
]
