cities = [
    'Abbeville',
    'Adams Run',
    'Aiken',
    'Alcolu',
    'Allendale',
    'Anderson',
    'Andrews',
    'Arcadia',
    'Awendaw',
    'Aynor',
    'Ballentine',
    'Bamberg',
    'Barnwell',
    'Batesburg',
    'Batesburg-Leesville',
    'Bath',
    'Beaufort',
    'Beech Island',
    'Belton',
    'Bennettsville',
    'Bethera',
    'Bethune',
    'Bishopville',
    'Blacksburg',
    'Blackstock',
    'Blackville',
    'Blair',
    'Blenheim',
    'Bluffton',
    'Blythewood',
    'Bonneau',
    'Bowling Green',
    'Bowman',
    'Bradley',
    'Branchville',
    'Brunson',
    'Buffalo',
    'Cades',
    'Calhoun Falls',
    'Camden',
    'Cameron',
    'Campobello',
    'Canadys',
    'Carlisle',
    'Cassatt',
    'Catawba',
    'Cayce',
    'Centenary',
    'Central',
    'Chapin',
    'Chappells',
    'Charleston',
    'Charleston AFB',
    'Cheraw',
    'Chesnee',
    'Chester',
    'Chesterfield',
    'Clarks Hill',
    'Clearwater',
    'Clemson',
    'Cleveland',
    'Clifton',
    'Clinton',
    'Clio',
    'Clover',
    'Columbia',
    'Conestee',
    'Converse',
    'Conway',
    'Coosawatchie',
    'Cope',
    'Cordesville',
    'Cordova',
    'Cottageville',
    'Coward',
    'Cowpens',
    'Crocketville',
    'Cross',
    'Cross Anchor',
    'Cross Hill',
    'Dale',
    'Dalzell',
    'Darlington',
    'Daufuskie Island',
    'Davis Station',
    'Denmark',
    'Dillon',
    'Donalds',
    'Dorchester',
    'Drayton',
    'Due West',
    'Duncan',
    'Early Branch',
    'Easley',
    'Eastover',
    'Edgefield',
    'Edgemoor',
    'Edisto Island',
    'Effingham',
    'Ehrhardt',
    'Elgin',
    'Elko',
    'Elliott',
    'Elloree',
    'Enoree',
    'Estill',
    'Eutawville',
    'Fair Play',
    'Fairfax',
    'Fairforest',
    'Fingerville',
    'Florence',
    'Floyd Dale',
    'Folly Beach',
    'Fork',
    'Fort Lawn',
    'Fort Mill',
    'Fountain Inn',
    'Furman',
    'Gable',
    'Gadsden',
    'Gaffney',
    'Galivants Ferry',
    'Garden City',
    'Garnett',
    'Gaston',
    'Georgetown',
    'Gifford',
    'Gilbert',
    'Glendale',
    'Gloverville',
    'Goose Creek',
    'Gramling',
    'Graniteville',
    'Gray Court',
    'Great Falls',
    'Greeleyville',
    'Green Pond',
    'Green Sea',
    'Greenville',
    'Greenwood',
    'Greer',
    'Gresham',
    'Grover',
    'Hamer',
    'Hampton',
    'Hardeeville',
    'Harleyville',
    'Hartsville',
    'Heath Springs',
    'Hemingway',
    'Hickory Grove',
    'Hilda',
    'Hilton Head Island',
    'Hodges',
    'Holly Hill',
    'Hollywood',
    'Honea Path',
    'Hopkins',
    'Horatio',
    'Huger',
    'Inman',
    'Irmo',
    'Islandton',
    'Isle Of Palms',
    'Iva',
    'Jackson',
    'Jacksonboro',
    'Jamestown',
    'Jefferson',
    'Jenkinsville',
    'Joanna',
    'Johns Island',
    'Johnsonville',
    'Johnston',
    'Jonesville',
    'Kershaw',
    'Kinards',
    'Kingstree',
    'La France',
    'Ladson',
    'Lake City',
    'Lake View',
    'Lamar',
    'Lancaster',
    'Lando',
    'Landrum',
    'Lane',
    'Langley',
    'Latta',
    'Laurens',
    'Leesville',
    'Lexington',
    'Liberty',
    'Liberty Hill',
    'Little Mountain',
    'Little River',
    'Little Rock',
    'Lobeco',
    'Lockhart',
    'Lodge',
    'Long Creek',
    'Longs',
    'Loris',
    'Lowndesville',
    'Lugoff',
    'Luray',
    'Lydia',
    'Lyman',
    'Lynchburg',
    'Manning',
    'Marietta',
    'Marion',
    'Martin',
    'Mauldin',
    'Mayesville',
    'Mayo',
    'McBee',
    'McClellanville',
    'McColl',
    'McConnells',
    'McCormick',
    'Miley',
    'Minturn',
    'Modoc',
    'Moncks Corner',
    'Monetta',
    'Monticello',
    'Montmorenci',
    'Moore',
    'Mount Carmel',
    'Mount Croghan',
    'Mount Pleasant',
    'Mountain Rest',
    'Mountville',
    'Mullins',
    'Murrells Inlet',
    'Myrtle Beach',
    'Neeses',
    'Nesmith',
    'New Ellenton',
    'New Zion',
    'Newberry',
    'Newry',
    'Nichols',
    'Ninety Six',
    'Norris',
    'North',
    'North Augusta',
    'North Charleston',
    'North Myrtle Beach',
    'Norway',
    'Olanta',
    'Olar',
    'Orangeburg',
    'Pacolet',
    'Pacolet Mills',
    'Pageland',
    'Pamplico',
    'Parksville',
    'Patrick',
    'Pauline',
    'Pawleys Island',
    'Peak',
    'Pelion',
    'Pelzer',
    'Pendleton',
    'Perry',
    'Pickens',
    'Piedmont',
    'Pineland',
    'Pineville',
    'Pinewood',
    'Pinopolis',
    'Plum Branch',
    'Pomaria',
    'Port Royal',
    'Prosperity',
    'Rains',
    'Ravenel',
    'Reevesville',
    'Reidville',
    'Rembert',
    'Richburg',
    'Richland',
    'Ridge Spring',
    'Ridgeland',
    'Ridgeville',
    'Ridgeway',
    'Rion',
    'Rock Hill',
    'Roebuck',
    'Round O',
    'Rowesville',
    'Ruby',
    'Ruffin',
    'Russellville',
    'Saint George',
    'Saint Helena Island',
    'Saint Matthews',
    'Saint Stephen',
    'Salem',
    'Salley',
    'Salters',
    'Saluda',
    'Sandy Springs',
    'Santee',
    'Sardinia',
    'Scotia',
    'Scranton',
    'Seabrook',
    'Sellers',
    'Seneca',
    'Sharon',
    'Shaw A F B',
    'Sheldon',
    'Silverstreet',
    'Simpsonville',
    'Six Mile',
    'Slater',
    'Smoaks',
    'Smyrna',
    'Socastee',
    'Society Hill',
    'Spartanburg',
    'Springfield',
    'Starr',
    'Startex',
    'State Park',
    'Sullivans Island',
    'Summerton',
    'Summerville',
    'Sumter',
    'Sunset',
    'Swansea',
    'Sycamore',
    'Tamassee',
    'Tatum',
    'Taylors',
    'Tigerville',
    'Tillman',
    'Timmonsville',
    'Townville',
    'Travelers Rest',
    'Trenton',
    'Troy',
    'Turbeville',
    'Ulmer',
    'Una',
    'Union',
    'Van Wyck',
    'Vance',
    'Varnville',
    'Vaucluse',
    'Wadmalaw Island',
    'Wagener',
    'Walhalla',
    'Wallace',
    'Walterboro',
    'Ward',
    'Ware Shoals',
    'Warrenville',
    'Waterloo',
    'Wedgefield',
    'Wellford',
    'West Columbia',
    'West Union',
    'Westminster',
    'Westville',
    'White Oak',
    'White Rock',
    'White Stone',
    'Whitmire',
    'Williams',
    'Williamston',
    'Williston',
    'Windsor',
    'Winnsboro',
    'Woodruff',
    'Yemassee',
    'York'
]
