cities = [
    'Adams',
    'Adamsville',
    'Afton',
    'Alamo',
    'Alcoa',
    'Alexandria',
    'Allardt',
    'Allons',
    'Allred',
    'Alpine',
    'Altamont',
    'Andersonville',
    'Antioch',
    'Apison',
    'Ardmore',
    'Arlington',
    'Arnold AFB',
    'Arrington',
    'Arthur',
    'Ashland City',
    'Athens',
    'Atoka',
    'Atwood',
    'Auburntown',
    'Bakewell',
    'Bath Springs',
    'Baxter',
    'Bean Station',
    'Beech Bluff',
    'Beechgrove',
    'Beersheba Springs',
    'Belfast',
    'Bell Buckle',
    'Bells',
    'Belvidere',
    'Benton',
    'Bethel Springs',
    'Bethpage',
    'Big Rock',
    'Big Sandy',
    'Birchwood',
    'Blaine',
    'Bloomington Springs',
    'Blountville',
    'Bluff City',
    'Bogota',
    'Bolivar',
    'Bon Aqua',
    'Braden',
    'Bradford',
    'Bradyville',
    'Brentwood',
    'Briceville',
    'Brighton',
    'Bristol',
    'Brownsville',
    'Bruceton',
    'Brunswick',
    'Brush Creek',
    'Buchanan',
    'Buena Vista',
    'Buffalo Valley',
    'Bulls Gap',
    'Bumpus Mills',
    'Burlison',
    'Burns',
    'Butler',
    'Bybee',
    'Byrdstown',
    'Calhoun',
    'Camden',
    'Campaign',
    'Carthage',
    'Caryville',
    'Castalian Springs',
    'Cedar Grove',
    'Cedar Hill',
    'Celina',
    'Centerville',
    'Chapel Hill',
    'Chapmansboro',
    'Charleston',
    'Charlotte',
    'Chattanooga',
    'Chestnut Mound',
    'Chewalla',
    'Christiana',
    'Chuckey',
    'Church Hill',
    'Clairfield',
    'Clarkrange',
    'Clarksburg',
    'Clarksville',
    'Cleveland',
    'Clifton',
    'Clinton',
    'Coalfield',
    'Coalmont',
    'Cokercreek',
    'College Grove',
    'Collegedale',
    'Collierville',
    'Collinwood',
    'Columbia',
    'Como',
    'Conasauga',
    'Cookeville',
    'Copperhill',
    'Cordova',
    'Cornersville',
    'Corryton',
    'Cosby',
    'Cottage Grove',
    'Cottontown',
    'Counce',
    'Covington',
    'Cowan',
    'Crab Orchard',
    'Crawford',
    'Crockett Mills',
    'Cross Plains',
    'Crossville',
    'Crump',
    'Culleoka',
    'Cumberland City',
    'Cumberland Furnace',
    'Cumberland Gap',
    'Cunningham',
    'Cypress Inn',
    'Dandridge',
    'Darden',
    'Dayton',
    'Decatur',
    'Decaturville',
    'Decherd',
    'Deer Lodge',
    'Del Rio',
    'Delano',
    'Dellrose',
    'Denmark',
    'Dickson',
    'Dixon Springs',
    'Dover',
    'Dowelltown',
    'Doyle',
    'Dresden',
    'Drummonds',
    'Duck River',
    'Ducktown',
    'Duff',
    'Dukedom',
    'Dunlap',
    'Dyer',
    'Dyersburg',
    'Eads',
    'Eagan',
    'Eagleville',
    'Eaton',
    'Eidson',
    'Elgin',
    'Elizabethton',
    'Elkton',
    'Ellendale',
    'Elmwood',
    'Elora',
    'Englewood',
    'Enville',
    'Erin',
    'Erwin',
    'Estill Springs',
    'Ethridge',
    'Etowah',
    'Eva',
    'Evensville',
    'Fairview',
    'Fall Branch',
    'Farner',
    'Fayetteville',
    'Finger',
    'Finley',
    'Five Points',
    'Flag Pond',
    'Flintville',
    'Fosterville',
    'Frankewing',
    'Franklin',
    'Friendship',
    'Friendsville',
    'Fruitvale',
    'Gadsden',
    'Gainesboro',
    'Gallatin',
    'Gallaway',
    'Gates',
    'Gatlinburg',
    'Georgetown',
    'Germantown',
    'Gibson',
    'Gladeville',
    'Gleason',
    'Goodlettsville',
    'Goodspring',
    'Gordonsville',
    'Grand Junction',
    'Grandview',
    'Granville',
    'Graysville',
    'Greenback',
    'Greenbrier',
    'Greeneville',
    'Greenfield',
    'Grimsley',
    'Gruetli Laager',
    'Guild',
    'Guys',
    'Halls',
    'Hampshire',
    'Hampton',
    'Harriman',
    'Harrison',
    'Harrogate',
    'Hartford',
    'Hartsville',
    'Heiskell',
    'Helenwood',
    'Henderson',
    'Hendersonville',
    'Henry',
    'Hermitage',
    'Hickman',
    'Hickory Valley',
    'Hickory Withe',
    'Hilham',
    'Hillsboro',
    'Hixson',
    'Hohenwald',
    'Holladay',
    'Hollow Rock',
    'Hornbeak',
    'Hornsby',
    'Humboldt',
    'Huntingdon',
    'Huntland',
    'Huntsville',
    'Huron',
    'Hurricane Mills',
    'Idlewild',
    'Indian Mound',
    'Iron City',
    'Jacks Creek',
    'Jacksboro',
    'Jackson',
    'Jamestown',
    'Jasper',
    'Jefferson City',
    'Jellico',
    'Joelton',
    'Johnson City',
    'Jonesborough',
    'Kelso',
    'Kenton',
    'Kingsport',
    'Kingston',
    'Kingston Springs',
    'Knoxville',
    'Kodak',
    'Kyles Ford',
    'La Follette',
    'La Grange',
    'La Vergne',
    'Laconia',
    'Lafayette',
    'Lake City',
    'Lancaster',
    'Lancing',
    'Lascassas',
    'Laurel Bloomery',
    'Lavinia',
    'Lawrenceburg',
    'Lebanon',
    'Lenoir City',
    'Lenox',
    'Leoma',
    'Lewisburg',
    'Lexington',
    'Liberty',
    'Limestone',
    'Linden',
    'Livingston',
    'Lobelville',
    'Lone Mountain',
    'Lookout Mountain',
    'Loretto',
    'Loudon',
    'Louisville',
    'Lowland',
    'Lupton City',
    'Luray',
    'Luttrell',
    'Lutts',
    'Lyles',
    'Lynchburg',
    'Lynnville',
    'Macon',
    'Madison',
    'Madisonville',
    'Manchester',
    'Mansfield',
    'Martin',
    'Maryville',
    'Mascot',
    'Mason',
    'Maury City',
    'Maynardville',
    'McDonald',
    'McEwen',
    'McKenzie',
    'McLemoresville',
    'McMinnville',
    'Medina',
    'Medon',
    'Memphis',
    'Mercer',
    'Michie',
    'Middleton',
    'Midway',
    'Milan',
    'Milledgeville',
    'Milligan College',
    'Millington',
    'Milton',
    'Minor Hill',
    'Miston',
    'Mitchellville',
    'Mohawk',
    'Monroe',
    'Monteagle',
    'Monterey',
    'Mooresburg',
    'Morris Chapel',
    'Morrison',
    'Morristown',
    'Moscow',
    'Mosheim',
    'Moss',
    'Mount Carmel',
    'Mount Juliet',
    'Mount Pleasant',
    'Mountain City',
    'Mountain Home',
    'Mulberry',
    'Munford',
    'Murfreesboro',
    'Nashville',
    'New Johnsonville',
    'New Market',
    'New Tazewell',
    'Newbern',
    'Newcomb',
    'Newport',
    'Niota',
    'Nolensville',
    'Norene',
    'Normandy',
    'Norris',
    'Nunnelly',
    'Oak Ridge',
    'Oakdale',
    'Oakfield',
    'Oakland',
    'Obion',
    'Ocoee',
    'Old Hickory',
    'Oldfort',
    'Olivehill',
    'Oliver Springs',
    'Oneida',
    'Only',
    'Ooltewah',
    'Orlinda',
    'Ozone',
    'Pall Mall',
    'Palmer',
    'Palmersville',
    'Palmyra',
    'Paris',
    'Parrottsville',
    'Parsons',
    'Pegram',
    'Pelham',
    'Petersburg',
    'Petros',
    'Philadelphia',
    'Pickwick Dam',
    'Pigeon Forge',
    'Pikeville',
    'Piney Flats',
    'Pinson',
    'Pioneer',
    'Pleasant Hill',
    'Pleasant Shade',
    'Pleasant View',
    'Pleasantville',
    'Pocahontas',
    'Portland',
    'Powder Springs',
    'Powell',
    'Powells Crossroads',
    'Primm Springs',
    'Prospect',
    'Pruden',
    'Pulaski',
    'Puryear',
    'Quebeck',
    'Ramer',
    'Readyville',
    'Reagan',
    'Red Boiling Springs',
    'Reliance',
    'Riceville',
    'Rickman',
    'Riddleton',
    'Ridgely',
    'Ridgetop',
    'Rives',
    'Roan Mountain',
    'Robbins',
    'Rock Island',
    'Rockford',
    'Rockvale',
    'Rockwood',
    'Rogersville',
    'Rossville',
    'Rugby',
    'Russellville',
    'Rutherford',
    'Rutledge',
    'Saint Andrews',
    'Saint Bethlehem',
    'Saint Joseph',
    'Sale Creek',
    'Saltillo',
    'Samburg',
    'Santa Fe',
    'Sardis',
    'Saulsbury',
    'Savannah',
    'Scotts Hill',
    'Selmer',
    'Sequatchie',
    'Sevierville',
    'Sewanee',
    'Seymour',
    'Shady Valley',
    'Sharon',
    'Sharps Chapel',
    'Shawanee',
    'Shelbyville',
    'Sherwood',
    'Shiloh',
    'Signal Mountain',
    'Silerton',
    'Silver Point',
    'Slayden',
    'Smartt',
    'Smithville',
    'Smyrna',
    'Sneedville',
    'Soddy Daisy',
    'Somerville',
    'South Fulton',
    'South Pittsburg',
    'Southside',
    'Sparta',
    'Speedwell',
    'Spencer',
    'Spring City',
    'Spring Creek',
    'Spring Hill',
    'Springfield',
    'Springville',
    'Stanton',
    'Stantonville',
    'Stewart',
    'Strawberry Plains',
    'Sugar Tree',
    'Summertown',
    'Summitville',
    'Sunbright',
    'Surgoinsville',
    'Sweetwater',
    'Taft',
    'Talbott',
    'Tallassee',
    'Tazewell',
    'Telford',
    'Tellico Plains',
    'Ten Mile',
    'Tennessee Ridge',
    'Thompsons Station',
    'Thorn Hill',
    'Tigrett',
    'Tipton',
    'Toone',
    'Townsend',
    'Tracy City',
    'Trade',
    'Trenton',
    'Trezevant',
    'Trimble',
    'Troy',
    'Tullahoma',
    'Turtletown',
    'Unicoi',
    'Union City',
    'Unionville',
    'Vanleer',
    'Viola',
    'Vonore',
    'Walland',
    'Walling',
    'Wartburg',
    'Wartrace',
    'Washburn',
    'Watauga',
    'Watertown',
    'Watts Bar Dam',
    'Waverly',
    'Waynesboro',
    'Westmoreland',
    'Westpoint',
    'Westport',
    'White Bluff',
    'White House',
    'White Pine',
    'Whites Creek',
    'Whitesburg',
    'Whiteside',
    'Whiteville',
    'Whitleyville',
    'Whitwell',
    'Wilder',
    'Wildersville',
    'Williamsport',
    'Williston',
    'Winchester',
    'Winfield',
    'Winona',
    'Woodbury',
    'Woodland Mills',
    'Woodlawn',
    'Wynnburg',
    'Yorkville',
    'Yuma'
]
