cities = {
    'alabama': 'cities.us.cities_alabama',
    'alaska': 'cities.us.cities_alaska',
    'arizona': 'cities.us.cities_arizona',
    'arkansas': 'cities.us.cities_arkansas',
    'california': 'cities.us.cities_california',
    'colorado': 'cities.us.cities_colorado',
    'connecticut': 'cities.us.cities_connecticut',
    'delaware': 'cities.us.cities_delaware',
    'florida': 'cities.us.cities_florida',
    'georgia': 'cities.us.cities_georgia',
    'hawaii': 'cities.us.cities_hawaii',
    'idaho': 'cities.us.cities_idaho',
    'illinois': 'cities.us.cities_illinois',
    'indiana': 'cities.us.cities_indiana',
    'iowa': 'cities.us.cities_iowa',
    'kansas': 'cities.us.cities_kansas',
    'kentucky': 'cities.us.cities_kentucky',
    'louisiana': 'cities.us.cities_louisiana',
    'maine': 'cities.us.cities_maine',
    'maryland': 'cities.us.cities_maryland',
    'massachusetts': 'cities.us.cities_massachusetts',
    'michigan': 'cities.us.cities_michigan',
    'minnesota': 'cities.us.cities_minnesota',
    'mississippi': 'cities.us.cities_mississippi',
    'missouri': 'cities.us.cities_missouri',
    'montana': 'cities.us.cities_montana',
    'nebraska': 'cities.us.cities_nebraska',
    'nevada': 'cities.us.cities_nevada',
    'new hampshire': 'cities.us.cities_new_hampshire',
    'new jersey': 'cities.us.cities_new_jersey',
    'new mexico': 'cities.us.cities_new_mexico',
    'new york': 'cities.us.cities_new_york',
    'north carolina': 'cities.us.cities_north_carolina',
    'north dakota': 'cities.us.cities_north_dakota',
    'ohio': 'cities.us.cities_ohio',
    'oklahoma': 'cities.us.cities_oklahoma',
    'oregon': 'cities.us.cities_oregon',
    'pennsylvania': 'cities.us.cities_pennsylvania',
    'rhode island': 'cities.us.cities_rhode_island',
    'south carolina': 'cities.us.cities_south_carolina',
    'south dakota': 'cities.us.cities_south_dakota',
    'tennessee': 'cities.us.cities_tennessee',
    'texas': 'cities.us.cities_texas',
    'utah': 'cities.us.cities_utah',
    'vermont': 'cities.us.cities_vermont',
    'virginia': 'cities.us.cities_virginia',
    'washington': 'cities.us.cities_washington',
    'west virginia': 'cities.us.cities_west_virginia',
    'wisconsin': 'cities.us.cities_wisconsin',
    'wyoming': 'cities.us.cities_wyoming'
}
