cities = [
    'Adamant',
    'Albany',
    'Alburg',
    'Arlington',
    'Ascutney',
    'Averill',
    'Bakersfield',
    'Barnard',
    'Barnet',
    'Barre',
    'Barton',
    'Beebe Plain',
    'Beecher Falls',
    'Bellows Falls',
    'Belmont',
    'Belvidere Center',
    'Bennington',
    'Benson',
    'Bethel',
    'Bomoseen',
    'Bondville',
    'Bradford',
    'Brandon',
    'Brattleboro',
    'Bridgewater',
    'Bridgewater Corners',
    'Bridport',
    'Bristol',
    'Brookfield',
    'Brownsville',
    'Burlington',
    'Cabot',
    'Calais',
    'Cambridge',
    'Cambridgeport',
    'Canaan',
    'Castleton',
    'Cavendish',
    'Center Rutland',
    'Charlotte',
    'Chelsea',
    'Chester',
    'Chester Depot',
    'Chittenden',
    'Colchester',
    'Concord',
    'Corinth',
    'Coventry',
    'Craftsbury',
    'Craftsbury Common',
    'Cuttingsville',
    'Danby',
    'Danville',
    'Derby',
    'Derby Center',
    'Derby Line',
    'Dorset',
    'East Arlington',
    'East Barre',
    'East Berkshire',
    'East Burke',
    'East Calais',
    'East Charleston',
    'East Corinth',
    'East Dorset',
    'East Dover',
    'East Fairfield',
    'East Hardwick',
    'East Haven',
    'East Middlebury',
    'East Montpelier',
    'East Poultney',
    'East Randolph',
    'East Ryegate',
    'East Saint Johnsbury',
    'East Thetford',
    'East Wallingford',
    'Eden',
    'Eden Mills',
    'Enosburg Falls',
    'Essex',
    'Essex Junction',
    'Fair Haven',
    'Fairfax',
    'Fairfield',
    'Fairlee',
    'Ferrisburg',
    'Fletcher',
    'Florence',
    'Forest Dale',
    'Franklin',
    'Gaysville',
    'Gilman',
    'Glover',
    'Grafton',
    'Granby',
    'Grand Isle',
    'Graniteville',
    'Granville',
    'Greensboro',
    'Greensboro Bend',
    'Groton',
    'Guildhall',
    'Hancock',
    'Hardwick',
    'Hartford',
    'Hartland',
    'Hartland Four Corners',
    'Highgate Center',
    'Highgate Springs',
    'Hinesburg',
    'Huntington',
    'Hyde Park',
    'Hydeville',
    'Irasburg',
    'Island Pond',
    'Isle La Motte',
    'Jacksonville',
    'Jamaica',
    'Jeffersonville',
    'Jericho',
    'Johnson',
    'Jonesville',
    'Killington',
    'Lake Elmore',
    'Lincoln',
    'Londonderry',
    'Lowell',
    'Lower Waterford',
    'Ludlow',
    'Lunenburg',
    'Lyndon',
    'Lyndon Center',
    'Lyndonville',
    'Manchester',
    'Manchester Center',
    'Marlboro',
    'Marshfield',
    'McIndoe Falls',
    'Middlebury',
    'Middletown Springs',
    'Milton',
    'Monkton',
    'Montgomery',
    'Montgomery Center',
    'Montpelier',
    'Moretown',
    'Morgan',
    'Morrisville',
    'Moscow',
    'Mount Holly',
    'New Haven',
    'Newbury',
    'Newfane',
    'Newport',
    'Newport Center',
    'North Bennington',
    'North Clarendon',
    'North Concord',
    'North Ferrisburg',
    'North Hartland',
    'North Hero',
    'North Hyde Park',
    'North Montpelier',
    'North Pomfret',
    'North Pownal',
    'North Springfield',
    'North Thetford',
    'North Troy',
    'Northfield',
    'Northfield Falls',
    'Norton',
    'Norwich',
    'Orleans',
    'Orwell',
    'Passumpsic',
    'Pawlet',
    'Peacham',
    'Perkinsville',
    'Peru',
    'Pittsfield',
    'Pittsford',
    'Plainfield',
    'Plymouth',
    'Post Mills',
    'Poultney',
    'Pownal',
    'Proctor',
    'Proctorsville',
    'Putney',
    'Quechee',
    'Randolph',
    'Randolph Center',
    'Reading',
    'Readsboro',
    'Richford',
    'Richmond',
    'Ripton',
    'Rochester',
    'Roxbury',
    'Rupert',
    'Rutland',
    'Saint Albans',
    'Saint Albans Bay',
    'Saint Johnsbury',
    'Saint Johnsbury Center',
    'Salisbury',
    'Saxtons River',
    'Shaftsbury',
    'Sharon',
    'Sheffield',
    'Shelburne',
    'Sheldon',
    'Sheldon Springs',
    'Shoreham',
    'South Barre',
    'South Burlington',
    'South Hero',
    'South Londonderry',
    'South Newfane',
    'South Pomfret',
    'South Royalton',
    'South Ryegate',
    'South Strafford',
    'South Woodstock',
    'Springfield',
    'Stannard',
    'Starksboro',
    'Stockbridge',
    'Stowe',
    'Strafford',
    'Sudbury',
    'Sutton',
    'Swanton',
    'Taftsville',
    'Thetford',
    'Thetford Center',
    'Townshend',
    'Troy',
    'Tunbridge',
    'Underhill',
    'Underhill Center',
    'Vergennes',
    'Vernon',
    'Vershire',
    'Waitsfield',
    'Wallingford',
    'Wardsboro',
    'Warren',
    'Washington',
    'Waterbury',
    'Waterbury Center',
    'Waterville',
    'Websterville',
    'Wells',
    'Wells River',
    'West Burke',
    'West Charleston',
    'West Danville',
    'West Dover',
    'West Dummerston',
    'West Fairlee',
    'West Glover',
    'West Halifax',
    'West Hartford',
    'West Newbury',
    'West Pawlet',
    'West Rupert',
    'West Rutland',
    'West Topsham',
    'West Townshend',
    'West Wardsboro',
    'Westfield',
    'Westford',
    'Westminster',
    'Westminster Station',
    'Weston',
    'White River Junction',
    'Whiting',
    'Whitingham',
    'Wilder',
    'Williamstown',
    'Williamsville',
    'Williston',
    'Wilmington',
    'Windsor',
    'Winooski',
    'Wolcott',
    'Woodbury',
    'Woodford',
    'Woodstock',
    'Worcester'
]
