cities = [
    'Aberdeen',
    'Acme',
    'Addy',
    'Adna',
    'Airway Heights',
    'Albion',
    'Allyn',
    'Almira',
    'Amanda Park',
    'Amboy',
    'Anacortes',
    'Anatone',
    'Anderson Island',
    'Appleton',
    'Ardenvoir',
    'Ariel',
    'Arlington',
    'Ashford',
    'Asotin',
    'Auburn',
    'Bainbridge Island',
    'Baring',
    'Battle Ground',
    'Bay Center',
    'Beaver',
    'Belfair',
    'Bellevue',
    'Bellingham',
    'Belmont',
    'Benge',
    'Benton City',
    'Beverly',
    'Bickleton',
    'Bingen',
    'Black Diamond',
    'Blaine',
    'Blakely Island',
    'Bothell',
    'Bow',
    'Boyds',
    'Bremerton',
    'Brewster',
    'Bridgeport',
    'Brinnon',
    'Brownstown',
    'Brush Prairie',
    'Buckley',
    'Bucoda',
    'Buena',
    'Burbank',
    'Burley',
    'Burlington',
    'Burton',
    'Camano',
    'Camas',
    'Camp Murray',
    'Carbonado',
    'Carlsborg',
    'Carlton',
    'Carnation',
    'Carrolls',
    'Carson',
    'Cashmere',
    'Castle Rock',
    'Cathlamet',
    'Centerville',
    'Centralia',
    'Chattaroy',
    'Chehalis',
    'Chelan',
    'Chelan Falls',
    'Cheney',
    'Chewelah',
    'Chimacum',
    'Chinook',
    'Cinebar',
    'Clallam Bay',
    'Clarkston',
    'Clayton',
    'Cle Elum',
    'Clearlake',
    'Clinton',
    'Colbert',
    'Colfax',
    'College Place',
    'Colton',
    'Colville',
    'Conconully',
    'Concrete',
    'Connell',
    'Conway',
    'Copalis Beach',
    'Copalis Crossing',
    'Cosmopolis',
    'Cougar',
    'Coulee City',
    'Coulee Dam',
    'Coupeville',
    'Cowiche',
    'Creston',
    'Cunningham',
    'Curlew',
    'Curtis',
    'Cusick',
    'Custer',
    'Dallesport',
    'Danville',
    'Darrington',
    'Davenport',
    'Dayton',
    'Deer Harbor',
    'Deer Park',
    'Deming',
    'Desert Aire',
    'Dixie',
    'Doty',
    'Dryden',
    'Dupont',
    'Duvall',
    'East Olympia',
    'East Wenatchee',
    'Easton',
    'Eastsound',
    'Eatonville',
    'Edmonds',
    'Edwall',
    'Elbe',
    'Electric City',
    'Elk',
    'Ellensburg',
    'Elma',
    'Elmer City',
    'Eltopia',
    'Endicott',
    'Entiat',
    'Enumclaw',
    'Ephrata',
    'Ethel',
    'Evans',
    'Everett',
    'Fairfield',
    'Fall City',
    'Federal Way',
    'Ferndale',
    'Ford',
    'Forks',
    'Four Lakes',
    'Fox Island',
    'Freeland',
    'Freeman',
    'Friday Harbor',
    'Fruitland',
    'Galvin',
    'Garfield',
    'George',
    'Gifford',
    'Gig Harbor',
    'Glenoma',
    'Glenwood',
    'Gold Bar',
    'Goldendale',
    'Goose Prairie',
    'Graham',
    'Grand Coulee',
    'Grandview',
    'Granger',
    'Granite Falls',
    'Grapeview',
    'Grayland',
    'Grays River',
    'Greenacres',
    'Greenbank',
    'Hamilton',
    'Hansville',
    'Harrah',
    'Harrington',
    'Hartline',
    'Hatton',
    'Hay',
    'Hazel Dell North',
    'Heisson',
    'Hobart',
    'Hoodsport',
    'Hooper',
    'Hoquiam',
    'Humptulips',
    'Hunters',
    'Husum',
    'Ilwaco',
    'Inchelium',
    'Index',
    'Indianola',
    'Ione',
    'Issaquah',
    'Joyce',
    'Kahlotus',
    'Kalama',
    'Kapowsin',
    'Keller',
    'Kelso',
    'Kenmore',
    'Kennewick',
    'Kent',
    'Kettle Falls',
    'Keyport',
    'Kingston',
    'Kirkland',
    'Kittitas',
    'Klickitat',
    'La Center',
    'La Conner',
    'La Grande',
    'La Push',
    'Lacey',
    'Lacrosse',
    'Lake Stevens',
    'Lakebay',
    'Lakewood',
    'Lamona',
    'Lamont',
    'Langley',
    'Latah',
    'Laurier',
    'Leavenworth',
    'Lebam',
    'Liberty Lake',
    'Lilliwaup',
    'Lincoln',
    'Lind',
    'Littlerock',
    'Long Beach',
    'Longbranch',
    'Longmire',
    'Longview',
    'Loomis',
    'Loon Lake',
    'Lopez Island',
    'Lummi Island',
    'Lyle',
    'Lyman',
    'Lynden',
    'Lynnwood',
    'Mabton',
    'Malaga',
    'Malden',
    'Malo',
    'Malone',
    'Malott',
    'Manchester',
    'Mansfield',
    'Manson',
    'Maple Falls',
    'Maple Valley',
    'Marblemount',
    'Marcus',
    'Marlin',
    'Marshall',
    'Marysville',
    'Matlock',
    'Mattawa',
    'Mazama',
    'Mccleary',
    'Mckenna',
    'Mead',
    'Medical Lake',
    'Medina',
    'Menlo',
    'Mercer Island',
    'Mesa',
    'Metaline',
    'Metaline Falls',
    'Methow',
    'Mica',
    'Milton',
    'Mineral',
    'Moclips',
    'Mohler',
    'Monitor',
    'Monroe',
    'Montesano',
    'Morton',
    'Moses Lake',
    'Mossyrock',
    'Mount Vernon',
    'Mountlake Terrace',
    'Moxee',
    'Mukilteo',
    'Naches',
    'Nahcotta',
    'Napavine',
    'Naselle',
    'Neah Bay',
    'Neilton',
    'Nespelem',
    'Newman Lake',
    'Newport',
    'Nine Mile Falls',
    'Nooksack',
    'Nordland',
    'North Bend',
    'North Bonneville',
    'North Lakewood',
    'Northport',
    'Oak Harbor',
    'Oakesdale',
    'Oakville',
    'Ocean Park',
    'Ocean Shores',
    'Odessa',
    'Okanogan',
    'Olalla',
    'Olga',
    'Olympia',
    'Omak',
    'Onalaska',
    'Orcas',
    'Orient',
    'Orondo',
    'Oroville',
    'Orting',
    'Othello',
    'Otis Orchards',
    'Outlook',
    'Oysterville',
    'Pacific',
    'Pacific Beach',
    'Packwood',
    'Palisades',
    'Palouse',
    'Paradise Inn',
    'Parker',
    'Parkland',
    'Pasco',
    'Pateros',
    'Paterson',
    'Pe Ell',
    'Peshastin',
    'Plymouth',
    'Point Roberts',
    'Pomeroy',
    'Port Angeles',
    'Port Gamble',
    'Port Hadlock',
    'Port Ludlow',
    'Port Orchard',
    'Port Townsend',
    'Poulsbo',
    'Prescott',
    'Preston',
    'Prosser',
    'Pullman',
    'Puyallup',
    'Quilcene',
    'Quinault',
    'Quincy',
    'Rainier',
    'Randle',
    'Ravensdale',
    'Raymond',
    'Reardan',
    'Redmond',
    'Redondo',
    'Renton',
    'Republic',
    'Retsil',
    'Rice',
    'Richland',
    'Ridgefield',
    'Ritzville',
    'Riverside',
    'Rochester',
    'Rock Island',
    'Rockford',
    'Rockport',
    'Rollingbay',
    'Ronald',
    'Roosevelt',
    'Rosalia',
    'Rosburg',
    'Roslyn',
    'Roy',
    'Royal City',
    'Ryderwood',
    'Saint John',
    'Salkum',
    'Sammamish',
    'Satsop',
    'Seabeck',
    'Seahurst',
    'Seattle',
    'Seaview',
    'Sedro Woolley',
    'Sekiu',
    'Selah',
    'Sequim',
    'Shaw Island',
    'Shelton',
    'Shoreline',
    'Silvana',
    'Silver Creek',
    'Silverdale',
    'Silverlake',
    'Skamokawa',
    'Skykomish',
    'Snohomish',
    'Snoqualmie',
    'Snoqualmie Pass',
    'Soap Lake',
    'South Bend',
    'South Cle Elum',
    'South Colby',
    'South Prairie',
    'Southworth',
    'Spanaway',
    'Spangle',
    'Spokane',
    'Sprague',
    'Springdale',
    'Stanwood',
    'Starbuck',
    'Startup',
    'Stehekin',
    'Steilacoom',
    'Steptoe',
    'Stevenson',
    'Stratford',
    'Sultan',
    'Sumas',
    'Sumner',
    'Sunnyside',
    'Suquamish',
    'Tacoma',
    'Taholah',
    'Tahuya',
    'Tekoa',
    'Tenino',
    'Thornton',
    'Thorp',
    'Tieton',
    'Tokeland',
    'Toledo',
    'Tonasket',
    'Toppenish',
    'Touchet',
    'Toutle',
    'Tracyton',
    'Trout Lake',
    'Tumtum',
    'Tumwater',
    'Twisp',
    'Underwood',
    'Union',
    'Uniontown',
    'University Place',
    'Usk',
    'Vader',
    'Valley',
    'Valleyford',
    'Vancouver',
    'Vantage',
    'Vashon',
    'Vaughn',
    'Veradale',
    'Wahkiacus',
    'Waitsburg',
    'Waldron',
    'Walla Walla',
    'Waller',
    'Wallula',
    'Wapato',
    'Warden',
    'Washougal',
    'Washtucna',
    'Waterville',
    'Wauconda',
    'Wauna',
    'Waverly',
    'Wellpinit',
    'Wenatchee',
    'West Richland',
    'Westport',
    'White Salmon',
    'White Swan',
    'Wilbur',
    'Wilkeson',
    'Wilson Creek',
    'Winlock',
    'Winthrop',
    'Wishram',
    'Woodinville',
    'Woodland',
    'Yacolt',
    'Yakima',
    'Yelm',
    'Zillah'
]
