cities = [
    'Abbotsford',
    'Abrams',
    'Adams',
    'Adell',
    'Afton',
    'Albany',
    'Algoma',
    'Allenton',
    'Alma',
    'Alma Center',
    'Almena',
    'Almond',
    'Altoona',
    'Amberg',
    'Amery',
    'Amherst',
    'Amherst Junction',
    'Aniwa',
    'Antigo',
    'Appleton',
    'Arcadia',
    'Arena',
    'Argonne',
    'Argyle',
    'Arkansaw',
    'Arkdale',
    'Arlington',
    'Armstrong Creek',
    'Arpin',
    'Ashippun',
    'Ashland',
    'Athelstane',
    'Athens',
    'Auburndale',
    'Augusta',
    'Avalon',
    'Avoca',
    'Babcock',
    'Bagley',
    'Baileys Harbor',
    'Baldwin',
    'Balsam Lake',
    'Bancroft',
    'Bangor',
    'Baraboo',
    'Barneveld',
    'Barron',
    'Barronett',
    'Bassett',
    'Bay City',
    'Bayfield',
    'Bear Creek',
    'Beaver Dam',
    'Beetown',
    'Beldenville',
    'Belgium',
    'Belleville',
    'Belmont',
    'Beloit',
    'Benet Lake',
    'Benoit',
    'Benton',
    'Berlin',
    'Big Bend',
    'Big Falls',
    'Birchwood',
    'Birnamwood',
    'Black Creek',
    'Black Earth',
    'Black River Falls',
    'Blair',
    'Blanchardville',
    'Blenker',
    'Bloomer',
    'Bloomington',
    'Blue Mounds',
    'Blue River',
    'Bonduel',
    'Bone Lake',
    'Boscobel',
    'Boulder Junction',
    'Bowler',
    'Boyceville',
    'Boyd',
    'Branch',
    'Brandon',
    'Brantwood',
    'Briggsville',
    'Brill',
    'Brillion',
    'Bristol',
    'Brodhead',
    'Brokaw',
    'Brookfield',
    'Brooklyn',
    'Brownsville',
    'Browntown',
    'Bruce',
    'Brule',
    'Brussels',
    'Bryant',
    'Burlington',
    'Burnett',
    'Butler',
    'Butte Des Morts',
    'Butternut',
    'Byron',
    'Cable',
    'Cadott',
    'Caledonia',
    'Cambria',
    'Cambridge',
    'Cameron',
    'Camp Douglas',
    'Camp Lake',
    'Campbellsport',
    'Caroline',
    'Cascade',
    'Casco',
    'Cashton',
    'Cassville',
    'Cataract',
    'Catawba',
    'Cazenovia',
    'Cecil',
    'Cedar Grove',
    'Cedarburg',
    'Centuria',
    'Chaseburg',
    'Chelsea',
    'Chetek',
    'Chili',
    'Chilton',
    'Chippewa Falls',
    'Clam Lake',
    'Clayton',
    'Clear Lake',
    'Cleveland',
    'Clinton',
    'Clintonville',
    'Clyman',
    'Cobb',
    'Cochrane',
    'Colby',
    'Coleman',
    'Colfax',
    'Colgate',
    'Collins',
    'Coloma',
    'Columbus',
    'Combined Locks',
    'Comstock',
    'Conover',
    'Conrath',
    'Coon Valley',
    'Cornell',
    'Cornucopia',
    'Cottage Grove',
    'Couderay',
    'Crandon',
    'Crivitz',
    'Cross Plains',
    'Cuba City',
    'Cudahy',
    'Cumberland',
    'Curtiss',
    'Cushing',
    'Custer',
    'Dale',
    'Dallas',
    'Dalton',
    'Danbury',
    'Dane',
    'Darien',
    'Darlington',
    'De Forest',
    'De Pere',
    'De Soto',
    'Deer Park',
    'Deerbrook',
    'Deerfield',
    'Delafield',
    'Delavan',
    'Dellwood',
    'Denmark',
    'Dickeyville',
    'Dodge',
    'Dodgeville',
    'Dorchester',
    'Dousman',
    'Downing',
    'Downsville',
    'Doylestown',
    'Dresser',
    'Drummond',
    'Dunbar',
    'Durand',
    'Eagle',
    'Eagle River',
    'East Ellsworth',
    'East Troy',
    'Eastman',
    'Eaton',
    'Eau Claire',
    'Eau Galle',
    'Eden',
    'Edgar',
    'Edgerton',
    'Edgewater',
    'Edmund',
    'Egg Harbor',
    'Eland',
    'Elcho',
    'Elderon',
    'Eldorado',
    'Eleva',
    'Elk Mound',
    'Elkhart Lake',
    'Elkhorn',
    'Ellison Bay',
    'Ellsworth',
    'Elm Grove',
    'Elmwood',
    'Elroy',
    'Elton',
    'Embarrass',
    'Emerald',
    'Endeavor',
    'Ephraim',
    'Ettrick',
    'Eureka',
    'Evansville',
    'Exeland',
    'Fairchild',
    'Fairwater',
    'Fall Creek',
    'Fall River',
    'Fence',
    'Fennimore',
    'Ferryville',
    'Fifield',
    'Fish Creek',
    'Florence',
    'Fond du Lac',
    'Fontana',
    'Footville',
    'Forest',
    'Forest Junction',
    'Forestville',
    'Fort Atkinson',
    'Fountain City',
    'Fox Lake',
    'Foxboro',
    'Francis Creek',
    'Franklin',
    'Franksville',
    'Frederic',
    'Fredonia',
    'Freedom',
    'Fremont',
    'Friendship',
    'Friesland',
    'Galesville',
    'Galloway',
    'Gays Mills',
    'Genesee Depot',
    'Genoa',
    'Genoa City',
    'Georgetown',
    'Germantown',
    'Gile',
    'Gillett',
    'Gilman',
    'Gilmanton',
    'Gleason',
    'Glen Flora',
    'Glen Haven',
    'Glenbeulah',
    'Glenwood City',
    'Glidden',
    'Goodman',
    'Gordon',
    'Gotham',
    'Grafton',
    'Grand Marsh',
    'Grand View',
    'Granton',
    'Grantsburg',
    'Gratiot',
    'Green Bay',
    'Green Lake',
    'Green Valley',
    'Greenbush',
    'Greendale',
    'Greenleaf',
    'Greenville',
    'Greenwood',
    'Gresham',
    'Hager City',
    'Hales Corners',
    'Hammond',
    'Hancock',
    'Hannibal',
    'Hanover',
    'Harshaw',
    'Hartford',
    'Hartland',
    'Hatley',
    'Haugen',
    'Hawkins',
    'Hawthorne',
    'Hayward',
    'Hazel Green',
    'Hazelhurst',
    'Heafford Junction',
    'Helenville',
    'Herbster',
    'Hertel',
    'Hewitt',
    'High Bridge',
    'Highland',
    'Hilbert',
    'Hillpoint',
    'Hillsboro',
    'Hillsdale',
    'Hingham',
    'Hixton',
    'Holcombe',
    'Hollandale',
    'Holmen',
    'Honey Creek',
    'Horicon',
    'Hortonville',
    'Hubertus',
    'Hudson',
    'Humbird',
    'Hurley',
    'Hustisford',
    'Hustler',
    'Independence',
    'Iola',
    'Irma',
    'Iron Belt',
    'Iron Ridge',
    'Iron River',
    'Ixonia',
    'Jackson',
    'Janesville',
    'Jefferson',
    'Jim Falls',
    'Johnson Creek',
    'Juda',
    'Jump River',
    'Junction City',
    'Juneau',
    'Kansasville',
    'Kaukauna',
    'Kellnersville',
    'Kempster',
    'Kendall',
    'Kennan',
    'Kenosha',
    'Keshena',
    'Kewaskum',
    'Kewaunee',
    'Kickapoo',
    'Kiel',
    'Kieler',
    'Kimberly',
    'King',
    'Kingston',
    'Knapp',
    'Kohler',
    'Kossuth',
    'Krakow',
    'La Crosse',
    'La Farge',
    'La Pointe',
    'La Valle',
    'Lac Du Flambeau',
    'Ladysmith',
    'Lake Delton',
    'Lake Geneva',
    'Lake Mills',
    'Lake Nebagamon',
    'Lake Tomahawk',
    'Lakewood',
    'Lancaster',
    'Land O Lakes',
    'Lannon',
    'Laona',
    'Larsen',
    'Lebanon',
    'Lena',
    'Leopolis',
    'Lewis',
    'Liberty Grove',
    'Lime Ridge',
    'Linden',
    'Little Black',
    'Little Chute',
    'Little Suamico',
    'Livingston',
    'Lodi',
    'Loganville',
    'Lomira',
    'Lone Rock',
    'Long Lake',
    'Lowell',
    'Loyal',
    'Lublin',
    'Luck',
    'Ludington',
    'Luxemburg',
    'Lyndon Station',
    'Lynxville',
    'Lyons',
    'Madison',
    'Maiden Rock',
    'Malone',
    'Manawa',
    'Manitowish Waters',
    'Manitowoc',
    'Maple',
    'Maplewood',
    'Marathon',
    'Marengo',
    'Maribel',
    'Marinette',
    'Marion',
    'Markesan',
    'Marquette',
    'Marshall',
    'Marshfield',
    'Mason',
    'Mather',
    'Mattoon',
    'Mauston',
    'Mayville',
    'Mazomanie',
    'McFarland',
    'McNaughton',
    'Medford',
    'Medina',
    'Mellen',
    'Melrose',
    'Menasha',
    'Menomonee Falls',
    'Menomonie',
    'Mequon',
    'Mercer',
    'Merrill',
    'Merrillan',
    'Merrimac',
    'Merton',
    'Middleton',
    'Mikana',
    'Milladore',
    'Millston',
    'Milltown',
    'Milton',
    'Milwaukee',
    'Mindoro',
    'Mineral Point',
    'Minocqua',
    'Minong',
    'Mishicot',
    'Mondovi',
    'Monroe',
    'Montello',
    'Montfort',
    'Monticello',
    'Montreal',
    'Morrisonville',
    'Mosinee',
    'Mount Calvary',
    'Mount Hope',
    'Mount Horeb',
    'Mount Sterling',
    'Mountain',
    'Mukwonago',
    'Muscoda',
    'Muskego',
    'Nashotah',
    'Necedah',
    'Neenah',
    'Neillsville',
    'Nekoosa',
    'Nelson',
    'Nelsonville',
    'Neopit',
    'Neosho',
    'Neshkoro',
    'New Auburn',
    'New Berlin',
    'New Diggings',
    'New Franken',
    'New Glarus',
    'New Holstein',
    'New Lisbon',
    'New London',
    'New Munster',
    'New Richmond',
    'Newburg',
    'Newton',
    'Niagara',
    'Nichols',
    'North Freedom',
    'North Lake',
    'North Prairie',
    'Norwalk',
    'Oak Creek',
    'Oakdale',
    'Oakfield',
    'Oconomowoc',
    'Oconto',
    'Oconto Falls',
    'Odanah',
    'Ogdensburg',
    'Ogema',
    'Ojibwa',
    'Okauchee',
    'Omro',
    'Onalaska',
    'Oneida',
    'Ontario',
    'Oostburg',
    'Oregon',
    'Orfordville',
    'Osceola',
    'Oshkosh',
    'Osseo',
    'Owen',
    'Oxford',
    'Packwaukee',
    'Palmyra',
    'Pardeeville',
    'Park Falls',
    'Patch Grove',
    'Pearson',
    'Pelican Lake',
    'Pell Lake',
    'Pembine',
    'Pepin',
    'Peshtigo',
    'Pewaukee',
    'Phelps',
    'Phillips',
    'Phlox',
    'Pickerel',
    'Pickett',
    'Pigeon Falls',
    'Pine River',
    'Pittsville',
    'Plain',
    'Plainfield',
    'Platteville',
    'Pleasant Prairie',
    'Plover',
    'Plum City',
    'Plymouth',
    'Poplar',
    'Port Edwards',
    'Port Washington',
    'Port Wing',
    'Portage',
    'Porterfield',
    'Potosi',
    'Potter',
    'Pound',
    'Powers Lake',
    'Poy Sippi',
    'Poynette',
    'Prairie Du Chien',
    'Prairie Du Sac',
    'Prairie Farm',
    'Prentice',
    'Prescott',
    'Presque Isle',
    'Princeton',
    'Pulaski',
    'Racine',
    'Radisson',
    'Randolph',
    'Random Lake',
    'Readfield',
    'Readstown',
    'Redgranite',
    'Reedsburg',
    'Reedsville',
    'Reeseville',
    'Rewey',
    'Rhinelander',
    'Rib Lake',
    'Rice Lake',
    'Richfield',
    'Richland Center',
    'Ridgeland',
    'Ridgeway',
    'Ringle',
    'Rio',
    'Ripon',
    'River Falls',
    'Roberts',
    'Rochester',
    'Rock Falls',
    'Rock Springs',
    'Rockland',
    'Rosendale',
    'Rosholt',
    'Rothschild',
    'Royalton',
    'Rubicon',
    'Rudolph',
    'Saint Cloud',
    'Saint Croix Falls',
    'Saint Francis',
    'Saint Germain',
    'Saint Joseph',
    'Saint Nazianz',
    'Salem',
    'Sand Creek',
    'Sarona',
    'Sauk City',
    'Saukville',
    'Saxeville',
    'Saxon',
    'Sayner',
    'Scandinavia',
    'Schofield',
    'Seneca',
    'Sextonville',
    'Seymour',
    'Sharon',
    'Shawano',
    'Sheboygan',
    'Sheboygan Falls',
    'Sheldon',
    'Shell Lake',
    'Sherwood',
    'Shiocton',
    'Shullsburg',
    'Silver Lake',
    'Sinsinawa',
    'Siren',
    'Sister Bay',
    'Slinger',
    'Sobieski',
    'Soldiers Grove',
    'Solon Springs',
    'Somers',
    'Somerset',
    'South Milwaukee',
    'South Range',
    'South Wayne',
    'Sparta',
    'Spencer',
    'Spooner',
    'Spring Green',
    'Spring Valley',
    'Springbrook',
    'Springfield',
    'Stanley',
    'Star Lake',
    'Star Prairie',
    'Stetsonville',
    'Steuben',
    'Stevens Point',
    'Stitzer',
    'Stockbridge',
    'Stockholm',
    'Stoddard',
    'Stone Lake',
    'Stoughton',
    'Stratford',
    'Strum',
    'Sturgeon Bay',
    'Sturtevant',
    'Suamico',
    'Sullivan',
    'Summit Lake',
    'Sun Prairie',
    'Superior',
    'Suring',
    'Sussex',
    'Taylor',
    'Tennyson',
    'Theresa',
    'Thiensville',
    'Thorp',
    'Three Lakes',
    'Tigerton',
    'Tilleda',
    'Tisch Mills',
    'Tomah',
    'Tomahawk',
    'Tony',
    'Townsend',
    'Trego',
    'Trempealeau',
    'Trevor',
    'Tripoli',
    'Tunnel City',
    'Turtle Lake',
    'Twin Lakes',
    'Two Rivers',
    'Union Center',
    'Union Grove',
    'Unity',
    'Upson',
    'Valders',
    'Van Dyne',
    'Verona',
    'Vesper',
    'Viola',
    'Viroqua',
    'Wabeno',
    'Waldo',
    'Wales',
    'Walworth',
    'Warrens',
    'Wascott',
    'Washburn',
    'Washington Island',
    'Waterford',
    'Waterloo',
    'Watertown',
    'Waukau',
    'Waukesha',
    'Waunakee',
    'Waupaca',
    'Waupun',
    'Wausau',
    'Wausaukee',
    'Wautoma',
    'Wauzeka',
    'Webster',
    'West Bend',
    'West Salem',
    'Westboro',
    'Westby',
    'Westfield',
    'Weyauwega',
    'Weyerhaeuser',
    'Wheeler',
    'White Lake',
    'Whitehall',
    'Whitelaw',
    'Whitewater',
    'Wild Rose',
    'Willard',
    'Williams Bay',
    'Willow',
    'Wilmot',
    'Wilson',
    'Wilton',
    'Windsor',
    'Winnebago',
    'Winneconne',
    'Winter',
    'Wisconsin Dells',
    'Wisconsin Rapids',
    'Withee',
    'Wittenberg',
    'Wonewoc',
    'Woodford',
    'Woodland',
    'Woodman',
    'Woodruff',
    'Woodville',
    'Woodworth',
    'Wrightstown',
    'Wyocena',
    'Zachow',
    'Zenda'
]
