cities = [
    'Vienna',
    'Graz',
    'Linz',
    'Favoriten',
    'Donaustadt',
    'Floridsdorf',
    'Salzburg',
    'Innsbruck',
    'Ottakring',
    'Simmering',
    'Meidling',
    'Klagenfurt am Woerthersee',
    'Villach',
    'Hernals',
    'Hietzing',
    'Dornbirn',
    'Wiener Neustadt',
    'Steyr',
    'Hoetting',
    'Feldkirch',
    'Jakomini',
    'Pradl',
    'Lend',
    'Bregenz',
    'Gries',
    'Baden',
    'Geidorf',
    'Weinzierl bei Krems',
    'Lustenau',
    'Sankt Poelten',
    'Moedling',
    'Eggenberg',
    'Sankt Peter',
    'Sankt Martin',
    'Andritz',
    'Wilten',
    'Wels',
    'Innere Stadt',
    'Hohenems',
    'Stockerau',
    'Strassgang',
    'Sankt Leonhard',
    'Wetzelsdorf',
    'Klosterneuburg',
    'Amstetten',
    'Telfs',
    'Sankt Peter',
    'Perchtoldsdorf',
    'Krems an der Donau',
    'Liebenau',
    'Woergl',
    'Schwaz',
    'Bludenz',
    'Hard',
    'Hall in Tirol',
    'Gmunden',
    'Korneuburg',
    'Spittal an der Drau',
    'Tulln',
    'Schwechat',
    'Waltendorf',
    'Ried im Innkreis',
    'Brunn am Gebirge',
    'Rankweil',
    'Lienz',
    'Knittelfeld',
    'Goetzis',
    'Neunkirchen',
    'Gaenserndorf',
    'Annabichl',
    'Traun',
    'Goesting',
    'Arzl',
    'Sankt Veit an der Glan',
    'Imst',
    'Lauterach',
    'Strasshof an der Nordbahn',
    'Laakirchen',
    'Kufstein',
    'Enns',
    'Purkersdorf',
    'Mariatrost',
    'Gerasdorf bei Wien',
    'Sankt Johann in Tirol',
    'Viktring',
    'Wiener Neudorf',
    'Voitsberg',
    'Sankt Valentin',
    'Weiz',
    'Eisenstadt',
    'Rum',
    'Guntramsdorf',
    'Bruck an der Mur',
    'Neu-Guntramsdorf',
    'Berndorf',
    'Attnang-Puchheim',
    'Maria Enzersdorf',
    'Saalfelden am Steinernen Meer',
    'Deutsch-Wagram',
    'Puntigam',
    'Leibnitz',
    'Judenburg',
    'Wolfurt',
    'Deutschlandsberg',
    'Villacher Vorstadt',
    'Finkenstein am Faaker See',
    'Marchtrenk',
    'Kitzbuehel',
    'Leoben',
    'Neusiedl am See',
    'Villach-Innere Stadt',
    'Zirl',
    'Langenzersdorf',
    'Hoechst',
    'Wattens',
    'Seiersberg',
    'Trofaiach',
    'Landeck',
    'Zell am See',
    'Vorchdorf',
    'Bad Voeslau',
    'Bischofshofen',
    'Sankt Ruprecht',
    'Haid',
    'Kottingbrunn',
    'Freistadt',
    'Ternitz',
    'Oberwart',
    'Hallein',
    'Jenbach',
    'Absam',
    'Voesendorf',
    'Sankt Martin',
    'Bruck an der Leitha',
    'Hollabrunn',
    'Gratkorn',
    'Voels',
    'Reutte',
    'Altach',
    'Gross-Enzersdorf',
    'Traiskirchen',
    'Liezen',
    'Kremsmuenster',
    'Mattersburg',
    'Hainburg an der Donau',
    'Auen',
    'Wilhelmsburg',
    'Mattighofen',
    'Hafendorf',
    'Gallneukirchen',
    'Mistelbach',
    'Frastanz',
    'Gleisdorf',
    'Spratzern',
    'Hoerbranz',
    'Fuerstenfeld',
    'Neuhofen an der Krems',
    'Pressbaum',
    'Lichtenegg',
    'Muerzzuschlag',
    'Kirchbichl',
    'Micheldorf in Oberoesterreich',
    'Breitenfurt bei Wien',
    'Ries',
    'Perg',
    'Oberndorf bei Salzburg',
    'Kirchenviertel',
    'Amras',
    'Wimpassing',
    'Lochau',
    'Hart',
    'Deuchendorf',
    'Horn',
    'Judendorf',
    'Voelkendorf',
    'Pinkafeld',
    'Muehlau',
    'Neuzeug',
    'Himberg',
    'Woelfnitz',
    'Bad Hall',
    'Haag',
    'Lind',
    'Kirchberg in Tirol',
    'Ebreichsdorf',
    'Kindberg',
    'Kalsdorf bei Graz',
    'Axams',
    'Oberhaid',
    'Leopoldsdorf',
    'Sollenau'
]
