cities = [
    'Toronto',
    'Montreal',
    'Calgary',
    'Ottawa',
    'Edmonton',
    'Mississauga',
    'North York',
    'Winnipeg',
    'Scarborough',
    'Vancouver',
    'Quebec',
    'Hamilton',
    'Brampton',
    'Surrey',
    'Laval',
    'Halifax',
    'Etobicoke',
    'London',
    'Okanagan',
    'Victoria',
    'Windsor',
    'Markham',
    'Oshawa',
    'Gatineau',
    'Vaughan',
    'Kitchener',
    'Longueuil',
    'Burnaby',
    'Ladner',
    'Saskatoon',
    'Richmond Hill',
    'Barrie',
    'Richmond',
    'Nepean',
    'Regina',
    'Oakville',
    'Burlington',
    'Greater Sudbury',
    'Abbotsford',
    'Saguenay',
    'St. Catharines',
    'Sherbrooke',
    'Anmore',
    'Levis',
    'Kelowna',
    'Cambridge',
    'Trois-Rivieres',
    'Guelph',
    'East York',
    'Coquitlam',
    'Kingston',
    'Sydney',
    'Delta',
    'Dartmouth',
    'Thunder Bay',
    "St. John's",
    'Waterloo',
    'Terrebonne',
    'Ajax',
    'Saint John',
    'Pickering',
    'Brantford',
    'Moncton',
    'Nanaimo',
    'Milton',
    'Sarnia',
    'Niagara Falls',
    'Willowdale',
    'Saint-Laurent',
    'Chilliwack',
    'Repentigny',
    'Fort McMurray',
    'Peterborough',
    'Sault Ste. Marie',
    'Newmarket',
    'La Haute-Saint-Charles',
    'Red Deer',
    'Saint-Leonard',
    'Saint-Jean-sur-Richelieu',
    'Lethbridge',
    'Maple Ridge',
    'Brossard',
    'Kamloops',
    'Notre-Dame-de-Grace',
    'White Rock',
    'Prince George',
    'Medicine Hat',
    'Norfolk County',
    'Drummondville',
    'New Westminster',
    'St. Albert',
    'Sherwood Park',
    'Saint-Jerome',
    'Jonquiere',
    'Granby',
    'Fredericton',
    'Welland',
    'Saint-Hyacinthe',
    'North Bay',
    'Belleville',
    'Shawinigan',
    'Dollard-Des Ormeaux',
    'Cornwall',
    'North Vancouver',
    'Vernon',
    'Blainville',
    'West End',
    'Chatham',
    'Timmins',
    'Chateauguay',
    'Quinte West',
    'West Vancouver',
    'Charlottetown',
    'Rimouski',
    'Saint-Eustache',
    'Grande Prairie',
    'Boucherville',
    'Salaberry-de-Valleyfield',
    'Penticton',
    'St. Thomas',
    'Rock Forest',
    'Joliette',
    'Mirabel',
    'Mascouche',
    'Prince Albert',
    'Victoriaville',
    'Brant',
    'Woodstock',
    'Campbell River',
    'Ancaster',
    'Courtenay',
    'Orangeville',
    'North Cowichan',
    'Moose Jaw',
    'Midland',
    'Cote-Saint-Luc',
    'Saint-Georges',
    "Val-d'Or",
    'Stratford',
    'Orillia',
    'Pointe-Claire',
    'Baie-Comeau',
    'Alma',
    'Sainte-Julie',
    'West Kelowna',
    'Port Moody',
    'Lloydminster',
    'Boisbriand',
    'Brandon',
    'Vaudreuil-Dorion',
    'Thetford-Mines',
    'Walnut Grove',
    'Prince Edward',
    'Sainte-Therese',
    'Airdrie',
    'Mount Pearl',
    'Saint-Bruno-de-Montarville',
    'Rouyn-Noranda',
    'Saint-Constant',
    'Brockville',
    'Langley',
    'Whitehorse',
    'Owen Sound',
    'Chambly',
    'Sept-Iles',
    'Langford',
    'Duncan',
    'La Prairie',
    'Lower Sackville',
    'Port Alberni',
    'Keswick',
    'Varennes',
    'Clarence-Rockland',
    'Truro',
    'Westmount',
    'Kirkland',
    'Lindsay',
    'New Glasgow',
    'Cole Harbour',
    'Glace Bay',
    'Huntsville',
    'Terrace',
    'North Battleford',
    'Beaconsfield',
    'Mont-Royal',
    'Beloeil',
    'Corner Brook',
    'Cranbrook',
    'Port Colborne',
    'Riviere-du-Loup',
    'Dieppe',
    'Thorold',
    'Miramichi',
    'Cobourg',
    'Dorval',
    'Oak Bay',
    'Amos',
    'Spruce Grove',
    'Pitt Meadows',
    'Fort St. John',
    'Deux-Montagnes',
    'Saint-Augustin-de-Desmaures',
    'Conception Bay South',
    'Saint-Lazare',
    'Sainte-Catherine',
    "L'Assomption",
    'Edmundston',
    "L'Ancienne-Lorette",
    'Cochrane',
    'Lutes Mountain',
    'Sainte-Catherine',
    'Salmon Arm',
    'Rayside-Balfour',
    'Petawawa',
    'Fort Erie',
    'Candiac',
    'Yellowknife',
    'Collingwood',
    'Mont-Saint-Hilaire',
    'Camrose',
    'Yorkton',
    'Saint-Basile-le-Grand',
    'Leduc',
    'Pembroke',
    'Magog',
    'Greater Napanee',
    'Kenora',
    'le Plateau',
    'Fort Saskatchewan',
    'Okotoks',
    'Gaspe',
    'Matane',
    'Summerside',
    'Prince Rupert',
    'Swift Current',
    'Colwood',
    'Rosemere',
    'Williams Lake',
    'Saint-Lin-Laurentides',
    'Simcoe',
    'Quesnel',
    'Bay Roberts',
    'Mont-Laurier',
    'Portage la Prairie',
    'Dolbeau-Mistassini',
    'Powell River',
    'Brooks',
    'Bathurst',
    'Kentville',
    'Elliot Lake',
    'Thompson',
    'Aldergrove',
    'Canmore',
    'Hawkesbury',
    'North Perth',
    'Grand Falls-Windsor',
    'Parksville',
    'Beauharnois',
    'Ingersoll',
    'Montmagny',
    'Cold Lake',
    'Sainte-Marie',
    'Uxbridge',
    'Fall River',
    'Amherstburg',
    'Sainte-Marthe-sur-le-Lac',
    'Wetaskiwin',
    'Pincourt',
    'Paris',
    'Becancour',
    'North Saanich',
    'Cowansville',
    'Dawson Creek',
    'Sainte-Anne-des-Plaines',
    'Lambton Shores',
    'Sainte-Adele',
    'Les Coteaux',
    'Whistler',
    'Smiths Falls',
    'Sylvan Lake',
    'Temiskaming Shores',
    'Cantley',
    'Rawdon',
    'Labrador City',
    'Angus',
    'Prevost',
    'Mercier',
    'Lacombe',
    'Strathmore',
    'Hanceville',
    'South Huron',
    'Bells Corners',
    "L'Ile-Perrot",
    'Estevan',
    'Hinton',
    "Notre-Dame-de-l'Ile-Perrot",
    'High River',
    'Nelson',
    'Carleton Place',
    'Trail',
    'Selkirk',
    'Lorraine',
    'Steinbach',
    'Arnprior',
    'Lachute',
    'Val-des-Monts',
    'La Tuque',
    'Weyburn',
    'Amherst',
    'Dorchester',
    'Roberval',
    'Saint-Raymond',
    'Huron East',
    'Kapuskasing',
    'Saint-Sauveur',
    'Oromocto',
    'Kitimat',
    'La Malbaie',
    'Stony Plain',
    'Mont-Tremblant',
    'Binbrook',
    'Whitecourt',
    'Lavaltrie',
    'Ladysmith',
    'Pont-Rouge',
    'Castlegar',
    'Otterburn Park',
    'Dauphin',
    'Bois-des-Filion',
    'Winkler',
    'Concord',
    'Bracebridge',
    'Notre-Dame-des-Prairies',
    'Dryden',
    'Taber',
    'Morinville',
    'Silver Berry',
    'Saint-Felicien',
    'Saint-Hippolyte',
    'Bridgewater',
    'Goderich',
    'Wild Rose',
    'Renfrew',
    'Edson',
    'Fort Frances',
    'Chandler',
    'Kirkland Lake',
    'Slave Lake',
    'Happy Valley-Goose Bay',
    'Wasaga Beach',
    'Chibougamau',
    'Revelstoke',
    'Aylmer',
    'Pont Rouge',
    'Camlachie',
    'Banff',
    'Yarmouth',
    'Carignan',
    'Campbellton',
    'Beaumont',
    'Innisfil',
    'Delson',
    'Sydney Mines',
    'Baie-Saint-Paul',
    'Hanover',
    'La Sarre',
    'Asbestos',
    'Merritt',
    'Bluewater',
    'Coaticook',
    'Hampstead',
    'Olds',
    'Greenwood',
    'Gibsons',
    'Carbonear',
    'Saint-Zotique',
    'Kincardine',
    'Plessisville',
    'Brownsburg-Chatham',
    'Ponoka',
    'Mont-Joli',
    'Rocky Mountain House',
    'Kimberley',
    'Perth',
    'Parry Sound',
    'Pointe-Calumet',
    'Morden',
    'Coaldale',
    'Summerland',
    'Stephenville',
    'Amqui',
    'Beauceville',
    'Saint-Joseph-du-Lac',
    'Sooke',
    'Iqaluit',
    'Drayton Valley',
    'Farnham',
    'The Pas',
    'Bromont',
    'Saint-Felix-de-Valois'
]
