cities = [
    'Bogota',
    'Cali',
    'Medellin',
    'Barranquilla',
    'Cartagena',
    'Cucuta',
    'Bucaramanga',
    'Pereira',
    'Santa Marta',
    'Ibague',
    'Bello',
    'Pasto',
    'Manizales',
    'Neiva',
    'Soledad',
    'Villavicencio',
    'Armenia',
    'Soacha',
    'Valledupar',
    'Itaguei',
    'Monteria',
    'Sincelejo',
    'Popayan',
    'Floridablanca',
    'Palmira',
    'Buenaventura',
    'Barrancabermeja',
    'Dosquebradas',
    'Tulua',
    'Envigado',
    'Cartago',
    'Maicao',
    'Florencia',
    'Girardot City',
    'Sogamoso',
    'Guadalajara de Buga',
    'Tunja',
    'Giron',
    'Malambo',
    'Magangue',
    'Facatativa',
    'Riohacha',
    'Duitama',
    'Zipaquira',
    'Fusagasuga',
    'Cienaga',
    'Tumaco',
    'Apartado',
    'Piedecuesta',
    'Montelibano',
    'Ocana',
    'La Dorada',
    'Ipiales',
    'Quibdo',
    'Aguachica',
    'Yumbo',
    'Arauca',
    'Sabanalarga',
    'Chinchina',
    'Caldas',
    'Villa del Rosario',
    'Chia',
    'Rionegro',
    'Calarca',
    'Yopal',
    'Sahagun',
    'Fundacion',
    'Los Patios',
    'San Andres',
    'Caucasia',
    'Santa Rosa de Cabal',
    'Espinal',
    'Turbaco',
    'Cerete',
    'El Banco',
    'Funza',
    'Pitalito',
    'Puerto Tejada',
    'Pamplona',
    'Agustin Codazzi',
    'Turbo',
    'Madrid',
    'Arjona',
    'La Estrella',
    'Copacabana',
    'Plato',
    'Chigorodo',
    'El Carmen de Bolivar',
    'Florida',
    'Chiquinquira',
    'Jamundi',
    'Pradera',
    'Baranoa',
    'Piendamo',
    'Sevilla',
    'El Bagre',
    'Santander de Quilichao',
    'Acacias',
    'Lorica',
    'Segovia',
    'Corozal',
    'El Cerrito',
    'Payande',
    'Planeta Rica',
    'La Ceja',
    'San Marcos',
    'Montenegro',
    'Villamaria',
    'Sabaneta',
    'Puerto Berrio',
    'La Virginia',
    'San Gil',
    'Pivijay',
    'San Onofre',
    'Caicedonia',
    'Granada',
    'Belalcazar',
    'Quimbaya',
    'Mompos',
    'San Luis de Since',
    'Puerto Asis',
    'Leticia',
    'San Juan Nepomuceno',
    'Morales',
    'Garzon',
    'Tame',
    'Zarzal',
    'El Charco',
    'Libano',
    'Honda',
    'Palmar de Varela',
    'Aracataca',
    'Roldanillo',
    'Santiago de Tolu',
    'Puerto Boyaca',
    'La Tebaida',
    'Mosquera',
    'San Juan del Cesar',
    'La Mesa',
    'Ariguani',
    'Tierralta',
    'Puerto Colombia',
    'Melgar',
    'Santo Tomas',
    'Anaime',
    'Anserma',
    'Cajica',
    'Sabanagrande',
    'Buenaventura',
    'San Carlos',
    'Marinilla',
    'Cumaribo',
    'Candelaria',
    'Fonseca',
    'La Union',
    'Maria la Baja',
    'Sucre',
    'Sibate',
    'San Sebastian de Mariquita',
    'Campo de la Cruz',
    'San Carlos',
    'Ayapel',
    'Campoalegre',
    'Yarumal',
    'San Jose del Guaviare',
    'Curumani',
    'Mocoa',
    'Sampues',
    'Carmen de Viboral',
    'Flandes',
    'Patia',
    'Villeta',
    'Carepa',
    'Villa de San Diego de Ubate',
    'Morales',
    'Barbosa',
    'San Jacinto',
    'Tuquerres',
    'Circasia',
    'Lerida',
    'Villanueva',
    'Chaparral',
    'Galapa',
    'Aguadas',
    'Guacari',
    'Chinu',
    'Padua',
    'La Plata',
    'Riosucio',
    'Urrao',
    'Zaragoza',
    'Malaga',
    'Villanueva',
    'Repelon',
    'La Jagua de Ibirico',
    'San Benito Abad',
    'El Copey',
    'Salamina',
    'Socorro',
    'Santuario',
    'Fresno',
    'Cienaga de Oro',
    'Andalucia',
    'Barrancas',
    'Sonson',
    'Chimichagua',
    'Barbosa',
    'Pacho',
    'Puerto Lopez',
    'Corinto',
    'Andes',
    'Manzanares',
    'Puerto Santander',
    'San Martin',
    'Ciudad Bolivar',
    'El Reten',
    'Darien',
    'Santa Lucia',
    'Belen de Umbria',
    'Aguazul',
    'Viterbo',
    'Chiriguana',
    'La Union',
    'Guamo',
    'Chicoral',
    'Guaduas',
    'Los Palmitos',
    'Guarne',
    'Manati',
    'San Pablo',
    'Santa Ana',
    'Guapi',
    'Istmina',
    'Toro',
    'Orito',
    'Puerto Wilches',
    'Tibu',
    'Paipa',
    'Puebloviejo',
    'El Zulia',
    'Samaniego',
    'Ovejas',
    'La Paz',
    'Luruaco',
    'Miranda',
    'El Doncello',
    'Villanueva',
    'Supia',
    'Santa Barbara',
    'San Estanislao',
    'Bugalagrande',
    'Ansermanuevo',
    'Dagua',
    'Puerto Rico',
    'Amaga',
    'El Bordo',
    'Santa Fe de Antioquia',
    'Sitionuevo',
    'Neira',
    'Polonuevo',
    'Armero-Guyabal',
    'San Antero',
    'Dabeiba',
    'San Pedro',
    'Chivolo',
    'Candelaria',
    'Venadillo',
    'Pelaya',
    'Sabana de Torres',
    'Cimitarra',
    'San Vicente de Chucuri',
    'Cumaral',
    'Ponedera',
    'Natagaima',
    'Junin',
    'Marsella',
    'Majagual',
    'Garagoa',
    'San Pedro de Uraba',
    'La Victoria',
    'Gaitania',
    'Soata',
    'Velez',
    'Quinchia',
    'Agua de Dios',
    'Purificacion',
    'Necocli',
    'San Juan de Uraba',
    'Abrego',
    'Algeciras',
    'Ituango',
    'Valencia',
    'San Alberto',
    'Santa Rosa',
    'Pailitas',
    'Sandona',
    'Suan',
    'Tocaima',
    'Turbana',
    'Puerto Carreno',
    'Santa Rosa de Osos',
    'La Calera',
    'Tado',
    'Algarrobo',
    'Donmatias',
    'Suarez',
    'Valle del Guamuez',
    'Arauquita',
    'Condoto',
    'Palermo',
    'Coello',
    'Puerto Salgar',
    'Gigante',
    'Olaya Herrera',
    'Moniquira',
    'Amalfi',
    'Planadas',
    'Manaure',
    'Chinacota',
    'Vegachi',
    'Zambrano',
    'Restrepo',
    'Curillo',
    'San Agustin',
    'Galeras',
    'Sibundoy',
    'Aranzazu',
    'Concordia',
    'Cajamarca',
    'Saldana',
    'Riofrio',
    'Mahates',
    'Calamar',
    'Usiacuri',
    'Alcala',
    'Puerto Leguizamo',
    'San Juan de Betulia',
    'Pueblo Nuevo',
    'Villa Rica',
    'Guamal',
    'Becerril',
    'Astrea',
    'San Bernardo del Viento',
    'Fredonia',
    'Lebrija',
    'Santa Rosa del Sur',
    'San Pedro',
    'Clemencia',
    'La Cruz',
    'Juan de Acosta',
    'Frontino',
    'Urumita',
    'San Antonio',
    'Achi',
    'Sopo',
    'Arboletes',
    'Yotoco',
    'La Union',
    'Remolino',
    'Tolu Viejo',
    'Silvania',
    'Pacora',
    'Cisneros',
    'Timana',
    'Tubara',
    'Pensilvania',
    'Soplaviento',
    'Rivera',
    'San Diego',
    'Muzo',
    'Aipe',
    'Caqueza',
    'Manaure Balcon del Cesar',
    'El Dovio',
    'Retiro',
    'Sardinata',
    'Palestina',
    'Monterrey',
    'Jerico',
    'Jardin',
    'San Carlos',
    'Cicuco',
    'Barbacoas',
    'El Paujil',
    'Cota',
    'Choconta',
    'Cartagena del Chaira',
    'Cumbal',
    'Uribia',
    'Yondo',
    'Restrepo',
    'El Pinon',
    'Silvia',
    'Abejorral',
    'Gamarra',
    'Obando',
    'Inirida',
    'El Tambo',
    'San Rafael',
    'La Dorada'
]
