cities = [
    'Prague',
    'Brno',
    'Ostrava',
    'Pilsen',
    'Olomouc',
    'Liberec',
    'Ceske Budejovice',
    'Hradec Kralove',
    'Usti nad Labem',
    'Pardubice',
    'Havirov',
    'Zlin',
    'Kladno',
    'Most',
    'Karvina',
    'Opava',
    'Frydek-Mistek',
    'Decin',
    'Karlovy Vary',
    'Teplice',
    'Chomutov',
    'Jihlava',
    'Prostejov',
    'Prerov',
    'Jablonec nad Nisou',
    'Mlada Boleslav',
    'Ceska Lipa',
    'Trebic',
    'Trinec',
    'Tabor',
    'Znojmo',
    'Pribram',
    'Orlova',
    'Cheb',
    'Modrany',
    'Liben',
    'Trutnov',
    'Pisek',
    'Kolin',
    'Kromeriz',
    'Sumperk',
    'Vsetin',
    'Valasske Mezirici',
    'Litvinov',
    'Novy Jicin',
    'Uherske Hradiste',
    'Hodonin',
    'Breclav',
    'Cesky Tesin',
    'Krnov',
    'Sokolov',
    'Litomerice',
    'Havlickuv Brod',
    'Zgar nad Sazavou',
    'Zgar nad Sazavou Druhy',
    'Chrudim',
    'Strakonice',
    'Koprivnice',
    'Klatovy',
    'Bohumin',
    'Stary Bohumin',
    'Jindrichuv Hradec',
    'Vyskov',
    'Cerny Most',
    'Kutna Hora',
    'Nachod',
    'Jirkov',
    'Blansko',
    'Zatec',
    'Hranice',
    'Melnik',
    'Louny',
    'Otrokovice',
    'Kadan',
    'Branik',
    'Bruntal',
    'Beroun',
    'Uhersky Brod',
    'Svitavy',
    'Kralupy nad Vltavou',
    'Roznov pod Radhostem',
    'Ostrov',
    'Ceska Trebova',
    'Pelhrimov',
    'Rakovnik',
    'Neratovice',
    'Jicin',
    'Benesov',
    'Dvur Kralove nad Labem',
    'Varnsdorf',
    'Letnany',
    'Bilina',
    'Bilina Kyselka',
    'Prosek',
    'Brandys nad Labem-Stara Boleslav',
    'Usti nad Orlici',
    'Slany',
    'Klasterec nad Ohri',
    'Turnov',
    'Chodov',
    'Nymburk',
    'Zabreh',
    'Horni Pocernice',
    'Marianske Lazne',
    'Hlucin',
    'Cesky Krumlov',
    'Strizkov',
    'Sternberk',
    'Rokycany',
    'Krupka',
    'Podebrady',
    'Roudnice nad Labem',
    'Vrchlabi',
    'As',
    'Jaromer',
    'Tachov',
    'Jesenik',
    'Unicov',
    'Holesov',
    'Vysoke Myto',
    'Vlasim',
    'Kyjov',
    'Novy Bor',
    'Veseli nad Moravou',
    'Karlin',
    'Prachatice',
    'Velke Mezirici',
    'Rychnov nad Kneznou',
    'Vysocany',
    'Susice',
    'Moravska Trebova',
    'Frenstat pod Radhostem',
    'Ricany',
    'Boskovice',
    'Rumburk',
    'Domazlice',
    'Humpolec',
    'Nove Mesto na Morave',
    'Hlinsko',
    'Studenka',
    'Litomysl',
    'Stare Mesto',
    'Nove Mesto nad Metuji',
    'Celakovice',
    'Litovel',
    'Caslav',
    'Chotebor',
    'Lanskroun',
    'Frydlant nad Ostravici',
    'Mohelnice',
    'Ivancice',
    'Milevsko',
    'Kurim',
    'Nova Paka',
    'Lovosice',
    'Steti',
    'Policka',
    'Rymarov',
    'Semily',
    'Chocen',
    'Bystrice nad Pernstejnem',
    'Duchcov',
    'Horice',
    'Trebon',
    'Pribor',
    'Bystrice pod Hostynem',
    'Prelouc',
    'Nejdek',
    'Cerveny Kostelec',
    'Lipnik nad Becvou',
    'Mnichovo Hradiste',
    'Tyn nad Vltavou',
    'Broumov',
    'Tisnov',
    'Lysa nad Labem',
    'Vimperk',
    'Moravske Budejovice',
    'Dacice',
    'Dobris',
    'Sedlcany',
    'Stribro',
    'Napajedla',
    'Mikulov',
    'Dubi',
    'Hulin',
    'Bilovec',
    'Frydlant',
    'Sezimovo Usti',
    'Odry',
    'Hradek nad Nisou',
    'Sobeslav',
    'Kaplice',
    'Novy Bydzov',
    'Kraslice',
    'Slapanice',
    'Dobruska',
    'Slavicin',
    'Svetla nad Sazavou',
    'Nyrany',
    'Tanvald',
    'Petrvald',
    'Benatky nad Jizerou',
    'Letovice',
    'Kravare',
    'Rychvald',
    'Stare Mesto',
    'Blatna',
    'Mimon',
    'Vodnany',
    'Dubnany',
    'Cesky Brod',
    'Veseli nad Luznici',
    'Hronov',
    'Zelezny Brod',
    'Horovice',
    'Kojetin',
    'Bucovice',
    'Vratimov',
    'Prestice',
    'Mala Strana',
    'Tyniste nad Orlici',
    'Holice',
    'Podborany',
    'Vitkov',
    'Letohrad',
    'Kostelec nad Orlici',
    'Fulnek',
    'Zamberk',
    'Vrbno pod Pradedem',
    'Chrastava',
    'Moravsky Krumlov',
    'Ledec nad Sazavou',
    'Trest',
    'Upice',
    'Lomnice nad Popelkou',
    'Roztoky',
    'Slavkov u Brna',
    'Hustopece',
    'Straznice',
    'Telc',
    'Horni Slavkov',
    'Kraluv Dvur',
    'Jablunkov',
    'Dobrany',
    'Jilemnice',
    'Bechyne',
    'Horazgovice',
    'Sluknov',
    'Trebechovice pod Orebem',
    'Luhacovice',
    'Stochov',
    'Ceska Kamenice',
    'Senov',
    'Milovice',
    'Kbely',
    'Plana',
    'Skutec',
    'Zubri',
    'Ceska Skalice',
    'Frantiskovy Lazne',
    'Habartov',
    'Jilove',
    'Chlumec nad Cidlinou',
    'Rosice',
    'Hradec nad Moravici',
    'Valasske Klobouky',
    'Namest nad Oslavou',
    'Chropyne',
    'Tynec nad Sazavou',
    'Kunovice',
    'Pacov',
    'Kynsperk nad Ohri',
    'Nove Straseci',
    'Bystrice',
    'Nyrsko',
    'Doksy',
    'Protivin',
    'Rousinov',
    'Polna'
]
