cities = [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Reims',
    'Le Havre',
    'Cergy-Pontoise',
    'Saint-Etienne',
    'Toulon',
    'Angers',
    'Grenoble',
    'Dijon',
    'Nimes',
    'Aix-en-Provence',
    'Saint-Quentin-en-Yvelines',
    'Brest',
    'Le Mans',
    'Amiens',
    'Tours',
    'Limoges',
    'Clermont-Ferrand',
    'Villeurbanne',
    'Besancon',
    'Orleans',
    'Metz',
    'Rouen',
    'Mulhouse',
    'Perpignan',
    'Caen',
    'Boulogne-Billancourt',
    'Nancy',
    'Argenteuil',
    'Saint-Denis',
    'Roubaix',
    'Tourcoing',
    'Montreuil',
    'Avignon',
    'Marseille 13',
    'Asnieres-sur-Seine',
    'Nanterre',
    'Poitiers',
    'Versailles',
    'Courbevoie',
    'Creteil',
    'Pau',
    'Colombes',
    'Vitry-sur-Seine',
    'Aulnay-sous-Bois',
    'Marseille 08',
    'Marseille 15',
    'Marseille 09',
    'La Rochelle',
    'Champigny-sur-Marne',
    'Rueil-Malmaison',
    'Antibes',
    'Saint-Maur-des-Fosses',
    'Calais',
    'Beziers',
    'Dunkerque',
    'Aubervilliers',
    'Cannes',
    'Merignac',
    'Bourges',
    'Saint-Nazaire',
    'Colmar',
    'Valence',
    'Quimper',
    'Drancy',
    'Noisy-le-Grand',
    "Villeneuve-d'Ascq",
    'La Seyne-sur-Mer',
    'Levallois-Perret',
    'Marseille 14',
    'Chambery',
    'Issy-les-Moulineaux',
    'Neuilly-sur-Seine',
    'Troyes',
    'Antony',
    'La Roche-sur-Yon',
    'Marseille 12',
    'Lorient',
    'Sarcelles',
    'Pessac',
    'Ivry-sur-Seine',
    'Evreux',
    'Venissieux',
    'Cergy',
    'Clichy',
    'Marseille 11',
    'Saint-Quentin',
    'Niort',
    'Belfort',
    'Ajaccio',
    'Vannes',
    'Sartrouville',
    'Maisons-Alfort',
    'Meaux',
    'Blois',
    'Brive-la-Gaillarde',
    'Arles',
    'Beauvais',
    'Chateauroux',
    'Cholet',
    'Frejus',
    'Pantin',
    'Saint-Brieuc',
    'Montauban',
    'Charleville-Mezieres',
    'Albi',
    'Tarbes',
    'Fontenay-sous-Bois',
    'Evry',
    'Clamart',
    'Marseille 10',
    'Chalons-en-Champagne',
    'Narbonne',
    'Saint-Malo',
    'Laval',
    'Hyeres',
    'Carcassonne',
    'Angouleme',
    'Annecy',
    'Bondy',
    'Le Blanc-Mesnil',
    'Villejuif',
    'Grasse',
    'Sevran',
    'Castres',
    'Chalon-sur-Saone',
    'Marseille 04',
    'Arras',
    'Boulogne-sur-Mer',
    'Chelles',
    'Cagnes-sur-Mer',
    'Saint-Herblain',
    'Douai',
    'Epinay-sur-Seine',
    'Vincennes',
    'Martigues',
    'Marseille 03',
    'Bourg-en-Bresse',
    'Bobigny',
    'Montlucon',
    'Aubagne',
    'Valenciennes',
    'Suresnes',
    'Meudon',
    'Marseille 05',
    'Bayonne',
    'Istres',
    'Thionville',
    'Mantes-la-Jolie',
    'Compiegne',
    'Nevers',
    'Chartres',
    'Marseille 06',
    'Le Cannet',
    'Wattrelos',
    'Caluire-et-Cuire',
    'Gap',
    'Talence',
    'Ales',
    'Gennevilliers',
    'Saint-Priest',
    'Rosny-sous-Bois',
    'Auxerre',
    'Salon-de-Provence',
    'Saint-Germain-en-Laye',
    'Bastia',
    'Marseille 01',
    'Sete',
    'Anglet',
    'Puteaux',
    'Corbeil-Essonnes',
    'Garges-les-Gonesse',
    'Roanne',
    'Savigny-sur-Orge',
    'Epinal',
    'Livry-Gargan',
    'Saint-Ouen',
    'Reze',
    'Montigny-le-Bretonneux',
    'Noisy-le-Sec',
    'Melun',
    'Bagneux',
    'Massy',
    'Haguenau',
    'Montrouge',
    'Marcq-en-Baroeul',
    'Vitrolles',
    'Draguignan',
    'Lens',
    'Gagny',
    'Saint-Chamond',
    'Bron',
    'Vaulx-en-Velin',
    'Joue-les-Tours',
    'Alfortville',
    'La Courneuve',
    'Chatellerault',
    'Villepinte',
    'Cambrai',
    'Poissy',
    'Conflans-Sainte-Honorine',
    'Mont-de-Marsan',
    'Plaisir',
    'Marseille 07',
    'Marignane',
    'Dieppe',
    'Montelimar',
    'Tremblay-en-France',
    'Choisy-le-Roi',
    "Saint-Martin-d'Heres",
    'Macon',
    'Romans-sur-Isere',
    'Saint-Raphael',
    'Pontault-Combault',
    'Six-Fours-les-Plages',
    'Perigueux',
    'Aurillac',
    'Neuilly-sur-Marne',
    'Lievin',
    'Agen',
    'Franconville',
    'Sainte-Genevieve-des-Bois',
    'Maubeuge',
    'Bagnolet',
    'Saumur',
    'Biarritz',
    'La Ciotat',
    'Echirolles',
    'Villefranche-sur-Saone',
    'Chatenay-Malabry',
    'Stains',
    'Chatillon',
    'Vienne',
    'Schiltigheim',
    'Les Mureaux',
    'Le Perreux-sur-Marne',
    'Guyancourt',
    'Palaiseau',
    'Saint-Dizier',
    'Creil',
    'Vandoeuvre-les-Nancy',
    'Thonon-les-Bains',
    'Bethune',
    'Colomiers',
    'Nogent-sur-Marne',
    'Athis-Mons',
    'Viry-Chatillon',
    'Houilles',
    'Soissons',
    'Dreux',
    'Charenton-le-Pont',
    'Villeneuve-Saint-Georges',
    'Elancourt',
    'Alencon',
    'Sotteville-les-Rouen',
    'Orange',
    "Villenave-d'Ornon",
    'Pontoise',
    'Villiers-sur-Marne',
    'Chatou',
    'Goussainville',
    'Lomme',
    'Vierzon',
    'Saint-Medard-en-Jalles',
    'Thiais',
    'Carpentras',
    "L'Hay-les-Roses",
    'Menton',
    'Saint-Laurent-du-Var',
    'Saintes',
    'Rochefort',
    'Malakoff',
    'Draveil',
    'Saint-Leu',
    'Saint-Sebastien-sur-Loire',
    'Le Chesnay',
    'Tournefeuille',
    'Clichy-sous-Bois',
    'Chaumont',
    'Saint-Etienne-du-Rouvray',
    'Meyzieu',
    'Yerres',
    'Montbeliard',
    'Saint-Cloud',
    'Sens',
    'Laon',
    'Lambersart',
    'Trappes',
    'Rodez',
    'Bergerac',
    'Annemasse',
    'La Garde',
    'Ermont',
    'Rillieux-la-Pape',
    'Villemomble',
    'Pierrefitte-sur-Seine',
    'Le Kremlin-Bicetre',
    'Champs-sur-Marne',
    'Aix-les-Bains',
    'Bezons',
    'Vallauris',
    'Taverny',
    'Illkirch-Graffenstaden',
    'La Teste-de-Buch',
    'Epernay',
    'Villiers-le-Bel',
    'Vichy',
    'Sannois',
    'Gonesse',
    'Vigneux-sur-Seine',
    'Cavaillon',
    'Rambouillet',
    'Cherbourg-Octeville',
    'Armentieres',
    'Lunel',
    'Cachan',
    'Le Grand-Quevilly',
    'Abbeville',
    'La Garenne-Colombes',
    'Montigny-les-Metz',
    'Vanves',
    'Vernon',
    'Savigny-le-Temple',
    'Dole',
    'Villeneuve-sur-Lot',
    'Les Ulis',
    'Marseille 02',
    'Oyonnax',
    'Oullins',
    'Le Creusot',
    'Henin-Beaumont',
    'Orvault',
    'Coudekerque-Branche',
    'Herblay',
    'Ris-Orangis',
    'Sucy-en-Brie',
    'Grigny',
    'Fresnes',
    'Bourgoin',
    'Romainville',
    'Fontenay-aux-Roses',
    'Decines-Charpieu',
    'Saint-Die-des-Vosges',
    'Fontaine',
    'Auch',
    'Bruay-la-Buissiere',
    'Lisieux',
    'Sarreguemines',
    'Torcy',
    'Gradignan',
    'Lanester',
    'Bretigny-sur-Orge',
    'Muret',
    'Bois-Colombes',
    'Blagnac',
    'Herouville-Saint-Clair',
    'Libourne',
    'Le Bouscat',
    'Miramas',
    'Beaune',
    'Brunoy',
    'Eaubonne',
    'Villeparisis',
    'Montfermeil',
    'Sevres',
    'Fougeres',
    'Saint-Pol-sur-Mer',
    'La Madeleine',
    'Gif-sur-Yvette',
    'Bourgoin-Jallieu',
    'Begles',
    'Cahors',
    'Hazebrouck',
    'Millau',
    'Grande-Synthe',
    'La Valette-du-Var',
    'Moulins',
    'Mont-Saint-Aignan',
    'Etampes',
    'Mons-en-Baroeul',
    'Agde',
    "Saint-Ouen-l'Aumone",
    'Vertou',
    'Montgeron',
    'Maisons-Laffitte',
    'Le Puy-en-Velay',
    'Le Petit-Quevilly',
    'Lormont',
    'Olivet',
    'Acheres'
]
