cities = [
    'Berlin',
    'Hamburg',
    'Munich',
    'Koeln',
    'Frankfurt am Main',
    'Essen',
    'Stuttgart',
    'Dortmund',
    'Duesseldorf',
    'Bremen',
    'Hannover',
    'Leipzig',
    'Duisburg',
    'Nuernberg',
    'Dresden',
    'Wandsbek',
    'Bochum',
    'Bochum-Hordel',
    'Wuppertal',
    'Bielefeld',
    'Bonn',
    'Mannheim',
    'Marienthal',
    'Karlsruhe',
    'Hamburg-Nord',
    'Wiesbaden',
    'Muenster',
    'Gelsenkirchen',
    'Aachen',
    'Moenchengladbach',
    'Augsburg',
    'Eimsbuettel',
    'Altona',
    'Chemnitz',
    'Braunschweig',
    'Krefeld',
    'Halle',
    'Hamburg-Mitte',
    'Kiel',
    'Magdeburg',
    'Neue Neustadt',
    'Oberhausen',
    'Freiburg',
    'Luebeck',
    'Erfurt',
    'Harburg',
    'Hagen',
    'Rostock',
    'Kassel',
    'Hamm',
    'Mainz',
    'Saarbruecken',
    'Herne',
    'Muelheim',
    'Neukoelln',
    'Osnabrueck',
    'Solingen',
    'Ludwigshafen am Rhein',
    'Leverkusen',
    'Oldenburg',
    'Neuss',
    'Prenzlauer Berg Bezirk',
    'Bezirk Kreuzberg',
    'Potsdam',
    'Heidelberg',
    'Paderborn',
    'Darmstadt',
    'Wuerzburg',
    'Regensburg',
    'Wolfsburg',
    'Recklinghausen',
    'Goettingen',
    'Heilbronn',
    'Ingolstadt',
    'Ulm',
    'Bottrop',
    'Charlottenburg Bezirk',
    'Bergedorf',
    'Pforzheim',
    'Offenbach',
    'Friedrichshain Bezirk',
    'Bremerhaven',
    'Remscheid',
    'Berlin Schoeneberg',
    'Schoneberg Bezirk',
    'Nippes',
    'Reutlingen',
    'Furth',
    'Moers',
    'Koblenz',
    'Siegen',
    'Bergisch Gladbach',
    'Jena',
    'Gera',
    'Marzahn',
    'Hildesheim',
    'Erlangen',
    'Witten',
    'Salzgitter',
    'Trier',
    'Zwickau',
    'Kaiserslautern',
    'Iserlohn',
    'Schwerin',
    'Guetersloh',
    'Wilmersdorf Bezirk',
    'Dueren',
    'Esslingen',
    'Ratingen',
    'Marl',
    'Luenen',
    'Hanau am Main',
    'Velbert',
    'Ludwigsburg',
    'Flensburg',
    'Gesundbrunnen',
    'Cottbus',
    'Wilhelmshaven',
    'Tuebingen',
    'Minden',
    'Villingen-Schwenningen',
    'Konstanz',
    'Mitte',
    'Worms',
    'Lichterfelde',
    'Dorsten',
    'Luedenscheid',
    'Marburg an der Lahn',
    'Neumuenster',
    'Wedding Bezirk',
    'Castrop-Rauxel',
    'Bogenhausen',
    'Dessau',
    'Gladbeck',
    'Arnsberg',
    'Rheine',
    'Viersen',
    'Delmenhorst',
    'Reinickendorf',
    'Bayreuth',
    'Hellersdorf',
    'Troisdorf',
    'Giessen',
    'Bocholt',
    'Detmold',
    'Steglitz Bezirk',
    'Norderstedt',
    'Lueneburg',
    'Celle',
    'Moabit',
    'Dinslaken',
    'Bamberg',
    'Aschaffenburg',
    'Neubrandenburg',
    'Lippstadt',
    'Aalen',
    'Neuwied',
    'Unna',
    'Plauen',
    'Herten',
    'Herford',
    'Grevenbroich',
    'Weimar',
    'Kerpen',
    'Fulda',
    'Dormagen',
    'Bergheim',
    'Garbsen',
    'Wesel',
    'Kempten',
    'Schwabisch Gmund',
    'Sindelfingen',
    'Landshut',
    'Rosenheim',
    'Kopenick Bezirk',
    'Brandenburg an der Havel',
    'Ruesselsheim',
    'Berlin Koepenick',
    'Langenfeld',
    'Offenburg',
    'Stralsund',
    'Stolberg',
    'Hameln',
    'Zehlendorf Bezirk',
    'Menden',
    'Friedrichshafen',
    'Goeppingen',
    'Goerlitz',
    'Pankow',
    'Hattingen',
    'Tempelhof Bezirk',
    'Hilden',
    'Sankt Augustin',
    'Eschweiler',
    'Ahlen',
    'Bad Salzuflen',
    'Euskirchen',
    'Meerbusch',
    'Wolfenbuettel',
    'Huerth',
    'Baden-Baden',
    'Schweinfurt',
    'Neustadt',
    'Pulheim',
    'Neu-Hohenschoenhausen',
    'Gummersbach',
    'Waiblingen',
    'Nordhorn',
    'Greifswald',
    'Cuxhaven',
    'Wetzlar',
    'Bergkamen',
    'Bad Homburg vor der Hoehe',
    'Willich',
    'Frankfurt',
    'Emden',
    'Neu-Ulm',
    'Lingen',
    'Winterhude',
    'Erftstadt',
    'Neubrueck',
    'Ibbenbueren',
    'Passau',
    'Langenhagen',
    'Schwerte',
    'Speyer',
    'Heidenheim an der Brenz',
    'Berlin Treptow',
    'Peine',
    'Mariendorf',
    'Neunkirchen',
    'Bad Oeynhausen',
    'Lichtenrade',
    'Hof',
    'Friedrichsfelde',
    'Kleve',
    'Ravensburg',
    'Frechen',
    'Elmshorn',
    'Bornheim',
    'Soest',
    'Rastatt',
    'Erkrath',
    'Weissensee',
    'Stuttgart-Ost',
    'Duelmen',
    'Frankenthal',
    'Herzogenrath',
    'Loerrach',
    'Albstadt',
    'Gotha',
    'Melle',
    'Alsdorf',
    'Boeblingen',
    'Gronau',
    'Rheda-Wiedenbrueck',
    'Neustadt am Ruebenberge',
    'Kamen',
    'Leonberg',
    'Singen',
    'Stade',
    'Hennef',
    'Buende',
    'Meiderich',
    'Wismar',
    'Amberg',
    'Erkelenz',
    'Homburg',
    'Straubing',
    'Halle Neustadt',
    'Bruehl',
    'Fellbach',
    'Lehrte',
    'Nordhausen',
    'Lahr',
    'Eisenach',
    'Hoyerswerda',
    'Freiberg',
    'Pirmasens',
    'Goslar',
    'Filderstadt',
    'Suhl',
    'Weinheim',
    'Rodgau',
    'Bad Kreuznach',
    'Monheim am Rhein',
    'Gifhorn',
    'Bruchsal',
    'Rottenburg',
    'Alt-Hohenschoenhausen',
    'Freising',
    'Staaken',
    'Weiden',
    'Kaufbeuren',
    'Oberursel',
    'Nettetal',
    'Kaarst',
    'Wunstorf',
    'Eberswalde',
    'Bautzen',
    'Lemgo',
    'Coburg',
    'Bietigheim-Bissingen',
    'Muelheim',
    'Landau in der Pfalz',
    'Heinsberg',
    'Seevetal',
    'Lankwitz',
    'Koenigswinter',
    'Memmingen',
    'Voelklingen',
    'Borken',
    'Rudow',
    'Oranienburg',
    'Pinneberg',
    'Dreieich',
    'Pirna',
    'Aurich',
    'Barmbek-Nord',
    'Nurtingen',
    'Kirchheim unter Teck',
    'Laatzen',
    'Hueckelhoven',
    'Dachau',
    'Halberstadt',
    'Schorndorf',
    'Neumarkt in der Oberpfalz',
    'Mettmann',
    'Loehne',
    'Kamp-Lintfort',
    'Britz',
    'Bensheim',
    'Siegburg',
    'Gallus',
    'Freital',
    'Ettlingen',
    'Voerde',
    'Warendorf',
    'Sankt Ingbert',
    'Altenburg',
    'Schwabach',
    'Westend',
    'Buckow',
    'Saarlouis',
    'Maintal',
    'Buxtehude',
    'Ahaus',
    'Muehlhausen',
    'Schwedt',
    'Neustadt/Sued',
    'Beckum',
    'Haltern',
    'Hofheim am Taunus',
    'Stendal',
    'Wilhelmstadt',
    'Hemer',
    'Falkensee',
    'Buchholz in der Nordheide',
    'Riesa',
    'Wuerselen',
    'Germering',
    'Wermelskirchen',
    'Leinfelden-Echterdingen',
    'Coesfeld',
    'Schwaebisch Hall',
    'Niederkassel',
    'Porta Westfalica',
    'Datteln',
    'Kempen',
    'Lage',
    'Lurup',
    'Gropiusstadt',
    'Backnang',
    'Falkenhagener Feld',
    'Pasing',
    'Wesseling',
    'Emsdetten',
    'Langen',
    'Neu Isenburg',
    'Markisches Viertel',
    'Zweibruecken',
    'Sinsheim',
    'Greven',
    'Uelzen',
    'Bernau bei Berlin',
    'Tuttlingen',
    'Merseburg',
    'Steinfurt',
    'Spandau',
    'Wernigerode',
    'Balingen',
    'Schoenebeck',
    'Tegel',
    'Meppen',
    'Papenburg',
    'Geldern',
    'Kehl',
    'Vegesack',
    'Juelich',
    'Leer'
]
