cities = [
    'Asuncion',
    'Ciudad del Este',
    'San Lorenzo',
    'Capiata',
    'Lambare',
    'Fernando de la Mora',
    'Limpio',
    'Nemby',
    'Pedro Juan Caballero',
    'Encarnacion',
    'Mariano Roque Alonso',
    'Itaugua',
    'Villa Elisa',
    'Villa Hayes',
    'San Antonio',
    'Caaguazu',
    'Presidente Franco',
    'Coronel Oviedo',
    'Concepcion',
    'Villarrica',
    'Pilar',
    'Caazapa',
    'Caacupe',
    'Ita',
    'San Juan Bautista',
    'Nueva Esperanza',
    'Juan de Ayolas',
    'Santa Rita',
    'Colonia General Alfredo Stroessner',
    'Aregua',
    'San Isidro de Curuguaty',
    'Horqueta',
    'Lima',
    'Piribebuy',
    'Paraguari',
    'Tobati',
    'Ypacarai',
    'San Pedro de Ycuamandiyu',
    'Capitan Bado',
    'Guarambare',
    'Eusebio Ayala',
    'Filadelfia',
    'San Juan Nepomuceno',
    'Benjamin Aceval',
    'Doctor Juan Leon Mallorquin',
    'Salto del Guaira',
    'Santa Rosa Misiones',
    'Yaguaron',
    'Repatriacion',
    'Obligado',
    'Emboscada',
    'Carapegua',
    'San Pedro del Parana',
    'Bella Vista',
    'Colonia Menno',
    'Nanawua',
    'Arquitecto Tomas Romero Pereira',
    'Hohenau',
    'Quiindy',
    'Puerto Rosario',
    'San Jose',
    'Fuerte Olimpo'
]
