cities = [
    'Quezon City',
    'Manila',
    'Caloocan City',
    'Budta',
    'Davao',
    'Malingao',
    'Cebu City',
    'General Santos',
    'Taguig',
    'Pasig City',
    'Las Pinas',
    'Antipolo',
    'Makati City',
    'Zamboanga',
    'Bacolod City',
    'Mansilingan',
    'Cagayan de Oro',
    'Dasmarinas',
    'Pasay',
    'Iloilo',
    'San Jose del Monte',
    'Bacoor',
    'Lapu-Lapu City',
    'Iligan',
    'Mandaue City',
    'Calamba',
    'Iligan City',
    'Butuan',
    'Cabuyao',
    'Mandaluyong City',
    'Binan',
    'Angeles City',
    'Santol',
    'Cainta',
    'Baguio',
    'San Pedro',
    'Mantampay',
    'San Fernando',
    'Libertad',
    'Navotas',
    'Tacloban',
    'Batangas',
    'Magugpo Poblacion',
    'Taytay',
    'Lucena',
    'Puerto Princesa',
    'Olongapo',
    'Cabanatuan City',
    'Binangonan',
    'Santa Rosa',
    'Imus',
    'Lipa City',
    'San Pablo',
    'Malolos',
    'Ormoc',
    'Panalanoy',
    'Mabalacat City',
    'Pagadian',
    'Meycauayan',
    'Tarlac City',
    'Legaspi',
    'Cotabato',
    'Naga',
    'Dagupan',
    'Toledo',
    'Guyong',
    'Bago City',
    'Marawi City',
    'Kabankalan',
    'Baliuag',
    'Rodriguez',
    'San Mateo',
    'Talisay',
    'Muricay',
    'Bulaon',
    'Cadiz',
    'Koronadal',
    'Hagonoy',
    'San Juan',
    'Silang',
    'San Jose',
    'Digos',
    'Cavite City',
    'Tuguegarao',
    'Dumaguete',
    'Santiago',
    'Santa Cruz',
    'Mati',
    'Tanza',
    'Roxas City',
    'Laoag',
    'Pulong Santa Cruz',
    'Urdaneta',
    'Jolo',
    'Bocaue',
    'General Trias',
    'Los Banos',
    'Iriga City',
    'Dipolog',
    'Ozamiz City',
    'Calumpit',
    'Mangaldan',
    'Arayat',
    'Surigao',
    'Angono',
    'Victorias',
    'Tagbilaran City',
    'Panabo',
    'Mariveles',
    'Binonga',
    'NIA Valencia',
    'Marilao',
    'San Fernando',
    'Sorsogon',
    'Kidapawan',
    'Norzagaray',
    'Gapan',
    'Daet',
    'Apalit',
    'Pulilan',
    'Polangui',
    'Guiguinto',
    'Kawit',
    'Balanga',
    'Ilagan',
    'Sagay',
    'Capas',
    'Solana',
    'Bulacan',
    'Tagaytay',
    'Plaridel',
    'Mariano',
    'Danao',
    'Magalang',
    'Libon',
    'Tanauan',
    'Catbalogan',
    'Calbayog City',
    'Subic',
    'Bislig',
    'City of Isabela',
    'Dinalupihan',
    'Calapan',
    'San Ildefonso',
    'San Miguel',
    'Bais',
    'Talisay',
    'Talavera',
    'Concepcion',
    'Polomolok',
    'Nasugbu',
    'Tinongan',
    'Minglanilla',
    'Malaybalay',
    'Candelaria',
    'Ualog',
    'Tanay',
    'Obando',
    'Balagtas',
    'Manaoag',
    'Banga',
    'Tabaco',
    'Santo Tomas',
    'Kalibo (poblacion)',
    'Lingayen',
    'Carmona',
    'Lubao',
    'Naic',
    'Tacurong',
    'Batac City',
    'Patuto',
    'Limay',
    'Malungun',
    'Monkayo',
    'Dapitan',
    'Balayan',
    'Cabiao',
    'Morong',
    'Liloan',
    'Port Area',
    'Consolacion',
    'Vigan',
    'Paniqui',
    'Bayombong',
    'Masbate',
    'Catarman',
    'Candaba',
    'Santa Ana',
    'Orion',
    'Bagong Pagasa',
    'Bugo',
    'Sariaya',
    'Parang',
    'Orani',
    'Canlaon',
    'Binmaley',
    'Mexico',
    'Samal',
    'Pinamalayan',
    'Alabel',
    'Passi',
    'Recodo',
    'Compostela',
    'Bustos',
    'Paombong',
    'Masantol',
    'La Trinidad',
    'Angat',
    'Indang',
    'La Carlota',
    'Malita',
    'Gerona',
    'Pagbilao',
    'Carcar',
    'Bayugan',
    'Mamatid',
    'Taal',
    'Jaen',
    'Camiling',
    'Hinigaran',
    'Banaybanay',
    'San Pascual',
    'Pantubig',
    'Oroquieta',
    'Escalante',
    'Tanjay',
    'Papaya',
    'Binalbagan',
    'Sablayan',
    'Calaca',
    'Tayabas',
    'Del Pilar',
    'Noveleta',
    'Munoz',
    'Calauan',
    'Ramon',
    'Solano',
    'Bongabon',
    'Bayawan',
    'Tagudin',
    'San Jose',
    'Abucay',
    'Pandi',
    'San Leonardo',
    'Teresa',
    'Pila',
    'Manapla',
    'San Nicolas',
    'San Antonio',
    'Aliaga',
    'Pandan',
    'Maramag',
    'Hermosa',
    'Malilipot',
    'Bauan',
    'Bay',
    'San Luis',
    'Aparri',
    'Midsayap',
    'General Tinio',
    'Mauban',
    'Jagna',
    'Guimba',
    'Kabacan',
    'Isulan',
    'Alaminos',
    'Maluso',
    'Cabadbaran',
    'Surallah',
    'Pagalungan',
    'Lucban',
    'Paraiso',
    'Pililla',
    'Tagoloan',
    'Lumbang',
    'Cardona',
    'Buhi',
    'Malvar',
    'Aringay',
    'Samal',
    'Tangub',
    'Atimonan',
    'Cordova',
    'San Simon',
    'Tandag',
    'Agoo',
    'Bah-Bah',
    'Pandacaqui',
    'Naga',
    'Bulan',
    'Itogon',
    'Narra',
    'Burgos',
    'Sibulan',
    'Masinloc',
    'Buluan',
    'Santa Maria',
    'Penaranda',
    'Pulupandan',
    'Castillejos',
    'Lupon',
    'Quezon',
    'Manolo Fortich',
    'Tabuk',
    'Iba',
    'Paete',
    'Catanauan',
    'Calabanga',
    'Bongao',
    'Santa Catalina',
    'Santa Cruz',
    'San Antonio',
    'Rizal',
    'Telabastagan',
    'Maao',
    'La Paz',
    'Lopez',
    'Nabua',
    'Concepcion Ibaba',
    'Cabagan',
    'Himamaylan',
    'Talisay',
    'Baggabag B',
    'Alicia',
    'Manibaug Pasig',
    'Nagcarlan',
    'Victoria',
    'La Castellana',
    'Pio',
    'Calasiao',
    'Glan',
    'Sipalay',
    'Mamburao',
    'Palayan City',
    'San Fernando',
    'Bogo',
    'Asia',
    'Quiapo',
    'Pinamungahan',
    'Mansalay',
    'Botolan',
    'Maragondon',
    'Guihulngan',
    'Bambang',
    'Apas',
    'Gumaca',
    'Bignay Uno',
    'Balamban',
    'Mendez-Nunez',
    'Guiset East',
    'Loma de Gato',
    'Malanday',
    'Cogan',
    'Sebu',
    'Porac',
    'Cuenca',
    'Bansalan',
    'Jose Panganiban',
    'Sexmoan',
    'Molave',
    'Goa',
    'Calauag',
    'Irosin',
    'New Corella',
    'Don Carlos',
    'Taloc',
    'Manay',
    'Baras',
    'Sampaloc',
    'Ternate',
    'Pacol',
    'Pangil',
    'Suay',
    'Baao',
    'San Francisco',
    'Malabanban Norte',
    'Malapatan',
    'Laur',
    'Ipil',
    'Saravia',
    'Bantayan',
    'Sumag',
    'Compostela',
    'San Marcelino',
    'Buenavista',
    'San Mariano',
    'San Miguel',
    'San Francisco',
    'Quezon',
    'General Mamerto Natividad',
    'Maasin',
    'Veruela',
    'Labo',
    'Wao',
    'Pilar',
    'Laguilayan',
    'Danao',
    'Baybay',
    'Palo',
    'Carigara'
]
