cities = [
    'Warsaw',
    'Lodz',
    'Krakow',
    'Wroclaw',
    'Poznan',
    'Gdansk',
    'Szczecin',
    'Bydgoszcz',
    'Lublin',
    'Katowice',
    'Bialystok',
    'Gdynia',
    'Czestochowa',
    'Sosnowiec',
    'Radom',
    'Mokotow',
    'Torun',
    'Kielce',
    'Gliwice',
    'Zabrze',
    'Bytom',
    'Praga Poludnie',
    'Bielsko-Biala',
    'Olsztyn',
    'Rzeszow',
    'Ursynow',
    'Ruda Slaska',
    'Wola',
    'Rybnik',
    'Bielany',
    'Srodmiescie',
    'Dabrowa Gornicza',
    'Tychy',
    'Opole',
    'Elblag',
    'Plock',
    'Walbrzych',
    'Gorzow Wielkopolski',
    'Targowek',
    'Wloclawek',
    'Zielona Gora',
    'Tarnow',
    'Chorzow',
    'Kalisz',
    'Koszalin',
    'Legnica',
    'Bemowo',
    'Grudziadz',
    'Slupsk',
    'Jaworzno',
    'Jastrzebie Zdroj',
    'Praga Polnoc',
    'Ochota',
    'Bialoleka',
    'Jelenia Gora',
    'Nowy Sacz',
    'Konin',
    'Piotrkow Trybunalski',
    'Inowroclaw',
    'Lubin',
    'Siedlce',
    'Pila',
    'Myslowice',
    'Ostrowiec Swietokrzyski',
    'Siemianowice Slaskie',
    'Ostrow Wielkopolski',
    'Stargard',
    'Pabianice',
    'Gniezno',
    'Fordon',
    'Suwalki',
    'Glogow',
    'Chelm',
    'Tomaszow Mazowiecki',
    'Przemysl',
    'Stalowa Wola',
    'Zamosc',
    'Kedzierzyn-Kozle',
    'Lomza',
    'Leszno',
    'Zory',
    'Belchatow',
    'Wawer',
    'Mielec',
    'Tarnowskie Gory',
    'Swidnica',
    'Tczew',
    'Piekary Slaskie',
    'Raciborz',
    'Bedzin',
    'Zgierz',
    'Biala Podlaska',
    'Elk',
    'Swietochlowice',
    'Pruszkow',
    'Ostroleka',
    'Starachowice',
    'Zawiercie',
    'Zoliborz',
    'Legionowo',
    'Tarnobrzeg',
    'Pulawy',
    'Wodzislaw Slaski',
    'Skarzysko-Kamienna',
    'Radomsko',
    'Skierniewice',
    'Kutno',
    'Starogard Gdanski',
    'Krosno',
    'Debica',
    'Ursus',
    'Nysa',
    'Wejherowo',
    'Ciechanow',
    'Rumia',
    'Zdunska Wola',
    'Sieradz',
    'Kolobrzeg',
    'Otwock',
    'Zyrardow',
    'Oswiecim',
    'Swinoujscie',
    'Boleslawiec',
    'Nowa Sol',
    'Sopot',
    'Jaroslaw',
    'Swidnik',
    'Chrzanow',
    'Knurow',
    'Sanok',
    'Chojnice',
    'Mikolow',
    'Zary',
    'Malbork',
    'Szczecinek',
    'Sochaczew',
    'Brzeg',
    'Jaslo',
    'Olkusz',
    'Kwidzyn',
    'Minsk Mazowiecki',
    'Olesnica',
    'Wolomin',
    'Piaseczno',
    'Wlochy',
    'Krasnik',
    'Cieszyn',
    'Lebork',
    'Czechowice-Dziedzice',
    'Police',
    'Czeladz',
    'Dzierzoniow',
    'Nowy Targ',
    'Ostroda',
    'Myszkow',
    'Zgorzelec',
    'Ilawa',
    'Zywiec',
    'Olawa',
    'Bielawa',
    'Lukow',
    'Srem',
    'Gizycko',
    'Lowicz',
    'Augustow',
    'Turek',
    'Mlawa',
    'Krotoszyn',
    'Bochnia',
    'Swarzedz',
    'Czerwionka-Leszczyny',
    'Wrzesnia',
    'Gorlice',
    'Gierloz',
    'Ketrzyn',
    'Klodzko',
    'Nowy Dwor Mazowiecki',
    'Zakopane',
    'Brodnica',
    'Bilgoraj',
    'Grodzisk Mazowiecki',
    'Wyszkow',
    'Bielsk Podlaski',
    'Lubon',
    'Zagan',
    'Szczytno',
    'Kluczbork',
    'Walcz',
    'Swiecie',
    'Jarocin',
    'Bartoszyce',
    'Pszczyna',
    'Sandomierz',
    'Kabaty',
    'Nowa Ruda',
    'Wagrowiec',
    'Wielun',
    'Bialogard',
    'Lubliniec',
    'Koscian',
    'Jawor',
    'Skawina',
    'Pruszcz Gdanski',
    'Kolo',
    'Zabki',
    'Koscierzyna',
    'Prudnik',
    'Piastow',
    'Swiebodzice',
    'Marki',
    'Zambrow',
    'Lubartow',
    'Grajewo',
    'Ostrow Mazowiecka',
    'Opoczno',
    'Goleniow',
    'Luban',
    'Plonsk',
    'Hajnowka',
    'Laziska Gorne',
    'Mragowo',
    'Andrychow',
    'Rembertow',
    'Rydultowy',
    'Sroda Wielkopolska',
    'Swiebodzin',
    'Kamienna Gora',
    'Leczna',
    'Polkowice',
    'Rawicz',
    'Gryfino',
    'Dzialdowo',
    'Gostyn',
    'Konskie',
    'Ozorkow',
    'Chelmno',
    'Aleksandrow Lodzki',
    'Tomaszow Lubelski',
    'Strzelce Opolskie',
    'Wesola',
    'Pionki',
    'Chodziez',
    'Bierun',
    'Naklo nad Notecia',
    'Krasnystaw',
    'Kety',
    'Wadowice',
    'Pisz',
    'Sokolka',
    'Pultusk',
    'Pyskowice',
    'Gostynin',
    'Sierpc',
    'Trzebinia',
    'Bogatynia',
    'Kozienice',
    'Wieliczka',
    'Miedzyrzecz',
    'Hrubieszow',
    'Szamotuly',
    'Lask',
    'Orzesze',
    'Sulejowek',
    'Zlotow',
    'Braniewo',
    'Krapkowice',
    'Lancut',
    'Sokolow Podlaski',
    'Reda',
    'Kostrzyn nad Odra',
    'Sulechow',
    'Oborniki',
    'Jozefow',
    'Libiaz',
    'Deblin',
    'Rawa Mazowiecka',
    'Myslenice',
    'Kobylka',
    'Pleszew',
    'Slubice',
    'Zielonka',
    'Radlin',
    'Konstantynow Lodzki',
    'Radzionkow',
    'Miedzyrzec Podlaski',
    'Busko-Zdroj',
    'Strzegom',
    'Trzcianka',
    'Brzesko',
    'Jedrzejow',
    'Boguszow-Gorce',
    'Bytow',
    'Gryfice',
    'Przasnysz',
    'Nowogard',
    'Gubin',
    'Zlotoryja',
    'Rypin',
    'Konstancin-Jeziorna',
    'Lidzbark Warminski',
    'Lapy',
    'Namyslow',
    'Zabkowice Slaskie',
    'Ledziny',
    'Ustka',
    'Staszow',
    'Swidwin',
    'Radzyn Podlaski',
    'Olecko',
    'Garwolin',
    'Przeworsk',
    'Milanowek',
    'Choszczno',
    'Ustron',
    'Nisko',
    'Leczyca',
    'Siemiatycze',
    'Chelmza',
    'Jelcz Laskowice',
    'Lomianki',
    'Jelcz',
    'Ropczyce',
    'Nowy Tomysl',
    'Solec Kujawski',
    'Glucholazy',
    'Glowno',
    'Kartuzy',
    'Cieplice Slaskie Zdroj',
    'Lubsko',
    'Wladyslawowo',
    'Grojec',
    'Lipno',
    'Kepno',
    'Skoczow',
    'Kozle',
    'Czluchow',
    'Morag',
    'Nidzica',
    'Limanowa',
    'Slupca',
    'Wschowa',
    'Ostrzeszow',
    'Darlowo',
    'Barlinek',
    'Chojnow',
    'Wilanow',
    'Pszow',
    'Znin',
    'Lezajsk',
    'Wabrzezno',
    'Grodzisk Wielkopolski',
    'Debno',
    'Goldap',
    'Glubczyce',
    'Wolsztyn',
    'Tuchola',
    'Niedobczyce',
    'Slawno',
    'Zdzieszowice',
    'Koluszki',
    'Zlocieniec',
    'Klobuck',
    'Wlodawa',
    'Rabka-Zdroj',
    'Golub-Dobrzyn',
    'Pyrzyce',
    'Szprotawa',
    'Brzeg Dolny',
    'Gora',
    'Lubaczow',
    'Wegrow',
    'Mogilno',
    'Wolin',
    'Strzelin',
    'Mosina',
    'Brwinow',
    'Aleksandrow Kujawski',
    'Brzeziny',
    'Wolow',
    'Krynica-Zdroj',
    'Paslek',
    'Trzebnica',
    'Blonie',
    'Krosno Odrzanskie',
    'Milicz',
    'Szydlowiec',
    'Mysliborz',
    'Kozy',
    'Wegorzewo',
    'Kowary',
    'Janow Lubelski',
    'Pinczow',
    'Brzeszcze',
    'Miechow',
    'Czarnkow',
    'Nowa Deba',
    'Wronki',
    'Puck',
    'Wisla',
    'Dabrowa Tarnowska'
]
