cities = [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
    'Sultanah',
    'Dammam',
    'Taif',
    'Tabuk',
    'Al Kharj',
    'Buraydah',
    'Khamis Mushait',
    'Al Hufuf',
    'Al Mubarraz',
    'Hafar Al-Batin',
    "Ha'il",
    'Najran',
    'Al Jubayl',
    'Abha',
    'Yanbu',
    'Khobar',
    'Arar',
    'Sakakah',
    'Jizan',
    'Qurayyat',
    'Dhahran',
    'Al Qatif',
    'Al Bahah',
    'Tarut',
    'Qal`at Bishah',
    'Ar Rass',
    'Ash Shafa',
    'Sayhat',
    'Al Mithnab',
    'Al Khafji',
    'Ad Dawadimi',
    'Sabya',
    'Az Zulfi',
    'Abu `Arish',
    'Safwa',
    'Afif',
    'Rabigh',
    'Rahimah',
    'Turaif',
    'Tubarjal',
    'Ad Dilam',
    'Umm Lajj',
    'Al-Ula',
    'Abqaiq',
    'Badr Hunayn',
    'Samitah',
    'Al Wajh',
    'Al Bukayriyah',
    'An Nimas',
    'As Sulayyil',
    'Turabah',
    'Al Jumum',
    'Duba',
    'At Taraf',
    'Qaisumah',
    'Al Battaliyah',
    'Al Munayzilah',
    'Adh Dhibiyah',
    'Al Majaridah',
    'Tanumah',
    'Al Qurayn',
    'Umm as Sahik',
    'Sajir',
    'Al Awjam',
    'Farasan',
    'Al Mindak',
    'Al Artawiyah',
    'Al Jubayl',
    'Al Qarah',
    'Marat',
    'Al Jafr',
    'Suwayr',
    'Tumayr',
    'At Tubi',
    'Al Jaradiyah',
    'Al Muwayh',
    'As Saffaniyah',
    'Al Hada',
    'Al Markaz',
    'Misliyah',
    'Al Mutayrifi',
    'Mizhirah',
    'Ad Darb',
    'Julayjilah',
    'Mulayjah',
    'Al Fuwayliq',
    'Tabalah'
]
