cities = [
    'Montevideo',
    'Salto',
    'Paysandu',
    'Las Piedras',
    'Rivera',
    'Maldonado',
    'Tacuarembo',
    'Melo',
    'Mercedes',
    'Artigas',
    'Minas',
    'San Jose de Mayo',
    'Durazno',
    'Florida',
    'Barros Blancos',
    'Treinta y Tres',
    'Rocha',
    'San Carlos',
    'Pando',
    'Fray Bentos',
    'Colonia del Sacramento',
    'Trinidad',
    'La Paz',
    'Canelones',
    'Delta del Tigre',
    'Carmelo',
    'Santa Lucia',
    'Progreso',
    'Young',
    'Dolores',
    'Paso de Carrasco',
    'Rio Branco',
    'Juan L. Lacaze',
    'Paso de los Toros',
    'Bella Union',
    'Chui',
    'Nueva Helvecia',
    'Nueva Palmira',
    'Libertad',
    'Rosario',
    'Colonia Nicolich',
    'Piriapolis',
    'Castillos',
    'Tranqueras',
    'Sarandi del Yi',
    'Punta del Este',
    'Pan de Azucar',
    'San Ramon',
    'Lascano',
    'Sarandi Grande',
    'Joaquin Suarez',
    'Tarariras',
    'Sauce',
    'Jose Pedro Varela',
    'Guichon'
]
