cities = [
    'Caracas',
    'Maracaibo',
    'Maracay',
    'Valencia',
    'Barquisimeto',
    'Ciudad Guayana',
    'Barcelona',
    'Maturin',
    'Puerto La Cruz',
    'Petare',
    'Barinas',
    'Turmero',
    'Ciudad Bolivar',
    'Merida',
    'Alto Barinas',
    'Santa Teresa del Tuy',
    'Cumana',
    'San Cristobal',
    'Nuestra Senora del Rosario de Baruta',
    'Mucumpiz',
    'Cabimas',
    'Coro',
    'Guatire',
    'Cua',
    'Guarenas',
    'Puerto Cabello',
    'Ocumare del Tuy',
    'Guacara',
    'El Tigre',
    'El Limon',
    'Acarigua',
    'Los Teques',
    'Punto Fijo',
    'Charallave',
    'Palo Negro',
    'Cagua',
    'Anaco',
    'Calabozo',
    'Guanare',
    'Carupano',
    'Ejido',
    'Catia La Mar',
    'Mariara',
    'Carora',
    'Valera',
    'Yaritagua',
    'Valle de La Pascua',
    'San Juan de los Morros',
    'Porlamar',
    'La Victoria',
    'Tinaquillo',
    'El Cafetal',
    'San Fernando de Apure',
    'San Carlos',
    'San Felipe',
    'Villa de Cura',
    'Araure',
    'Guigue',
    'La Villa del Rosario',
    'Chacao',
    'San Antonio de Los Altos',
    'Machiques',
    'San Jose de Guanipa',
    'El Vigia',
    'Caucaguita',
    'Punta Cardon',
    'Los Dos Caminos',
    'El Hatillo',
    'La Dolorita',
    'San Carlos del Zulia',
    'Upata',
    'El Tocuyo',
    'Maiquetia',
    'Caucaguito',
    'Puerto Ayacucho',
    'Rubio',
    'Tucupita',
    'San Mateo',
    'Chivacoa',
    'Moron',
    'Lagunillas',
    'San Joaquin',
    'Quibor',
    'Zaraza',
    'Carrizal',
    'Altagracia de Orituco',
    'Gueiria',
    'Tacarigua',
    'Colon',
    'Trujillo',
    'Caraballeda',
    'La Asuncion',
    'Los Rastrojos',
    'Barinitas',
    'Las Tejerias',
    'Cantaura',
    'San Antonio del Tachira',
    'Santa Rita',
    'Guasdualito',
    'Nirgua',
    'Santa Elena de Uairen',
    'Juan Griego',
    'Villa Bruzual',
    'Tariba',
    'La Fria',
    'La Guaira',
    'Chichiriviche',
    'Tucacas'
]
